### ISSUE TITLE
dragging gumps not working properly

### ISSUE THREAD

**Issue by dissident76** [ClassicUO/ClassicUO#1000]
I submitted a pull request some time ago that fixed this -although apparently it created other problems that I have not been able to reproduce. It was rolled back and now when trying to drag gumps too quickly, the gump stays behind the cursor again.

**Comment by andreakarasho** [comment]
i tried to reproduce but everything looks good

**Comment by dissident76** [comment]
it only happens with lower-end computers when mouse is fast. Press left button and the first drag move has to be quite fast. try with a small gump, like a health bar, and press the mouse button close to the edge where you are going to move the mouse to.

example:
- gump TOP RIGHT corner x=500, y=500
- press left button on x=495, y=495 and move the mouse to x=1000,y=800 very fast (like when you want to move a gump in-game out of the way). Important, the first move should be sudden.

The mistake in the code is to check for dragging after the mouse already started moving (second sample after mouse is down), so it takes the second mouse sample as the origin for the drag, and not the coordinates where mouse was pressed.

Seems complicated but it is actually really easy to reproduce...

**Comment by andreakarasho** [comment]
fixed
