### ISSUE TITLE
Race change token not opening character creation gump

### ISSUE THREAD

**Issue by comiluv** [ClassicUO/ClassicUO#1002]
**Describe the bug**
Using race change token does not open character creation gump

**To Reproduce**
1. Use race change token
2. Choose any race
3. Click OK

**Expected behavior**
A character creation gump should appear

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10

**Additional context**
Using a race change token without classicUO normally opens a character creation gump

**Comment by andreakarasho** [comment]
yep missing this gump
![image](https://user-images.githubusercontent.com/20810422/78460708-5978a300-76c3-11ea-9d0d-176b01b9c8c1.png)

**Comment by AvernalFury** [comment]
This bug also affects the race change Human to Elf quest - you get an error message stating the gump has not been added yet when you follow the NPC and this gump is meant to trigger. Currently the only way to finish that quest is to use another client like Enhanced.
