### ISSUE TITLE
Casting chivalry spell throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by comiluv** [ClassicUO/ClassicUO#1006]
**Describe the bug**
Casting any chivalry spell throws this error message:
System.ArgumentOutOfRangeException: 지정한 인수가 유효한 값 범위를 벗어났습니다.
매개 변수 이름: index
   위치: System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   위치: Assistant.PacketHandlers.ExtendedClientCommand(Packet p, PacketHandlerEventArgs args)
   위치: Assistant.PacketHandler.ProcessFilters(List`1 list, Packet p)

**To Reproduce**
1. Open Book of Chivalry
2. Cast Close Wounds or any other chivalry spell
3. Error message

**Expected behavior**
No error message

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
Also happens with Spellweaving, Bushido and Ninjitsu spells
Does not happen with Magery, Necromancy, Mysticism spells.
First appeared in 0.1.3.300, didn't happen in 0.1.3.200

**Comment by andreakarasho** [comment]
it's a razor issue. 
Post your error here: https://github.com/markdwags/Razor/issues
