### ISSUE TITLE
Support for big bank vault gump and custom backpack option

### ISSUE THREAD

**Issue by comiluv** [ClassicUO/ClassicUO#1010]
There are options in vanilla client that gives you big bank vault gump and some custom back pack options like suese, ghoul, etc. any plan on supporting these features?

**Comment by Admin-Yukiko** [comment]
This would be a great addition. I use the polar bear backpack option because it is easier to see those small brown graphics items than with the normal backpack.

**Comment by Alias-Alan** [comment]
Gump art like this that has so many options and more being created all the time that is out there for the public is probably best not included in a client. It would be too hard to cater to everyone in my opinion.

**Comment by comiluv** [comment]
> Gump art like this that has so many options and more being created all the time that is out there for the public is probably best not included in a client. It would be too hard to cater to everyone in my opinion.

Those gumps mentioned in this thread are optional gumps included in vanilla client that can be selected by default (no modding necessary)

**Comment by andreakarasho** [comment]
done
