### ISSUE TITLE
Window "zoomed in" or wrong DPI on macOS 10.15.3 (Catalina)

### ISSUE THREAD

**Issue by nathanvy** [ClassicUO/ClassicUO#1011]
**Describe the bug**
When launching the game, it appears to open at the correct window size, except I can only see a zoomed-in view of the login gump.

**To Reproduce**
1. `$ mono ClassicUO.exe`

**Expected behavior**
Am presented with the standard login screen

**Screenshots**
<img width="1440" alt="Screen Shot 2020-03-30 at 20 28 09" src="https://user-images.githubusercontent.com/2128134/77974665-d40d8100-72c5-11ea-8d99-3bc799c567bd.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.3
 - Browser: Firefox (why does this matter?)
 - Version: Latest

**Additional context**
Using latest tagged release.

**Comment by andreakarasho** [comment]
Try to run the file ‘ClassicUO’ no extension

**Comment by nathanvy** [comment]
That's a shell script that tries to overwrite my homebrew installation using the deprecated (old) installer, which I'm obviously not going to allow:

```
➜  classicuo chmod +x ClassicUO
➜  classicuo ./ClassicUO
./ClassicUO: line 5: type: : not found
Warning: The Ruby Homebrew installer is now deprecated and has been rewritten in
Bash. Please migrate to the following command:
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/sbin
==> The Xcode Command Line Tools will be installed.

Press RETURN to continue or any other key to abort
```

However I went into that script and manually installed the packages it wants me to install (`mono-libgdiplus` and `zlib`) and then ran ClassicUO.bin.osx:  The game starts properly but I have the same symptom as above in the screenshot.

**Comment by SaschaKP** [comment]
the correct way to do the check is this, this will not trigger a reinstall of homebrew if it's already present:
`which -s brew
        if [[ $? != 0 ]] ; then
            # Install Homebrew
            ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        fi`

this code must replace the type and all the if that installs homebrew

**Comment by nathanvy** [comment]
Thanks @SaschaKP 

Unfortunately that does not resolve the error as I still get the window in a strange zoomed-in state per the screenshot above.

**Comment by andreakarasho** [comment]
@nathanvy 
- Download: https://ci.appveyor.com/project/andreakarasho/classicuo/build/artifacts
- Copy all contents into your cuo folder [OS will ask you to replace files]
- run `mono ClassicUO.exe -highdpi`

**Comment by nathanvy** [comment]
Okay, some progress.  The window draws its contents properly but:

a. It does not respond to mouse clicks (can't click any buttons or check boxes)
b. It's still very very small and I can't seem to specify the window size in `settings.json`.  Perhaps I have the wrong syntax?  I don't see anything on the wiki about this.
<img width="1440" alt="Screen Shot 2020-03-31 at 14 26 00" src="https://user-images.githubusercontent.com/2128134/78061795-bbe84100-735b-11ea-8bc7-e093ab9076c7.png">

**Comment by andreakarasho** [comment]
what's happen if you remove the `-highdpi` arg?

**Comment by nathanvy** [comment]
It goes back to what looks like the first screenshot.

**Comment by andreakarasho** [comment]
Can you join the discord channel?

**Comment by nathanvy** [comment]
Sure, I will join later this evening.  Thanks.

**Comment by andreakarasho** [comment]
Fixed.
You can remove the `-highdpi` arg if you prefer.

**Comment by nathanvy** [comment]
Hi,

The only commits I see since I opened this issue pertain to github issue templates.  Where was the fix published?

**Comment by andreakarasho** [comment]
https://ci.appveyor.com/project/andreakarasho/classicuo/build/artifacts

**Comment by nathanvy** [comment]
That did resolve the issue, thanks very much.
