### ISSUE TITLE
32-bit (x86) support?

### ISSUE THREAD

**Issue by burakt91** [ClassicUO/ClassicUO#1013]
I've an old PC with x86 processor. I can't launch the exe. Is there any x86 version?

**Comment by SaschaKP** [comment]
x86s aren't supported, there is one user who did all the work in compiling the libs, maybe you can try asking him, as 32bit machine are slowly being put aside for their main limitation: memory (4GB max on 32bit).

Join in discord and ask to steaksauce in cuo channel, he managed to recompile the whole lib to 32bit machines.
