### ISSUE TITLE
Back screen when triyng to log in

### ISSUE THREAD

**Issue by greccobruno** [ClassicUO/ClassicUO#1015]
Hi!

when i trying to open the game, its open in a black screen (everything works fine but no image)

![image](https://user-images.githubusercontent.com/52800235/78088156-b3aef680-7399-11ea-97e8-b18b1fbcab3c.png)

thanks for the help

**Comment by TannerBist** [comment]
hi, I have encountered this problem with some Intel HD graphics video cards on windows. Updating to the latest available driver often solved the problem

**Comment by andreakarasho** [comment]
yes fixed in dev
