### ISSUE TITLE
Headless character when playing gargoyle

### ISSUE THREAD

**Issue by comiluv** [ClassicUO/ClassicUO#1016]
1. Description:
When playing a gargoyle character, a headless man appears below the character when flying
Doesn't happen without ClassicUO

2. How to reproduce:
1) Make a gargoyle character
2) Start flying
3) Walk or run to any direction and a headless man appears below the character

3. Environment
Client version 7.0.85.15
ClassicUO version 0.1.3.415 ("dev" version)

4. Other material
Here is the gif screenshot of the bug

![headless](https://user-images.githubusercontent.com/19642705/78205659-b3b51080-74d7-11ea-900a-1c69f437a1ef.gif)

**Comment by andreakarasho** [comment]
fixed in dev
