### ISSUE TITLE
Localized city string message is broken in VvV announcement

### ISSUE THREAD

**Issue by comiluv** [ClassicUO/ClassicUO#1017]
1. Description
When a VvV battle begins the name of city which VvV battle takes place at is announce in the message and journal. The name of the city gets broken. Doesn't happen in vanilla client.

2. How to reproduce
Login with a character that has VvV activated

3. Environment
UO 7.0.85.15
ClassicUO 0.1.3.415

4. Screenshot
![Cap 2020-04-02 12-03-22-021](https://user-images.githubusercontent.com/19642705/78206878-017f4800-74db-11ea-9c35-fe21dbccd815.jpg)

**Comment by andreakarasho** [comment]
fixed in dev
