### ISSUE TITLE
Leaf tunic turns invisible with female elf characters

### ISSUE THREAD

**Issue by comiluv** [ClassicUO/ClassicUO#1018]
1. Description
When a female elf character puts on a leaf tunic, it becomes invisible and inaccessible (can't click on it)

2. Reproduce steps
1) Acquire a leaf tunic
2) Put it on a female elf character

3. Environment
Client version: 7.0.85.15
ClassicUO version: 0.1.3.300

4. Screenshots
1) This is a female elf character wearing a leaf tunic in vanilla client
![Cap 2020-04-02 13-02-00-960](https://user-images.githubusercontent.com/19642705/78209656-933e8380-74e2-11ea-8b60-e637159cee19.jpg)

2) Exactly the same character in ClassicUO
![Cap 2020-04-02 13-02-33-738](https://user-images.githubusercontent.com/19642705/78209667-9a659180-74e2-11ea-832c-b1c189fed222.jpg)

**Comment by andreakarasho** [comment]
fixed in dev
