### ISSUE TITLE
Chest armor turns invisible when epaulette is equipped

### ISSUE THREAD

**Issue by comiluv** [ClassicUO/ClassicUO#1019]
1. Description
Putting on an epaulette while equipping a chest armor turns the chest armor turn invisible

2. How to reproduce
(1) Make a character equip a chest armor
(2) Put on an epaulette

3. Screenshot
![epaulette](https://user-images.githubusercontent.com/19642705/78210169-49ef3380-74e4-11ea-81cf-0b03ad7bf2a8.gif)

**Comment by andreakarasho** [comment]
fixed in dev
