### ISSUE TITLE
Mouse overing items on a reward gump doesn't give item tooltip on some items

### ISSUE THREAD

**Issue by comiluv** [ClassicUO/ClassicUO#1020]
1. Desciption
If you put a mouse cursor over Mace and Shield Reading Glasses in a VvV reward gump, there's no tooltip appearing

2. How to produce
(1) Go to Silver Trader
(2) Open reward gump by double clicking on him
(3) Click on next 6 times
(4) Hover mouse cursor over the second item, Mace and Shield Reading Glasses

3. Expected behavior
An item tooltip appears

4.Environment
Client version 7.0.85.15
ClassicUO version 0.1.3.415 ("dev" version)

5. Notes
Other items correctly produce tooltips, such as potion kegs in page 1, but wearable equipments at least are not giving tooltips

**Comment by andreakarasho** [comment]
Probably it is an obvious question: Does it work on standard client?

**Comment by comiluv** [comment]
Yes it works on standard client either decryption patched or run through razor or uosteam. 
Below screenshot is Minax Artifact reward gump in vanilla client.
![vanillacli](https://user-images.githubusercontent.com/19642705/79033914-1d769e00-7bed-11ea-8cb6-d854d190fa21.gif)

And below is same gump in ClassicUO 0.1.3.470
![classicuocli](https://user-images.githubusercontent.com/19642705/79033927-3717e580-7bed-11ea-9153-6c809a629611.gif)

**Comment by andreakarasho** [comment]
Fixed in latest dev
