### ISSUE TITLE
Cannot cast Momentum Strike with a macro

### ISSUE THREAD

**Issue by comiluv** [ClassicUO/ClassicUO#1021]
1. Description
When trying to cast Bushido spell Momentum Strike using a macro, ClassicUO does not cast spell and displays message "You do not have that spell!" instead

2. How to reproduce
(1) Make a character that has over 70 Bushido skill, which is minimum to cast Momentum Strike
(2) Acquire a book of Bushido
(3) Open Options menu
(4) Macros -> New Macro -> set any name -> Cast spell Momentum Strike
![Cap 2020-04-02 14-56-53-622](https://user-images.githubusercontent.com/19642705/78215388-62664a80-74f2-11ea-99b4-51bef33df234.jpg)
(5) Press assigned hotkey or double click on a macro icon
(6) Message says "You do not have that spell!"

3. Expected result
Player character casts Momentum Strike

4. Environment
Client version 7.0.85.15
ClassicUO version 0.1.3.300

**Comment by andreakarasho** [comment]
fixed in dev
