### ISSUE TITLE
Ethereal dragon mount is invisible

### ISSUE THREAD

**Issue by comiluv** [ClassicUO/ClassicUO#1026]
1. Description
Ethereal dragon mount, which is a veteran reward item, turns invisible when mounted

2. How to reproduce
(1) Double click on ethereal dragon statue

3. Expected result
Vanilla client:
![normdragon](https://user-images.githubusercontent.com/19642705/78461513-97e28200-7704-11ea-8669-caaba688c3d5.gif)

4. What happened
![invisdragon](https://user-images.githubusercontent.com/19642705/78461517-a03abd00-7704-11ea-9d69-f5f13bdccbf1.gif)

**Comment by andreakarasho** [comment]
graphic?
[-info in game]

**Comment by comiluv** [comment]
I dunno man I just post bug reports lol

**Comment by andreakarasho** [comment]
Just write in game -info and target the ethereal in your backpack.
A gump will appear, search for the key “graphic” on the left side

**Comment by comiluv** [comment]
It says 40976 in row "Graphic"

**Comment by andreakarasho** [comment]
added in dev
