### ISSUE TITLE
Out of range mobile health bars are filled with random names

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#1032]
Mobile health bars that are out of range gets their name replaced by some random other name (something that you encountered during that session it seems).

Not neccesary, better to keep old name, or leave it blank.

![image](https://user-images.githubusercontent.com/39037141/78820653-791c0e00-79d8-11ea-96f1-0e96ddee37c4.png)

**Comment by andreakarasho** [comment]
This pr https://github.com/andreakarasho/ClassicUO/pull/1069 should fix
