### ISSUE TITLE
Salvage bag context menu appears far away top left in the screen

### ISSUE THREAD

**Issue by comiluv** [ClassicUO/ClassicUO#1033]
Desc.:
A salvage bag which can be bought from a provisioner can be used through its context menu when it's in player's backpack. But the context menu appears far away top left in the game screen.

How to reproduce:
(1) Turn "always use full size window" on in Options -> Video (not sure if it's necessary)
(2) Buy a salvage bag from a provisioner
(3) Single click on a salvage bag, inside player's backpack
(4) Context menu appears top left corner of the screen

Expected behavior:
Context menu appears near mouse cursor

Environment:
ClassicUO version 0.1.3.463 (dev)

**Comment by andreakarasho** [comment]
Fixed
