### ISSUE TITLE
Trying to use a virtue immediately cancels target cursor

### ISSUE THREAD

**Issue by comiluv** [ClassicUO/ClassicUO#1034]
1. Description: When trying to invoke a virtue such as valor or honor through Virtue gump, target cursor is immediately cancelled thus impairing the player ability to invoke a virtue.

2. Reproducing steps:
(1) Make a new character
(2) Open Virtue gump
(3) Double click on valor (or any other virtue that gives player a target cursor)
(4) Cursor appears but is immediately cancelled
![virtuecursorbug](https://user-images.githubusercontent.com/19642705/78970355-15165880-7b44-11ea-9e1e-49b16c3f6ce2.gif)

3. Expected result: Cursor stays so that the player can select a target

4. Environment: ClassicUO 0.1.3.463 (dev)

5. Some notes: This looks like a closed bug happening again in newest version. See https://github.com/andreakarasho/ClassicUO/issues/653

**Comment by comiluv** [comment]
Opening option and pressing ok resolved issue automagically.

**Comment by comiluv** [comment]
Sorry for confusion and inconvenience. The cursor stays only if there's another classicuo gump on screen activated and virtue gump is over it. I thought the bug resolved itself automagically but it was so because virtue gump was over option gump when I tried again.

**Comment by andreakarasho** [comment]
Looks like similar to https://github.com/andreakarasho/ClassicUO/issues/1023

**Comment by comiluv** [comment]
What I feel is that this issue is targeting cursor is activated too fastly and target cursor thinks something like mouseButtonPressed is mouseButtonClicked, instead of waiting for mouseButtonReleased event.
In vanilla client, I feel the client waits for mouseButtonReleased event before activating target cursor.
This can be tested by aligning Virtue gump over a champion spawning altar, which is an object that can actually be targeted by Virtue, and then using Valor.

Screenshots:
Vanilla client, cursor waits for player mouse released event after player double clicks on the gump
![vanillaclie](https://user-images.githubusercontent.com/19642705/79034430-bce96000-7bf0-11ea-8268-2370b044b96d.gif)

ClassicUO version 0.1.3.470, cursor doesn't wait and player immediately uses Valor on Champion Altar, but player didn't click the target but double clicked on Virtue gump.
![classicuocli](https://user-images.githubusercontent.com/19642705/79034472-fa4ded80-7bf0-11ea-8fba-5e1dcc5c2ce3.gif)

Plus there's https://github.com/andreakarasho/ClassicUO/issues/1023 so player targets the ground tile immediately.

**Comment by andreakarasho** [comment]
fixed in dev
