### ISSUE TITLE
Can we have a separate gump for zoom levels? 

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#1035]
The debug is nice but:
a. the coordinates constantly fluctuate and distract me (i drag it to the bottom of my monitor so they are off screen)

b. the yellow font makes them stick out/flicker (grey would be better), while the world map is fine (unnoticeable)

I have a health issue and get easily dizzy from flashing bright colors, it would be great if:
a. debug was grey text
b. coordinates optional to turn off or a separate gump for zoom levels

thanks a ton for consideration!

**Comment by andreakarasho** [comment]
done
