### ISSUE TITLE
Items and containers.

### ISSUE THREAD

**Issue by Hoogie1980** [ClassicUO/ClassicUO#1037]
1) Items that are put into a container now will sometimes show up outside the scope of the backpack.

2) When I double click to open a chest/bag sometimes the items do no show.  Have to open the chest/bag a few times to show all the contents.

**Comment by andreakarasho** [comment]
1- already reported here: https://github.com/andreakarasho/ClassicUO/issues/1036
2- pushed a fix in dev. If the issue persist do you think you able to reproduce?

Open an issue per argument please :)

**Comment by Hoogie1980** [comment]
Sorry about having double issues in same post.  

I was able to test the disappearing items bug, and it seems to be fixed now.  Thank you

**Comment by andreakarasho** [comment]
> Sorry about having double issues in same post.
> 
> I was able to test the disappearing items bug, and it seems to be fixed now. Thank you

Can you give me a detailed description how you reproduce it?
