### ISSUE TITLE
ClassicUO tries to load gumpartLegacyMUL.uop for files from 7.0.15.1 which has gumpart.mul (etc.)

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [ClassicUO/ClassicUO#1038]
Hello,
Thanks for the client, amazing work.

I have been struggling with ClassicUO trying to load gumpartLegacyMUL.uop file, in a client that shouldn't have such file.

7.0.15.1 apparently has:
- gumpart.mul
- gump.def
- gumpidx.mul

As such, those should be loaded instead of the UOP file from my understanding.

I currently "fixed" it by dropping the uop file from a much newer client (gumpartLegacyMUL.uop) to get the client running.
Please notice that I'm running this on Ubuntu 18.04 through Mono (goal being to do some development on ServUO).

Unfortunately I can't use files from a too-new client because CentrED+ (tool to edit statics and map) works only with files up to 7.0.18, from my understanding (it didn't work with the latest anyway), for server development not being able to edit the map is problematic!

**Comment by andreakarasho** [comment]
the UOP installation is due to the client version [ >= 7.0.0.0 and MainMisc.uop exists].
Should be fine now
