### ISSUE TITLE
[FEATURE] Add Crypt in the JSON

### ISSUE THREAD

**Issue by Arutosio** [ClassicUO/ClassicUO#1039]
this is necessary to be able to play on some servers and to be able to activate it on the razor would be fantastic..
EXSAMPLE:

"clientversion": "1.26.04",
  "Crypt": "1",
  "lastcharactername": "",
  "plugins": [
    "../Razor-1.6.4.2/Razor.exe"
  ]

**Comment by andreakarasho** [comment]
crypt means osi encryption?

**Comment by Arutosio** [comment]
> crypt means osi encryption?

yes

**Comment by andreakarasho** [comment]
Already exists an issue about encryption
