### ISSUE TITLE
Identifying items shows the item text in the wrong position (Outlands specific?)

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#1041]
Hello!

In the most recent dev build, when identifying items using an item ID wand on the Outlands server, the text appears offset randomly from the actual item. Like this:
![image](https://user-images.githubusercontent.com/39037141/79073727-665f4d00-7ce8-11ea-9e3e-8ed3a06aee1d.png)

This is the normal look:
![image](https://user-images.githubusercontent.com/39037141/79073734-6fe8b500-7ce8-11ea-861a-89b83153af93.png)

**Comment by andreakarasho** [comment]
still?

**Comment by BlackTeaOutlands** [comment]
Yes still

**Comment by andreakarasho** [comment]
fixed

**Comment by dissident76** [comment]
I noticed it was fixed at some point and now it's been happening again for a few weeks. Please re-open
