### ISSUE TITLE
Boating issues on UO Outlands

### ISSUE THREAD

**Issue by natryl** [ClassicUO/ClassicUO#1044]
When a boat comes on your screen fast, often you will lose visual of the crew.

https://i.imgur.com/taR5RoK.gifv

I think this is related to the speeds that boats can get to on UO outlands but I am not sure. Ive seen this happen with stock boats in the water too.

Unrelated separate issue but maybe not. Sometimes object just disappear from other boats. Two screenshots. One the tillerman is gone and he circled my boat and the tillerman showed back up. 

https://i.imgur.com/7hxj06N.png
https://i.imgur.com/Mi9mOGM.png

**Comment by andreakarasho** [comment]
pushed a fix
