### ISSUE TITLE
Open World map and char move

### ISSUE THREAD

**Issue by canerksk** [ClassicUO/ClassicUO#1047]
When he opens the world map, the character starts walking/move on his own.

**Comment by andreakarasho** [comment]
Test with UOSteam and open the uos map.

**Comment by andreakarasho** [comment]
I close it until the test is done, because from test i've done in tns.gen.tr  it's not a CUO issue

**Comment by canerksk** [comment]
dev and master branch
https://imgur.com/Rrzjmvo

**Comment by andreakarasho** [comment]
Again, test with UOSteam
