### ISSUE TITLE
Arm Disarm Macro Does Not Work

### ISSUE THREAD

**Issue by tazmanyak** [ClassicUO/ClassicUO#1051]
When you use repeatedly ArmsDisarm->Left/Right, it does not work. There is memory problem. When you select weapon again, it starts working.

**Comment by andreakarasho** [comment]
Can you describe better what you mean with “it does not work”?

**Comment by tazmanyak** [comment]
Let say you set Letter F1 for Right, and F2 for Left about Arm Disarm. When you dclick right hand weapon and use arms disarm and then doing same thing for left hand. When you use these macros after and after , it does nothing.

**Comment by andreakarasho** [comment]
cuo version?

**Comment by tazmanyak** [comment]
Latest Development Version

Andrea Angelini <notifications@github.com>, 24 Nis 2020 Cum, 18:38
tarihinde şunu yazdı:

**Comment by tazmanyak** [comment]
Any progress on this ?

**Comment by andreakarasho** [comment]
fixed
