### ISSUE TITLE
Paperdoll bug on Unhide/Reveal

### ISSUE THREAD

**Issue by fetuffani** [ClassicUO/ClassicUO#1055]
The paperdoll shows a very buggy behaviour after unhiding/revealing
It may happen on hiding as well

reopening the paperdoll will not fix
the game interface turn into an unusable state
it may crash when opening the backpack
even the playermobile becomes buggy (naked char without any equiped item & mount)

![ppdoll](https://user-images.githubusercontent.com/8229714/80426784-ccd59500-88bc-11ea-8a36-b9dae1cc543a.png)

![settings](https://user-images.githubusercontent.com/8229714/80426840-f393cb80-88bc-11ea-9ee7-57b6b1d2eadc.PNG)

**Comment by andreakarasho** [comment]
CUO version?

**Comment by fetuffani** [comment]
Tested on 0.1.3.602

**Comment by andreakarasho** [comment]
Seems like one of the texture in paperdoll is changing when you hide/unhide.

The only way to figure out is trying to remove 1 item per time and see which one causes the issue. Can you do this attempt?

**Comment by fetuffani** [comment]
After some debugging, the problem was with the 7.0.33 protocol changes on the server side
It was sending the wrong packet version (>7.0.33) while my CUO client version was set to 7.0.23

I've also tested with other client versions and CUO seems to be behaving correctly

**Comment by andreakarasho** [comment]
Nice!
