### ISSUE TITLE
Item Tooltip not shown until dragging the  item

### ISSUE THREAD

**Issue by HankTheDrunk** [ClassicUO/ClassicUO#1059]
Bug: When hovering cursor over an item the tooltip doesn't show until the item is drag and dropped.

![tooltip](https://user-images.githubusercontent.com/7755620/80803781-51583a00-8b81-11ea-9d43-69a10c93547c.gif)

**Comment by andreakarasho** [comment]
Hi, cuo version?

**Comment by HankTheDrunk** [comment]
CUO: Beta - 0.1.3.500 HOTFIX

If there is any further information I can provide let me know.
I've had this happen with UO client versions 5.0.8.3, 7.0.15.1 and the latest UO 7.0.85.15

**Comment by andreakarasho** [comment]
Did you try with standard client?

**Comment by HankTheDrunk** [comment]
Yes, with the standard client it functions properly.
UORice, Razor or Steam (as decryptors) this is not an issue.

This bug has happened on ServUO & RunUO shards.
On PoL the bug is similar but applies almost to everything draggable.

Also I tested left clicking once to see if that would spur the tooltip to appear, only dragging seems to work.

Edit: I even took the time to install a fresh windows on a VM with a clean UOC and UO install.
Tested this again and got the same results.

**Comment by andreakarasho** [comment]
i pushed a fix to solve: https://github.com/andreakarasho/ClassicUO/issues/1060
can you test with the dev version?

**Comment by HankTheDrunk** [comment]
Tested on the latest Dev build as of this post.

This fixed the problem on Servuo & Runuo shards.
Thank you for working with me on this issue.

ps. The PoL shard is ancient, If and when they update to the latest PoL Core I'll report back with a new issue if it persists. Thanks Again.
