### ISSUE TITLE
Items overlapping doesn't update tooltip

### ISSUE THREAD

**Issue by Novocaine85** [ClassicUO/ClassicUO#1060]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7164237/80843134-cbc99e00-8c03-11ea-8160-e6fc9aa6be4b.gif)

if the items are overlapped in your backpack, the tooltip is not updated when hovering the other item.

Using 0.1.3.500

**Comment by andreakarasho** [comment]
can't reproduce

**Comment by Novocaine85** [comment]
We are using spherex. Do you believe is server related?

**Comment by andreakarasho** [comment]
Is possible to login into this server?

**Comment by Novocaine85** [comment]
Sure, you visit our shard some time ago to fix our vendor. If I'm not wrong
our server admin have not deleted your account. However, I'll contact you
on discord ASAP.

Il Mar 5 Mag 2020, 08:45 Andrea Angelini <notifications@github.com> ha
scritto:

**Comment by andreakarasho** [comment]
fixed
