### ISSUE TITLE
Body.def (and probably other .def files) override priorities

### ISSUE THREAD

**Issue by brndd** [ClassicUO/ClassicUO#1061]
I'm just writing this bug up here so that I don't forget about it myself if I don't get to it tomorrow.

`Body.def` is used to override some animations with different animations, apparently. It's possible to define multiple overrides for the same animation in the same file. This probably shouldn't be done, but some servers with customization do this anyway, likely in error.

If the same override is defined multiple times, like here (excerpt from a real example from a real server, line numbers added by me for clarity):
```
[line 312]
669 {909} 0
[line 425]
669 {447} 0
[line 427]
669 {710} 0
```

The original client will use the **first** override and ignore all overrides after it.

ClassicUO will instead assign all the overrides as it gets to them (reading the file top-to-bottom), in effect using the **last** override. This will result in items getting different graphics than on the original client.

## suggested fixes

1. A simple, dumb fix: read `body.def` (and probably other .def files) backwards, so the first override in the file applies instead of the last one

2. A complicated, dumb fix: put some sort of a variable flag in the `IndexAnimation`, such as `AlreadyReadFromDefFileDontAssignIntoMeAnymore`, and if that flag is true then skip over the entry. https://github.com/andreakarasho/ClassicUO/blob/master/src/IO/Resources/AnimationsLoader.cs#L617

**Comment by andreakarasho** [comment]
solved thanks
