### ISSUE TITLE
Items Are Not Shown After Cutting Body

### ISSUE THREAD

**Issue by tazmanyak** [ClassicUO/ClassicUO#1065]
After cutting body in to peaces, not all of items are shown on the ground.

**Comment by andreakarasho** [comment]
Tested in local with lastest DEV [0.1.3.641] and it works.
Did you try to see if missing parts are overlapped each other?

**Comment by tazmanyak** [comment]
When I cut it, everyhing just disappered not overlapped. Only bod parts are shown on the ground but not the items inside of corpse.

**Comment by andreakarasho** [comment]
Still working in local with 0.1.3.641+ , because i pushed a fix yesterday about corpses
![image](https://user-images.githubusercontent.com/20810422/81067402-e7bc9080-8ede-11ea-938c-fb1ffd8c4055.png)

**Comment by andreakarasho** [comment]
This pr should solve this issue https://github.com/andreakarasho/ClassicUO/pull/1070
