### ISSUE TITLE
Target Does Not Work On Groud After Last Dev Build

### ISSUE THREAD

**Issue by tazmanyak** [ClassicUO/ClassicUO#1068]
When I try to cast Wall of Stone or other ground level Spells, I cannot select ground to target.

**Comment by andreakarasho** [comment]
What server ?

**Comment by tazmanyak** [comment]
Sphere Server. But in previous dev of ClassicUO ,  I did not have such problem.

**Comment by andreakarasho** [comment]
Is possible to login into that server?
I need to analyze the network

**Comment by tazmanyak** [comment]
I deleted and downloded again the all source, now it is working.

**Comment by andreakarasho** [comment]
Actually it is working because i forced the code.
I want to take open it until i’ll figure out how it really works.

Note for me: check the cursortype (object/ground). This is a potential solution

**Comment by andreakarasho** [comment]
> Note for me: check the cursortype (object/ground). This is a potential solution

This should solve. Pushed fix to dev
