### ISSUE TITLE
Body.def override parsing is wrong

### ISSUE THREAD

**Issue by brndd** [ClassicUO/ClassicUO#1072]
This one looks like another stinker.

Body.def has the following line for silver steeds (animation id 117):
`117 {200, 226, 228, 204} 1154`

On the **original client**, silver steeds look like this:

![1588969958238](https://user-images.githubusercontent.com/5822375/81446973-6dad3580-9184-11ea-9808-fc6030d2f458.png)

On ClassicUO (and, to cut us some credit, in UOFiddler also), they look like this:

![1588969928886](https://user-images.githubusercontent.com/5822375/81446980-7140bc80-9184-11ea-9ade-b0b9b167cc71.png)

## Why is this happening

ClassicUO picks the first override from body.def, 200, and uses that graphic. However, the original client for some unknown reason picks the **third** override, 228. I do not yet know why.

## How do we fix this

We figure out the real logic for which of these 4 overrides is picked, then implement that logic into AnimationsLoader.cs.

## How do we test this

Can be tested on eg. latest POL using the standard POL distro by spawning a silver steed with `.createnpc silversteed`. I'm sure it will also work on ServUO and others.

**Comment by brndd** [comment]
I asked Grimoric on the ServUO forums about this, and he told me that the original client first selects a random value, but then **overwrites that random value** with the 3rd value if it exists and the 1st value if it doesn't. Yes, really.

So the initial hunch I had is literally the behaviour it's supposed to have.

Big thanks to Grimoric for helping us out on this.

**Comment by andreakarasho** [comment]
solved thanks
