### ISSUE TITLE
Bars don't magnetically attach properly

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#1077]
When you have a few bars (and maybe in other situations) - they dont attach properly at the bottom anymore.

See gif:

https://imgur.com/I4DU9dn

**Comment by andreakarasho** [comment]
I can't reproduce.
what's happen if you press ALT?

**Comment by BlackTeaOutlands** [comment]
Alt doesn't do anything obvious.

I can't reproduce it reliably either. But it seems to happen if you pull several bars, and the problem is the bottom anchor spot.

**Comment by BlackTeaOutlands** [comment]
Happening quite frequently.

Seems to be related to one specific bar that becomes buggy. That specific bar can then not be attached to other bars (usually top or bottom anchoring position), but I also had instances where it could not be attached anywhere.

If you drag the bugged bar and hold ALT then it seemed to fix it (but I havent tried it enough yet to know for sure).

**Comment by andreakarasho** [comment]
these bars are restored after logout due to the "save bars on logout" option?

**Comment by BlackTeaOutlands** [comment]
They are saved, but upon relogging the bugged bar was attached to another bar and was working again. Also it seems that a random bar that I didnt see before appeared upon login.

Could there be ghosted bars that are bugging it out?

**Comment by BlackTeaOutlands** [comment]
I feel this is related. When you grab bars sometimes it doesnt attach to your cursor properly. In the example below I click on the mob and hold and grab. Usually you grab the bar without problem. I have sallos easy grab on. This behaviour is something that started happening recently.

https://imgur.com/74CKrlp

**Comment by andreakarasho** [comment]
fixed
