### ISSUE TITLE
Humanoid mobile corpses are drawn naked with warning messages produced in console

### ISSUE THREAD

**Issue by Agetian** [ClassicUO/ClassicUO#1078]
After a relatively recent automatic update ClassicUO started manifesting erroneous behavior with mobile corpses, in particular, the effect is seen on humanoid mobile corpses. Visually the issue manifests itself in the fact that a mobile is drawn completely naked (despite having worn clothes when it died), and in the console I'm getting the following messages which didn't used to appear in prior versions of ClassicUO:

```
ADD ITEM TO CONTAINER -- CLEAR HOLD
08:52:11 |  Trace   | Bitstream: 0 bytes read == sync?
08:54:14 |  Trace   | Bitstream: 0 bytes read == sync?
08:55:50 |  Trace   | Bitstream: 0 bytes read == sync?
08:56:05 |  Warning | No container (68211975) found
08:56:05 |  Warning | No container (282396452) found
08:56:05 |  Warning | AddItemToContainer function adds mobile as Item
08:56:05 |  Warning | No container (3573861440) found
08:56:05 |  Warning | No container (151142402) found
08:56:05 |  Warning | No container (8387874) found
08:56:05 |  Warning | AddItemToContainer function adds mobile as Item
08:56:05 |  Warning | No container (0) found
```

This effect can be seen when playing Ultima Odyssey server (RunUO 2.2-based, client 7.0.15.1), not sure how/if this manifests itself on other servers and shards.

Operating System: Linux Mint 18.3
ClassicUO version: 0.1.3.750 (after automatic update)
Running a local copy of Ultima Odyssey.

**Comment by andreakarasho** [comment]
everything looks fine here.
Where can i download odyssey?

**Comment by Agetian** [comment]
Both the server and the client packages are available here:
https://www.servuo.com/archive/ultima-odyssey.1117/

To reproduce, log in as Wizard (password: admin), spawn a mobile (e.g. [add thief), then [kill it. For me, it consistently reproduces with the mobile drawn naked and with the warning messages spawned in the console.

**Comment by Agetian** [comment]
Also, just tried it on standard Ultima Online client, and it works fine there (the mobile is drawn with the clothes on when he dies :) )

**Comment by andreakarasho** [comment]
fixed in dev

**Comment by Agetian** [comment]
I can confirm the primary issue with the mobile being undressed being fixed. However, I'm now always getting a strange "UNUSED" object in the inventory of a dead mobile (see screenshot):
![изображение](https://user-images.githubusercontent.com/24357441/82404753-be693c00-9a6a-11ea-95de-357fe3435aec.png)

On a separate note, the light in this build is also very strange - it's a separate issue (and I'll post it as a separate issue),but looks like something broke very recently related to it, now it's some kind of eerie bright or pale green. I'm on Linux Mint 18.3 if it matters :)

**Comment by Agetian** [comment]
Also regarding the original naked corpses issue - I noticed that currently, when the death animation is played, the mobile will be drawn naked for a split second and then turn back to being dressed, while in the original client it's dressed during the animation too (maybe it's a bit of nitpicking, but I thought I'd report my observation too :D )

Thanks again for looking into this! :)

**Comment by andreakarasho** [comment]
Please don’t mix multiple issues. Open other threada

**Comment by Agetian** [comment]
I already did :) Just thought I'd mention it here since there's a two-in-one on a single screenshot :)

**Comment by Agetian** [comment]
The "unused" object is most likely related to this issue though, its appearance appears to coincide with the fix for this issue (but that said, I'll prolly open a separate thread for this as well, just in case)
