### ISSUE TITLE
Bug Report: Disabling tooltips doesn't tooltips from displaying.

### ISSUE THREAD

**Issue by Admin-Yukiko** [ClassicUO/ClassicUO#1080]
I unchecked the "Use tooltip", clicked the "Apply" button and clicked the "Okay" button to close the options gump. When I hover over an item, the tooltips still appear.

**Comment by andreakarasho** [comment]
over server entities it will work.
Not over gumps

**Comment by Admin-Yukiko** [comment]
That is odd because when I change it on the standard client between "Follow mouse" and single-click tooltips work properly. Unfortunately, there is no way to disable tooltips entirely in the standard client. So I used the best options available to compare.

**Comment by andreakarasho** [comment]
Because CUO does not support the "tooltip display mode"

**Comment by Admin-Yukiko** [comment]
I hope it will be placed on the road map. I am distracted very easily by unnecessary pop-ups on the screen.

**Comment by andreakarasho** [comment]
Maybe you didn’t noticed my answer here :) 
https://github.com/andreakarasho/ClassicUO/issues/1079
