### ISSUE TITLE
War boar graphic and mount animation is wrong.

### ISSUE THREAD

**Issue by Admin-Yukiko** [ClassicUO/ClassicUO#1082]
This is a new mount. As far as I know, there is no NPC for the war boar. I think it is one of the anniversary gifts. Anyway, the graphic for the war boar item, and the mounted animation, does not display correctly in ClassicUO. UOFiddler does not have the graphic fixed yet either.
The item graphic is :0xA554.
The mount piece is 0x3ED2.

ClassicUO graphic:
![wrong_war_bear_graphic](https://user-images.githubusercontent.com/14107983/82259783-a4850780-994b-11ea-8139-c9ecc73aa4cc.jpg)

Standard client graphic:
![correct_war_bear_graphic](https://user-images.githubusercontent.com/14107983/82259872-c7172080-994b-11ea-847f-4d1c9d74d49b.jpg)

ClassicUO mounted animation:
![wrong_war_bear_when_mounted](https://user-images.githubusercontent.com/14107983/82259934-e44bef00-994b-11ea-9eb0-95cd52bea7f1.jpg)

Standard client animation:
![correct_war_bear_when_mounted](https://user-images.githubusercontent.com/14107983/82259980-faf24600-994b-11ea-9dfb-b5afc9084a13.jpg)

**Comment by andreakarasho** [comment]
I added the war boar mount today:
https://github.com/andreakarasho/ClassicUO/commit/530124373293b47ceb714070849f6aa1b7345732

And if I remember well both item and mount showed correctly.
What cuo version are you using?

**Comment by Admin-Yukiko** [comment]
0.1.3.600

**Comment by andreakarasho** [comment]
So you are compiling cuo by yourself. 
Try to pull with git

**Comment by Admin-Yukiko** [comment]
Ok. I take it that is the current version?

**Comment by andreakarasho** [comment]
Try with dev binaries directly, i think it’s will work

https://github.com/andreakarasho/ClassicUO/releases/tag/ClassicUO-dev-preview

**Comment by Admin-Yukiko** [comment]
The same issue exists with the build you posted. I am using UO client 7.0.85.15

**Comment by andreakarasho** [comment]
This is so weird. Are you sure that cuo is pointing to the right uo folder?
What server is it?

**Comment by Admin-Yukiko** [comment]
It is POL server. I just recloned the ClassicUO source, built the solution and now it is crashing. I will post crash log and settings.json in Discord.

**Comment by Admin-Yukiko** [comment]
After deleting my copy of ClassicUO repo and recloning it and closing the open, not logged in standard client, CUO ran with no crashes. 
Anyway, the item graphic for the war boar displays correctly but the mounted animation still shows the character mounted but the mount is invisible.

**Comment by andreakarasho** [comment]
![image](https://user-images.githubusercontent.com/20810422/82448793-8550bc00-9aaa-11ea-8b60-8d7a7c0690ed.png)

as i said, here works with a fresh UO installation

**Comment by Admin-Yukiko** [comment]
Very strange. I just did a clean install of UO and the issue is still present for me. I will see if I can find out if I am doing something that is causing it but right now I cannot see where I could be introducing the problem.

**Comment by andreakarasho** [comment]
Cuo implements 0x3ED2 as mount layer item. 
I wonder if your server puts it in another layer

**Comment by Admin-Yukiko** [comment]
It is applied to the mount layer, if I remember correctly that is 0x25.
I managed to resolve the issue. Do not ask me how. I performed another reinstall of the client. I deleted my copy of the CUO repo and recloned it, checked out the dev branch again. Now it works. It is very frustrating when you cannot figure out what went wrong but I am glad it works. :)
