### ISSUE TITLE
Most of the lighting is displayed as eerie green (bright or pale)

### ISSUE THREAD

**Issue by Agetian** [ClassicUO/ClassicUO#1083]
Starting with a recent build, I'm now getting a strange green lighting in many (most?) places in the game, which is either bright green or eerie pale green instead of traditional yellowish:

![изображение](https://user-images.githubusercontent.com/24357441/82404850-05573180-9a6b-11ea-9d73-89efc8962399.png)
![изображение](https://user-images.githubusercontent.com/24357441/82404894-19029800-9a6b-11ea-9055-afc21920e789.png)

This is a very recent change, maybe related to the hue changes in the recent commits (at first I started getting a very pale coloring on item descriptions, now those appear to be back to normal, but the ingame light turned green).

Operating system: Linux Mint 18.3
ClassicUO build: recent snapshot from 8 hours ago as of this writing (was testing the naked corpse fix)
Server: Ultima Odyssey running locally (RunUO 2.2-based, client 7.0.15.1)

**Comment by andreakarasho** [comment]
can you give me some coords to test?

**Comment by Agetian** [comment]
Sure thing,
For example, the screenshots above were made at (2989, 1043) in Trammel. The issue most likely manifests itself at night time.

**Comment by Agetian** [comment]
By the way, tested this on standard stock ServUO running on client 7.0.85.15 and I have the same effect - for example, all the lamp post lights are tinted green in Britain (e.g. in Felucca).

**Comment by andreakarasho** [comment]
ok, let's continue here
https://github.com/andreakarasho/ClassicUO/issues/786
