### ISSUE TITLE
An "unused" object appears in dead mobiles' corpses

### ISSUE THREAD

**Issue by Agetian** [ClassicUO/ClassicUO#1084]
As a followup to the issue with mobile corpses behaving strangely lately, I'm now getting a strange object marked "Unused" in the top left corner of the dead mobile's inventory. If I double click it, it seems to disappear with no trace. This is also on Ultima Odyssey, with client 7.0.15.1 assets.
Screenshot attached.

![изображение](https://user-images.githubusercontent.com/24357441/82411357-4e62b200-9a7a-11ea-8ef0-02562736d60c.png)

This consistently reproduces if I kill a NPC (e.g. [add thief, then [kill) and look inside its inventory.
This didn't used to happen before a very recent build, so it might be related to the fix for the naked corpses.

Operating system: Linux Mint 18.3
ClassicUO version: latest snapshot from Appveyor as of this writing
Server: Ultima Odyssey (RunUO 2.2-based, client 7.0.15.1)

**Comment by andreakarasho** [comment]
fixed
