### ISSUE TITLE
As GM on sphere, .info updates skills gump

### ISSUE THREAD

**Issue by Novocaine85** [ClassicUO/ClassicUO#1092]
Hello.

As a GameMaster on a Sphere based server, when i do .info on a character, my skills gump update the skills of that character.

How to reproduce:

Start a new SphereX server and create an admin/gm account and login.
Set your skills whatever you like.
Open Skills gump to check skills.
Create a player account
Set skills differently to that player.
With .info, check the player.
You'll see the admin skills gump change with the skills that the target had at that moment.

video sample (zipped)
[classicuobug.zip](https://github.com/andreakarasho/ClassicUO/files/4676740/classicuobug.zip)

Thanks

**Comment by andreakarasho** [comment]
is possible to connect to this server?

**Comment by Novocaine85** [comment]
Sure. I'll contact you very soon.

**Comment by andreakarasho** [comment]
not cuo related
