### ISSUE TITLE
Please make “reduce fps when game is inactive” checked by default

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#1094]
This is something I help cuo users check on a daily basis. Thanks!
![579E0504-93C1-4EB1-A16D-47B9DE28EFFF](https://user-images.githubusercontent.com/26830362/82910369-2ec30200-9f30-11ea-9065-38549cccab5c.png)

**Comment by Admin-Yukiko** [comment]
Seems logical to me.

**Comment by andreakarasho** [comment]
done !
