### ISSUE TITLE
Updating razor enhanced to the latest

### ISSUE THREAD

**Issue by daat99** [ClassicUO/ClassicUO#1096]
Razor enhanced was updated and added some very useful features (like auto-loot agent).
Will be nice to have it implemented or a guide on how to update the local razor plugin.

**Comment by andreakarasho** [comment]
```json
{
  "ip": "SERVER_IP_ADDRESS",
  "port": 2593,
  "ultimaonlinedirectory": "YOUR/PATH/TO/ULTIMA_ONLINE_INSTALLATION",
  "clientversion": "7.0.15.1",
  "plugins": [
    "./Assistant/Razor.dll",
  ]
}
```

Replace the ./Assistant/Razor.dll path with your razorenhanced path.
Don't forget that all plugins must be site in `CUO_FOLDER/Plugins/` folder

**Comment by daat99** [comment]
when I download razor enhanced I don't see razor.dll (or razorenhanced.dll) only "razorenhanced.exe".
what should I write in the plugin in that case or am I downloading the wrong razor enhanced?

**Comment by andreakarasho** [comment]
put the name of the executable, so: RazorEnhanced.exe

**Comment by daat99** [comment]
Thank you, works great
