### ISSUE TITLE
Problem with installing with PowerShell script (no settings.json)

### ISSUE THREAD

**Issue by LukaszChrzanowski** [ClassicUO/ClassicUO#1097]
Hello,

I've problem with installing (I've installed the same way two weeks before with no problems on this same machine):

Steps for reproduce:
1. Created new folder for game
2. Used PowerShellScript (options: y, 1)
![obraz](https://user-images.githubusercontent.com/34500544/82959316-bacc3c80-9fb7-11ea-82f2-5142f6db3072.png)

**Comment by andreakarasho** [comment]
It's not a "error",
powershell runs cuo to create an empty settings.json as usual.
From latest cuo version [and dev too] cuo will advice you with the msg above if settings.json is invalid.

Just click ok and continue the powershell setup

**Comment by LukaszChrzanowski** [comment]
Thank You - that helped a lot
