### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by LukaszChrzanowski** [ClassicUO/ClassicUO#1098]
Is there a way to enable logging to standard output (console) or to file?

Every time i open any book my client crashes and after death I cannot move until restart.
I would like to share details of this bugs, but cannot becouse of lack of any errors.
I know that I could install Visual Stufdio and see there - but it would be nice to see stacktraces without enabling debuggning by VS.

**Comment by LukaszChrzanowski** [comment]
update - I found logs in LOG directory- that solves first issue 
`System.IndexOutOfRangeException:Index out of bounds.
   w ClassicUO.Network.PacketHandlers.BookData(Packet p)
   w ClassicUO.Network.PacketHandlers.OnPacket(Object sender, Packet p)
   w ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender)
   w ClassicUO.Network.NetClient.Update()`

but in second case no clue how to verify and checks what's happens

**Comment by andreakarasho** [comment]
Dont’t mix issues in a single post, open a new one. Thanks :)
