### ISSUE TITLE
Client closing on opening a book

### ISSUE THREAD

**Issue by LukaszChrzanowski** [ClassicUO/ClassicUO#1099]
When opening any book Client crashes:

`
System.IndexOutOfRangeException:Index out of bounds. w ClassicUO.Network.PacketHandlers.BookData(Packet p) w ClassicUO.Network.PacketHandlers.OnPacket(Object sender, Packet p) w ClassicUO.Utility.Exstentions.Raise[T](EventHandler1 handler, T e, Object sender)
`

**Comment by andreakarasho** [comment]
Does it happen with .600 cuo version too?
(I can’t try atm)

**Comment by LukaszChrzanowski** [comment]
yeap. Problem still persists

**Comment by LukaszChrzanowski** [comment]
I've debugged it and found that pages also can have page number equal or less 0.

This resolved issue:
PacketHandlers.cs line 1836
`
 if (pageNum <= pages.Length && pageNum > 0)
`

after that books looks fine :)

Could I have request to add this to next version?

**Comment by andreakarasho** [comment]
yep thanks!
