### ISSUE TITLE
After death cannot move

### ISSUE THREAD

**Issue by LukaszChrzanowski** [ClassicUO/ClassicUO#1100]
After death cannot move in any direction. Have to restart client.
Tried to check options in Video suited with "death" (white screen) - nothing helps.

Nothing in LOG file.

**Comment by andreakarasho** [comment]
what server do you play?

**Comment by LukaszChrzanowski** [comment]
One of Polish shards, from about 12 years now. :)

**Comment by andreakarasho** [comment]
i need to connect to this shard. Can you give me a link?

**Comment by LukaszChrzanowski** [comment]
if You want an account I have to talk with admins there to create one special for You. If only a link:
"ip": " *deleted due request from admins*
 "port":  *deleted due request from admins*

**Comment by andreakarasho** [comment]
What CUO version are you using?

**Comment by LukaszChrzanowski** [comment]
ok, You have simply to register at:XXXX

**Comment by LukaszChrzanowski** [comment]
laterst stable release, in config:
 "clientversion": "7.0.85.15",

installed yesterday from powershellscript

**Comment by LukaszChrzanowski** [comment]
if You want I can show You on Discord desktop sharing what's happens and how it looks

**Comment by LukaszChrzanowski** [comment]
problem is crucial for us (that's not only my problem, but for random people using ClassicUOClient) - this bug occurs every time - therefore You did great job creating this Client for UO that even this inconvenience isn't stopping us for using it :).

**Comment by andreakarasho** [comment]
i tried with latest CUO [.600] and i can move

**Comment by LukaszChrzanowski** [comment]
Yes! I've updated to latest client and works.
