### ISSUE TITLE
Inventory and backpack in paperdoll disappers after killing something

### ISSUE THREAD

**Issue by LukaszChrzanowski** [ClassicUO/ClassicUO#1107]
Hello,

To reproduce:

1) have open backpack (inventory)
2) kill something (bear, panther) that have no loot and doubleclick on corpse
3) move away few steps

Inventory and backpack disappears  - after that there is no way to open inventory (either from tooltab or using shortcut (alt+i)). After restarting client - everything goes back to normal

No scripts used at the moment - tried on clean install (defaults) - latest stable version.

**Comment by andreakarasho** [comment]
write me on discord please

**Comment by LukaszChrzanowski** [comment]
I'm on Your's discord channel now - what's Your's nick? (mine: Aru)

**Comment by andreakarasho** [comment]
fixed in dev
