### ISSUE TITLE
Layering issues observed in dev 

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#1111]
Thanks for reviewing.
a. gold was transferred from chest to pack horse and fell on the ground (new UO outlands change, did not go back to container is not CUO related)

b. however the gold did not appear on my screen. Went to bank, no gold!

c. went back to guild house used ctrl+shift to locate gold piles, it was hard to tell if invisible or underneath the carpet/rug

d. I do have circle of transparency on (tested at 50 and 150 similar experience). 

e. also observed if you go very far out of range, the objects will render (roughly 16-18 tiles away)

f. this last behavior was also observed at ice fort the night previously
-sometimes the outlines of floor tiles would be "above" the "snow piles" that are on top or "cut through" the snow piles
-however if you went 16-18 tiles away, the tiles would render properly

thank you!
[2020-05-30_11-18-17_dump_gameobject.txt](https://github.com/andreakarasho/ClassicUO/files/4706018/2020-05-30_11-18-17_dump_gameobject.txt)

[2020-05-30_11-19-30_dump_gameobject.txt](https://github.com/andreakarasho/ClassicUO/files/4706017/2020-05-30_11-19-30_dump_gameobject.txt)

![image](https://user-images.githubusercontent.com/26830362/83333783-f5f49700-a267-11ea-968a-9db42f890cd1.png)

far away looks better:
![image](https://user-images.githubusercontent.com/26830362/83333792-00169580-a268-11ea-8bbb-05a2ba1ef012.png)

closer (still outside of transparency range) it started to break:
![image](https://user-images.githubusercontent.com/26830362/83333812-17558300-a268-11ea-98a1-c3426b2a9c6b.png)

**Comment by oroechimaru** [comment]
boss clippin'
![2020-06-03 19_45_08-Start](https://user-images.githubusercontent.com/26830362/83710631-d0101f00-a5e6-11ea-8454-8a910e13a6ae.png)
[2020-06-03_07-44-54_dump_gameobject.txt](https://github.com/andreakarasho/ClassicUO/files/4727276/2020-06-03_07-44-54_dump_gameobject.txt)

**Comment by andreakarasho** [comment]
NOTE: #1110

**Comment by oroechimaru** [comment]
New bug... layers complete cutoff when near carpet or other tiles (plants are cutoff)
![A25F696F-645C-4AC1-B076-5C614690C64D](https://user-images.githubusercontent.com/26830362/86698263-c5c1b600-bfd4-11ea-98a9-b726e205e4cc.png)
