### ISSUE TITLE
Plate Arms Appear Under Chain Chest

### ISSUE THREAD

**Issue by aclark13** [ClassicUO/ClassicUO#1115]
Platemail arms are appearing under the chainmail chest piece on the paperdoll.  Should show over top.

Arms
Graphic 5143 (0x1417)
Layer says Invalid in CUO (steam layer says 19)

Chest
Graphic 5060 (0x13c4)
Layer says Invalid (steam layer says 13)
![image](https://user-images.githubusercontent.com/38568913/83973663-9de41300-a8ad-11ea-80ba-5d3d70ce2ef2.png)

![image](https://user-images.githubusercontent.com/38568913/83973720-e4d20880-a8ad-11ea-9f1b-964a27331c32.png)

**Comment by andreakarasho** [comment]
fixed
