### ISSUE TITLE
Land tiles appear stretched in house customization tool

### ISSUE THREAD

**Issue by Agetian** [ClassicUO/ClassicUO#1119]
When playing Ultima Odyssey (client 7.0.15.1, RunUO 2.1) and attempting to customize the house layout, the land tiles appear vertically stretched, with the bottom ones being partly covered by the top ones and partly invisible. To reproduce:

1. Login as admin (Wizard / admin) to a local copy of Ultima Odyssey.
2. [add houseplacementtool
3. Place a customizable house (e.g. a standard 2-floor 7x7 custom house).
4. Activate the customization tool and switch over to the land tiles.

You'll see the land tiles being stretched vertically.
In standard client (7.0.15.1), the land tiles appear normal.

Example of the issue:
![image](https://user-images.githubusercontent.com/24357441/84227795-fa357580-aaed-11ea-95c0-5660cadecb1b.png)

The same game, running on stock client 7.0.15.1 (non-ClassicUO):
![image](https://user-images.githubusercontent.com/24357441/84227851-251fc980-aaee-11ea-9176-8f8b9a9736c7.png)

This is tested on ClassicUO dev 0.1.3.810 and a few previous releases.
OS Linux Mint 18.3.

**Comment by 3HMonkey** [comment]
Same here on UOForever with 7.0.45.0 and Windows 10.

**Comment by Agetian** [comment]
It looks like the problem may be that the height of the floor tiles is set incorrectly or something like that, modifying AddFloor in HouseCustomizationGump so that the height of the floor tiles is e.g. 48 instead of 120 makes things look better.

**Comment by andreakarasho** [comment]
fixed
