### ISSUE TITLE
Invisible items in loot grid on human mage enemies in Odyssey

### ISSUE THREAD

**Issue by Agetian** [ClassicUO/ClassicUO#1121]
In the current dev build of ClassicUO (version 810), invisible items marked as "Unused" appear in the top left slot of loot grid or slots for humanoid enemies, primarily mages (most other types seem unaffected). These items do not appear in the standard corpse loot gump, only in the loot grid when it's enabled. It's impossible to determine what these items are, it's not possible to "take" them or [props them, that results in no effect.

This doesn't happen in the same version of Odyssey using an older build of ClassicUO, for example, version 0.1.3.500. 

An example of the issue:
![image](https://user-images.githubusercontent.com/24357441/84247050-31b51980-ab10-11ea-8340-60b6ffe92930.png)

To reproduce the issue:
1. Start a local copy of Ultima Odyssey, log in as admin (Wizard / admin).
2. Make sure the Grid Loot mode is enabled.
3. [add evilmage
4. [kill the spawned evil mage
5. Check the corpse in Grid Loot mode.

**Comment by andreakarasho** [comment]
fixed
