### ISSUE TITLE
Skill gump capturing your typing cursor

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#1122]
If I click on the label to edit a skill category name, the typing cursor gets locked there and cannot be recovered for typing text or for using hotkeys.

To fix it you have to close and reopen the skill gump.

![image](https://user-images.githubusercontent.com/39037141/84506116-2522f380-acbf-11ea-931d-0169fcf0bdef.png)

**Comment by andreakarasho** [comment]
fixed in dev thanks
