### ISSUE TITLE
Can't see item tooltips from other bags or banks owned by other players as GM

### ISSUE THREAD

**Issue by Novocaine85** [ClassicUO/ClassicUO#1123]
Hi,

while playing as gamemaster and trying to check banks or items in bags of players currently offline, I'm unable to see any tooltip of their items.

It was working in version dev .666

in current dev version tooltips are not shown anymore.

Our server is using spherex

Thanks

**Comment by andreakarasho** [comment]
.666 ? 
I should try on this server

**Comment by Novocaine85** [comment]
Sorry. I was sure that was working on .666 but I was wrong. I'll try to contact you tonight. We should check together also bug #1092 . I had no time those days. :(

**Comment by andreakarasho** [comment]
not cuo related.
