### ISSUE TITLE
Build on macOS (and most likely on Linux) is broken after recent merge of fna-3d branch into dev

### ISSUE THREAD

**Issue by binff04** [ClassicUO/ClassicUO#1124]
Just tried to build current dev (with fna-3d merge) on macOS and it's failing now with the next error(s):

```
/usr/local/Cellar/mono/6.8.0.105/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5187,5): error MSB3073: The command "if not exist "/Users/mel/Projects/ClassicUO/bin/Release/lib64/" mkdir  "/Users/mel/Projects/ClassicUO/bin/Release/lib64/" [/Users/mel/Projects/ClassicUO/src/ClassicUO.csproj]
...
```

The problem is in this post build event:

```
<PropertyGroup>
    <PostBuildEvent>if not exist "$(TargetDir)lib64\" mkdir  "$(TargetDir)lib64\"
if not exist "$(TargetDir)osx\" mkdir  "$(TargetDir)osx\"
if not exist "$(TargetDir)x64\" mkdir  "$(TargetDir)x64\"

xcopy $(SolutionDir)external\lib64\*.*   $(TargetDir)lib64\   /Y
xcopy $(SolutionDir)external\osx\*.*      $(TargetDir)osx\    /Y
xcopy $(SolutionDir)external\x64\*.*      $(TargetDir)x64\    /Y

    </PostBuildEvent>
</PropertyGroup>
```

It doesn't work when building on macOS and most likely will not work on Linux too due to the usage of platform-dependent commands (`if not exist`, `xcopy`).

**Comment by andreakarasho** [comment]
fixed in dev.
I tried it on Ubuntu 20 and it worked. Let me know

**Comment by binff04** [comment]
You are using non-macOS-compatible options in `cp` commands. You need to use `cp -Rf source_dir/*.* target_dir/` instead, so it will work on both macOS and Linux.

`man cp` for macOS: https://ss64.com/osx/cp.html
`man cp` for Linux: https://linux.die.net/man/1/cp

**Comment by binff04** [comment]
Here is the pull request that fixes this: https://github.com/andreakarasho/ClassicUO/pull/1128
