### ISSUE TITLE
Bald Hair Doesn't Work on Char Creation

### ISSUE THREAD

**Issue by aclark13** [ClassicUO/ClassicUO#1126]
Selecting "None" for hair doesn't update the paperdoll image on the character creation screen.  It also doesn't apply "None" for the character when created.

Latest Dev
UO Outlands

![image](https://user-images.githubusercontent.com/38568913/84778253-585bd000-afa8-11ea-9c23-f362e5ae745c.png)

![image](https://user-images.githubusercontent.com/38568913/84778299-6c9fcd00-afa8-11ea-8878-79b829f7592a.png)

**Comment by andreakarasho** [comment]
fixed
