### ISSUE TITLE
Update Trees.txt

### ISSUE THREAD

**Issue by aclark13** [ClassicUO/ClassicUO#1130]
Trees tested on UO Outlands - may differ on other shards.

4790, 4791, 4796, 4797 all need to be added to hide tress but NOT marked as stumps since they are passable (parts of the yew tree foliage)
![image](https://user-images.githubusercontent.com/38568913/85300452-2b0d9700-b46c-11ea-8aa3-767116fe6e42.png)

also 12596, 12593, 3221, 3222, 12602, 12599, 3238, 3225, 3229, 3228, 3227 are jungle trees that aren't in the trees.txt
12881 is a weird log/stump thing that might be a good idea to put in trees since its impassable
all the 3k ones are little deco trees but are impassable (at least on outlands)

I personally added all these to my Trees.txt
```12596=0
12593=0
3221=0
3222=0
12596=0
12593=0
3221=0
3222=0
12602=0
12599=0
3238=0
3225=0
3229=0
12881=0
3228=0
3227=0
```

**Comment by aclark13** [comment]
Update from Gaechti on Discord....
The Yew tree branches seem to need a special case programmed.
They dont have the foliage tag:
4790
4791
4796
4797

These are good to be added:
3221
3222
3238
3225
3229
3228
3227

Theese seem to be server specific:
12596
12593
12602
12599

on fiddler with OSI client theyr unused tiles:
(or I did something wrong when loading the files)
![image](https://user-images.githubusercontent.com/38568913/85300769-9a838680-b46c-11ea-8752-33d25465a35a.png)

**Comment by gaechti** [comment]
More trees have just recently been added:
3221
3222
3225
3227
3228
3229
3238
3383
3384

https://github.com/andreakarasho/ClassicUO/pull/1314

Whats left is the Yew tree branches

Question is, hard code it or make a foliage.txt?
@andreakarasho 

If you want I can look into it. But I'd like to know if hard code or a foliage.txt is preffered
