### ISSUE TITLE
Health Bars Getting Extra Words

### ISSUE THREAD

**Issue by aclark13** [ClassicUO/ClassicUO#1134]
Been getting a lot of this lately.  This players name was just "Fish Eye".  Getting the Razor on the end, and then it appears to be trying to repeat the name.

![image](https://user-images.githubusercontent.com/38568913/85744070-35c56780-b6ca-11ea-81d0-b1cc99dad5cb.png)

**Comment by andreakarasho** [comment]
pushed a fix.

**Comment by andreakarasho** [comment]
i consider it closed. If it will happen i'll reopen the issue
