### ISSUE TITLE
Book crashes when page count is 40

### ISSUE THREAD

**Issue by andreakarasho** [ClassicUO/ClassicUO#1137]
Graphic does not handle big textures creation.

EDIT: the crash reason seems to be different.

**Comment by 2dchaos** [comment]
Just a quick update, apparently only "locked" books have this issue, unlocked books can be opened. Also, when trying to paste text over the character limit of any book, there's a crash.

**Comment by oroechimaru** [comment]
@2dchaos  post crash logs please from cuo logs folder thanks! Should be able to upload them here or use code tags and paste

**Comment by LukaszChrzanowski** [comment]
have in mind, that code in  ModernBookGump.class:ServerSetBookText  is adding "\n":
` if (i + 1 < l && (string.IsNullOrWhiteSpace(BookLines[i])  || w + sw < _bookPage.renderedText.MaxWidth))
                {
                    sb.Append('\n');
                    BookLines[i] += '\n';
                }`
but it should check also is current line already containing "\n". This was case in my issue. This doubled output lines more than 160 lines.
This issue and fix that was working for it, is described by me in here: https://github.com/andreakarasho/ClassicUO/issues/1258

**Comment by LukaszChrzanowski** [comment]
Guys - I've found that this is a reason why this crashes overall - finally method that generate graphic for book try to put 8 lines per page and in method "ServerSetBookText" are adding "\n" even if in line there is one - so in the end lines for books are more than 160 - so checking before there is "\n" before adding "\n" and before send lines to method that generates book gump - there should be something like regex to find and replace multiple ocurences "\n" to one per line!

**Comment by andreakarasho** [comment]
i think this behaviour can be added at packet reading and exclude `\n` character

**Comment by LukaszChrzanowski** [comment]
this is effect:
![obraz](https://user-images.githubusercontent.com/34500544/100926504-d58de980-34e3-11eb-9850-cb6ddc28bf3b.png)
and after that it interpretes single '\n' as a new line:
![obraz](https://user-images.githubusercontent.com/34500544/100926564-f0605e00-34e3-11eb-8e66-cc486ad58c3d.png)

and this is going to method to generate book gump, so it has more than 160 lines. and this is reason why this crashes.

@andreakarasho - even if You exclude new line character when reading book (therefore You will loose line breaks) it will be added more than once in ServerSetBookText() in if on 89 line:
` 
                if (i + 1 < l && (string.IsNullOrWhiteSpace(BookLines[i]) && !BookLines[i].Contains("\n") || w + sw < _bookPage.renderedText.MaxWidth))
                {
                    sb.Append('\n');
                    BookLines[i] += '\n';
                }
`
I think more optimal for compatibility for older servers is adding before line 97:
` _bookPage.SetText(sb.ToString());`
regex that will replace occurence to one per line. Maybe something like that:
`BookLines[i] = Regex.Replace(BookLines[i], "\n.*", "");`
or checking on line 89 in that if - is there already \n on line:
` if (i + 1 < l && (string.IsNullOrWhiteSpace(BookLines[i]) && !BookLines[i].Contains("\n") || w + sw < _bookPage.renderedText.MaxWidth))`
