### ISSUE TITLE
Old PoL Shard Tooltip Partially Working

### ISSUE THREAD

**Issue by HankTheDrunk** [ClassicUO/ClassicUO#1139]
Tooltips don't appear on my paperdoll items or main backpack items until I drag each individual item, as well as other player's/npc's paperdoll individual items which I obviously cant drag.
Edit: players/npc names also do not appear when clicked or hovered over.
Edit: Bankbox items and sub container items don't have tooltips until dragged.

When I open any container inside my main backpack all the items inside those containers have properly working tooltips.
edit: items on corpses have proper tooltips
edit: player/npc corpses have proper tooltips
This is new, I can't say when but in prior versions not even sub containers items had tooltips.
My hope is that this information is relevant enough to solve the problem.

I unfortunately can't get you access to this shard, it's a private roleplay shard that dates back to the early 2000s
I can record a video demonstrating if required. I'll provide any information you want.

Version: The latest Classic dev available as of this message.  The uo client version is 5.0.8.3

**Comment by andreakarasho** [comment]
>  The latest Classic dev available as of this message
.925 or more?
if it is, can i login to this server?

**Comment by HankTheDrunk** [comment]
Version 0.1.3.927
I'd have to supply you with my login information, since accounts are created by GMs

**Comment by andreakarasho** [comment]
join the CUO discord and send me a pvt: 
https://discord.gg/VdyCpjQ

**Comment by andreakarasho** [comment]
fixed!
