### ISSUE TITLE
Journal filters (system/objects/client) similar to orion UO 

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#1141]
https://github.com/Hotride/OrionUO/blob/master/OrionUO/Gumps/GumpJournal.h
https://github.com/Hotride/OrionUO/blob/master/OrionUO/Gumps/GumpJournal.cpp
https://github.com/Hotride/OrionUO/wiki/Journal-Orion-Assistant

![image](https://user-images.githubusercontent.com/26830362/86399539-0b951c00-bc6d-11ea-9e5f-255a3cb3e9e3.png)

possibly related to:
https://github.com/andreakarasho/ClassicUO/issues/205
 #205

**Comment by andreakarasho** [comment]
done in dev!
