### ISSUE TITLE
Direct3d is ignoring Nvidia Geforce vsync settings

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#1142]
Bug:
a. monitor refresh rate is 75hz
b. I set FPS to 144 in classicuo, which should only be possible with vsync off.
c. Enable vsync "on", adaptive vsync or off , all three scenarios stay at 144fps.

It seems that vsync is being ignored in D3D (possibly FNA issue?) . This is ok, I am not having screen tearing/fps jitterness like in OpenGL, close if this is deemed a non-important issue or headache.

Pre-direct3d, I was able to use vsync for openGL. However when FPS would drop for a second I would experience jitterness. This went away when direct3d was implemented  along with for openGL using "adaptive vsync" or "vsync off".

**Comment by andreakarasho** [comment]
seems fixed in latest FNA
