### ISSUE TITLE
Character description on Paperdoll is read-only

### ISSUE THREAD

**Issue by TyrAntilles2** [ClassicUO/ClassicUO#1143]
Heya. As i reported here on Discord [https://discordapp.com/channels/290936867199909888/531582541078069248/728888656705617920](url)
this feature doesn't seem to work in CUO.  I am using it for RP, so I hope it will be implemented.
I mean is working to read what was previously written with the 2D client, but in CUO I cannot write there.

It looks like I can;t add photo here, but is the first rolled map on bottom-left on paperdoll, near the party manifest.
Ah, photo from discord is here: [https://cdn.discordapp.com/attachments/531582541078069248/728888653019086888/J20200704_112039.png](url)

**Comment by oroechimaru** [comment]
![0045EB4A-2578-424E-B329-5950048924C8](https://user-images.githubusercontent.com/26830362/86520714-22727480-be0d-11ea-9439-ef203cbcbf66.png)

**Comment by andreakarasho** [comment]
fixed
