### ISSUE TITLE
journal filters working as intended?

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#1147]
a. alliance chat is occurring under SYSTEM from other players but shows up under objects for me.
- guild members that type appear under system, however my responses in guild chat and alliance appear under objects

b. say/yell/guild are occurring under Objects
-its not overly useful due to the object spam

c. anyway to have a custom "chat" filter that only shows say/yell etc/guild/party/alliance? currently its not as useful since you miss messages or spam for too many. 

d. "you see", half occur under "objects" and other half under "client", can these "you see" be moved entirely to "client" that way "objects" is cleaned up to be more chat like? 

e. if there was a "chat filter", have it pick up:
[guild]
[alliance]
say, yell etc ? 

![image](https://user-images.githubusercontent.com/26830362/86679674-6909cf80-bfc3-11ea-9221-47e9bd922f6e.png)

![image](https://user-images.githubusercontent.com/26830362/86679712-71faa100-bfc3-11ea-8bb2-5da401905b31.png)

![image](https://user-images.githubusercontent.com/26830362/86679873-98b8d780-bfc3-11ea-8abe-52aa242522b6.png)

**Comment by oroechimaru** [comment]
after " fix text filtering - andreakarasho" 
- similar issues
a. system now has alliance/guild chats
b. objects now has local say/yell/whisper chats. Objects filter gets flooded with corpse and local pvm/pvp activity and is difficult to find journal entries

SUGGESTION: move all local chat (say etc) to SYSTEM since its a lot cleaner than objects spam in practice =)
-or an all communications filter

![image](https://user-images.githubusercontent.com/26830362/86816807-e4ae5f80-c049-11ea-97ea-05f0c629afd4.png)

![image](https://user-images.githubusercontent.com/26830362/86816862-f55ed580-c049-11ea-9132-cf5a71fbbfe6.png)

**Comment by andreakarasho** [comment]
System: all text that appears on bottom-left
Objects: text above mobiles and items
Client: internal client messages

The screen seems good

**Comment by oroechimaru** [comment]
ok so for journal to work for comms you have to check system and objects . I think from a coding perspective its working. From a user functionality perspective it would be awesome if [guild] and [alliance] from system were a chat filter flag, that then included the local speech from objects. Doesn't seem like that is possible , if its not just close it out:)

![image](https://user-images.githubusercontent.com/26830362/86832291-9905b100-c05d-11ea-96c5-3ab97bd103ab.png)

**Comment by andreakarasho** [comment]
Justo to track what i said in discord:
I tried to add the guild/ally filter, but it does not work in the same way for all servers because when receiving an ally message it can be sent as a Regular system text, so you will see these msgs as System text. This makes the option a waste of UI space. 
Im evaluating to add it tought.

**Comment by oroechimaru** [comment]
Understandable:)

**Comment by Admin-Yukiko** [comment]
KaRaShO,
Is it a different packet for each type of chat (guild or ally) or is it a different sub-command in the packet? If you can give me the details I will have out POL developers check to assure POL is compliant and, if not, I will urge them to fix the issue.

**Comment by andreakarasho** [comment]
This one: http://docs.polserver.com/packets/index.php?Packet=0xAE
I added the guild/ally filter in the journal. 
I hope this will not cause a flood of: "it does not work!11!"
