### ISSUE TITLE
Uncropped artwork has faulty offset in containers 

### ISSUE THREAD

**Issue by owyn-outlands** [ClassicUO/ClassicUO#1148]
This is the native file that has been loaded into the art files. 
![Item-29989](https://user-images.githubusercontent.com/45541111/86874807-21f90880-c0af-11ea-8bdd-d1e51322ccbe.jpg)

This is the way the item appears in containers.  Out of reach/unmovable for players.
![unknown](https://user-images.githubusercontent.com/45541111/86874493-79e33f80-c0ae-11ea-99e0-c2b8c45be423.png)

Proposed solution:  ignore all black space/offset

**Comment by andreakarasho** [comment]
What graphic is it?

**Comment by owyn-outlands** [comment]
> What graphic is it?

29989 

This is just one example of many that function this way due to the amount of black space around them.  If it's possible to fix via code that would be ideal, otherwise I can fix the art.

**Comment by gaechti** [comment]
Well if the original client ignores the black part/offset, so should classicUO

**Comment by andreakarasho** [comment]
fixed in dev.
There was a bug when casting negative INTEGER to an USHORT value.

![image](https://user-images.githubusercontent.com/20810422/87013807-7d201d80-c1cb-11ea-932b-cef0bf531dea.png)

**Comment by owyn-outlands** [comment]
Thank you, @andreakarasho!
