### ISSUE TITLE
Issue with targeting prompt using Chivalry

### ISSUE THREAD

**Issue by George-Semple** [ClassicUO/ClassicUO#1149]
Warning pops before targeting prompt. Clicking 'Ignore' works and allows targeting. 

To duplicate, cast Close Wounds. Warning box will popup. Click Ignore and target.
![image](https://user-images.githubusercontent.com/12295138/86961661-34af2400-c127-11ea-9970-e719f5af0a81.png)

**Comment by oroechimaru** [comment]
Maybe add how to connect to server details for testing:)

**Comment by andreakarasho** [comment]
It is a razor issue.
Ask here: https://github.com/markdwags/Razor/issues/

**Comment by George-Semple** [comment]
Thanks for the quick work!  I'll shake my fist at Razor.
