### ISSUE TITLE
Screenhot path and name written with green text

### ISSUE THREAD

**Issue by TyrAntilles2** [ClassicUO/ClassicUO#1150]
Please, make an option to disable the green text on screen and journal for Screenshots. Or an option to just disable screenshots.
* * *
I am sorry to post this here but I see no other way. Please don't get upset on me.  I asked many times on Discord for a way to stop showing the path and name of screenshot on screen and journal every time I hit PrintScreen.
Reasons:
- I share many screenshots and I don't want others to see that path on my computer.
- I am into RP and that green text is ruining my screenhots I want to use in RP.
- I see no reason for that ugly long green text to appear every time a screenshot is taken.
- I don't use razor internal screenshots ever as I capture my screen with PicPick. The only time I go to screeshots folder in CUO is to delete them all.
- An option to disable the showing of screenshot path should be very easy to implement. Or an option to disable CUO screenshots completely so i won't need to go to delete them every time.
𝕊𝕪𝕣𝕦𝕡𝕫-𝕌𝕆 even sent me a way to fix it, but I am not tech savvy and i don;t know how to implement this fix: https://discordapp.com/channels/290936867199909888/531582541078069248/731083270678118400

**Comment by deccer** [comment]
Hi @TyrAntilles2 there is a new entry now in options
`Hide "Screenshot saved in" Message` in the general options.
