### ISSUE TITLE
Bug: Full name is not displayed in name bar

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#1152]
Full name is not always displayed in name bar

Look below. Before, the name used to be truncated if it was too long, which was helpful. Look in the below example, there are so many mobs called "an ossuarian..." and it would be helpful to see the first few letters of the third word.

![image](https://user-images.githubusercontent.com/39037141/87201523-0c7a1d80-c2ff-11ea-8cf7-c482f5b5e183.png)

**Comment by BlackTeaOutlands** [comment]
Another example
![image](https://user-images.githubusercontent.com/39037141/87203577-35041680-c303-11ea-956c-703a7d6a66c4.png)

Seems like if full text doenst fit, it doesnt write truncated.

**Comment by andreakarasho** [comment]
fixed
