### ISSUE TITLE
Bug? Drop Item in Hand doesn't always show the item in your backpack after dropped

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#1157]
If you use the razor function to Drop What you are Currently Holding, it does not always display the item after it has been dropped to your backpack.

What it does it should drop the item in your hand into your backpack.

The setup I'm using when I notice this bug is pulling items from this blue chest here and dropping them in my backpack using Drop What you are Currently Holding.

![image](https://user-images.githubusercontent.com/39037141/87852382-caa23600-c901-11ea-81bc-7eaecec002fd.png)

**Comment by SaschaKP** [comment]
this is not currently related to CUO, Razor bugs should be addressed to https://github.com/markdwags/Razor
