### ISSUE TITLE
Ninjitsu Missing From Classic Skill Gump

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#1160]
The new skill list has it but the classic skill list gump does not.

**Comment by andreakarasho** [comment]
Try to delete the skillgroups.xml
![image](https://user-images.githubusercontent.com/20810422/88062161-bdd34b80-cb68-11ea-93e1-ed51c4e9e3df.png)

**Comment by Djeryv** [comment]
That worked. Thanks.
