### ISSUE TITLE
Circle of Transparency cannot be used to pick up/drop items behind buildings

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#1161]
https://cdn.discordapp.com/attachments/599124913265049610/735190171330281482/unknown.png

Old client to the left. CUO to the right.

In old client you can pick up the nightshade and drop items there. In CUO you can not drop items OR pick up items. 

It seems the circle of transaprency is not strong enough in CUO.

**Comment by andreakarasho** [comment]
fixed
