### ISSUE TITLE
Some containers have incorrect geometry after 0.1.4.0

### ISSUE THREAD

**Issue by beevik** [ClassicUO/ClassicUO#1165]
After patch 0.1.4.0, the armoire and fancy armoire containers no longer allow you to use the upper visual half of the container.  

A possible cause could be the container geometry changes in this commit: https://github.com/andreakarasho/ClassicUO/commit/d18ddd639a6812f8c000ba72d900cdfd39aa0f9c

**Comment by andreakarasho** [comment]
fixed!
