### ISSUE TITLE
UseSkill Imbuing macro does not work

### ISSUE THREAD

**Issue by VoxelBoy** [ClassicUO/ClassicUO#1166]
Triggering the Imbuing skill from the Skills gump brings up the Imbuing gump correctly, however setting up a simple "UseSkill Imbuing" macro does not do anything. Looking at the code, in MacroManager.cs line 822, there's a check against 0xFF and in the byte[] _skillTable declared at the top of the file, we can see that 0xFF is marked with a comment saying /*imbuing*/. Not sure why Imbuing is being disregarded like this but I feel like the "UseSkill Imbuing" macro should bring up the same gump that the Imbuing skill button does from the Skill gump.

**Comment by andreakarasho** [comment]
fixed
