### ISSUE TITLE
Unable to see the easel item in game

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#1168]
When an easel is in game, it cannot be seen.

5.0.8.3 on OSI vs on ClassicUO (I tested on the latest release and the latest dev code base)

![image](https://user-images.githubusercontent.com/577652/89103372-05fb3500-d3d7-11ea-8c3c-41c6dce5125a.png)

**Comment by andreakarasho** [comment]
I think i fixed it. Not sure how standard client handles this specific item, because the NoDiagonal flag (HoverOver) forces items to be invisble in older client versions. Infact newest do not have this flag.

**Comment by markdwags** [comment]
Looks good, thank you! 
![image](https://user-images.githubusercontent.com/577652/89105432-a9a01180-d3e6-11ea-833a-c122eca167cd.png)
