### ISSUE TITLE
Variables with apostrophes causes strange behavior in razor scripting

### ISSUE THREAD

**Issue by Kadoba** [ClassicUO/ClassicUO#1169]
Using either an item name or a macro variable that contains an apostrophe will cause lifttype to only move 1 of the item, regardless of the stack size parameter. I haven't tested this with other commands.

Variables with apostrophes will also mess up the color formatting if you load or paste code until you try editing the line.

```
// lifts up to 999 nightshade
lifttype "nightshade" 999
drop backpack 28 104 0
wait 1100

// lifts 1 spider's silk
lifttype "spider's silk" 999
drop backpack 28 104 0
```

**Comment by andreakarasho** [comment]
i think it's better if you post this issue on razor git: https://github.com/markdwags/Razor/issues
