### ISSUE TITLE
Dropping a bookshelf into a container makes bookshelf disappear

### ISSUE THREAD

**Issue by blendax78** [ClassicUO/ClassicUO#1170]
When dropping a bookshelf into a container (tested by dropping into another bookshelf).  The dropped shelf is no longer visible (and thus cannot be taken out of the container).  Its weight registers on the parent container, but there's no way to access it.

In the old client, the bookshelf is visible in the container.

**Comment by andreakarasho** [comment]
server?

**Comment by blendax78** [comment]
UO: Renaissance.

Sorry if I'm missing any details. First time I've posted a bug before.

**Comment by andreakarasho** [comment]
im trying on UOR test center and it works with cuo 0.1.4.35.
What cuo version do you use?

**Comment by blendax78** [comment]
I was speaking with one of the UOR developers ... and it seems like I'm using an outdated version of CUO... 0.1.3.600. He also tried it in 0.1.4.35.  Sorry for the confusion.  This bug can be closed!

**Comment by andreakarasho** [comment]
no problem, glad you solved :)
