### ISSUE TITLE
Hold Item on Cursor

### ISSUE THREAD

**Issue by aclark13** [ClassicUO/ClassicUO#1174]
On steam if you pick up and item with your cursor and use ctrl+scroll down it will lock the item to your cursor on the screen, but will allow you to click other objects.  This is very useful to protect against thieves, and to gate hop heavy items.  You can open runebooks, spellbooks, cast, etc all while the item is safely on your cursor.  The only thing you can't do is pick up other items.

https://streamable.com/0jphv3

**Comment by andreakarasho** [comment]
done!
