### ISSUE TITLE
Shadow Not Offsetting Properly

### ISSUE THREAD

**Issue by GoldDraco72** [ClassicUO/ClassicUO#1175]
I wouldn't call this a bug if we are comparing this to UO exactly, but it is a bug in the sense of how the system should handle shadows! Since they are not in the OSI client and are in CUO, could I suggest you have them find the surface z and draw them there instead of a constant offset to mobile! 

Here is my problem as it pertains to the shadow, I have made a flying system and it works good on the normal client, I added shadows that show on the ground but in the CUO client it is messed up do to the additional shadows, so I have it cancel out my shadows if someone is using CUO, but the shadows in CUO are off and don't look right for when a mobile is 10+ z off the ground! 

I looked at your code and can fix this myself but thought it would be a good inclusion to the main client as the shadow should always find the surface, not just offset from the mobile regardless of surface!

Besides that, great client! +++

**Comment by andreakarasho** [comment]
UO in general does not have the "layer" concept due to the isometric and tiled nature. So i'ts not possible to "cast to terrain" only.

Do you want post a screenshot of the issue? Maybe there is some math mismatch

**Comment by GoldDraco72** [comment]
I see, so the shadow is fixed to the animation? No biggy as I saw there is a toggle to turn shadows off which solves the issue as my custom flying system comes with shadows, not as good as UOC but they follow the surface or static, what ever is higher and below the flying mobile. 

My flying system utilizes the z in the maps, most of them have 100 z zone to move up/down in, since UO was never meant for such a system, I’ve had to make work arounds, ie the shadows to give the feeling of height!

With the default UOC shadows, when you go up, so does the shadow! Not sure you need a screenshot, just use the command [m incz 1, target frozen mobile in game and watch the shadow follow them up in z’s, idealy, the shadow should stay on the ground!
