### ISSUE TITLE
ClassicUO client crashing at startup

### ISSUE THREAD

**Issue by Kraker01** [ClassicUO/ClassicUO#1176]
All'avvio di ClassicUO, ricevo questo errore:

Nome dell'applicazione che ha generato l'errore: TmClient.exe, versione: 0.1.3.0, timestamp: 0x5eae8ec6
Nome del modulo che ha generato l'errore: unknown, versione: 0.0.0.0, timestamp: 0x00000000
Codice eccezione: 0xc0000005
Offset errore 0x00007ffa3d941ad6
ID processo che ha generato l'errore: 0x2d30
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d67600566ea178
Percorso dell'applicazione che ha generato l'errore: C:\The Miracle PD\TmClient.exe
Percorso del modulo che ha generato l'errore: unknown
ID segnalazione: 2c42b892-1ac3-405f-b408-54652813c606
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore: 
Applicazione: TmClient.exe
Versione framework: v4.0.30319
Descrizione: il processo è stato terminato a causa di un'eccezione non gestita.
Informazioni sull'eccezione: System.NullReferenceException
   in ClassicUO.Bootstrap.Main(System.String[])

Bucket errato , tipo 0
Nome evento: CLR20r3
Risposta: Non disponibile
ID CAB: 0

Firma problema: 
P1: TmClient.exe
P2: 0.1.3.0
P3: 5eae8ec6
P4: ClassicUO
P5: 0.1.3.0
P6: 5eae8ec6
P7: 30
P8: 11e
P9: System.NullReferenceException
P10: 

File allegati:

I file potrebbero essere disponibili qui:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_TmClient.exe_77b035d1459a9bc2f942d6aa3bbebc1c86a2fc7e_e6cabedc_dc557199-e543-4b3d-8049-cd785e35cec8

Simbolo analisi: 
Nuova ricerca di soluzioni: 0
ID rapporto: 2c42b892-1ac3-405f-b408-54652813c606
Stato rapporto: 524388
Bucket con hash: 
GUID CAB: 0

Bucket errato , tipo 0
Nome evento: CLR20r3
Risposta: Non disponibile
ID CAB: 0

Firma problema: 
P1: TmClient.exe
P2: 0.1.3.0
P3: 5eae8ec6
P4: ClassicUO
P5: 0.1.3.0
P6: 5eae8ec6
P7: 30
P8: 11e
P9: System.NullReferenceException
P10: 

File allegati:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFB4B.tmp.WERInternalMetadata.xml

I file potrebbero essere disponibili qui:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_TmClient.exe_77b035d1459a9bc2f942d6aa3bbebc1c86a2fc7e_e6cabedc_dc557199-e543-4b3d-8049-cd785e35cec8

Simbolo analisi: 
Nuova ricerca di soluzioni: 0
ID rapporto: 2c42b892-1ac3-405f-b408-54652813c606
Stato rapporto: 524388
Bucket con hash:

**Comment by SaschaKP** [comment]
Ciao, miracle usa un suo sviluppo a parte, parla con @TannerBist.

Comunque only english
