### ISSUE TITLE
Enhancement: ctrl+shift show names, show guild tags

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#1177]
This would be great for roleplayers so I don't have to single click them all when busy thanks a ton! 

just guild tag not all the titles.

**Comment by SaschaKP** [comment]
you mean an extra option?

**Comment by oroechimaru** [comment]
Hmm I am ok either way but it would be nice! Especially when in large parties for a boss or roleplaying sometimes want to see who is what guild and not click each person. Thanks!!

**Comment by Hezkore** [comment]
I'd really like an option where it shows all times but no corpses.

**Comment by roxya** [comment]
Closing because it's not possible
