### ISSUE TITLE
Tooltip Hover Text

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#1178]
I can no longer hover over items and characters to have the tooltip show the names, stats, etc. I confirmed it is enabled in options and it worked previously...but now it has a T2A behavior where I have to single click things to get the name of it only.

**Comment by SaschaKP** [comment]
I have tried and couldn't get this issue in any way.

Can you give some more info that maybe can help us understand why this is happening?
(client version, it is a custom one or the dev one? shard? an img of the problem...the log of the client would also help out)

**Comment by Djeryv** [comment]
I updated today and it is back to normal.
