### ISSUE TITLE
Incorrect seated graphic facing North

### ISSUE THREAD

**Issue by owyn-outlands** [ClassicUO/ClassicUO#1183]
ClassicUO: 
![unknown](https://user-images.githubusercontent.com/45541111/91058880-fe563700-e5f6-11ea-8a72-204ec7416b92.png)

Original Client:  
![unknown](https://user-images.githubusercontent.com/45541111/91058890-044c1800-e5f7-11ea-8aa9-c25b0f1ec6d9.png)

**Comment by andreakarasho** [comment]
done
