### ISSUE TITLE
1.4.96 (since .90 or earlier): unable to see item descriptions when single clicking in trade windows

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#1184]
Trade window items, when single click them do not display the item description/name tags. Thanks!

**Comment by andreakarasho** [comment]
seems working with latest cuo dev vers [0.1.4.100]

**Comment by oroechimaru** [comment]
Hmm people are reporting it on outlands. @roxya  do you have this issue on outlands launcher? A few folks and myself had it last night. Maybe its an issue with outlands build?

**Comment by oroechimaru** [comment]
Confirmed fixed in 1.4.102 (not 100 though for outlands players) . Thanks!!!
