### ISSUE TITLE
Fix Compile_Shaders.bat

### ISSUE THREAD

**Issue by deccer** [ClassicUO/ClassicUO#1185]
**Problem:**
Currently `ClassicUO\shaders\compile_shaders.bat` is looking into `C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\` to find `fxc.exe` to compile the few .fx shader effect files we have. 

This should be fixed since not everyone has the Windows Kit in that specific Version.

**Solution:**
Provide a powershell script which is iteratively going through 
`C:\Program Files (x86)\Windows Kits` to find the most recent `fxc.exe` (in the most recent installed version of the sdk) to set its path there in order to call `fxc.exe`

**Support:**
To install Windows SDKs use the Visual Studio 2019 Installer
Goto Modify -> Individual Components -> SDKs, libraries and frameworks
and find the Windows SDKs at the end of that list.

**Comment by roxya** [comment]
https://github.com/ClassicUO/ClassicUO/commit/88bb5fa68176f9909dc56cc6d9959d7015f4ee2b
