### ISSUE TITLE
Items in bags can go outside of boundary

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#1188]
I'm not sure if this is an Outlands issue or if it's something the client is doing.
But I often get items at the edge of my bag, which aren't a "valid" draggable position.

Look at this fishing rod.
It's in the corner of the bag, and when I try to place it in the corner manually; it ends up way closer to the center.
![2020-08-25_19-08-20](https://user-images.githubusercontent.com/1727541/91205783-65164600-e706-11ea-8367-34b733eb2779.gif)

And this may be unrelated.
But I've noticed that items (at least on Outlands) now very often appear in the lower right corner, instead of randomly in the bag like before.

**Comment by Hezkore** [comment]
Having crafted a bunch of clubs, I can say, with 100% certainty, that items are incorrectly placed too far to the bottom right.
It might be the server (Outlands) or it might be the client, I don't know.

![ClassicUO_2020-09-03_19-46-30](https://user-images.githubusercontent.com/1727541/92149455-56264680-ee1e-11ea-86e8-4c642ccd7024.png)

**Comment by Belialzao** [comment]
Options > Containers > Rebuild containers.txt ;)

**Comment by Hezkore** [comment]
Very much the same result.

![ClassicUO_2020-09-03_21-04-51](https://user-images.githubusercontent.com/1727541/92156353-20d32600-ee29-11ea-98b4-1eab537b86f4.png)

**Comment by andreakarasho** [comment]
would be cool to test with original client. Can you do that?
