### ISSUE TITLE
Request:  Add .editorconfig file at root of solution folder to force spaces.

### ISSUE THREAD

**Issue by wiscow** [ClassicUO/ClassicUO#1199]
I usually have my environment setup for tabs.  In order to force spaces at the solution level an .editorconfig file would be nice so that developers don't have to change their global settings in visual studio.

This file can also be used to force any other coding standards that are required of the repository.

**Comment by andreakarasho** [comment]
I totally agree. CUO needs a code standardization.

Today i found this one: https://github.com/DotNetAnalyzers/StyleCopAnalyzers and @deccer proposed this stylecop https://gist.github.com/deccer/4101f05264548d2d1681fc7ffa13e9dc

csproj implementation:

```csharp
 <PropertyGroup>
    <CodeAnalysisRuleSet>..\ClassicUO.StyleCop.ruleset</CodeAnalysisRuleSet>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
```

**Comment by wiscow** [comment]
Yeah StyleCop would work too.  The nice thing about an `.editorconfig` file is that visual studio natively supports it and doesn't require an extension.  It also automatically overrides your visual studio settings unless you explicitly turn it off.  With that said, I *think* StyleCop may have more functionality as an Analyzer.  I have really only used .editorconfig for simple formatting and ReSharper as my Analyzer (which also will adhere to your .editorconfig settings).

**Comment by deccer** [comment]
I created a first draft of an `.editorconfig`

https://gist.github.com/deccer/435a6490e0aee87bd317b328d7ac59bb

**Comment by andreakarasho** [comment]
done
