### ISSUE TITLE
Feature Request: Highlight container on opened container hover. Like UOTD client (Third Dawn)

### ISSUE THREAD

**Issue by Nic84** [ClassicUO/ClassicUO#1201]
UO Third Dawn client used to have a simple but useful feature, the containers get highlighted when you hover the mouse over the opened container.

![Containers Highlight](https://user-images.githubusercontent.com/11181203/91642926-97c18680-ea05-11ea-8a93-aa0e881ebfd0.gif)

Benefits: 

1 - When you have multiple bags open (searching for something) and decide drag one to your backpack, you don't know which one is that, you need to close and re open them till you open the correct one and finally drag it.

2 - When you open multiple containers looking for something and move your character while opening more and more, sometimes you want to drag some items and you cannot because you are "too far away" but the thing is that you don't know which direction you need to move to grab it.

Maybe more, but I can't remember now. I feel it's a good qol and won't affect gameplay, maybe toggleable under options is a good idea.

Thanks!!

**Comment by andreakarasho** [comment]
cool feature. done

**Comment by Nic84** [comment]
Great!! Thank you
