### ISSUE TITLE
Health bars won't close when creature out of range

### ISSUE THREAD

**Issue by spectre-1337** [ClassicUO/ClassicUO#1202]
**Describe the bug**
When health bars are stuck together and a creature dies out of range, the health bars cannot be closed by right click.

**To Reproduce**
1. Open two health bars and stick them together
2. Run away from the creatures
3. Try to close the health bars that are stuck together with right click
4. Health bars will not close

**Expected behavior**
When a creature dies, their health bar should be removed. If they are out of range, the health bar should go to its "greyed out" state like the official client and the health bar should be able to be closed.

**Screenshots**
See video: https://streamable.com/p0u4on

**Shard**
 - Name of the shard: Ultima Online Forever

**Information (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.18363.900]
 - ClassicUO Version: 0.1.4.112
 - [ ] Using DEV Version?
 - Launcher: classicuo_launcher

**Additional context**
 - How many clients do you run in parallel: 1
 - Screen Resolution: [e.g. 1920x1080] Screen Resolution : 1920x1080  --- Game Resolution: Scaled manually by dragging.

**Comment by Alias-Alan** [comment]
Healthbars are anchorable(anchored in your case), there will appear a lock gump if you hover, you can click that to un-anchor it. I wonder if a feature to close if dead and if anchored would garner traction, maybe set it to only close non-player bars.

**Comment by aclark13** [comment]
Working as expected
