### ISSUE TITLE
Hair and facial hair items being shown in player corpses

### ISSUE THREAD

**Issue by spectre-1337** [ClassicUO/ClassicUO#1203]
**Describe the bug**
Hair and facial hair are being shown in player corpses as items

**To Reproduce**
1. Find a dead player (might also be an issue with human npc)
2. Open their body (doesn't matter if fresh corpse or bones)
3. Observe hair and facial hair items shown on the corpse as their text placeholder

**Expected behavior**
Hair and facial hair items should not be shown within the corpse loot gump

**Screenshots**
Screenshot attached

**Shard**
 - Name of the shard: Ultima Online Forever

**Information (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.18363.900]
 - ClassicUO Version: 0.1.4.112
 - [ ] Using DEV Version?
 - Launcher: classicuo_launcher

**Additional context**
 - How many clients do you run in parallel: 1
 - Screen Resolution: [e.g. 1920x1080] Screen Resolution : 1920x1080  --- Game Resolution: Scaled manually by dragging.
<img width="470" alt="Corpsehair" src="https://user-images.githubusercontent.com/16633665/91656921-02aca500-ea7a-11ea-97e6-f081c096968c.PNG">

**Comment by andreakarasho** [comment]
do an "-info" in game, select one of these items, hit "Dump" button and post the log here please

**Comment by sirdonpiano** [comment]
###################################################
CUO version: 0.1.5.39
OBJECT TYPE: ClassicUO.Game.GameObjects.Item
AllowedToDraw = True
AlphaHue = 0
Amount = 1
AnimIndex = 0
ClosedObjectHandles = False
Container = 1124106574
CurrentRenderIndex = 0
Direction = North
DisplayedGraphic = 12239
Distance = 2159
Exists = True
Flags = None
FoliageIndex = -1
FrameInfo = {X:0 Y:0 Width:0 Height:0}
Graphic = 12239
Hits = 0
HitsMax = 0
HitsPercentage = 0
HitsTexture = null
Hue = 2101
IsClicked = False
IsCoin = False
IsCorpse = False
IsDamageable = False
IsDestroyed = False
IsEmpty = True
IsHidden = False
IsLocked = False
IsLootable = False
IsMulti = False
IsPositionChanged = False
Items = null
LastStepTime = 0
Layer = Invalid
LightID = 0
MultiDistanceBonus = 0
MultiGraphic = 0
MultiInfo = null
Name = null
Next = null
ObjectHandlesOpened = False
Offset = {X:0 Y:0 Z:0}
OnGround = False
Opened = False
Previous = ClassicUO.Game.GameObjects.Item
Price = 0
PriorityZ = 0
RealScreenPosition = {X:0 Y:0}
RootContainer = 1124106577
Serial = 1124107733
TextContainer = null
TNext = null
TPrevious = null
UsedLayer = False
UseInRender = 0
UseObjectHandles = False
WantUpdateMulti = True
X = 48
Y = 98
Z = 0
###################################################

**Comment by andreakarasho** [comment]
fixed in https://github.com/ClassicUO/ClassicUO/commit/3afaacf55b3f712b615f9c491d229493df215498
