### ISSUE TITLE
Rendering Issue on World Load

### ISSUE THREAD

**Issue by aclark13** [ClassicUO/ClassicUO#1207]
**Describe the bug**
The screen becomes large grayscale boxes when minimized during world load.

**To Reproduce**
1. Start CUO on login
2. During the world load screen click the "show desktop" button in the windows taskbar.
3. Maximize CUO and the screen appears with the image below.

**Expected behavior**
CUO should load the world normally even when in the background.

**Screenshots**
![image](https://user-images.githubusercontent.com/38568913/91992826-35fd6700-ecfa-11ea-9b0d-1b5deb0255cf.png)

**Information (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19041.450]
 - ClassicUO Version: Latest dev
 - Launcher: Compiled with VB

**Additional context**
Single client running
Nvidia GT 730 running at 1680x1050

**Comment by andreakarasho** [comment]
Can't reproduce it anymore. FNA fixed it [?]

**Comment by andreakarasho** [comment]
update: The error has been reported by another user in the FNA discord, so it is not a CUO issue
