### ISSUE TITLE
World Map and Water Tiles

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#1224]
On 0.1.5.35...I noticed on the World Map that some water tiles are not showing. Here you can see there is a spot on the map not showing the water but the brown tile beneath the sea or maybe it is rendering tile the wrong color? You can also see the in game image of where I am at. I do have transparent water tiles here so you can see the sunken shipwreck. The in game radar system works and looks fine. The transparent tile seems to be working fine as that is the blue circle in the middle, but some of the sea tiles around it are showing brown.

![image](https://user-images.githubusercontent.com/49735284/94351175-da35ad80-001b-11eb-923f-37694d994ac8.png)

![image](https://user-images.githubusercontent.com/49735284/94351236-4b756080-001c-11eb-846a-e3da2b485548.png)

**Comment by Djeryv** [comment]
The only difference I could see with this is that the water tiles not showing on the world map are in the 0x5000 or higher range of ItemIDs. Everything else is lower than that and shows as blue water on the map just fine.

**Comment by andreakarasho** [comment]
what map is it? I'd like to test it

**Comment by Djeryv** [comment]
It is my single player UO game from here....

https://drive.google.com/drive/u/1/folders/10iYDHeQEgr6SWVIZdmE5bZdp7X2sQx98

Both client (Game.7z) and server (Odyssey.zip) are there.
