### ISSUE TITLE
Journal/Objects filters speech

### ISSUE THREAD

**Issue by hwirth** [ClassicUO/ClassicUO#1235]
I would like to filter "You see..." messages from Journal, but keep the displaying of names in-scenery intact.
Unchecking "Objects" in the journal removes all spoken text, too.

If you consider people and animals to be objects, then it is probably a bug, that speech is also filtered, and the naming of the option might be unlucky; I would call it "Mobiles" instead.

If I misunderstand the meaning of that option, please consider this a feature request to have the possibility to clean the journal from those pesky "You see:..." messages.

**Comment by hwirth** [comment]
Addendum: Unchecking "System" hides party messages.

Expected behavior: Only hide system messages.

**Comment by Stallind** [comment]
I've changed it to be filtered when checking the Guild/ally checkbox. 
https://github.com/andreakarasho/ClassicUO/commit/10464feeaeed2a78a4c38cae3f189013037c98aa
