### ISSUE TITLE
Log out via bedroll creates error message

### ISSUE THREAD

**Issue by hwirth** [ClassicUO/ClassicUO#1236]
When logging out on a secure camp by clicking a bedroll, the client brings up the message "Connection lost: Socket Error".

Expected behaviour: Should be the same as logging out using the button on the paperdoll.

**Comment by andreakarasho** [comment]
Server? 
Does it happen everytime you logout in this way?

**Comment by hwirth** [comment]
It seems to happen every time.
Client: Arch Linux/unmodified ClassicUO
Servers: Outlands, my local ServUO (unmodified)

**Comment by andreakarasho** [comment]
can you list the steps you done? I cant replicate the connection lost

**Comment by andreakarasho** [comment]
Unable to replicate the issue
