### ISSUE TITLE
[FEATURE] Tell me, WHICH macro uses that key assignment

### ISSUE THREAD

**Issue by hwirth** [ClassicUO/ClassicUO#1239]
When I get "This key combination already exists.", and I don't remember which macro I assigned it to, it is hard to find that macro. 

* In order to find it, I have to click every macro in the list and check the set key combo
* Because I cannot use the keyboard to scroll through the macro entries, I am forced to click every macro. I have to actively target each click, which makes that process slow.

Possible solutions:
* Ideally, have the gump tell me, which macro uses the key combination
* Alternatively, let me select the next macro in the list by pressing the down arrow key, so I can keep my gaze on the box with the key combination, thus making searching a lot faster

**Comment by Stallind** [comment]
Fixed by commit 
https://github.com/andreakarasho/ClassicUO/commit/9a601ac3fdf9abf2d8389f42b6a692b691463277
