### ISSUE TITLE
Avatars not sitting on couches

### ISSUE THREAD

**Issue by hwirth** [ClassicUO/ClassicUO#1244]
**Describe the bug**
Unlike with most items like chairs, couches seem not to be considered a place to sit.

1. Go to a couch.

**Expected behavior**
Avatar sits down

**Screenshots**
https://i.imgur.com/M612eQg.png

**Shard**
 - Outlands, though running the original CUO since I run Linux.

**Information (please complete the following information):**
 - Arch Linux
 - Using DEV Version.

**Comment by andreakarasho** [comment]
can you provide graphics of these items?

**Comment by hwirth** [comment]
I did :)

**Comment by andreakarasho** [comment]
No, what i meant is the item graphic code, not a picture :) 
To get the graphic follow these steps:
- write in game "-info"
- target the item
- search for the Graphic row
- click on the value
- copy here

**Comment by hwirth** [comment]
19596, 19590 show the bug. The north facing couch, I have, works properly.

**Comment by hwirth** [comment]
The hapsichord with the bench facing east has the bug too: 25542. I cannot easily place it facing south at the moment, so I don't have the other code right now.

**Comment by hwirth** [comment]
Tested on my local ServUO:

Not sitting down on:

Fancy Couch East (19594-19596)  [The other directions work: (19597-19599), (40029-40031), (40032-40034)]
Fancy Love Seat East (19592-19593), South (19590-19591)  [North and west facing work: (40025-40026), (40023-40024)]
Plush Love Seat East (19588-19589), South (19586-19587)
Rustic Bench East (3666-3667), South (3664-3665)

And

Elven Love Seat East (12424-12425), South (12426-12427) 
allow seating in all 4 directions (should only allow 2): https://i.imgur.com/9b7x6Fa.png

**Comment by hwirth** [comment]
Not sitting down:
Hapsichord East (25539-25540), South (25532-25533)

**Comment by broxen** [comment]
Can you all please retest now that #1306 has merged? This should be resolved.
