### ISSUE TITLE
Case sensitivity for MUL files & settings.json

### ISSUE THREAD

**Issue by Desttro** [ClassicUO/ClassicUO#1246]
**Describe the bug**
When your *.mul files start with a capital letter, for example, Tieldata.mul, Light.mul, ... and you are using Unix based system - in my case, Ubuntu 20.04 client will not start, because generally, Unix/Linux systems are case sensitive - they will see both files (one with a capital letter, one without) like two different files.
Since ClassicUO was maybe firstly developed for Windows, there is no issue on Windows, because it does not care about case sensitivity - Windows is case insensitive.

**To Reproduce**
1. Use Linux
2. Rename your mul files to the capital letter at start, e.g.: Tiledata.mul, Fonts.mul, ... (Tiledata is enough)
3. Start: ./ClassicUO
4. You will get messages, that these muls does not exist

**Expected behavior**
Start ClassicUO normally

**Information (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - ClassicUO Version: Beta - 0.1.5.000
 - Launcher: no launcher - starting ClassicUO directly

**EDIT:**
Also settings.json are affected, **cliloc**:
`"cliloc" : "cliloc.enu",`

**Comment by andreakarasho** [comment]
note: https://github.com/FNA-XNA/FNA/wiki/6:-FNA-Build-Options#case_sensitivity_hack 
this just open a Stream.

**Comment by andreakarasho** [comment]
https://github.com/ClassicUO/ClassicUO/pull/1435
