### ISSUE TITLE
Need a new macro for mining in Tur Mur.

### ISSUE THREAD

**Issue by roro4ever** [ClassicUO/ClassicUO#1252]
ClassicUo has a built-in macro named 'gather'. In most cases,it's handy,except minging in Tur Mur.
As you know, Tur Mur has no mine Cave, you can only mining on the mountain.
The built-in macro 'gather' can only dig the tile under character's foot, while mountain minging should mine adjacent tile.

Could you make a new macro 'mining in Tur Mur', or any other solution can resolve this?
Thank you.

**Comment by roro4ever** [comment]
I have write a uorazor script which can dig adjacent tile. But razor has no findtile command, so I have to wrote 4 scripts for the 4 directions(left/right/top/bottom), and manually hotkey them.

**Comment by andreakarasho** [comment]
> ClassicUo has a built-in macro named 'gather'. 

Not the real classicuo.

![](https://www.hynerd.it/wp-content/uploads/2020/09/Among-Us-cover-1.png)

Cheater detected.
