### ISSUE TITLE
Crafting menus dont load correct custom colors (hues.mul)

### ISSUE THREAD

**Issue by Iron-Wolf-UO** [ClassicUO/ClassicUO#1256]
Items with custom colors are shown correctly in the world, but shown wrongly in menus (like blacksmithing menu)
Using: Sphere X
Hues.mul attached for test
[hues.zip](https://github.com/andreakarasho/ClassicUO/files/5537934/hues.zip)

**Comment by andreakarasho** [comment]
- hue? write `-info` in CUO, target the item in your backpack with the correct hue, search for `Graphic` voice, click over the value column to copy the number, paste here the result
- is possible to try the server?

**Comment by Iron-Wolf-UO** [comment]
Hello, Thanks for reply.I cannot find ”Graphic voice”Only Graphic.  Login to the server is: 37.128.215.213 : 2593Free account is on http://iron-wolf.eu/?page_id=203

**Comment by andreakarasho** [comment]
Can't connect to the server.
I was wrong: i meant "Hue" voice

**Comment by andreakarasho** [comment]
fixed in https://github.com/ClassicUO/ClassicUO/commit/14c770ce0e6725dbebf09b8a4f91aa45a3bc175d
