### ISSUE TITLE
Reading a book crashes client (FNA2DTexture Error)

### ISSUE THREAD

**Issue by LukaszChrzanowski** [ClassicUO/ClassicUO#1258]
**Describe the bug**
Problem for shards with loing history - one update for runUO added "\n" to books already". In effect some books cannot be read due to more than 160 lines (in effect there was 498 lines) in string builder "sb" object in ServerSetBookText() in ModernBookGump.cs.

In debug mode it shows clear that "\n" is added more and more to the lines of the book after invoke method ServerSetBookText().

In effect text in books (first two pages) are not justified as should be. After switching page - client crashes.

**To Reproduce**
1. Have this buged books on server
2. open book
3. move between pages.
4. Client crashes after moving page

**Expected behavior**
Books should open normally

**Information (please complete the following information):**
 - OS: windows 10
 - ClassicUO Version: (can be fetched from the login screen)
 - [ X] Using DEV Version?
 - Launcher: ClassicUO

***FIX for this problem***

Added:
```
  for (int i = 0, l = BookLines.Length; i < l; i++)
            {
                //BookLines[i] = Regex.Replace(BookLines[i], "\n.*", "");

                if (BookLines[i].Contains("\n"))
                {
                    BookLines[i] = BookLines[i].Replace("\n", "");
                }
            }
```
and changed if:
```
 if (i + 1 < l && (string.IsNullOrWhiteSpace(BookLines[i]) && !BookLines[i].Contains("\n") || w + sw < _bookPage.renderedText.MaxWidth))
```

ModernBookGump.class:
```
     internal void ServerSetBookText()
        {
            if (BookLines == null || BookLines.Length <= 0)
            {
                return;
            }

            StringBuilder sb = new StringBuilder();
            int sw = _bookPage.renderedText.GetCharWidth(' ');

            for (int i = 0, l = BookLines.Length; i < l; i++)
            {
                //BookLines[i] = Regex.Replace(BookLines[i], "\n.*", "");

                if (BookLines[i].Contains("\n"))
                {
                    BookLines[i] = BookLines[i].Replace("\n", "");
                }
            }

            for (int i = 0, l = BookLines.Length; i < l; i++)
            {
                int w = IsNewBook ?
                    FontsLoader.Instance.GetWidthUnicode(_bookPage.renderedText.Font, BookLines[i]) :
                    FontsLoader.Instance.GetWidthASCII(_bookPage.renderedText.Font, BookLines[i]);

                sb.Append(BookLines[i]);

                if (i + 1 < l && (string.IsNullOrWhiteSpace(BookLines[i]) && !BookLines[i].Contains("\n") || w + sw < _bookPage.renderedText.MaxWidth))
                {
                    sb.Append('\n');
                    BookLines[i] += '\n';
                }
            }

            _bookPage._ServerUpdate = true;
            _bookPage.SetText(sb.ToString());
            _bookPage.CaretIndex = 0;
            _bookPage.UpdatePageCoords();
            _bookPage._ServerUpdate = false;
        }
```

**Comment by andreakarasho** [comment]
Do you want open a PR pointed it to dev branch?

**Comment by andreakarasho** [comment]
NOTE: https://github.com/andreakarasho/ClassicUO/issues/1137

**Comment by LukaszChrzanowski** [comment]
I can create push request with working wersion if You want

**Comment by andreakarasho** [comment]
Don't forget te PR!!

**Comment by LukaszChrzanowski** [comment]
that what was pushed by brndd solver issue :) this can be closed now - checked on DEV branch
