### ISSUE TITLE
Armoire gump issue on Packhorse

### ISSUE THREAD

**Issue by aclark13** [ClassicUO/ClassicUO#1259]
**Describe the bug**
Armoire gump closes immediately when it is in a packhorse. 

**To Reproduce**
1. Place an Armoire in a pack horse
2. Try to open it
3. The gump closes immediately

**Expected behavior**
The gump should stay open.

**Screenshots**
![gump close](https://user-images.githubusercontent.com/38568913/99696551-6f6d8500-2a54-11eb-88ff-b2184e7c73a4.gif)

**Shard**
 - Name of the shard: Outlands

**Information (please complete the following information):**
 ###################################################
CUO version: 0.1.6.1
OBJECT TYPE: ClassicUO.Game.GameObjects.Item
AllowedToDraw = True
AlphaHue = 0
Amount = 1
AnimIndex = 0
ClosedObjectHandles = False
Container = 1137002259
CurrentRenderIndex = 0
Direction = North
DisplayedGraphic = 2639
Distance = 2655
Exists = True
Flags = None
FoliageIndex = -1
FrameInfo = {X:0 Y:0 Width:0 Height:0}
Graphic = 2639
Hits = 0
HitsMax = 0
HitsPercentage = 0
HitsTexture = null
Hue = 0
IsClicked = False
IsCoin = False
IsCorpse = False
IsDamageable = False
IsDestroyed = False
IsEmpty = True
IsHidden = False
IsLocked = True
IsLootable = True
IsMulti = False
IsPositionChanged = False
Items = null
LastStepTime = 0
Layer = Invalid
LightID = 0
MultiDistanceBonus = 0
MultiGraphic = 0
MultiInfo = null
Name = null
Next = null
ObjectHandlesOpened = False
Offset = {X:0 Y:0 Z:0}
OnGround = False
Opened = False
Previous = ClassicUO.Game.GameObjects.Item
Price = 0
PriorityZ = 0
RealScreenPosition = {X:0 Y:0}
RootContainer = 939542
Serial = 1081926016
TextContainer = null
TNext = null
TPrevious = null
UsedLayer = False
UseInRender = 0
UseObjectHandles = False
WantUpdateMulti = True
X = 44
Y = 65
Z = 0
###################################################

**Comment by andreakarasho** [comment]
i think armoire acts in this way serverside.
Can you test with og client?

**Comment by aclark13** [comment]
> i think armoire acts in this way serverside.
> Can you test with og client?

It doesn't in fact open in the OG client.  I didn't even think to check for that to be the case.
