### ISSUE TITLE
Ignore list

### ISSUE THREAD

**Issue by roxya** [ClassicUO/ClassicUO#1261]
The standard client has an ignore list feature, where you target a mobile to add their name and serial to a list (ignore.lst file). Razor does a good job of it also, but since it's a standard feature, it might be a good idea to add to the client.

In the standard client, the list is client-wide for all accounts and characters, and blocks all messages originating directly from the mobile. This includes spells they cast and their name / guild tag when single clicking them.

My opinion on a ClassicUO version of this

- Similar behaviour to standard, with a list in the options menu, and a button to bring up a target cursor to add someone
- A macro for adding to the list (and removing from) without going into the options menu.
- A macro to toggle the whole ignore list on and off
- Client-wide makes sense but it should only ignore players by unique serial+servername
- Be more selective about what types of messages are blocked. I think the general idea is to remove speech from those mobiles, and hiding their spells is a bad side-effect in the standard client.
- Some kind of indicator (maybe on single-click) to show the person is ignored

**Comment by aclark13** [comment]
On one hand I agree with the spells being ignored a bad thing.  On the other hand, I may want to ignore someone spamming spells/macroing at a bank or somewhere public.  Not sure which is the better method to handle ignoring, but just something to think about.
