### ISSUE TITLE
ClassicUO launch script for Linux and OS X uses CRLF instead of LF, causing errors

### ISSUE THREAD

**Issue by brndd** [ClassicUO/ClassicUO#1264]
https://github.com/andreakarasho/ClassicUO/blob/master/tools/monokickstart/ClassicUO

It seems in some builds (eg. the [0.1.6.1 beta](https://github.com/andreakarasho/ClassicUO/releases/tag/0.1.6.1)) this file uses Windows-style line endings (CRLF) instead of Unix-style, which causes some shell interpreters to error out when trying to run it:

```
$ ./ClassicUO
zsh: ./ClassicUO: bad interpreter: /bin/bash^M: no such file or directory
```

Not sure where they're coming from since the one in the repo seems to use LF. Probably an issue with the build process?

**Comment by andreakarasho** [comment]
If you delete it from `{launcher folder}/ClassicUO/` is still Windows like?

**Comment by brndd** [comment]
> If you delete it from `{launcher folder}/ClassicUO/` is still Windows like?

It seems the one downloaded by the launcher is fine. I downloaded the release .zip from Github directly and that one has CRLF.
