### ISSUE TITLE
Bugs Music, Colors and Object

### ISSUE THREAD

**Issue by Arutosio** [ClassicUO/ClassicUO#1272]
Music dose not work, the colors are not exact and some objects are not seen

Video:
[![BG](https://i.imgur.com/JDQSgT3.jpeg)](https://puu.sh/GWLio/b7f50219e5.mp4)
CrashLog:
######################## [START LOG] ########################
ClassicUO [STANDARD_BUILD] - 0.1.6.1 - 12/12/2020 07:53:35
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Shard: 127.0.0.1
ClientVersion: 1.26.4b

Exception:
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in ClassicUO.Game.UI.Gumps.StatusGumpModern.Update(Double totalTime, Double frameTime)
   in ClassicUO.Game.Managers.UIManager.Update(Double totalTime, Double frameTime)
   in ClassicUO.GameController.Update(GameTime gameTime)
   in Microsoft.Xna.Framework.Game.Tick() in D:\Progetti\ClassicUO\client\external\FNA\src\Game.cs:riga 533
   in Microsoft.Xna.Framework.Game.RunLoop() in D:\Progetti\ClassicUO\client\external\FNA\src\Game.cs:riga 866
   in Microsoft.Xna.Framework.Game.Run() in D:\Progetti\ClassicUO\client\external\FNA\src\Game.cs:riga 416
   in ClassicUO.Client.Run()
   in ClassicUO.Bootstrap.Main(String[] args)

**Comment by andreakarasho** [comment]
Does it use verdata.mul?
A patch has been pushed in dev branch about and it fixed all of issues described above.
Download cuo launcher from: https://www.classicuo.eu

**Comment by Arutosio** [comment]
> Does it use verdata.mul?
> A patch has been pushed in dev branch about and it fixed all of issues described above.
> Download cuo launcher from: https://www.classicuo.eu

yes, there is a verdata.mul file insane on the folder game.
ok.
i did it but this not resolve this problem

**Comment by andreakarasho** [comment]
can you provide me UO files and server address?

**Comment by Arutosio** [comment]
> can you provide me UO files and server address?

done, i sent a email with a link to download

**Comment by andreakarasho** [comment]
where you prefer. I need a link :)

**Comment by Arutosio** [comment]
> where you prefer. I need a link :)

did you receive the email?

**Comment by andreakarasho** [comment]
everything fixed!
