### ISSUE TITLE
"New" book header packet (0xD4) uses ASCII instead of Unicode

### ISSUE THREAD

**Issue by brndd** [ClassicUO/ClassicUO#1277]
According to https://docs.polserver.com/packets/index.php?Packet=0xD4 this packet is supposed to use unicode, two bytes per character. ClassicUO is currently both sending and receiving the package as ASCII.

Haven't actually been able to test whether or not this leads to breakage, but reporting this since I noticed it so others can investigate.

EDIT: Looking at [ServUO source](https://github.com/ServUO/ServUO/blob/d8670d7150ea0c6586d46df0f90b1abcc9fa6aaa/Scripts/Items/Books/BaseBook.cs) at a glance it seems they're parsing this packet as UTF-8 which is just... *sigh*. Either way that's also incompatible with what CUO is currently doing (CP1252 parsed as UTF-8 leads to garbage with non-ASCII characters). Good luck.

**Comment by sorsarre** [comment]
Is this also the case for speech btw? I keep seing garbage when using non-western locale, wondering if that is a server or a client thing. Might be both, alright. Definitely remember non-ASCII speech working alrighty on some of RunUO-based servers back in the day.

**Comment by brndd** [comment]
@sorsarre https://docs.polserver.com/packets/index.php?Packet=0xAD ("new") and https://docs.polserver.com/packets/index.php?Packet=0x03 (old)

The "new" client-side speech packet can do both ASCII (which is really [CP1252](https://en.wikipedia.org/wiki/Windows-1252) AFAIK, though it could depend on client locale) and Unicode. I don't know when or how exactly the client picks between which one to use in the 0xAD packet -- perhaps it only uses ASCII for speech.mul messages like "bank" and "vendor buy".

The POL docs again seem to claim it would be 2 bytes per character so UTF-16, but ClassicUO is sending UTF-8 and all I know is that it works fine on my end on the servers I've tried. Maybe the client will use the "ASCII" version of that packet depending on whether the characteres you're sending happen to fit in some codepage defined for your locale, but that's just a guess. Locale definitions are in Langcode.iff.
