### ISSUE TITLE
Macro settings are erased if it cause parsing errors

### ISSUE THREAD

**Issue by birdinforest** [ClassicUO/ClassicUO#1291]
If the macro setting file `macors.xml` gets parsing error by any reason, macro settings will be erased. (Maybe it will be deleted and a new one is created. I haven't look into relevant code.)

Reproduce: 
Detele any tag to corrupt the file. Run ClassicUO and login. All macro settings are erased without notification.

System: 
Proved on Window and MacOS. Didn't test on Linux.

Suggest solution: 
Backup the file before erase and pop out a notification.

Not sure it is a bug or a missing feature. Please lable this issue. Thanks.
I could try to fix it after we get a agree of the solution.

**Comment by andreakarasho** [comment]
do not edit that file!
