### ISSUE TITLE
Alternative Lighting does not work on Linux

### ISSUE THREAD

**Issue by broxen** [ClassicUO/ClassicUO#1294]
**Describe the bug**
Running the Linux Client. When Alternative Lighting is Enabled the day/night cycle is broken and caves are at full brightness. It appears that the light level is always maxed out.

Perhaps I'm just misunderstanding the function of Alternative Lighting. If so, I can submit a PR for some helper text.

I have not tested this on Windows, as I don't have access to a windows machine.

**To Reproduce**
1. Enable Alternative Lighting
2. Wait for Night Time, or Visit a Cave/Dungeon
3. Lighting will be full brightness.
4. Disable Alternative Lighting
5. Lighting will return to normal

**Expected behavior**
Alternative Lighting should not affect day/night, or caves, unless Light level is enabled and turned up to max. Per  https://github.com/andreakarasho/ClassicUO/issues/763

**Screenshots**
Original Client with Razor (v5.0.2g) logged in with another character, at the same time. (ClassicUO Client seen underneath)
![Screenshot from 2021-01-16 16-23-46](https://user-images.githubusercontent.com/10159505/104828164-200cc080-581b-11eb-9b63-40b1391a8c07.png)

**Without** Alternative Lighting
![Screenshot from 2021-01-16 16-23-40](https://user-images.githubusercontent.com/10159505/104828165-20a55700-581b-11eb-9943-fbfcdf9f540a.png)

With Alternative Lighting
![Screenshot from 2021-01-16 16-23-53](https://user-images.githubusercontent.com/10159505/104828161-1e42fd00-581b-11eb-9dd0-5002c381c0fa.png)

**Shard**
 - Name of the shard: UnrealUO (I'm not GM), but also a local server.

**Information (please complete the following information):**
 - OS: Fedora 32
 - ClassicUO Version: 0.1.7.8
 - [ ] Using DEV Version?
 - Launcher: ClassicUO Launcher

**Additional context**
 - How many clients do you run in parallel: Max 2, often 1
 - Screen Resolution: 1920x1080

**Comment by andreakarasho** [comment]
Alternative lights option forces ClassicUO to draw lights with light level at max value. 
Usually lights are drawn when lights level is under the max only.
