### ISSUE TITLE
Problems with broken text when changing the name to rune in Korean language

### ISSUE THREAD

**Issue by badungi** [ClassicUO/ClassicUO#1297]
shard : Margo(lod.so.tl:2594) RunUO

When entering Korean text where all names are designated, Korean text is broken.

And if you enter a chat in Korean, the last letter goes down to the next line.

Is there any solution?

![aadd](https://user-images.githubusercontent.com/77443721/105665229-e96d2f00-5f19-11eb-99b4-e3569a7a944b.png)

**Comment by andreakarasho** [comment]
I see 0.1.7.0 version. Try the version provided by the launcher

**Comment by badungi** [comment]
> I see 0.1.7.0 version. Try the version provided by the launcher

The same problem occurs with the 1.7.30 version provided by the launcher.
![112233](https://user-images.githubusercontent.com/77443721/105858061-45c17300-602e-11eb-914c-ba59c85c1201.png)

**Comment by andreakarasho** [comment]
related maybe to https://github.com/andreakarasho/ClassicUO/issues/1352

I'll open it if it is not fixed in latest dev
