### ISSUE TITLE
Viewport Window

### ISSUE THREAD

**Issue by 3HMonkey** [ClassicUO/ClassicUO#13]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
The viewport should be rendered in its own window as original client is doing. It should also be resizable.

![grafik](https://user-images.githubusercontent.com/4610892/45244767-9323d500-b2f9-11e8-8901-8e96f3ddb29c.png)

**Comment by 3HMonkey** [comment]
Any news here?

**Comment by andreakarasho** [comment]
Done!
