### ISSUE TITLE
Multiple Crashes a Day

### ISSUE THREAD

**Issue by Mivoc** [ClassicUO/ClassicUO#1305]
Classic UO Client Crashing.
System Specs:
Windows 10 Pro 64bit
Nvidia 3080 GTX, Driver version: 461.40

This crash seems to occur most often when running multiple clients, hard to say if this is the specific reason for crashing.

**Shard**
 - UO:R

**Information (please complete the following information):**
 - OS: Windows 10 Pro version 2004 OS Build 19041.685
 - ClassicUO Version: 0.1.7.0
 - [ ] Using DEV Version?
 - Launcher: UO:Renaissance Launcher

**Additional context**
 - How many clients do you run in parallel:  3
 - Screen Resolution: 2560x1440

Going to attach crash logs from C:\UORenaissance\ClassicUO\Logs
[2021-02-06_12-15-33_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978344/2021-02-06_12-15-33_crash.txt)
[2021-02-08_06-33-03_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978345/2021-02-08_06-33-03_crash.txt)
[2021-02-08_06-33-12_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978346/2021-02-08_06-33-12_crash.txt)
[2021-02-08_06-33-19_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978347/2021-02-08_06-33-19_crash.txt)
[2021-02-09_07-00-10_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978348/2021-02-09_07-00-10_crash.txt)
[2021-02-09_07-00-24_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978349/2021-02-09_07-00-24_crash.txt)
[2021-02-11_01-31-01_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978350/2021-02-11_01-31-01_crash.txt)
[2021-02-11_06-50-17_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978351/2021-02-11_06-50-17_crash.txt)
[2021-02-11_06-50-25_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978352/2021-02-11_06-50-25_crash.txt)
[2021-02-11_08-51-36_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978353/2021-02-11_08-51-36_crash.txt)
[2021-02-11_08-51-37_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978354/2021-02-11_08-51-37_crash.txt)
[2021-02-12_09-35-09_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978355/2021-02-12_09-35-09_crash.txt)
[2021-02-12_09-35-22_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978356/2021-02-12_09-35-22_crash.txt)
[2021-02-13_01-39-30_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978357/2021-02-13_01-39-30_crash.txt)
[2021-02-13_02-11-42_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978358/2021-02-13_02-11-42_crash.txt)
[2021-02-13_02-11-59_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978359/2021-02-13_02-11-59_crash.txt)
[2021-02-13_03-45-21_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978360/2021-02-13_03-45-21_crash.txt)
[2021-02-13_03-45-28_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978361/2021-02-13_03-45-28_crash.txt)
[2021-02-13_03-45-29_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978362/2021-02-13_03-45-29_crash.txt)
[2021-02-13_08-00-08_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978363/2021-02-13_08-00-08_crash.txt)
[2021-02-13_08-00-21_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978364/2021-02-13_08-00-21_crash.txt)
[2021-02-13_08-51-56_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978365/2021-02-13_08-51-56_crash.txt)
[2021-02-13_08-52-16_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978366/2021-02-13_08-52-16_crash.txt)
[2021-02-13_12-26-47_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978367/2021-02-13_12-26-47_crash.txt)
[2021-02-13_12-27-00_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5978368/2021-02-13_12-27-00_crash.txt)

**Comment by andreakarasho** [comment]
i'll check on my side, but most of the time these crashes happens due to corrupted UO file data.

**Comment by Mivoc** [comment]
Would you recommend a full reinstall of the client?
This happens to my friends as well. They are both running Nvidia 3080's as well.

**Comment by oroechimaru** [comment]
@Mivoc  update nvidia drivers to 461.51 if possible 

can you guys launch your uor launcher and make sure its patched too? Possibly delete the art files then repatch?

also check for windows updates

**Comment by Mivoc** [comment]
I performed a clean reinstall of the UO:R ClassicUO/Razer Client, still getting crashes. I am working on downloading and installing the Nvidia driver oroechimaru recommended. Also going to install all available windows updates.

**Comment by Wayslayer** [comment]
@andreakarasho @oroechimaru This same thing is happening to my game. I have a 3080 with latest drivers @Mivoc said. I worked with Quick on UOR discord, and he sent me the stand alone launcher, and I completely reinstalled the game and launcher and still have the same issues. Seems to happen to Mivoc a bit more, but we have another friend with the same video card with the same issue as well. Thanks for the help.
[2021-02-10_03-22-50_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5989432/2021-02-10_03-22-50_crash.txt)
[2021-02-10_03-23-26_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5989433/2021-02-10_03-23-26_crash.txt)
[2021-02-10_03-53-27_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5989434/2021-02-10_03-53-27_crash.txt)
[2021-02-12_05-40-06_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5989436/2021-02-12_05-40-06_crash.txt)
[2021-02-13_08-14-48_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5989437/2021-02-13_08-14-48_crash.txt)
[2021-02-14_03-31-01_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5989438/2021-02-14_03-31-01_crash.txt)
[2021-02-16_06-01-51_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5989439/2021-02-16_06-01-51_crash.txt)
[2021-02-16_06-01-53_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5989440/2021-02-16_06-01-53_crash.txt)
[2021-02-10_03-22-25_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5989441/2021-02-10_03-22-25_crash.txt)
[2021-02-10_03-22-49_crash.txt](https://github.com/andreakarasho/ClassicUO/files/5989442/2021-02-10_03-22-49_crash.txt)

**Comment by andreakarasho** [comment]
Do you have any external application that write to the cuo window?
Like showing FPS, temps, voltages, etc..?

**Comment by Mivoc** [comment]
No I do not use anything like that unfortunately. I do not use any capture
or overlay software.

**Comment by oroechimaru** [comment]
Add antivirus folder exception for your uor folder?

any windows event errors?

is it this as in known issues for the cards?
https://videocardz.com/newz/manufacturers-respond-to-geforce-rtx-3080-3090-crash-to-desktop-issues

**Comment by Mivoc** [comment]
I do not use anti virus but scan weekly manually. There are windows events,
when I get home from work I will post them.

I can’t speak to the validity of that article but I do play other games
routinely without issues. Including WoW Shadowlands and CoD Blackops Cold
War with no issues.

**Comment by Mivoc** [comment]
I got the info for the crash dump. I also updated to my nvidia drivers to 461.51 prior to this crash. After the crash I did all my Windows Updates, I will continue to test with all the latest Windows Updates installed.

Here is the latest crash dump from yesterday:

Log Name:      Application
Source:        Application Error
Date:          2/15/2021 4:31:10 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-BPSQSTL
Description:
Faulting application name: ClassicUO.exe, version: 0.1.7.0, time stamp: 0xf038433a
Faulting module name: KERNELBASE.dll, version: 10.0.19041.662, time stamp: 0xec58f015
Exception code: 0xe0434352
Fault offset: 0x000000000002d759
Faulting process id: 0x371c
Faulting application start time: 0x01d703f0f8872c7c
Faulting application path: C:\UORenaissance\ClassicUO\ClassicUO.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: e94ad60f-264d-4d49-b586-d0e3186f4195
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-02-15T23:31:10.9874814Z" />
    <EventRecordID>20850</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-BPSQSTL</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ClassicUO.exe</Data>
    <Data>0.1.7.0</Data>
    <Data>f038433a</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.662</Data>
    <Data>ec58f015</Data>
    <Data>e0434352</Data>
    <Data>000000000002d759</Data>
    <Data>371c</Data>
    <Data>01d703f0f8872c7c</Data>
    <Data>C:\UORenaissance\ClassicUO\ClassicUO.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>e94ad60f-264d-4d49-b586-d0e3186f4195</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by Mivoc** [comment]
Had another crash with all the latest Windows 10 Updates

**Comment by andreakarasho** [comment]
I need your dxdiag log.
https://support.microsoft.com/en-us/windows/open-and-run-dxdiag-exe-dad7792c-2ad5-f6cd-5a37-bf92228dfd85


You can also try to switch to opengl driver passing: `-force_driver 1` as argument or just download the cuolauncher and set the backend driver from it

**Comment by Mivoc** [comment]
Here us my DXDIAG
[DxDiag.txt](https://github.com/andreakarasho/ClassicUO/files/5997278/DxDiag.txt)

I can try to switch to opengl driver passing. Where would I put the "-force_driver 1" argument? On my UO:R launcher shortcut?

**Comment by andreakarasho** [comment]
I don't know honestly if UOR launcher can pass arguments to CUO.
I invoke @markdwags

**Comment by Mivoc** [comment]
I found the argument in the settings file of the ClassicUO folder of UO:R. I will change the value from 0 to 1.

**Comment by markdwags** [comment]
> I don't know honestly if UOR launcher can pass arguments to CUO.
> I invoke @markdwags

Yeah, just edit settings.json directly, the launcher won't change it.

**Comment by Mivoc** [comment]
After playing with the opengl driver it ran much longer without a crash, but still crashed. Oddly enough there was no ClassicUO client crash log file. However there were events logged in the Event Viewer in windows.

Log Name:      Application
Source:        NVIDIA OpenGL Driver
Date:          2/18/2021 5:12:04 PM
Event ID:      1
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-BPSQSTL
Description:
The description for Event ID 1 from source NVIDIA OpenGL Driver cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

A TDR has been detected.
The application must close.


Error code: 7
 (pid=14420 tid=5848 classicuo.exe 64bit)

Visit http://nvidia.custhelp.com/app/answers/detail/a_id/3633 for more information.

The message resource is present but the message was not found in the message table

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="NVIDIA OpenGL Driver" />
    <EventID Qualifiers="49152">1</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-02-19T00:12:04.2607141Z" />
    <EventRecordID>21574</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-BPSQSTL</Computer>
    <Security />
  </System>
  <EventData>
    <Data>A TDR has been detected.
The application must close.


Error code: 7
 (pid=14420 tid=5848 classicuo.exe 64bit)

Visit http://nvidia.custhelp.com/app/answers/detail/a_id/3633 for more information.</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          2/18/2021 5:12:04 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-BPSQSTL
Description:
Faulting application name: ClassicUO.exe, version: 0.1.7.0, time stamp: 0xf038433a
Faulting module name: nvoglv64.dll, version: 27.21.14.5671, time stamp: 0x5f75532b
Exception code: 0xc0000409
Fault offset: 0x00000000011584c9
Faulting process id: 0x3854
Faulting application start time: 0x01d7054fdb3f9cac
Faulting application path: C:\UORenaissance\ClassicUO\ClassicUO.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_1c83a5d7cffd7bff\nvoglv64.dll
Report Id: 2830c0cd-8818-4659-bb01-1e0b95e72b0d
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-02-19T00:12:04.4665807Z" />
    <EventRecordID>21575</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-BPSQSTL</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ClassicUO.exe</Data>
    <Data>0.1.7.0</Data>
    <Data>f038433a</Data>
    <Data>nvoglv64.dll</Data>
    <Data>27.21.14.5671</Data>
    <Data>5f75532b</Data>
    <Data>c0000409</Data>
    <Data>00000000011584c9</Data>
    <Data>3854</Data>
    <Data>01d7054fdb3f9cac</Data>
    <Data>C:\UORenaissance\ClassicUO\ClassicUO.exe</Data>
    <Data>C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_1c83a5d7cffd7bff\nvoglv64.dll</Data>
    <Data>2830c0cd-8818-4659-bb01-1e0b95e72b0d</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by roxya** [comment]
Are you sure about the driver version? Dxdiag shows a driver from Windows Update (27.21.14.5671) which translates to 456.71

There's were known TDR issues for those cards with drivers before 461.09

**Comment by Mivoc** [comment]
I downloaded and installed the hotfix driver as suggested above. It must be
a bug in what driver version is displayed for the hotfix driver. Driver has
not changed for the video card since then.
 
Also it has crashed no matter what driver is loaded I’ve tried a few, not sure this matters at all either way.

**Comment by oroechimaru** [comment]
@Mivoc  that doesn't sound like a solid install. Often drivers have bugs and can be compounded if they get mixed up. One common solution is to use the Driver Uninstaller tool from guru3d. UNINSTALL / scrub everything nvidia and reboot to safemode with networking if possible after to install 461.51 again 
https://www.guru3d.com/files-details/display-driver-uninstaller-download.html

fyi their download links auto download, dont click ads. 
specifically at the bottom use the auto download links like:
https://www.guru3d.com/files-get/display-driver-uninstaller-download,9.html

have the new hotfix driver downloaded (again auto download or get from nvidia, dont use their nvidia driver experience panel)

again let this hotfix driver autodownload:
https://www.guru3d.com/files-get/geforce-461-51-hotfix-driver-download,1.html

possibly reboot to safemode or at least reboot afterwards. it may try to install an older driver. make sure 461.51 gets installed then reboot again.

keep the nvidia settings at defaults especially vsync, activesync, gsync etc until its stable before tweaking any settings. also make sure refresh rate is correct in windows at highest setting to match your monitor. 

when CUO was earlier on in the project both AMD and Nvidia had major driver issues from 201911-202004 or so, and often those get corrupted and leftover pieces remain that have issues.

possibly consider using the directx/default configuration again before trying openGL or vulkan etc

your crash errors are often observed for open gl issues, so i'd stick to settings.json to direct3d if you can:
https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/344784/nvidia-opengl-error/

consider updating FIRMWARE on your graphics card (most of the games you mentioned are not openGL) and update the bios on your motherboard as well. these gpus have a history of major crash issues in games.

**Comment by Mivoc** [comment]
Ok, I went into Safe Mode and ran the DDU and wiped out everything and rebooted. Did a clean install of the 461.51 hot fix driver and rebooted.

I am currently sticking to Direct3d although I will note the vast majority of my crashes were with Direct3D. It does not seem to make a difference in stability whether its OpenGL or Direct3D unfortunately.

I attached my latest DXDiag since performing those actions.

[DxDiag.txt](https://github.com/andreakarasho/ClassicUO/files/6012560/DxDiag.txt)

**Comment by oroechimaru** [comment]
It looks like the driver successfully updated . How is the stability? If better you and friends with same gpu could of had a corrupt driver  that didnt cleanup during updates (common issue)

**Comment by Mivoc** [comment]
I will post an update after playing this evening. Thanks :D

**Comment by oroechimaru** [comment]
@Mivoc any luck?

**Comment by Mivoc** [comment]
So far no crashes. *checks and makes sure PC is not listening*

I checked with a friend who has not performed any troubleshooting like I
have and he hasn't crashed recently either... so yeah not sure what's going
on. I am hoping it was the DDU that ultimately fixed the issue for me but
only time will tell as this issue was not easily repeatable and was pretty
random.

**Comment by oroechimaru** [comment]
This probably can be closed then. :)

**Comment by Mivoc** [comment]
Ok sounds good to me :D

I really think the DDU helped in my case, I can't speak for my friends'
issues if they are even having them anymore.

Thanks  for the help! So far I am really impressed with the ClassicUO
client.
