### ISSUE TITLE
After Recall or Gate, some tiles don't render

### ISSUE THREAD

**Issue by broxen** [ClassicUO/ClassicUO#1313]
**Describe the bug**
After recalling or gating, some tiles will fail to render properly. They are always in a straight vertical line, and always close to the middle of the screen. They render properly after moving. I have only tested on Linux. Let me know if you need any additional info

**Screenshots**
![Screenshot from 2021-02-22 01-48-37](https://user-images.githubusercontent.com/10159505/108691877-d154e500-74b0-11eb-972d-fd3ff12c20cb.png)
![Screenshot from 2021-02-22 00-04-13](https://user-images.githubusercontent.com/10159505/108691887-d5810280-74b0-11eb-9d75-e54a76d004af.png)

**Shard**
 - Name of the shard: Oberon (ServUO)

**Information (please complete the following information):**
 - OS: Fedora 32
 - ClassicUO Version: 0.1.7.71 (latest update from launcher)
 - [X] Using DEV Version?
 - Launcher: classicuo_launcher

**Comment by andreakarasho** [comment]
No reports about this on recent versions
