### ISSUE TITLE
Flamestrike Animation Doesn't Apply Hue

### ISSUE THREAD

**Issue by aclark13** [ClassicUO/ClassicUO#1320]
When casting a flamestrike that should have a hue applied, in CUO the hue is missing.  This worked up until recently on Outlands, but a change was made (in dev) that broke the hue applying correctly.

Steam
![steam FS](https://user-images.githubusercontent.com/38568913/110884078-1f882780-82aa-11eb-8fe7-ee7de47e3cad.gif)

Classic UO Dev
![CUO fs](https://user-images.githubusercontent.com/38568913/110884079-1f882780-82aa-11eb-8bd7-11e4a3422152.gif)

**Comment by gaechti** [comment]
this is fixed
