### ISSUE TITLE
books gump

### ISSUE THREAD

**Issue by andreakarasho** [ClassicUO/ClassicUO#133]
**Describe the solution you'd like**
books gump to be implemented

**Comment by DarkLotus** [comment]
I'm working on a basic implementation for this

**Comment by SaschaKP** [comment]
are you still working on this? I picked up your work and integrated it inside the dev branch, if you're still working on it, look at my modifications, I'll be busy a little with ultimalive, but I think that books should be the next thing to integrate.

**Comment by DarkLotus** [comment]
Nice, I should have time again midweek.

**Comment by SaschaKP** [comment]
finished, if you found any bug, report, since there could be any minor issues not evaluated. Thank you
