### ISSUE TITLE
Can't edit tamed pet names until you recall somewhere

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#1341]
I doubt it's outlands specific, but I play outlands.

When I tame a pet, I can't edit the name of the pet until I recall somewhere (refresh the bar?). Closing bar and opening it again without recalling somewhere doesn't work.

**Comment by anethus** [comment]
Can't reproduce on private server - after Animal Taming can easly change tamed pet name.

I am able to reproduce it on ClassicUO and UOSteam on Outlands - so it's Outlands problem (i think problem is in packet 0x11 where IsRenamable came from - after AnimalTaming i didn't get that packet with correct Flag).

**Comment by Alias-Alan** [comment]
I had this fixed in 2020, ask ShakinJaden and Owen to stop breaking the client. This is why the move to BSD was a horrible idea, this could have been fixed in 5minutes but instead, the community has no idea what's even being installed.

**Comment by andreakarasho** [comment]
thanks for the help @anethus
