### ISSUE TITLE
Client often fails to complete login process.

### ISSUE THREAD

**Issue by Timorio** [ClassicUO/ClassicUO#1344]
**Describe the bug**
The client often fails to complete the login process, leaving the user with no choice but to restart the client.  I believe this can happen at any point during login.  The "Quit" button can still be pressed when this occurs.

**Expected behavior**
It'd be good if the client had measures to recognize when this happens and reattempt the login process.  At the least, it'd be good to have a button that sends the user back to the initial login screen to avoid having to restart.

**Shard**
UOForever

**Information (please complete the following information):**
 - OS: Windows 10
 - ClassicUO Version: 0.1.8.14
 - Launcher: None

**Additional context**
 - How many clients do you run in parallel: 3
 - Screen Resolution: 1680x1050

**Comment by andreakarasho** [comment]
shoudl be fixed here https://github.com/ClassicUO/ClassicUO/commit/b8b0db4fe90963023a511b35c10f136583553b46
