### ISSUE TITLE
Incorrect behavior when clicking and dragging the cursor over context-menu items.

### ISSUE THREAD

**Issue by Timorio** [ClassicUO/ClassicUO#1345]
**Describe the bug**
Initiating a mouse click over a context-menu item then moving the cursor to another item before releasing the mouse button erroneously selects the initially clicked item.

**Expected behavior**
The menu item highlighted when the mouse button is _released_ should be the one that is selected.  This is true of the original client and every similar system I've experienced.

**Information (please complete the following information):**
 - OS: Windows 10
 - ClassicUO Version: 0.1.8.14

**Comment by roxya** [comment]
Can't reproduce in the current version
