### ISSUE TITLE
WorldMap gump layer order

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#1354]
**Describe the bug**
When you open the World Map and your Paperdoll, the World Map will always be behind the gump, bordered or borderless.  It uses to come to the top when it was clicked to be active.

**To Reproduce**
Open the world map, open the paperdoll, try to get the world map to cover the paperdoll.

**Expected behavior**
When you click on the WorldMap, it should come to the front, and go above anything that is over it

Using the latest CUO dev version as of yesterday.

**Comment by andreakarasho** [comment]
This is exactly what i did :D

I think it's better to keep the map in the background because some gump can spawn under it and you will not see it if the map gump size is loo large.

**Comment by markdwags** [comment]
Would it be possible to make that an option to do that? Probably the number 1 complaint I'm getting is the world map stuck behind everything.

**Comment by anethus** [comment]
To WorldMap stay at front user have to reload GameScene (reload user) when Settings `Keep On Top` is selected

I create small fix for that:
https://github.com/andreakarasho/ClassicUO/pull/1364

**Comment by andreakarasho** [comment]
fixed https://github.com/andreakarasho/ClassicUO/commit/c7d1fc669df1586b3b0480c2e1af431af050fa57
