### ISSUE TITLE
ClassicUO handles a server-side target cursor cancellation wrong

### ISSUE THREAD

**Issue by lvcmenezes** [ClassicUO/ClassicUO#1373]
**Describe the bug**
According to [this documentation](https://docs.polserver.com/packets/index.php?Packet=0x6C), the server is able to send a packet to cancel the target cursor in the client - which would result in the same behavior as pressing ESC. ClassicUO does cancel the target, but all the future targets are automatically canceled as well. 

**To Reproduce**
1. Packet 0x6C (Target Cursor Commands) from Server
2. Cursor Type - 3

**Expected behavior**
ClassicUO should handle the cancellation the same way hitting ESC would do.

**Shard**
 - Name of the shard: Mystic (www.mystic.com.br)

**Information (please complete the following information):**
 - OS: win.10.0.19042.867
 - ClassicUO Version: 1.9.0 (dev [a6b8e72])
 - Using DEV Version? Yes

**Additional context**
- Nothing relevant.

**Comment by roxya** [comment]
This code is different since 1.7.0 so I suggest you update your ClassicUO version and try it again.

**Comment by lvcmenezes** [comment]
Still same problem with version 1.9.0 (dev [a6b8e72])

**Comment by andreakarasho** [comment]
i tried casting a spell, wait until server cancel the target. Once i received the 0x6C with targetcancel from the server i tried to recast a spell and the cursor was ON.
What's happen if you follow the same steps i did?
Do you have a specific use-case to try on?

**Comment by lvcmenezes** [comment]
Hmm I am starting to think this is actually a problem with POL. 

          Ticks: 55261 | Server -> Client |  ID: 6C   Length: 19
          0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
          -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
00000000  6C 00 00 00 00 00 03 00  00 00 00 00 00 00 00 00  l...............
00000010  00 00                                             ..



          Ticks: 55261 | Client -> Server |  ID: 6C   Length: 19
          0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
          -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
00000000  6C 00 00 00 00 00 03 00  00 00 00 FF FF FF FF 00  l...............
00000010  00 00                                             ..

The target cursor is actually gone after that, but if I try casting another spell it fails and POL shows "Client is busy with another target cursor".

I will check what POL is doing and come back here to inform you.

**Comment by andreakarasho** [comment]
Any news?

**Comment by AsYlum-** [comment]
I'll jump in with little update. Looks like it will be fixed in POL emulator there is PR for this here https://github.com/polserver/polserver/pull/404. I'll try to test in next few days.

**Comment by frozenblit** [comment]
Hi all, just to comment on the fix for POL: there seems to be a difference between the original client and CUO when handling a cancellation request with a "cursor id" 0x00 and "cursor type" of 0x03. 

From what @lvcmenezes gathered, the OG client replies with the "cursor id" of the active cursor while CUO sends back 0x00 in that field. Because POL doesn't use cursors with id 0x00, the reply was considered invalid and ignored by POL. The fix is that POL now cancels cursors also when they have a wrong id.

However, it might still be worth changing the behavior in CUO if compatibility with the OG client is desired (we haven't checked whether other emus do the same)

**Comment by andreakarasho** [comment]
Ok so now when receiving a "cancel target" CUO sends the `last active cursor id`.
Thank you!
