### ISSUE TITLE
[Feature Request] Implementation of the Logout function in packet-handlers

### ISSUE THREAD

**Issue by nitro-codes** [ClassicUO/ClassicUO#1376]
Is it possible to include in the backlog the implementation of the Logout function in packet-handlers so Assistants like Razor Enhanced could request the client to disconnect?

Source:
https://github.com/andreakarasho/ClassicUO/blob/4bb88a21ee832380c304c13392254a4f20dee1e5/src/Network/PacketHandlers.cs#L4806

**Comment by andreakarasho** [comment]
Server does not force to you to logout with this packet, it can just close the socket connection.
This is the real behaviour of thge 0xD1 packet 
http://docs.polserver.com/packets/index.php?Packet=0xD1
