### ISSUE TITLE
Blank healthbar / health line when health is unknown

### ISSUE THREAD

**Issue by roxya** [ClassicUO/ClassicUO#1381]
Before the standard client receives status info, it shows a blank healthbar:
![image](https://user-images.githubusercontent.com/7057924/124397703-71493780-dd09-11eb-8b98-d3795569fd93.png)

ClassicUO shows the healthbar background, so it appears the mobile is low on health, when really it's unknown:
![image](https://user-images.githubusercontent.com/7057924/124397731-8f169c80-dd09-11eb-92a8-0d796488e0fb.png)

**Comment by andreakarasho** [comment]
has it fixed by https://github.com/andreakarasho/ClassicUO/commit/ffb52a3388bf4446baf0d00ed58c87ec2063ee1d ?

**Comment by roxya** [comment]
It hasn't been. For the standard healthbars it always shows. The only condition that changes it is if the mobile is out of range, the bar background is hued grey. But I think it's an issue for HP lines/overheads also.

I'll have a look at hiding any type of HP bar/percent if HitsMax = 0, I think it should work and it's a logical thing to check.

**Comment by roxya** [comment]
I think https://github.com/andreakarasho/ClassicUO/commit/d35fba42c5168b3ad59fa1ddfc31bb93278cafc8 is ok, let's see.
