### ISSUE TITLE
Skills Missing?

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#1388]
Here are blanks when making a new character. The missing skills are likely Stealth and Spellweaving, but Bushido is also missing. How does ClassicUO know to omit these and how can I have them appear if I have my server set to have those skills at creation? I looked through the source code and couldn't find anything like a 1=appear and 0=not type setting.

![image](https://user-images.githubusercontent.com/49735284/126079712-0553b8e7-ba74-4871-9b22-f89b188ba86f.png)

**Comment by SaschaKP** [comment]
what are you looking is here:
https://github.com/andreakarasho/ClassicUO/blob/73df529288a38749219302666ab0e5a070eb9d18/src/Game/UI/Gumps/CharCreation/CreateCharTradeGump.cs#L170

**Comment by Djeryv** [comment]
Thanks for that. I am going to close this because it answers my question...but one comment...I am not sure why Bushido is removed during character creation because I can't see where you cannot pick that from the start. Maybe I don't know the way Bushido works on live but I didn't read any indication that you can't start with it.
