### ISSUE TITLE
Rune Symbols Not Glowing

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#1390]
For some reason the client will not show light for these ItemIDs of the runes. Below is an example of the green rune symbols that have the exact same TILEDATA settings as the other circled blue rune. The green one glows while the blue one does not. They both have their in game light levels set to Circle150. The both look fine when using a 3rd party map editor, but the client just won't light up the blue rune.

![image](https://user-images.githubusercontent.com/49735284/126868334-bdb23ef6-a60f-471f-9d44-b8850c47f55c.png)

![image](https://user-images.githubusercontent.com/49735284/126868375-dcac9915-abc8-47d6-ac82-ca1b082c271b.png)

**Comment by roxya** [comment]
what about the standard client?

**Comment by Djeryv** [comment]
This particular game does not work with the standard client anymore so there is no way to test that. To add an extra comment, they used to glow in the client. At some point they stopped glowing.

**Comment by roxya** [comment]
The light shader for this item (6 - dark blue) doesn't affect the green channel at all. So against green grass, it won't do much. Try to stand near it or place it on other surfaces which aren't green.

This is from the standard client:
![image](https://user-images.githubusercontent.com/7057924/126870003-60231da0-8bf7-4564-b0b4-6bdddc835319.png)

And ClassicUO:
![image](https://user-images.githubusercontent.com/7057924/126870020-2678456e-4be2-4975-b4c8-13836c92f05b.png)

**Comment by Djeryv** [comment]
I am going to close this then...because when I stop using the COLORED LIGHTS option it does light up. So everything you stated is probably correct. Thanks for pointing me in the right direction.
