### ISSUE TITLE
Hair showing up on corpse

### ISSUE THREAD

**Issue by Soulless-1** [ClassicUO/ClassicUO#1391]
This does not happen with the vanilla client, but seems to show items on a layer that would be inaccessible to a player when they look into a corpse.

![image](https://user-images.githubusercontent.com/17236327/127319961-1d88a7d1-f032-43de-9559-12dba04d2457.png)

**Comment by andreakarasho** [comment]
fixed https://github.com/ClassicUO/ClassicUO/commit/3afaacf55b3f712b615f9c491d229493df215498
