### ISSUE TITLE
Constant Disconnect

### ISSUE THREAD

**Issue by Iomega0318** [ClassicUO/ClassicUO#1397]
Is there a way to monitor or find out why I constantly get disconnected from a sever, if I run the client by itself or with assist every few mins I will get dc'd and then auto rejoin. Sometimes it just freezes up and I have to log out..

This does not happen with OSI Clients, UOSteam, or Orion or any other client other than this one.

Any insight or some help would be greatly appreciated, thank you.

**Comment by andreakarasho** [comment]
What assistant?
What server?
Can you reproduce the issue?

**Comment by Iomega0318** [comment]
ClassicAssist,
UOEvolution
and yes, every time I log on it takes from a few mins to several and then it times out and I either get kicked or have to relog.

**Comment by Ironfists** [comment]
I have the same issue on UOEvolution there's times it'll start saying TimeOut in the messages then disconnect.  At first thought cause afk then happened during amidst a battle.

**Comment by Ironfists** [comment]
![image](https://user-images.githubusercontent.com/88750815/129481511-61ce5827-694c-43bf-b5c0-b379c90f7e53.png)

**Comment by andreakarasho** [comment]
check if your scripts have valid paues [min 10ms] when interacting with action like  `drag/drop items`, `single/double click objects/mobiles`, `gump actions`.
