### ISSUE TITLE
House Editor problems compared to OSI client

### ISSUE THREAD

**Issue by rebb** [ClassicUO/ClassicUO#1402]
**Describe the bug**
I'm able to build certain things in the OSI Classic Client that ClassicUO either disallows or shows as broken.
Is ClassicUO using outdated / problematic housing editor rules ?

In this particular case, i am unable to place a half-arch that sits on the outer edge of the house footprint.
This is however possible in the standard classic client, and the house i built exists on an OSI server, so the commit was accepted, and the OSI editor also did not show any errors and allowed this.

**To Reproduce**
1. Build a piece of wall near the upper footprint edge, while leaving space for another tile next to it.
2. Try to place a "half arch" piece so it connects to this wall, sitting on the upper footprint.
3. Notice this is disallowed ( red ). While it is valid in the OSI classic editor

**Expected behavior**
ClassicUO Editor to allow architecture that is allowed in the OSI editor.

**Screenshots**
1. The house as i built it on the OSI servers, using the OSI classic client.
2. The house inside the editor of the OSI client, notice the half-arch on the house that i'm about to place ( allowed )
3. The house inside the editor of ClassicUO, notice how parts are shown as orange ( not the case in the OSI editor ), and that i am also unable to place the half-arch for some reason

![uo_house_osi](https://user-images.githubusercontent.com/3278522/130324431-51aed341-3c6a-46c0-92fb-5195d8770790.jpg)

![uo_house_editor_osi](https://user-images.githubusercontent.com/3278522/130324442-747c41af-6402-4915-a836-6a4886481673.jpg)

![uo_house_editor_classicuo](https://user-images.githubusercontent.com/3278522/130324447-3dedbee0-0e40-4fdd-9615-a3848e91c34c.jpg)

**Shard**
Doesn't matter really, the editor shows the same behaviour on both OSI and UOAlive servers.

**Information (please complete the following information):**
 - OS: Win7
 - ClassicUO Version: 0.1.9.31
 - [x] Using DEV Version?
 - Launcher: ClassicUO

**Comment by Pumpk1ns** [comment]
I have the same issue.

**Comment by andreakarasho** [comment]
https://github.com/ClassicUO/ClassicUO/pull/1717
