### ISSUE TITLE
Launcher GPU and CPU spike when minimized

### ISSUE THREAD

**Issue by rebb** [ClassicUO/ClassicUO#1404]
**Describe the bug**
It looks like the GPU and CPU use of the ClassicUO Launcher go up very high for no apparent reason, when the launcher gets minimized.
I have Rainmeter running with CPU and GPU meters, and noticed today some strange 80% GPU usage spikes.
Apparently they happen when the ClassicUO launcher gets minimized, possibly while it is "Getting Manifest" ( it is stuck on there for some reason, even though it worked fine earlier today ).

**To Reproduce**
1. Run ClassicUOLauncher.exe
2. Observe normal GPU usage using something like Rainmeter
3. Minimize the launcher
4. Observe GPU spike and high CPU usage

**Expected behavior**
Low GPU and CPU usage, given that this is just a launcher

**Information (please complete the following information):**
 - OS: Win7
 - ClassicUO Version: 0.1.9.31
 - [x] Using DEV Version?
 - Launcher: ClassicUO Launcher

**Comment by rebb** [comment]
Actually i think i heard about similar problems with launchers that use GPU UI recently. Something about VSync or FPS Limits not being applied when they are minimized, so they run at silly refresh rates.

**Comment by rebb** [comment]
Update : Today i tried it again, and got a "Critical Launcher Update" message, so now it is at 0.1.9.35.
The issue does not seem to happen now when i minimize.

But i am unsure if the problem occurred as a side-effect of something else ( like a manifest update being stuck ), or if it's indeed fixed now.

**Comment by andreakarasho** [comment]
Yep i fixed it yesterday
