### ISSUE TITLE
NODRAW tiles hide other tiles they are placed on

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#1405]
Sometime today the client is hiding static items that are placed in the same spot as the static NO DRAW tiles. The original client didn't have this behavior. The difference is the NO DRAW textures that don't draw on the map landscape they are covering, but the static NO DRAWS are simply used a blocker tiles that players can't see.

The ones I specifically use often in the map making is 0x21A3 which has a height of 100 and we use these to block line of site between players and creatures...or players from each other.

I just tested with 0x21A4, which is a NO DRAW static that is 4 high and my static was not hidden, but maybe because it is 5 off the ground.

If it helps, things were working fine about a couple of hours before I made this post.

**Comment by andreakarasho** [comment]
I tested and i can't see tiles like 0x21A3 and 0x21A4.
Nothing has changed about tiles/static.

**Comment by Djeryv** [comment]
Maybe these images will help....

![image](https://user-images.githubusercontent.com/49735284/130924962-70db124a-08cf-496c-993b-e23c8b56a664.png)

**Comment by andreakarasho** [comment]
i misread, my bad.
What older cuo version is working?

**Comment by Djeryv** [comment]
![image](https://user-images.githubusercontent.com/49735284/130925553-0299a6a6-34d0-490d-8fa0-61d5f9d3901d.png)

I am messing with this now too if you want to do a back and forth for testing.

To say again in case it is pertinent. 0x21A3 is 100 high so I am not sure if that is maybe taller than the tornado graphic so it is hiding it. I placed a NO DRAW tile that is 4 high and it does not hide the tornado. Just trying to state everything I can think of here.

**Comment by andreakarasho** [comment]
if it's higher the graphic will not be displayed.
Try to increase the Z of you character

**Comment by Djeryv** [comment]
I am sorry...what I meant is that if you go into the TILEDATA for the NO DRAW tile it has a HEIGHT of 100.

I didn't mean the Z axis of the items/mobiles.

The original client has 0x21A3 with a HEIGHT of 100 so it can block line of sight and such...but it should never hide anything from view.

**Comment by andreakarasho** [comment]
can you give me the world position of the static?

**Comment by Djeryv** [comment]
Did you download my game? If so do a "[go 1458 1364 70"

**Comment by andreakarasho** [comment]
i did, but the Admin/password credentials do not work

**Comment by Djeryv** [comment]
admin
password

**Comment by andreakarasho** [comment]
yeah nvm i had multiples server in local open.
The issue is caused by this fix: https://github.com/andreakarasho/ClassicUO/commit/e46ad1d95c06849bf612124ba8ecb48358188690

should be ok now

**Comment by Djeryv** [comment]
Confirmed. Thanks.
