### ISSUE TITLE
Client Crashing starting today when running multiple clients 

### ISSUE THREAD

**Issue by Sethisto** [ClassicUO/ClassicUO#1409]
I have been multiboxing 3 characters for the past month with CUO on a private server called UO Alive. Starting today, the clients will randomly crash and shut down when I tab between them. This happens especially badly when doing champion spawns, where it's basically impossible to tab between them more than a few times before one or two crash. Plugin is regular Razor

 - Name of the shard: UO Alive
 - OS: Windows 10 
 - ClassicUO Version: 1.9.50
 - No
 - Launcher:  classicuo_launcher
 - How many clients do you run in parallel: 3
 - Screen Resolution: 1920x1080

Here is the crash logs. They are always the same: 

######################## [START LOG] ########################
ClassicUO [STANDARD_BUILD] - 0.1.9.50 - 08/27/2021 19:46:56
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Shard: login.uoalive.com
ClientVersion: 7.0.90.16

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.Scenes.GameScene.DrawWorld(UltimaBatcher2D batcher, Matrix& matrix, Boolean use_render_target)
   at ClassicUO.Game.Scenes.GameScene.Draw(UltimaBatcher2D batcher)
   at ClassicUO.GameController.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.RedrawWindow()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.Win32OnPaint(IntPtr userdata, IntPtr evtPtr)
######################## [END LOG] ########################

Thanks for reading! I have no idea why this is happening today. I haven't updated any drivers today, and as far as I know CUO hasn't updated. I'm stumped.

**Comment by andreakarasho** [comment]
fixed
