### ISSUE TITLE
PGumpResponse Bug

### ISSUE THREAD

**Issue by OutsideTheBoxGit** [ClassicUO/ClassicUO#142]
**Describe the bug**
PGumpResponse Bug
This is a fix for multiple text entries response.
Lenght * 2 is used to calc the packet size, but not here on lenght of each text item.

**To Reproduce**
Response a gump with multiple text entries, just the first one will be sent correctly.

**Solution**
                Just change the line "entries[i].Item2.Length * 2;"

                for (int i = 0; i < entries.Length; i++)
                {
                    int length = entries[i].Item2.Length;
                    WriteUShort(entries[i].Item1);
                    WriteUShort((ushort) length);
                    WriteUnicode(entries[i].Item2, entries[i].Item2.Length);
                }`

**Comment by andreakarasho** [comment]
fixed locally. It will available next release.
Thanks :D
