### ISSUE TITLE
SystemChatControl is missing Party System command for removing party members

### ISSUE THREAD

**Issue by Xoduz** [ClassicUO/ClassicUO#1421]
**Describe the bug**
The Party System in UO has a party chat command for removing targeted players from the party, which is missing from SystemChatControl in ClassicUO.

Quote: "Typing “/rem” will allow the party leader to remove a party member. A targeting cursor will appear, select the character you wish to remove. Once targeted, the party member is immediately removed from
the party."
Source: https://uo.com/wiki/ultima-online-wiki/player/the-party-system/

**To Reproduce**
1. Invite another player to a party using /add chat command or party gump from paperdoll
2. After they /accept the invitation, use /rem to attempt to remove them from the party
3. Observe that the /rem chat command gets sent to the party chat like any other text, and no target cursor appears

**Expected behavior**
Party leader is given a target cursor when using the /rem party chat command, with which they can remove a targeted party member from the party

**Information (please complete the following information):**
 - ClassicUO Version: 0.1.9.79
 - [ ✔ ] Using DEV Version?
 - Launcher: ClassicUO Launcher

**Comment by SaschaKP** [comment]
done with https://github.com/ClassicUO/ClassicUO/pull/1424
