### ISSUE TITLE
item.Amount is not reporting correctly for non stackable items like armor, weapon and jewelry

### ISSUE THREAD

**Issue by robinhood-code** [ClassicUO/ClassicUO#1422]
**Describe the bug**
item.Amount is not reporting correctly for non stackable items like armor, weapon and jewelry

If they are worn then it's reported correctly , which is 1. If they are put in bag, corpse or on the ground then it's not correct. 

When using RE inspector it reports correctly, so it's a CUO issue. 

**To Reproduce**
type -info, target an non stackable item armor, weapon and jewelry which is on the ground, bag or corpse and the amount field will report something larger than 1. 

**Expected behavior**
all non stackable item should only has amount = 1

**Screenshots**
https://ibb.co/DGMymx9

**Shard**
 - Name of the shard: OSI

**Information (please complete the following information):**
 - OS: win10
 - ClassicUO Version: 0.1.9.79
 - [Y] Using DEV Version?  Yes
 - Launcher: classicuo

**Additional context**
 - How many clients do you run in parallel: 1
 - Screen Resolution: 1920*1080

**Comment by robinhood-code** [comment]
Closing the ticket as KARASHO has confirmed the amount value is sent by the server so this is not a bug of CUO.

**Comment by andreakarasho** [comment]
fixed in: https://github.com/ClassicUO/ClassicUO/commit/061137467d970afd1d84811a21a406c78901a0bd
