### ISSUE TITLE
Statics file parse

### ISSUE THREAD

**Issue by OutsideTheBoxGit** [ClassicUO/ClassicUO#143]
**Describe the bug**
I guess something is going wrong when parsing static files.
Maybe its related to some custom stuff on OUOutlands that is going wrong here.

It works fine on Orion, im going to check how its doing the parse there and it should be an easy fix.

**To Reproduce**
Login on Outlands, at starter city

**Screenshots**
ClassicUO
![image](https://user-images.githubusercontent.com/35537681/48296787-11c7fa80-e482-11e8-9ea7-5ff50e7fe667.png)

OrionUO
![image](https://user-images.githubusercontent.com/35537681/48296730-a2520b00-e481-11e8-8d90-c8ef56b52682.png)

**Comment by andreakarasho** [comment]
fixed locally. It will available next release
