### ISSUE TITLE
Turn player to face target when attacking

### ISSUE THREAD

**Issue by jaedan** [ClassicUO/ClassicUO#159]
The client should automatically turn the player to face their target when attacking. This behavior should trigger when sent the animation packet by the server.

**Comment by andreakarasho** [comment]
I don't know if this feature exist into the original client. If it exists could be a server issue? 
Btw I'll check.

**Comment by SaschaKP** [comment]
isn't the server that sends a "turn" to the player? I've double checked on the server locally, and is always the server that sends a packet, after processing the deltaqueue.

**Comment by jkachhad** [comment]
Tested on 7.0.20.0/RunUO
1. Spawn an NPC and begin attacking (warmode enabled). Perform a swing.
2. Run away from the NPC, set frozen to true to prevent it from moving around.
3. Face away from the target.

You can set a breakpoint on NetState.Send() on RunUO and wait for the MovementAck to be sent, triggered by a MovementReq on the call stack. 

On it's own, periodically, 7.0.20.0 will request (Direction | Running) movement towards the NPC.

**Comment by andreakarasho** [comment]
So, it is a server side issue?

**Comment by jaedan** [comment]
No - the client automatically turns to face the current target while in warmode, if you haven't made a movement request in some period of time.

**Comment by andreakarasho** [comment]
added

**Comment by Djeryv** [comment]
I have been playing on a more recent beta version and this is happening again. I never face the targets I am attacking.

**Comment by Admin-Yukiko** [comment]
In my opinion I don't think the client should make the player face the opponent. This is an easy server side fix. We have implemented it on several POL servers. So a RunUO or ServUO server ought to be able to implement it. All the server needs to do is change the attackers "facing" to face the opponent. The server should probably also do the same for the defender.

**Comment by Djeryv** [comment]
So anyway, the original client will make you face your opponent. Since it was stated that it was added, my assumption is that it broke again down the line so I am just letting you know it is occurring.

**Comment by andreakarasho** [comment]
0x2F packet added

EDIT: https://github.com/andreakarasho/ClassicUO/pull/916
