### ISSUE TITLE
Outlands Custom Status Gump

### ISSUE THREAD

**Issue by floyd501** [ClassicUO/ClassicUO#162]
**Description**
The Outlands player status gump needs to be rendered slightly differently than the regular player status gump.  For example, murder count and various timers are displayed rather than swing speed, resists, etc.

**Additional context**
Shard: Outlands

**Comment by floyd501** [comment]
I've begun working on this, added for tracking.

**Comment by 3HMonkey** [comment]
Hey,

will you reach a working version until december so for the alpha release?

Greetings

**Comment by floyd501** [comment]
December sounds realistic for at least the basic functionality.  There are a few outstanding things like minimization (I noticed that none of the other gumps can be minimized currently), group / party member status gumps, etc.  I'm also wondering how shard-specific functionality or rendering is to be handled in general.  I see client version being checked often, but I'm not sure yet how the client will actually decide to render the Outlands status bar vs. the standard one.

Regarding the alpha release, and when we say December, is that beginning, middle, or end, or yet to be determined?

Thanks.

**Comment by andreakarasho** [comment]
Hi, Outlands uses a modded client. That s the reason status bar shows different values.
Here there is the correct outlands statusbar layout: https://github.com/jaedan/OrionUO/blob/master/OrionUO/Gumps/GumpStatusbar.cpp

Atm we are focussed on others hot tasks, so maybe this option will be done in future.

**Comment by floyd501** [comment]
Thanks. I have been using Jaedan's implementation in Orion as a reference already.

I was just wondering how Outlands-specific features that make it into ClassicUO are going to be handled, whether it's with a separate fork (similar to Jaedan's fork of Orion) or if the client will determine at runtime somehow.

I understand there are many other high priority items.

**Comment by andreakarasho** [comment]
My idea is to release an unique client that can support these mods (
That s exactly why i wrote: "it will be done in future". We have to discuss about how to handle different client customization).

I dont like to see lots of obsolete forks like sallos client.
I hope to do it in the best way. 
If you have some idea contact me on discord.

**Comment by jaedan** [comment]
We're here: https://discord.gg/VdyCpjQ

I agree that we don't want to encourage forks, so we should probably implement it as a configuration option.

**Comment by andreakarasho** [comment]
done!
