### ISSUE TITLE
Callback for targets

### ISSUE THREAD

**Issue by 3HMonkey** [ClassicUO/ClassicUO#165]
**Describe the solution you'd like**
A callback should be assigned to the target system to handle the delay between spells and the upcoming target cursor packet like Razor does.

**Comment by andreakarasho** [comment]
I thought about that.
It's not necessary to add this feature. Simply use the Update() function to handle it.

- You press the button of healtbar to heal  the healthbar owner (GameActions.CastSpell()).
- add tow field inside party healtbar : _timeToTarget, _spellTarget.  After GameActions.CastSpell(), set timeToTarget = CoreGame.Ticks + 500 and _spelltarget = healtbar owner,
-intop the Update() check if a _spelltarget != null && TargetSystem.IsTargeting && _timeToTarget > totalms, then send the target with TargetSystem.SetTarget(heatlbar owner)
