### ISSUE TITLE
Compile to javasscript

### ISSUE THREAD

**Issue by boberski666** [ClassicUO/ClassicUO#178]
Hey guys,

this is question mainly for our developers, did yoy guys tried to compile client into javascript to run it as web page? I mean with JSIL or Bridge.NET?

**Comment by DarkLotus** [comment]
Theoretically it should be possible JSIL has been used with other XNA based games, though asset loading would need to be rewritten to stream from a server or bundle content in the client build, and sockets would need to be wrapped in a websocket layer, with a server sitting someone converting to standard sockets and proxying onto your server.

**Comment by boberski666** [comment]
Is it even in plans for someone to do that at this point?

**Comment by andreakarasho** [comment]
Hi, 

Why we should port the game to a webapp?
Us plan is to distribuite an executable crossplatform application thanks to Mono (or netcore).

We already discussed on Discord why a webapp is not a valid option:
First of all the legality. We cannot redistribuite game files without authorization.
Second one, we will have a big performance impact.

@3HMonkey has more experience than me about legaly question.

**Comment by boberski666** [comment]
You do not share any UO files the same as it is right now. It would be cool to have client that is accessable from anywhere you want. About performance, it is a thing to test. UO rendering is not so complex as in other games so it maybe not so bad.

**Comment by andreakarasho** [comment]
UO rendering is more complex that you expect :D .
Btw we already can run the game everywhere (not android or ios, but whoes play UO on a mobile phone ?).
So i think we'll never do a JS porting.
BTW if you want explain better your idea login Discord :)
