### ISSUE TITLE
IndexOutOfRange

### ISSUE THREAD

**Issue by plugtopus** [ClassicUO/ClassicUO#190]
Hi all,
Please help how to fix this error

![3yw4qch](https://user-images.githubusercontent.com/36801212/50551518-59048780-0c8a-11e9-9e2b-52766fda239f.png)

Use Ultima Online: High Seas (7.0.18.1 and 7.0.23.1)

**Comment by plugtopus** [comment]
![clip2net_181230233311](https://user-images.githubusercontent.com/36801212/50551571-4474bf00-0c8b-11e9-9dd2-267a9e20fcec.png)

settings.json:

{
  "username": "",
  "password": "",
  "ip": "127.0.0.1",
  "port": 2593,
  "lastcharactername": "",
  "ultimaonlinedirectory": "D:\\UltimaOnlineHS",
  "clientversion": "7.0.23.1",
  "maxfps": 144,
  "debug": true,
  "profiler": true,
  "preload_maps": false
}

**Comment by ghost** [comment]
попробуй так
обрати внимание на двойной бэкслеш в пути к папке УО, и то что двойной бэкслеш стоит в конце пути

settings.json:

{
"username": "",
"password": "",

"ip": "ЗДЕСЬ_АДРЕСС_СЕРВЕРА(play.uooutlands.com)",
"port": 2593,
"lastcharactername": "",
"ultimaonlinedirectory": "D:\\\\UltimaOnlineHS\\\\",
"clientversion": "ПРАВИЛЬНАЯ_ВЕРСИЯ_КЛИЕНТА(outlands: 7.0.15.1)",
"maxfps": 144,
"debug": true,
"profiler": true,
"preload_maps": false
}

**Comment by plugtopus** [comment]
Да, дабл слеш тоже делал, без него не сработало сразу, а вот двойной вконце не пробовал
Сейчас попробую для uooutlands.com тогда, может у меня с файлами клиента что-то не так

**Comment by andreakarasho** [comment]
English please.

**Comment by plugtopus** [comment]
D:\2222\ClassicUO-master\bin\Debug>ClassicUO.exe
IGLDevice: OpenGLDevice
OpenGL Device: Intel(R) Iris(TM) Graphics 540
OpenGL Driver: 4.4.0 - Build 21.20.16.4664
OpenGL Vendor: Intel
MojoShader Profile: glsl120
EXT_swap_control_tear unsupported. Fall back to standard VSync.
21:04:51 |  Trace   | Initialized service : Settings
21:04:51 |  Trace   | Checking for Ultima Online installation...
21:04:51 |  Trace   | Client version: 7.0.18.1 - 117445121
21:04:51 |  Trace   | Done!
21:04:51 |  Trace   | Ultima Online installation folder: D:\uo\
21:04:51 |  Trace   | Loading files...
21:04:51 |  Trace   | Loading file:             D:\uo\map0.mul
21:04:51 |  Trace   | Loading file:             D:\uo\statics0.mul
21:04:51 |  Trace   | Loading file:             D:\uo\staidx0.mul
21:04:51 |  Trace   | Loading file:             D:\uo\map1.mul
21:04:51 |  Trace   | Loading file:             D:\uo\statics1.mul
21:04:51 |  Trace   | Loading file:             D:\uo\staidx1.mul
21:04:51 |  Trace   | Loading file:             D:\uo\map2.mul
21:04:51 |  Trace   | Loading file:             D:\uo\statics2.mul
21:04:51 |  Trace   | Loading file:             D:\uo\staidx2.mul
21:04:51 |  Trace   | Loading file:             D:\uo\map3.mul
21:04:51 |  Trace   | Loading file:             D:\uo\statics3.mul
21:04:51 |  Trace   | Loading file:             D:\uo\staidx3.mul
21:04:51 |  Trace   | Loading file:             D:\uo\map4.mul
21:04:51 |  Trace   | Loading file:             D:\uo\statics4.mul
21:04:51 |  Trace   | Loading file:             D:\uo\staidx4.mul
21:04:51 |  Trace   | Loading file:             D:\uo\map5.mul
21:04:51 |  Trace   | Loading file:             D:\uo\statics5.mul
21:04:51 |  Trace   | Loading file:             D:\uo\staidx5.mul
21:04:51 |  Trace   | Loading file:             D:\uo\artidx.mul
21:04:51 |  Trace   | Loading file:             D:\uo\art.mul
21:04:52 |  Trace   | Loading file:             D:\uo\anim.idx
21:04:52 |  Trace   | Loading file:             D:\uo\anim.mul
21:04:52 |  Trace   | Loading file:             D:\uo\anim2.idx
21:04:52 |  Trace   | Loading file:             D:\uo\anim2.mul
21:04:52 |  Trace   | Loading file:             D:\uo\AnimationFrame1.uop
21:04:52 |  Trace   | Loading file:             D:\uo\anim3.idx
21:04:52 |  Trace   | Loading file:             D:\uo\anim3.mul
21:04:52 |  Trace   | Loading file:             D:\uo\AnimationFrame2.uop
21:04:52 |  Trace   | Loading file:             D:\uo\anim4.idx
21:04:52 |  Trace   | Loading file:             D:\uo\anim4.mul
21:04:52 |  Trace   | Loading file:             D:\uo\AnimationFrame3.uop
21:04:52 |  Trace   | Loading file:             D:\uo\anim5.idx
21:04:52 |  Trace   | Loading file:             D:\uo\anim5.mul
21:04:52 |  Trace   | Loading file:             D:\uo\AnimationFrame4.uop
21:04:53 |  Trace   | Loading file:             D:\uo\AnimationSequence.uop

Необработанное исключение: System.IndexOutOfRangeException: Индекс находился вне границ массива.
   в ClassicUO.IO.Resources.Animations.Load() в D:\2222\ClassicUO-master\src\IO\Resources\Animations.cs:строка 822
   в ClassicUO.IO.FileManager.LoadFiles() в D:\2222\ClassicUO-master\src\IO\FileManager.cs:строка 71
   в ClassicUO.Engine.Initialize() в D:\2222\ClassicUO-master\src\Engine.cs:строка 268
   в Microsoft.Xna.Framework.Game.DoInitialize()
   в Microsoft.Xna.Framework.Game.Run()
   в ClassicUO.Engine.Main(String[] args) в D:\2222\ClassicUO-master\src\Engine.cs:строка 191

D:\2222\ClassicUO-master\bin\Debug>

**Comment by plugtopus** [comment]
Unhandled exception: System.IndexOutOfRangeException: The index was outside the bounds of the array.

settings.json:

{
"username": "",
"password": "",
"ip": "127.0.0.1",
"port": 2593,
"lastcharactername": "",
"ultimaonlinedirectory": "D:\\uo\\",
"clientversion": "7.0.18.1",
"maxfps": 144,
"debug": true,
"profiler": true,
"preload_maps": false
}

**Comment by plugtopus** [comment]
As far as I understand the problem in the file "AnimationSequence", but it is in the "uo" folder.

**Comment by plugtopus** [comment]
if use 2.0.3 client - have error in file "LoginScene.cs"

![3ywtf88](https://user-images.githubusercontent.com/36801212/50566360-7cd6d480-0d41-11e9-84d7-bfc4389a1f1a.png)

**Comment by plugtopus** [comment]
Вы можете мне сбросить свой рабочий ClassicUO.exe ? 
Может дело в сборке самого файла (я брал последние файлы с репозитория)

**Comment by plugtopus** [comment]
The problem is partially solved, I managed to run for 7.0.15.1 client from Outlands. Why it does not work for a standard client of HS - so far a mystery to me.

**Comment by andreakarasho** [comment]
I run fine 7.0.58.9 and outlands version. 

Can you provide us a link to download your fully client?

**Comment by ghost** [comment]
https://drive.google.com/file/d/0ByOhk1t5lwpVUzVyZU5WdzVqVlE/view
here is ClassicUO client

**Comment by andreakarasho** [comment]
That s the client i linked to you today :D

**Comment by plugtopus** [comment]
Use outlands client pack, edit login.cfg - run client.exe - success login & connect in my server

Use classic uo - edit settings.json (path to outlands, version 7.0.15.1) - success login but crash when I select "server" in the list 

![3ywuu4g](https://user-images.githubusercontent.com/36801212/50567675-51a7b180-0d50-11e9-93a7-6b1f939e92fb.png)

It seems to me, without debugging the code, I cannot find the problem and run it from the box, so I will try :) It’s strange that using Orion, I didn’t have such problems.

**Comment by plugtopus** [comment]
For the server "Outland" everything is fine, if you do not press the "new" button, otherwise the client crashes again. I think my path to mastering ClassicUO will simply not be for sure))) Does everyone have similar problems when you first start or is it so lucky for me?

![3ywv0qv](https://user-images.githubusercontent.com/36801212/50567759-77818600-0d51-11e9-8534-ad2cfe720c38.png)

![3ywuyzq](https://user-images.githubusercontent.com/36801212/50567760-7b150d00-0d51-11e9-9981-97ed0ec90949.jpg)

**Comment by ghost** [comment]
you better use ClassicUO client files i gave you in previous comment. Client executable was created specifically for them, so you will get less errors

**Comment by SaschaKP** [comment]
Check now, last commit to the *DEV* branch should have fixed the issue.

**Comment by SaschaKP** [comment]
Tested on local, this is fixed in dev branch, my commit fixes also the null ref on character creation and subsequent pages.

**Comment by plugtopus** [comment]
The dev branch has certain problems, maybe I'm doing something wrong. Probably, I will wait for the release, or I will try to independently find the required changes in your commits. 

![3ywnhfu](https://user-images.githubusercontent.com/36801212/50575840-300cff80-0e0e-11e9-9cb6-f2a4b96df7b3.png)

![3ywnizj](https://user-images.githubusercontent.com/36801212/50575841-326f5980-0e0e-11e9-99dd-c60e9b4ba661.png)

![3ywnizn](https://user-images.githubusercontent.com/36801212/50575842-34d1b380-0e0e-11e9-86af-7624cd67a0e7.png)

**Comment by andreakarasho** [comment]
It's normal, please wait for the next commit :) (or comment each error)
