### ISSUE TITLE
Incorrect name 

### ISSUE THREAD

**Issue by ghost** [ClassicUO/ClassicUO#196]
Incorrect name and missing Information

![untitled](https://user-images.githubusercontent.com/37397739/50862814-ef2c6200-139c-11e9-87ae-a59065916451.png)

UODreams shard

**Comment by ghost** [comment]
it say "IsLocked = False"
should be true

**Comment by jkachhad** [comment]
1. In regards to the name issue, can't seem to reproduce on the dev branch. 
2. The locked down displayed in the tooltip is unrelated to the IsLocked in the info gump.

**Comment by andreakarasho** [comment]
fixed: https://github.com/andreakarasho/ClassicUO/commit/d69d62621c8027b9aa687ecbf690fe4c7069ce3e
