### ISSUE TITLE
Launcher for ClassicUO

### ISSUE THREAD

**Issue by 3HMonkey** [ClassicUO/ClassicUO#2]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
The client should be started by using a launcher application. I suggest using the one I created some time ago. It is using a one file NoSQL-database (because of different shard and user profiles). Its very easy to work with that. Maybe we can also think about swapping from settings.json to that db.

**Additional context**

![grafik](https://user-images.githubusercontent.com/4610892/44910069-1d7c9f80-ad22-11e8-8a01-9b3ad70e1944.png)

**Comment by Alaca35** [comment]
Everything is beautiful, however! ClassicUO rises up to 30-33 or even 35 when CPU Cache is around 2-3 in Normal Clients!

**Comment by andreakarasho** [comment]
> Everything is beautiful, however! ClassicUO rises up to 30-33 or even 35 when CPU Cache is around 2-3 in Normal Clients!

seems the right place to post

**Comment by andreakarasho** [comment]
done
