### ISSUE TITLE
Stacked Items

### ISSUE THREAD

**Issue by aclark13** [ClassicUO/ClassicUO#202]
- Shift + drag doesn't pull the whole stack
- When pulling a stack you can't just hit "1" to pull one item, you have to backspace the whole stack number and type in how many you want
- Kindling doesn't give a stack count on single click

**Comment by andreakarasho** [comment]
1) not implemented yet
2) done in https://github.com/andreakarasho/ClassicUO/commit/61f8c6d2910038d7cab0879572923e434622dc24
3) wat !?

**Comment by aclark13** [comment]
#3: Stacked kindling doesn't say "Kindling: 10", just says "Kindling".  Boards, ingots, regs, etc all seem to properly display the stacks count.
