### ISSUE TITLE
Don't dispose items out of range

### ISSUE THREAD

**Issue by jkachhad** [ClassicUO/ClassicUO#211]
After #210, we need a way to keep items from disposing if not near the player. Why? My server has a feature where ObjectPropertyLists get sent to the player for items they may not necessarily see. 
For example, in this gump, the item has been internalized on the server-side:
![image](https://user-images.githubusercontent.com/1934897/50955309-9f699b80-146d-11e9-8af6-02705b4f208a.png)

Far as 7.0.20.0 - we can still display this OPLs on gumps without issues. I was able to create dummy entities on ClassicUO when receiving OPL, but they are disposed on the next update (out of range). 

```
                foreach (Item item in Items)
                {
                    item.Update(totalMS, frameMS);

                    if (item.Distance > ViewRange && item.OnGround)
                    {
                        if (item.IsMulti)
                        {
                            if (HouseManager.TryToRemove(item, ViewRange))
                                RemoveItem(item);
                        }
                        else
                            RemoveItem(item);
                    }

                    if (item.IsDisposed)
                        Items.Remove(item);
                }
```

**Comment by andreakarasho** [comment]
is the item displayed movable/pickable or is it a picture only?

**Comment by jkachhad** [comment]
It is picture only. The tooltip is displayed when you hover over it.

**Comment by andreakarasho** [comment]
So server sends opl, original client makes dummy item and you see the tooltip when mouse is over it.
Right?

**Comment by jkachhad** [comment]
Correct

**Comment by andreakarasho** [comment]
Maybe it s not necessary to make a dummy item.
Simply we need a dictionary <serial, opl string>.
When gump is closed, remove the entry by the serial from dictionary
