### ISSUE TITLE
House Tiles

### ISSUE THREAD

**Issue by aclark13** [ClassicUO/ClassicUO#217]
You can see part of the foundation, or a mis-drawn tile on the North wall/floor when you walk around a house. Video attached in zip file.

[Media1.zip](https://github.com/andreakarasho/ClassicUO/files/2752213/Media1.zip)

**Comment by andreakarasho** [comment]
it's an algorithm error

**Comment by zolter** [comment]
https://i.imgur.com/EUq9xmX.gifv

**Comment by zolter** [comment]
llama head https://i.imgur.com/QObihak.gifv

**Comment by andreakarasho** [comment]
should be fixed by @SaschaKP
