### ISSUE TITLE
Gump options need a restyle.

### ISSUE THREAD

**Issue by andreakarasho** [ClassicUO/ClassicUO#231]
horrible gump options :D

**Comment by plugtopus** [comment]
Clone the original client?

**Comment by andreakarasho** [comment]
please no!

**Comment by plugtopus** [comment]
> please no!

I'm not crazy 🤣

**Comment by plugtopus** [comment]
If the project named "ClassicUO", then is there a goal to clone function (and visual display) from original client (>HS)? For example, Orion tries to fully comply with the original client + expand useful functionality. We have some basic goal, except for "make it all work"?

**Comment by andreakarasho** [comment]
Done.
