### ISSUE TITLE
Target Coordinates return 0,0,0 value for POL when ESC

### ISSUE THREAD

**Issue by vitorfdl** [ClassicUO/ClassicUO#232]
**Describe the bug**
In POL server, when you target for coordinates, the cuo return a 0,0,0 coordinate to the server. POL handle this in it's core, so we can change the behaviour to get 0,0,0 as null.

**Expected behavior**
It should return the same as the original client. OrionUO doesn't have this bug, maybe could help by looking at their code.

**Comment by andreakarasho** [comment]
fixed : https://github.com/andreakarasho/ClassicUO/commit/6d1b6208115e461d7d0c05eb9999388b747fe857
