### ISSUE TITLE
Custom Tooltips for GUMPS not working

### ISSUE THREAD

**Issue by vitorfdl** [ClassicUO/ClassicUO#233]
**Describe the bug**
When I sent "Tooltip 1114057 @My Text go here@'" to the gump layout, it should apply a custom tooltip with the specified text. It's returning "1_val" instead.

The same behaviour is expected for Buff icons too. Not sure if it's not working there.

**Expected behavior**
<img width="291" alt="image" src="https://user-images.githubusercontent.com/5141631/51574336-8660e180-1e94-11e9-9470-c17bf5e9dbe4.png">

**Screenshots**
<img width="225" alt="image" src="https://user-images.githubusercontent.com/5141631/51574385-ac868180-1e94-11e9-9890-1e7b29be3a8a.png">

**Desktop (please complete the following information):**
 - OS: win 10
 - Version [e.g. 7.0.74]

**Comment by andreakarasho** [comment]
![image](https://user-images.githubusercontent.com/20810422/51604345-d24f6d00-1f0c-11e9-844d-41076b9bec72.png)

Fixed, but some special characters are not displayed, let me know if that it's a my side problem only.

**Comment by vitorfdl** [comment]
Yes, special characters aren't being displayed here.
