### ISSUE TITLE
circle of transparency inside houses

### ISSUE THREAD

**Issue by uophs** [ClassicUO/ClassicUO#244]
**Describe the bug**
When circle of transparency is enabled and you run into a house it will not remove the roof so you cannot see much inside.

**To Reproduce**
1. click last checkbox in general options
2. run inside a player house, npc city houses seem to work fine

**Comment by andreakarasho** [comment]
done
https://github.com/andreakarasho/ClassicUO/commit/7d54ff8c0317328673eca15a12e3b2e910735481
