### ISSUE TITLE
context menu missing

### ISSUE THREAD

**Issue by uophs** [ClassicUO/ClassicUO#246]
In the paperdoll or in your backpack there should be a context menu when single leftclicking an item. While you can use the skill menu to get the arms lore dialog or poison weapons, there is no way to recharge aspect items at the moment.

**Comment by andreakarasho** [comment]
and this done too 🗡 

https://github.com/andreakarasho/ClassicUO/commit/f2934d761df1140a7c8ca30e31fad747d9cde01d
