### ISSUE TITLE
StartCharCreation()

### ISSUE THREAD

**Issue by zolter** [ClassicUO/ClassicUO#247]
Login to sphereserver (AccApp=2, MaxCharsPerAccount=1) with new account
1. no create button
2. no start autocreation screen

### CUO

![cuo](https://user-images.githubusercontent.com/1370602/51915894-cb30cf00-23e4-11e9-80a6-9839cf9ed477.jpg)

### Orion

![orion](https://user-images.githubusercontent.com/1370602/51915908-d5eb6400-23e4-11e9-9d72-858a1c648f76.jpg)

### client_7.0.18.0.exe

![origin](https://user-images.githubusercontent.com/1370602/51915943-eb608e00-23e4-11e9-84b7-ec4ed7f160e5.jpg)

**Comment by zolter** [comment]
```
  "username": "ozzy1231www1",
  "password": "",
  "ip": "uoconnect.ru",
  "port": 2593,
```

**Comment by andreakarasho** [comment]
https://github.com/andreakarasho/ClassicUO/commit/2d047e8c509be491efe271b6dc6439775ea0c8d2
done but not tested

**Comment by zolter** [comment]
correct
