### ISSUE TITLE
PClientViewRange

### ISSUE THREAD

**Issue by zolter** [ClassicUO/ClassicUO#252]
You remember why disable this code from Orion?

![3zpy6ri](https://user-images.githubusercontent.com/1370602/52086800-79d53b00-25b0-11e9-8747-5de5346fcce3.png)

VIDEO: https://www.youtube.com/watch?v=G0-xW-Xg8Nk

This line corrects the problem because the server knows the maximum client area (sphereServer).

if return this code : https://www.youtube.com/watch?v=O2tLsaqw24A (FIX)

CV_70331 >= default 24
CV_305D >= default 18 but client can send packet what supports more
CV_305D <= 18

"clientversion": "7.0.18.0",

**Comment by andreakarasho** [comment]
Time ago i tried on uodemise to send 24 as viewrange and the server sent 18, but on original client it uses 24.
That's the reason why i disabled it atm.

**Comment by zolter** [comment]
I think we should return the default area to 18 pixels and increase this value to 24 as Orion does. 
We can also add an option that helps clients >=CV_305D through settings to set 24 pixels (if their shard supports this value)

Without this code server does not know that the client (>=CV_305D  && <=CV_70331 ) is ready to accept 24 and returns the default of 18.

**Comment by andreakarasho** [comment]
Done.


I hope.
