### ISSUE TITLE
Pets disappear offscreen

### ISSUE THREAD

**Issue by jnelson76** [ClassicUO/ClassicUO#276]
**Describe the bug**
When you run to far away from pets and come back you can no longer see them.  After a bit they reappear sometimes

**To Reproduce**
Run fast away from pets until they offscreen.  Then run back to them.

**Expected behavior**
Pets to stay visible

**Additional context**
Orion had this issue also.

**Comment by andreakarasho** [comment]
Hi, i need some infos:

- shard
- shard client version
- OS

**Comment by jnelson76** [comment]
- Outlands
- 7.0.15.1
-W10 1803
-I was on latest dev pull

I'm Mordekai

**Comment by Nirad** [comment]
any pet ? or horse or ...

**Comment by jnelson76** [comment]
It was a Dragon and a Drake

**Comment by andreakarasho** [comment]
try to set fixed time step = false

**Comment by andreakarasho** [comment]
News?

**Comment by andreakarasho** [comment]
fixed https://github.com/andreakarasho/ClassicUO/pull/298
