### ISSUE TITLE
TargetSystem revamp

### ISSUE THREAD

**Issue by andreakarasho** [ClassicUO/ClassicUO#296]
Missing:
- highlight current target by its notoriety
- hp % above target (or all mobiles)*
- hp line above all mobiles*

Done:
- hp line under target*
- different target type (harmful/beneficial/neutral)

* Basically the hp line above mobile or all mobiles is an option. Atm the hp line is under the current target

**Comment by oroechimaru** [comment]
can we get: (currently tested in alpha3 and 3/10 dev)
a. a bit smoother clicking for barding skills, bandages etc when clicking health bars or monsters (sometimes you have to click a few times before it registers or try a different part of the health bar)

b. is there a way to filter "tame" and some other items on the screen? often it may spam 3-10 popups for various timetables and it makes it hard to see your actual target. if i should post this in a separate thread let me know!

**Comment by andreakarasho** [comment]
A. Try to set fixed time.step to false into settings.json

B. Open a mew feature request and explain it better please

**Comment by oroechimaru** [comment]
sounds good I will do both after work. thanks for your hard work

**Comment by andreakarasho** [comment]
A. before to set fixed time step = false, try the latest dev. Fixed miss clicking

**Comment by oroechimaru** [comment]
I can click a ton better in dev (maybe alpha 3 too) when bandaging, attacking etc.

**Comment by andreakarasho** [comment]
done
