### ISSUE TITLE
QuestArrowGump position

### ISSUE THREAD

**Issue by zolter** [ClassicUO/ClassicUO#302]
The coordinates of the gamp do not correspond to the position of the animal on the map.

### classic (7.0.18.0)

![404ibxk](https://user-images.githubusercontent.com/1370602/53443086-83b55700-3a13-11e9-889c-9896783bc53c.jpg)

### CUO

![404i7w3](https://user-images.githubusercontent.com/1370602/53443087-83b55700-3a13-11e9-8286-c7180c9762a0.jpg)

### Scale position bug

![404jqga](https://user-images.githubusercontent.com/1370602/53443143-acd5e780-3a13-11e9-96c3-c7d1d723c14e.jpg)

![404joj0](https://user-images.githubusercontent.com/1370602/53443144-acd5e780-3a13-11e9-8fa6-e1ff5df2b6bc.jpg)

**Comment by andreakarasho** [comment]
@jkachhad can you put an eye on it please?

**Comment by jkachhad** [comment]
I'll take a look, thank you!
