### ISSUE TITLE
Elf (7.0.18)

### ISSUE THREAD

**Issue by zolter** [ClassicUO/ClassicUO#303]
### CUO

![404kxdm](https://user-images.githubusercontent.com/1370602/53444420-c75d9000-3a16-11e9-8ff7-c65adf93955b.jpg)

![404kzkl](https://user-images.githubusercontent.com/1370602/53444421-c9275380-3a16-11e9-8e82-709a09544947.png)

### 7.0.18 (all ok)

![404kgs0](https://user-images.githubusercontent.com/1370602/53444433-d2b0bb80-3a16-11e9-89ba-06f82078f8ad.jpg)

**Comment by andreakarasho** [comment]
does it happen when you login and open paperdoll? Because from your screen the charcreation seems good

**Comment by zolter** [comment]
An error occurs after the city selection screen.

**Comment by andreakarasho** [comment]
can you see the call stack in debug mode?

**Comment by zolter** [comment]
The problem is in the creation. 
If I create an Elf through a classic client - I can successfully login in through CUO

**Comment by zolter** [comment]
I simply will not have enough time in the coming days to look at these problems myself, so I created issues.

**Comment by zolter** [comment]
![4051zyq](https://user-images.githubusercontent.com/1370602/53472742-2e0f9780-3a71-11e9-81b9-c0dd45170089.png)

![4051fdn](https://user-images.githubusercontent.com/1370602/53472774-4aabcf80-3a71-11e9-9c3e-6763b1d6c67f.png)

**Comment by andreakarasho** [comment]
fixed

**Comment by zolter** [comment]
Do not forget to send commit :)

**Comment by andreakarasho** [comment]
https://github.com/andreakarasho/ClassicUO/commit/b837b600bd76e6d66318e579e1c103e382f1f3a0
