### ISSUE TITLE
Gargoyle (7.0.18)

### ISSUE THREAD

**Issue by zolter** [ClassicUO/ClassicUO#304]
### 7.0.18 - cant click button

![404koku](https://user-images.githubusercontent.com/1370602/53444509-012e9680-3a17-11e9-8391-fed8e8b89b09.jpg)

### CUO

![404kbrx](https://user-images.githubusercontent.com/1370602/53444550-1d323800-3a17-11e9-8acc-968e3b9c3091.jpg)

![404kd2d](https://user-images.githubusercontent.com/1370602/53444549-1d323800-3a17-11e9-8642-55fd09f67261.png)

**Comment by andreakarasho** [comment]
i think your client.exe has been modded. Can you confirm that?

**Comment by zolter** [comment]
No,
I use default 7.0.18.0 and default sphere 56d
I think support for gargoyles appear in later versions.

**Comment by andreakarasho** [comment]
https://github.com/andreakarasho/ClassicUO/pull/1280
