### ISSUE TITLE
Minimize mode (books & containers)

### ISSUE THREAD

**Issue by zolter** [ClassicUO/ClassicUO#305]
### Classic 7.0.18

![404l0aq](https://user-images.githubusercontent.com/1370602/53444836-dc86ee80-3a17-11e9-9bbb-7c3fb3eb0501.jpg)
![404kzhh](https://user-images.githubusercontent.com/1370602/53444837-dd1f8500-3a17-11e9-93d0-54c7289285f3.jpg)
![404kxxs](https://user-images.githubusercontent.com/1370602/53444839-dd1f8500-3a17-11e9-8029-611892ffce15.jpg)

**Comment by SaschaKP** [comment]
done
