### ISSUE TITLE
Click to spell name bug

### ISSUE THREAD

**Issue by zolter** [ClassicUO/ClassicUO#306]
1. Click "Strength" spell name -> open "Cure" (https://i.imgur.com/YV5giiR.gif)

2. Click  "Lighting" -> open "Fire field" (https://i.imgur.com/3EYWW9M.gif) 

The problem is reproduced with all the "latest" spells on the list.

7.0.18

**Comment by SaschaKP** [comment]
fixed with https://github.com/andreakarasho/ClassicUO/pull/310
