### ISSUE TITLE
Small window on osx

### ISSUE THREAD

**Issue by sharabdin1988** [ClassicUO/ClassicUO#308]
<img width="1437" alt="1" src="https://user-images.githubusercontent.com/38672017/53451413-bf5e1a00-3a2f-11e9-9418-0e1c7c4cab38.png">
Small windows macbook pro 2017 OSX 10.14.3

**Comment by andreakarasho** [comment]
It s the highdpi. I needed a confirm, thanks

**Comment by andreakarasho** [comment]
fixed: https://github.com/andreakarasho/ClassicUO/commit/49472c4826788db568b74d9f5d63b39ff0ce74f6
