### ISSUE TITLE
Assigned hotkeys (F1, F2 etc) are linked to "letters" as well

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#321]
from UOA:
a. on the hotkeys tab assign hotkeys to F1, F2, F3, F4 (example hotkey to hide) 
b. these also will link to various letters (I forget which like F, S etc)

**Comment by oroechimaru** [comment]
Version:
https://github.com/andreakarasho/ClassicUO/releases/tag/alpha2

I verified UOA from ClassicUO does this on two different devices (laptop and desktop) with three keyboards. 

Workaround:
assign the keys to number keys or ctrl+number keys and bypass using function keys.

**Comment by oroechimaru** [comment]
Retested on dev 2019/03/09 build (morning) , same issue.

example in UOA assign hotkey for something (Skill, potion etc) to F5. Then type the letter T which also inherits/functions as F5.

**Comment by andreakarasho** [comment]
do you mean Razor?

**Comment by oroechimaru** [comment]
ya sorry lol i do that alot

**Comment by oroechimaru** [comment]
Using razor and 3/14/2019 dev build and am no longer having this issue. Resolving.
