### ISSUE TITLE
Tracking - is it working? 

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#327]
a. start tracking
b. select "reds"
- the arrows only move to upper right corner of the screen or left, doesn't seem to track pks I have seen

**Comment by jkachhad** [comment]
Are you using ```dev``` or ```master```

**Comment by oroechimaru** [comment]
I'm not sure how to tell this is the version I'm using which is pinned in the UO Discord for Outlands:
https://github.com/andreakarasho/ClassicUO/releases/tag/alpha2

this is the version that most of us are using:
https://github.com/andreakarasho/ClassicUO/releases/download/alpha2/ClassicUO-alpha-2-release.zip

which version can I help test?

**Comment by andreakarasho** [comment]
It should work on dev branch.
I keep open this issue until next release

**Comment by oroechimaru** [comment]
I loaded dev it works pretty decent but the message doesnt stick out in the chat window. can we have the text color changed to a shade of red so it sticks out? gray is easy to miss

**Comment by andreakarasho** [comment]
issue fixed, i ll check that feature request
