### ISSUE TITLE
Remove developer folder references (may be related to crashing)

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#330]
The following directories are often observed when crashing, these appear to be folders of previous CLASSICUO/ORIONUO developers.

Suggestion:
a. create an installer for Classic UO
b. have the installer create any necessary folders and permissions (%USERPROFILE% or the classic uo folder)
c. have the installer prompt the user for their UO game folder (And update the settings file), also detect the "client" file and read the version details (possibly also the server IP or dns address) to create the auto config
d. repeat for UOA app that runs for Classic UO

d. any required GUMP or other files for developers need to be created and added to the CLASSIC UO client
e. any necessary files (screenshots UOA feature) need to be created under %USERPROFILE% or a classic uo folder (subfolder)

Classic UO observed crash of developer's folder (not my username ):
D:\Progetti\ClassicUO\client\src\Game\UI\Gumps\QuestArrowGump.cs:lin

The client, src , game, ui and gumps folders do not exist on our machine's (only developers).

UO Assist - Developer example (Screenshots menu):
c:\users\andre\pictures\razorscreenshots

Again Andre is not a user on my machine.

**Comment by DarkLotus** [comment]
No installer is needed, though as you mention a launcher would be nice for people who prefer a GUI over editing the settings file.

All required files are in the ClassicUO folder, and files created such as settings.json and files from the assistant remain in the same folder as ClassicUO.exe or a subfolder.

The folder names you see in crash reports are just a helpful pointer to the source code file/line number for developers and are meaningless for end users.

ClassicUO works with the original UO files, it does not need any GUMP's or other files created.

**Comment by oroechimaru** [comment]
For the app to take off it really needs a gui interface (with or without an installer to simplify it). Most folks shy away. I helped package it 2 years ago for ORION UO when it was still a Russian based project and it helped get a few dozen more testers that are intimated by the logic. However I think that part is super easy to implement down the road in comparison to all the cool bells and whistles in the client:)

Thanks for the explanation of the crash reports. It was odd to see the references so I thought it had crashed because certain files it was looking for didn't exist. Now it makes more sense. Possibly if a fail/catch could be introduced that reduces the crash out of the app that would be cool. 

Version:
https://github.com/andreakarasho/ClassicUO/releases/tag/alpha2

**Comment by andreakarasho** [comment]
a launcher will be implemented.. soon :D
