### ISSUE TITLE
Slow vendor purchases (bulk purchases of regs etc) 

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#331]
**Describe the bug**
When making a vendor purchase for regs, bolts, arrows etc and you hold down the "plus sign" at the vendor, it goes at a trickling speed (probably increases a few a second). 

Version:
https://github.com/andreakarasho/ClassicUO/releases/tag/alpha2

**To Reproduce**
a. go to vendor
b. buy bolts, regs, etc
c. click the "plus symbol" to purchase larger quantities > wait

**Expected behavior**
Once a few seconds of "holding" the plus sign or minus, the "speed should" increase to an exponential rate. You can see how it will work by launching the standard client (non classicUO) which will make purchases quickly.  (single > a few > dozens per second... it increases in speed)

The CLASSICUO client does a "trickle" speed that is much slower/consistent over time (a few per second always at the same rate)

**Comment by andreakarasho** [comment]
Fixed in dev branch.
