### ISSUE TITLE
UO outlands - "ranger hood" disappears (custom item) upon death or exit but is still equipped. 

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#332]
**Description:**
a. purchase a custom item from the item shop such as a hood
b. equip it...
c. after death or some considerable time or upon logging back in... it will appear on your client that you do not have anything equipped on your head (but it still shows up in the head gear "square" in the paperdoll")
d. if you take off the hood (there still is an icon in the little square in the paperdoll for something being equipped)  > place it in backpack (displays as hood) > and put it back on its back to normal.

One observation, the "hood" looks like a "miniature knight" when you do unequip it to reset the graphic.

https://github.com/andreakarasho/ClassicUO/releases/tag/alpha2

**Comment by oroechimaru** [comment]
A secondary issue may be related:
a. equip a bow or weapon
b. periodically it will show up as both equipped and in your backpack ... its difficult to know "is it truly equipped or in my backpack?"

Workaround:
a. try to equip/unequip it again and its back to normal.

Possibly this could be a separate issue from UOA (auto equip/disarm) however I have seen it work when UOA is not functioning for auto/equip disarm.

**Comment by andreakarasho** [comment]
This bug should be fixed in dev branch.

**Comment by oroechimaru** [comment]
confirmed fixed
