### ISSUE TITLE
No Description on the Paperdoll "boxes"

### ISSUE THREAD

**Issue by aclark13** [ClassicUO/ClassicUO#335]
**Describe the bug**
Cannot click items in the small boxes to get the description

**Screenshots**

![untitled](https://user-images.githubusercontent.com/38568913/53913187-59b9f100-4020-11e9-9e61-ecd62e5de49f.png)

**Comment by aclark13** [comment]
To expand, it seems to actually double the description in the main window for whatever items are linked to the small boxes.
![image](https://user-images.githubusercontent.com/38568913/53913319-b1f0f300-4020-11e9-91f1-fa2b23e2d1d4.png)

**Comment by andreakarasho** [comment]
added
