### ISSUE TITLE
Foul Water Death animation

### ISSUE THREAD

**Issue by natryl** [ClassicUO/ClassicUO#336]
**Describe the bug**
Foul Water Death animation doesn't finish. 

https://i.imgur.com/4wPXMY5.png

https://i.imgur.com/ASVwwJd.png

**Comment by andreakarasho** [comment]
I think i know why.
Basically while it is dying the mobile animation starts, then server delete the mobile and add the corpse (it's a different game object), so animation doesnt find the parent game object and runs in loop

**Comment by kamronbatman** [comment]
I would assume it should loop only if the server tells it to loop?  I don't remember the animation having a link to new (or old) object for sequence referencing.

**Comment by andreakarasho** [comment]
fixed in dev. 
Actually the problem was the corpse.def file that i  disabled to fix animations
