### ISSUE TITLE
Gumps while off screen 

### ISSUE THREAD

**Issue by natryl** [ClassicUO/ClassicUO#338]
**Describe the bug**
When a window such as Journal is outside of the monitor resolution, clicking it again form the button don't bring it back on visible screen area.
I moved CUO settings from my computer with dispaly res 1920x1080 to other computer with 1600x900 and journal gump was outside the screen.
I think those buttons should act as switches: one click open gump, next click close it, on next the program should check if the window is visible on screen and if not open it on default position.

**To Reproduce**
1. Launch cuo and open a gump such as journal
2. now shrink down the client so the journal is no longer in view
3. Use the hotkeys to open and close the journal and it continues to remain out of view
4. To get the journal back you need to re expand cuo so the journal is visible or delete the gumps.bin

**Additional context**
reported by TyrAntilles in Outlands discord,

**Comment by andreakarasho** [comment]
fixed in dev
