### ISSUE TITLE
Dev and Master: sound remains playing when game is not in focus/minimized

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#339]
This occurs with or without "reproduce music when classic uo is not focused" being checked. Thanks!

windows 10 x64

**Comment by andreakarasho** [comment]
Not implemented yet, you are right :D

**Comment by andreakarasho** [comment]
added in dev

**Comment by oroechimaru** [comment]
I am still having this issue @andreakarasho I rebuilt / repulled dev 3/9/2019 9am central.

**Comment by andreakarasho** [comment]
I ve to merge anomatoons2 with dev branch

**Comment by oroechimaru** [comment]
oh oj!!
