### ISSUE TITLE
How to keep gumps (backpack) open on log off/back on? Is there a lock?

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#340]
dev build 3/5/19

**Comment by andreakarasho** [comment]
Logout with backpack on.
When you will relogin, cuo will try to open it

**Comment by f1uffy0ne** [comment]
Just checked it on a newly compiled version of CUO -- it does save backpack's position correctly, but doesn't open it upon log in.

**Comment by andreakarasho** [comment]
Are you running razor with cuo?
Probably the action queue cuts off the backpack open action.
