### ISSUE TITLE
unable to pick spellshielding rune up off corpse in dev 3/9/2019 build

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#345]
I killed a necromancer in newb dungeon.
Afterwards I could loot everything but the spellshielding rune (purle inscription item). I relaunched classicuo, same issue (dev 3/9/2019 build).

I then launched standard uo outlands client and was able to pick it up and loot it .

**Comment by andreakarasho** [comment]
I need:
- item graphic
- mob graphic

You can take them with the ingame command -info

**Comment by oroechimaru** [comment]
<img width="494" alt="2019-03-09 16_14_41-Cortana" src="https://user-images.githubusercontent.com/26830362/54078019-94bd5e00-4286-11e9-96c8-ca0225a2ee89.png">


it still is stuck while in my bag

**Comment by oroechimaru** [comment]
Bulk bolts also have this issue . i was able to double click them and "unbulk them" but not pick up the graphic and move them.

utilizing morning 3/10/19 dev build 

<img width="430" alt="bulk bolts" src="https://user-images.githubusercontent.com/26830362/54089786-c42da280-433a-11e9-96e8-6adf5d66d7bd.png">

**Comment by andreakarasho** [comment]
news?

**Comment by oroechimaru** [comment]
fixed for both. nice job! (alpha 3)
