### ISSUE TITLE
Can’t use home surveying tool

### ISSUE THREAD

**Issue by kevinchow9527** [ClassicUO/ClassicUO#347]
Can’t use home surveying tool

**Comment by kevinchow9527** [comment]
outlands shard

**Comment by andreakarasho** [comment]
item graphic please

**Comment by oroechimaru** [comment]
in game command type:
-info

a. then select the item that is having issues
b. I used greenshot to snag the details

**Comment by andreakarasho** [comment]
if it's a tool like placementtool it doesnt work. News?

**Comment by andreakarasho** [comment]
No feedback. I think it works
