### ISSUE TITLE
Pulled bars close when out of range

### ISSUE THREAD

**Issue by natryl** [ClassicUO/ClassicUO#348]
Pulled bars currently close when out of range or when mobs make themselves disappear briefly. Original client only closes pulled bars when the mob dies.

**Comment by andreakarasho** [comment]
added in dev branch

**Comment by BravoSierraUO** [comment]
this is not fixed - either i leave all the bars open for mobs that are dead - or i loose my pet bars every time they walk off the screen - pets are special like group members

**Comment by BravoSierraUO** [comment]
under the current behavior i set it to mobile is dead (see screenshot)
I still loose pet bars when i tell them to all stay and walk off the screen
![image](https://user-images.githubusercontent.com/49131722/55442530-aa1b6480-5574-11e9-8d71-19e47b8671f3.png)

**Comment by BravoSierraUO** [comment]
![image](https://user-images.githubusercontent.com/49131722/55442591-e3ec6b00-5574-11e9-8bed-7deacbd87b38.png)

**Comment by BravoSierraUO** [comment]
This gives the pet behavior i want but not the moster
![image](https://user-images.githubusercontent.com/49131722/55442701-61b07680-5575-11e9-92f5-dc91931a1efa.png)

**Comment by BravoSierraUO** [comment]
This will close the monster if he dies - also closes my pet bars if i walk away - need a hybrid code for pets
![image](https://user-images.githubusercontent.com/49131722/55442807-cd92df00-5575-11e9-99d7-f05faa722ff9.png)

**Comment by oroechimaru** [comment]
Last i checked it also closed party members. Possibly allow us to only drop monsters that are dead as an option.

**Comment by andreakarasho** [comment]
Fixed i. Dev
