### ISSUE TITLE
grass tile shows up as "no draw" (part of map in our house build) 

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#352]
alpha 3... 

<img width="373" alt="2019-03-13 21_00_00-Start" src="https://user-images.githubusercontent.com/26830362/54326080-38827300-45d3-11e9-841e-0d676c4393a1.png">

**Comment by oroechimaru** [comment]
different house similar issue may not be the same thing lol

<img width="473" alt="2019-03-13 21_46_49-People bar flyout" src="https://user-images.githubusercontent.com/26830362/54328278-4dfb9b00-45db-11e9-90be-ef90056046cc.png">

**Comment by andreakarasho** [comment]
Fixed in dev
