### ISSUE TITLE
fire elemental displays "flat" dev and master

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#353]
dev build: 3/14/19
<img width="360" alt="2019-03-15 15_39_20-Start" src="https://user-images.githubusercontent.com/26830362/54461006-44884500-4739-11e9-8c44-fd1c27d6278a.png">

**Comment by andreakarasho** [comment]
the issue is known.
I know the problem, but i don't know where i can take the value to set a mobile (monster) with partial hue or not

**Comment by oroechimaru** [comment]
would water elementals be similar? i think they look more detailed to me (water spirits too)

earth elementals also look normal.

bone skeletons are a bit muddy/distorted.

**Comment by andreakarasho** [comment]
fixed
