### ISSUE TITLE
Should XNA be converted to something supported?

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#355]
XNA is dead I think as of 2010, is this going to cause an issue down the road?  Possibly monogame ? 
https://www.microsoft.com/en-us/download/details.aspx?id=20914

https://www.lifehacker.com.au/2013/02/xna-is-dead-3-alternatives-that-let-you-use-your-c-and-net-skills/

monogame:
http://community.monogame.net/t/moving-from-xna-to-monogame/8312

http://community.monogame.net/t/why-microsoft-doesnt-promote-monogame/10889

https://www.gamasutra.com/view/feature/192209/from_xna_to_monogame.php?page=3

ps I didnt mean this to be a "bug" just a feature/suggestion sorry! please reclassify

**Comment by andreakarasho** [comment]
ClassicUO adopts FNA
https://fna-xna.github.io/
