### ISSUE TITLE
Max zoom

### ISSUE THREAD

**Issue by Belialzao** [ClassicUO/ClassicUO#357]
Would be interesting to be able to zoom-in to 0.5 scale (200%)
At the moment, the max is 0.7 scale (160% zoom) and it makes the stretched pixels look weird when the user is trying to get a clearer/better image.

Also, for the zoom-out, I suggest it to be capped the same way, at 2.0 or 2.5, it's at 2.3 atm.
(not as important as the zoom-in, because zooming out will get rid of some pixels either way)
![zoom](https://user-images.githubusercontent.com/42892655/54479757-1a995600-47ff-11e9-94ae-a1a5f205974f.png)

**Comment by zolter** [comment]
Already a very long time done 0.5 - 2.5 ;)

**Comment by zolter** [comment]
![40rMO8b](https://user-images.githubusercontent.com/1370602/54479857-42ea7a00-482a-11e9-998e-918f9b4062ce.jpg)

![3e185-clip-675kb](https://user-images.githubusercontent.com/1370602/54479858-42ea7a00-482a-11e9-9792-3133a8ca70c5.jpg)

**Comment by Belialzao** [comment]
OOPS!! MY BAD! shortcut was pointing to alpha 3! damn... you guys are fast! haha
