### ISSUE TITLE
Robe Layer

### ISSUE THREAD

**Issue by Belialzao** [ClassicUO/ClassicUO#362]
2 little things I noticed about the paperdoll:

-Wearing a robe should remove from paperdoll view: arms and chest (but not tunic/doublet)

-Robe layer should be under Hair layer, atm long hairstyles are going under the robe.

**Comment by zolter** [comment]
I think this behavior should depend on the client version.

**Comment by zolter** [comment]
![40PwkWn](https://user-images.githubusercontent.com/1370602/55535158-04284100-56bf-11e9-8710-cba4750772a2.jpg)
![40Pwmow](https://user-images.githubusercontent.com/1370602/55535159-04284100-56bf-11e9-8646-19a861eb74e2.jpg)
![40PwnX5](https://user-images.githubusercontent.com/1370602/55535160-04284100-56bf-11e9-88b2-47740e2b94aa.jpg)
![40Pwqvs](https://user-images.githubusercontent.com/1370602/55535161-04c0d780-56bf-11e9-8e25-bb03bd29aafd.jpg)

![40PwZkf](https://user-images.githubusercontent.com/1370602/55535162-04c0d780-56bf-11e9-90de-3c821cfc8894.jpg)

**Comment by SaschaKP** [comment]
probably fixed with https://github.com/andreakarasho/ClassicUO/commit/c21c2e39e7ba19cf31bf68e728bd58a7406e76da and https://github.com/andreakarasho/ClassicUO/commit/541f7ccb3aedb4f6f770bdc54154efb72c3c84b1

eventually recomment with issue and I'll reopen it
