### ISSUE TITLE
Too many popups on screen when looting or incoming pks

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#365]
I am not sure if this is a bug or overlap with uo razor features. I previously reported ctrl+shift would benefit from blue/red/gray corpse identification and wanted to put this in a separate thread. 

a. this occurs the most when in a party with 1 or more tamer guildmate

b. also occurs if too many people rush on the screen while spawn dies (monster) or pks rush

c. also makes it worse with 1-5 pets summoned

d. I am also a bard, sometimes the bard timers also spam/linger

e. if someone talks this too gets mixed in and difficult to read

f. if you kill a pet, have pets summoned, in a group with tamers, do bard skills (peace/disco) on monsters and one or monsters dies > you will have 0% chance to find the monster corpse since it will be hidden by all the text 

<img width="382" alt="2019-03-19 22_33_30-Start" src="https://user-images.githubusercontent.com/26830362/54794021-69862780-4c13-11e9-9a57-eefe503012c6.png">

<img width="489" alt="2019-03-20 22_37_39-Start" src="https://user-images.githubusercontent.com/26830362/54794022-69862780-4c13-11e9-8d05-c7bd9d6ff693.png">

**Comment by oroechimaru** [comment]
happened a few times after typing "all kill" . I do have UO chat delay to 200

this has been an issue since alpha 2 (not new):
a. tested tonight 3/21/2019 evening build same

<img width="371" alt="2019-03-21 21_07_11-Start" src="https://user-images.githubusercontent.com/26830362/54796444-46ad4080-4c1e-11e9-8525-99db39eec3d4.png">
<img width="343" alt="2019-03-21 20_55_53-Start" src="https://user-images.githubusercontent.com/26830362/54796445-46ad4080-4c1e-11e9-8c76-9e9dbae9da86.png">

**Comment by oroechimaru** [comment]
<img width="685" alt="2019-03-21 21_16_35-Start" src="https://user-images.githubusercontent.com/26830362/54797931-3b5d1380-4c24-11e9-9add-be2204d9b422.png">

**Comment by andreakarasho** [comment]
Disable razor incoming messages

**Comment by oroechimaru** [comment]
I played with checkboxes in razor and classicUO and keep having the issues below. Is there a specific checkbox maybe I'm missing in razor? If so any tips? Thanks!

<img width="323" alt="2019-03-24 15_02_48-Start" src="https://user-images.githubusercontent.com/26830362/54885071-61fa9480-4e46-11e9-91a3-3ee770a3b2e5.png">
