### ISSUE TITLE
Unable to close some monster windows that stick together

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#366]
I try not to purposely make the health bars touch as a habbit. Sometimes when I drag them too close and as intended they stick. Once the monsters are dead, sometimes I can't right click and close the health gump windows unless I relog.

Thanks!
<img width="521" alt="2019-03-24 16_05_05-Start" src="https://user-images.githubusercontent.com/26830362/54885847-cc173780-4e4e-11e9-908e-a3b61014ed21.png">

**Comment by zolter** [comment]
Fixed
