### ISSUE TITLE
Journal size reset to default after logging in

### ISSUE THREAD

**Issue by f1uffy0ne** [ClassicUO/ClassicUO#367]
**Describe the bug**
CUO doesn't save/restore journal's size upon logging out/in.

**To Reproduce**
1. Open journal and resize it to your desired size;
2. Log out and close CUO client;
3. Open CUO client and log back in;
4. Journal's position saved/restored properly, but not its size.

**Expected behavior**
Journal's size also should be saved/restored.

**Additional context**
Latest dev build:
commit 206ccde43931eacd59b2170a7e0a3d40a8897219 (HEAD -> dev, origin/dev)
Date:   Sun Mar 24 17:26:05 2019 +0100

**Comment by zolter** [comment]
I can not reproduce your problem :( 
Can you try again?

**Comment by andreakarasho** [comment]
added!
