### ISSUE TITLE
Hotkey for zoom feature

### ISSUE THREAD

**Issue by natryl** [ClassicUO/ClassicUO#371]
Current hotkey is mouse scroll up and down for zoom feature. This prevents that from being used by the assistant. mouse scroll up and down is a common hotkey for targeting.

Suggestion is to change the zoom hotkey to ctrl+mouse scroll up and ctrl+mouse scroll down

**Comment by Belialzao** [comment]
+1

**Comment by andreakarasho** [comment]
Added!
