### ISSUE TITLE
Windows Scaling does not Scale the UO mouse cursor

### ISSUE THREAD

**Issue by natryl** [ClassicUO/ClassicUO#375]
In windows 10 using a high resolution monitor with windows scaling, CUO does not scale the UO mouse cursor.

See this screenshot: https://i.imgur.com/6KZVUH1.jpg

Tested on a 4k screen with 200% scaling in the display settings

**Comment by f1uffy0ne** [comment]
I'm experiencing the same issue and sometimes it's really hard to see the cursor.

**Comment by oroechimaru** [comment]
did some googling, not sure if useful


https://stackoverflow.com/questions/26073635/windows-forms-dpi-scaling


https://stackoverflow.com/questions/9373260/detect-windows-font-size-100-125-and-150

https://developer.rhino3d.com/guides/rhinocommon/supporting-high-dpi-displays/


http://crsouza.com/2015/04/13/how-to-fix-blurry-windows-forms-windows-in-high-dpi-settings/

**Comment by oroechimaru** [comment]
Are you guys having this issue? I do not at 125% on a 2k monitor.

**Comment by andreakarasho** [comment]
option -> video -> uncheck run mouse in a separate thread should fix
