### ISSUE TITLE
Paperdoll backpack wont open

### ISSUE THREAD

**Issue by BravoSierraUO** [ClassicUO/ClassicUO#384]
**Describe the bug**
Unable to open backpack from paperdoll after updating to alpha 6

**To Reproduce**
1. login
2. click paperdoll on map bar
3. attempt to open backpack

**Expected behavior**
I expect my inventory screen to open
-work around is to use the map bar inventory button that works
-work around is to set hotkey to open- oops found another

**Comment by zolter** [comment]
fixed
