### ISSUE TITLE
Macro screen broken

### ISSUE THREAD

**Issue by BravoSierraUO** [ClassicUO/ClassicUO#385]
**Describe the bug**

**To Reproduce**
1. Paperdoll - options - macros
2. Click on 'new macro' set name
3. Click on hotkey to set key
4. unable to use drop down to select macro functions

**Expected behavior**
I wanted to set a macro for "open inventory"

**Screenshots**
SS included
![image](https://user-images.githubusercontent.com/49131722/55296032-b7e8b280-53d9-11e9-9d50-69ff0dad3a92.png)

**Comment by zolter** [comment]
fixed
