### ISSUE TITLE
Scaling of UI

### ISSUE THREAD

**Issue by natryl** [ClassicUO/ClassicUO#387]
Feature Request:
Many modern mmo games allow you to scale the UI so that they are easily viewed no matter the resolution or the eyesight of the user.

For UO this would allow the user to set a scale that handles many of the UI features such as gumps, inventory, items, etc. Everything not in the view window.

I am envisioning some sort of slider that as you drag it to the right those parts of the UI scale larger. 

Current workaround is to use Windows scaling option in display settings but this not ideal as many users like to use a certain scale for windows and changing each time for 1 game is a poor user experience

**Comment by tsul** [comment]
One possible hang-up here is that many of UO’s UI elements are tiny bitmaps and aren’t going to scale well without some kind of filtering

**Comment by andreakarasho** [comment]
As tsul said, this behavior is not possible with the current texture format, because they are images with a fixed size.
The scaling result will be an horrible unredeable stretched image
