### ISSUE TITLE
Unable to target this sconce

### ISSUE THREAD

**Issue by BravoSierraUO** [ClassicUO/ClassicUO#392]
**Describe the bug**
I had a sconce in my pouch - i put it down on the floor then locked it - now i am unable to move it - I can lock down or release but not pick it up in classic

**To Reproduce**
1. see image

**Expected behavior**
I expect to move it

**Screenshots**
Included
![released](https://user-images.githubusercontent.com/49131722/55424419-dbc90700-5545-11e9-88eb-195659f5c4e9.png)

**Comment by oroechimaru** [comment]
type: -info 
then target the item
-post screenshot

Lol I realized I was standing next to it:

![image](https://user-images.githubusercontent.com/26830362/55451998-13ae6980-559b-11e9-85e3-ae4cdb8257e2.png)

![image](https://user-images.githubusercontent.com/26830362/55452004-1ad57780-559b-11e9-9305-e529cfe7a84c.png)

**Comment by andreakarasho** [comment]
should be fixed in dev, give me a feedback please

**Comment by BravoSierraUO** [comment]
![image](https://user-images.githubusercontent.com/49131722/56658814-334c2580-6661-11e9-91f9-93e2dc6f1b9a.png)
was able to target and release and move - but the client left the artifact behind.  looked like i had duped it 9 times but my friend on the "regular client" was only seeing 1

**Comment by andreakarasho** [comment]
fixed
