### ISSUE TITLE
transfer pet wrong target in chat (transfer pet works)

### ISSUE THREAD

**Issue by BravoSierraUO** [ClassicUO/ClassicUO#393]
I gave this bird to OREO and it said i gave it to myself
![image](https://user-images.githubusercontent.com/49131722/55443741-6d9e3780-5579-11e9-846c-d495c3d8468c.png)

**Comment by BravoSierraUO** [comment]
> A clear and concise description of what the bug is.

a

**Comment by zolter** [comment]
Does it work correctly on a classic client?
I think this message from your server.

**Comment by BravoSierraUO** [comment]
Tested on "old client" transfering to "classic" client and message is correct in "old client" message still says transfered pet to yourself in "classic" client - oreo was testing the dev build for inferno when I caught up with him so it was a good test  - screenshot is from my "old client" giving the pet to the "classic client"

![image](https://user-images.githubusercontent.com/49131722/55554004-58272b80-56a7-11e9-8a5d-37e4f9a2ada9.png)

**Comment by oroechimaru** [comment]
The screenshot from bravo is similar to what I had when I transferred the pet back to Bravo. It said I was transferring the pet to oRoechimaru Roe (myself). Old client did not have this issue.

**Comment by andreakarasho** [comment]
News? I close it untile i'll not receive a feedback
