### ISSUE TITLE
Mobs clothes showing at corner of their loot boxes 

### ISSUE THREAD

**Issue by ichiokada** [ClassicUO/ClassicUO#397]
**Describe the bug**
Mobs clothes showing at corner of their loot boxes (clickable and says item too far away)

**Screenshots**
https://i.imgur.com/ON8xnBp.jpg

**Desktop (please complete the following information):**
 - OS: windows10
- UO outlands shard
- alpha 7

**Comment by BravoSierraUO** [comment]
i would like to see this *fixed* but i get the same issue with UOSteam - so this is an Outlands issue not a Classic issue

**Comment by owyn-outlands** [comment]
This is indeed an Outlands issue.

**Comment by andreakarasho** [comment]
ok, btw if you will fix it, my patch will not interfere with it
