### ISSUE TITLE
master sound lower than usual

### ISSUE THREAD

**Issue by ichiokada** [ClassicUO/ClassicUO#398]
**Describe the bug**
comparing to old client, the sound of classicUO is at least 40% quieter when maxed out

**Desktop (please complete the following information):**
 - win10
 -Outlands
 - alpha 7

**Comment by oroechimaru** [comment]
I believe this was introduced in alpha 4 or alpha 5 after the fna fixes (odd audio and extreme loudness differences)... so its less extreme but now overall quieter. my guess is a future fna build will resolve it.

**Comment by andreakarasho** [comment]
feedback?

**Comment by ichiokada** [comment]
Still much lower than original client .  When my alpha crashes, I go back to login using razor old client, the music is super loud in comparison

**Comment by ichiokada** [comment]
I m using newest dev prev for cuo and razor the sound seems perfect now! Thanks
