### ISSUE TITLE
Enhancement request: allow a notoriety popup when accidentally looting a blue corpse

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#402]
wishlist item... if you try to loot a blue corpse (such as you dont have kill rights to it but thought you did), have the criminal action yes/no prompt come up as a warning (or make this an optional feature).

**Comment by oroechimaru** [comment]
In this week's dev I now at least get a system text message (lower left corner) ... no popup yet for looting blue corpses by mistake or open a treasure chest that i do not have rights to

**Comment by ichiokada** [comment]
Can you guys do the same warning for bandaging grey? (Sometimes lag causes bandage self macro to break - target stuck.... And will accidentally target and heal a monster without warning, didn't know I become grey...  ;(

**Comment by oroechimaru** [comment]
another one probably outlands specific: opening someone elses tmap chest makes you gray. i didnt know that.

**Comment by ichiokada** [comment]
i think i saw it in discord chat that its on purpose, so ppl doing tgt in party is fine.. but outsider turns grey to avoid free riders

**Comment by andreakarasho** [comment]
Basically the same of: https://github.com/andreakarasho/ClassicUO/issues/536
