### ISSUE TITLE
Enhancement: modify overlapping message stacking and transparency 

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#406]
Common scenario:
a. party hunting with 2-3 team members and 2 pets and 2 summoned creatures
b. Pet status (summoned time, tamed) may create a popup text bubble
c. if peaced, provoked etc this may create a popup bubble (time left for peacing).
d. your party may chat (2-3 people chatting at the same time)
e. the monster may die creating additional corpse popups

Two key issues occur:
a. you may not find the corpse quickly underneath the text messages
b. you may not be able to read each other's chat messages (they overlap)

Suggestion:
a. give priority "weight" to new/dead corpses over pet information or statuses (peace, disco etc)

b. allow chat / text bubbles if overlapping with other text to "bubble" and go to the sides/corners of your screen. Imagine a "bulls eye" where all the action is on a target, allow the text to move to the next "ring/circle outer loop" so its legible and offset (like a comic book)

c. remove "transparency/dimming" of text/talking from losing focus to other types of messages (often the underneath messages start fading out and are less readable)

d. instead of overlapping important messages allow them to "offset" 
- new corpses stay where their text should and clear (no dimming)
- party chat stays clear (no dimming) but may be offset
- pet statuses, skill status etc may dim/transparent and have lowest priority

e. limit overlapping of messages and transparency of text . Currently 5-10 messages may overlap each other and become hard to read. IT also makes it difficult to react, loot or see corpses or what is going on due to the text.

**Comment by oroechimaru** [comment]
<img width="567" alt="2019-04-06 11_03_23-Start" src="https://user-images.githubusercontent.com/26830362/55672015-b137c080-585b-11e9-8899-65f50685478c.png">
<img width="609" alt="2019-04-06 11_02_24-Start" src="https://user-images.githubusercontent.com/26830362/55672017-b6950b00-585b-11e9-8c9a-817065ce38fa.png">
<img width="753" alt="2019-04-03 20_58_17-Clipboard" src="https://user-images.githubusercontent.com/26830362/55672018-bf85dc80-585b-11e9-829b-d5b727ebefea.png">
<img width="559" alt="2019-03-29 21_40_21-Jump List for Visual Studio 2017" src="https://user-images.githubusercontent.com/26830362/55672022-cd3b6200-585b-11e9-94ab-eff938f2d943.png">

**Comment by oroechimaru** [comment]
Anyone able to help test? It seems better but I havn't done large hunts since April with people. There is alot less noise now between updated razor and cuo, and newer razor filter features. A journal filter system would also help us track chats between guild/party members which is a separate community request.

**Comment by andreakarasho** [comment]
mostly features you asked have been added to dev
