### ISSUE TITLE
Draw aura under characters (like in Orion)

### ISSUE THREAD

**Issue by f1uffy0ne** [ClassicUO/ClassicUO#409]
This is a very convenient feature for PvP and for PvM as well. Here are some screen shots that show how it works:

![Capture_1](https://user-images.githubusercontent.com/48736613/55660694-8f3b3100-57bc-11e9-95ec-0096cae1c0b2.PNG)
**Settings for this feature.**

![Capture_2](https://user-images.githubusercontent.com/48736613/55660696-94987b80-57bc-11e9-82f8-d9d3d86c964a.PNG)
**How it basically works.**

![Capture_3](https://user-images.githubusercontent.com/48736613/55660698-98c49900-57bc-11e9-9bfb-a112eee6e7d2.PNG)
**One more example where different mobs are shown.**

What it basically does is the next: it renders a rounded shape with gradient colored in the same color as mobile's name. When you click on a player/npc/any other mobile, you can see its name as blue/green/orange/red/gray. This feature allows you to quickly understand mobile notoriety without clicking on it, hovering your cursor over or executing macros like "Show all names". This is super helpful when you have a bunch of moving mobiles (players, creatures) on a screen to quickly understand "who is who" in terms of their notoriety.

P.S. This is the only feature that holds me from switching from Orion to ClassicUO at the moment.

**Comment by andreakarasho** [comment]
![image](https://user-images.githubusercontent.com/20810422/56461432-2f937700-63b3-11e9-8527-ae5643e360ac.png)
added in dev
