### ISSUE TITLE
Gate goes behind player

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#410]
When a gate exists in the world, and you stand on the tile NW of the moongate, you will stand on top of it.

![image](https://cdn.discordapp.com/attachments/531214935804608515/563884359384301579/unknown.png)

**To Reproduce**
1. Cast Gate
2. Stand on the tile NW of it

**Expected behavior**
When you stand on that tile, you are behind it, like this:

![image](https://i.imgur.com/TKCyXPu.png)

**Comment by andreakarasho** [comment]
https://github.com/andreakarasho/ClassicUO/issues/217

**Comment by SaschaKP** [comment]
fixed with https://github.com/andreakarasho/ClassicUO/commit/79ba69a4ba573ec5addb6476e854435cc208c73b and relative sub patches later on

![image](https://user-images.githubusercontent.com/15030741/60727150-82ee7d80-9f3d-11e9-90a8-2bf0b22bbace.png)
