### ISSUE TITLE
Gump coloring

### ISSUE THREAD

**Issue by Belialzao** [ClassicUO/ClassicUO#412]
In normal client, the color 000008 is not colored on any gump.

**Expected behavior**
Do not dye the portion of gumps where the color is 000008

**Client version:**
7.0.15.1 (Outlands)

![000008](https://user-images.githubusercontent.com/42892655/55673450-a5a9c100-587e-11e9-9cb1-24e6246ff6ca.png)

**Comment by SaschaKP** [comment]
that should be transparent, in fact

**Comment by Belialzao** [comment]
transparent is only 000000

000008 is used when something is supposed to be 'true black' and not get colored.
it's the color used around helms and other wearables to 'hide' the layer behind it.

if something is 080000 or 000800 it will be colored, many items are, by mistake, since the game converts everything to 16bit bmp RGB555 and most of the original artists didn't have this in mind.

anything less than 8 in RGB will automatically become 000000 when you import to  the game,
thats why there are so many bad looking missing pixels, specially when there is a dark shade of green.

i've edited 420+ gumps since February
I made a macro to select the color 000008 in photoshop, thats how much i use it :P

**Comment by SaschaKP** [comment]
fixed with https://github.com/andreakarasho/ClassicUO/commit/c21c2e39e7ba19cf31bf68e728bd58a7406e76da
