### ISSUE TITLE
Bone dragon bones shown when CTRL+SHIFT

### ISSUE THREAD

**Issue by TyrAntilles** [ClassicUO/ClassicUO#413]
Bone dragon special attack - label of each bone can be shown in CUO when pressing CTRL+SHIFT. I am almost sure they shouldn't be displayed. 

Short clip here: [https://1drv.ms/v/s!AqtI3rSJQnG_kns3Kp8sBSMn3CUa](https://1drv.ms/v/s!AqtI3rSJQnG_kns3Kp8sBSMn3CUa)

**Desktop (please complete the following information):**
 - OS: [win10x64]
 - Version [CUO v.0.0.1.8 Alpha dev edition]

**Comment by oroechimaru** [comment]
can confirm, just hard to get screenshot. It can make it difficult to battle.

**Comment by Belialzao** [comment]
Thats a normal behavior in the normal client

**Comment by TyrAntilles** [comment]
Ah, didn't know that. If that's the case this report can be removed.
