### ISSUE TITLE
Closing with mouse UO Positioning System map crashes CUO

### ISSUE THREAD

**Issue by TyrAntilles** [ClassicUO/ClassicUO#414]
Closing with mouse UO Positioning System map crashes CUO. If I open and close it from keyboard shortcut it works well.

Here is a clip that illustrates the problem: [https://1drv.ms/v/s!AqtI3rSJQnG_knz4VJmkQ-utnc7q](https://1drv.ms/v/s!AqtI3rSJQnG_knz4VJmkQ-utnc7q)

[Win10x64, AMD Radeon R7 370, CUO v.0.0.1.8 Alpha dev edition]

**Comment by rhemz** [comment]
I am able to reproduce this consistently.  However, it only manifests on the second close.

Steps to reproduce:

1. Open UO Map System in Razor Assistant
2. Close UO Positoining System by clicking the X in the title bar
3. Open UO Map System in Razor Assistant
4. Close UO Positoining System by clicking the X in the title bar - crashes consistently

**Comment by oroechimaru** [comment]
It may be a razor bug. I used the map feature last night to take a screenshot... it then froze and crashed on me but didnt create an error log.

**Comment by andreakarasho** [comment]
fixed in alpha 8
