### ISSUE TITLE
Command line argument for settings.json

### ISSUE THREAD

**Issue by zolter** [ClassicUO/ClassicUO#416]
![40SSA0O](https://user-images.githubusercontent.com/1370602/55673734-6dbd7080-58b4-11e9-8e20-89c89ad3d6d9.png)

**Comment by andreakarasho** [comment]
already exists:
https://github.com/andreakarasho/ClassicUO/blob/8e8c1e00ecbd64852b244a754f00540b46a06818/src/Engine.cs#L394

**Comment by zolter** [comment]
Need add this info to readme

**Comment by zolter** [comment]
![40T3irw](https://user-images.githubusercontent.com/1370602/55679014-37134480-590c-11e9-9fc5-8d5a5ee14fbb.jpg)

I'll check it out, I think Mel described the correct behavior.
We need to support two client startup options.

**Comment by zolter** [comment]
**Now we can use:** 

`path/to/ClassicUO.exe -settings "player1.json"`

This will allow you to create separate configuration files for various servers and players.
I left full compatibility with the current implementation and updated arguments list.

argn **settings** ignores all other argns

Updating existing parameters through arguments - i add in the future.
