### ISSUE TITLE
UO Forever - Can't log in :( 

### ISSUE THREAD

**Issue by proz9c** [ClassicUO/ClassicUO#417]
Hi guys,

I tried to set up the file this evening but it just doesnt work so i assume in doing something wrong.

I followed the guide on this page.

I filled these collums (ofcourse acc name & pw aswel)

  "ip": "login.uoforever.com",
  "port": 2599,
  "ultimaonlinedirectory": "D:\Games\Ultima Online Classic",
  "clientversion": "7.0.45.0",
  "lastcharactername": "",
  "lastservernum": 1,
  "login_fps": 60,
  "debug": false,
  "profiler": true,
  "preload_maps": false,
  "saveaccount": false,
  "autologin": false,
  "reconnect": false,
  "reconnect_time": 0,
  "login_music": true,
  "login_music_volume": 2,
  "shard_type": 0,
  "fixed_time_step": true,
  "plugins": [
    ".\\Assistant\\Razor.dll"
  ]
}

**Comment by andreakarasho** [comment]
double black slashes at:
```"ultimaonlinedirectory": "D:\\Games\\Ultima Online Classic",```

**Comment by proz9c** [comment]
Hey Andrea, 

Thanks for replying! 

Unfortunately it aint helping.

the crashlog says following: 

ClassicUO [dev] - v0.0.1.108
OS: Win32NT x64

Exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: z. Path 'username', line 2, position 15.
   ved Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   ved Newtonsoft.Json.JsonTextReader.ReadAsString()
   ved Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   ved Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   ved Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   ved Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   ved ClassicUO.Configuration.ConfigurationResolver.Load[T](String file, JsonSerializerSettings jsonsettings) i c:\projects\classicuo\src\Configuration\ConfigurationResolver.cs:linje 42
   ved ClassicUO.Engine..ctor(Settings settings) i c:\projects\classicuo\src\Engine.cs:linje 106
   ved ClassicUO.Engine.Main(String[] args) i c:\projects\classicuo\src\Engine.cs:linje 295
ClassicUO [dev] - v0.0.1.108
OS: Win32NT x64

Exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: z. Path 'username', line 2, position 15.
   ved Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   ved Newtonsoft.Json.JsonTextReader.ReadAsString()
   ved Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   ved Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   ved Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   ved Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   ved Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   ved ClassicUO.Configuration.ConfigurationResolver.Load[T](String file, JsonSerializerSettings jsonsettings) i c:\projects\classicuo\src\Configuration\ConfigurationResolver.cs:linje 42
   ved ClassicUO.Engine..ctor(Settings settings) i c:\projects\classicuo\src\Engine.cs:linje 106
   ved ClassicUO.Engine.Main(String[] args) i c:\projects\classicuo\src\Engine.cs:linje 295

I dont know if that helps :/

**Comment by zolter** [comment]
![40SVKbi](https://user-images.githubusercontent.com/1370602/55674714-0954de00-58c1-11e9-96c2-3b6b3abb5268.png)

Your char name?
Show your settings.json now

**Comment by andreakarasho** [comment]
you are missign the initial json part

**Comment by proz9c** [comment]
> ![40SVKbi](https://user-images.githubusercontent.com/1370602/55674714-0954de00-58c1-11e9-96c2-3b6b3abb5268.png)
> 
> Your char name?
> Show your settings.json now

Hey these are my settings: 

  "ip": "login.uoforever.com",
  "port": 2599,
  "ultimaonlinedirectory": "D:\\Games\\Ultima Online Classic",
  "clientversion": "7.0.45.0",
  "lastcharactername": "DickRyder",
  "lastservernum": 1,
  "login_fps": 60,
  "debug": false,
  "profiler": true,
  "preload_maps": false,
  "saveaccount": false,
  "autologin": false,
  "reconnect": false,
  "reconnect_time": 0,
  "login_music": true,
  "login_music_volume": 2,
  "shard_type": 0,
  "fixed_time_step": true,
  "plugins": [
    ".\\Assistant\\Razor.dll"

the "Username" is my account name is that correct? If so its ziticDK - I also tried with char names.

**Comment by proz9c** [comment]
Also the link is: 

  "ultimaonlinedirectory": "D:\\Games\\Ultima Online Classic"

i dont know why it showed without double backslash!

**Comment by zolter** [comment]
you skip
may you not have permission to edit the file.

```
{
  "username": "",
  "password": "",

```
