### ISSUE TITLE
Incorrect item name position in paperdoll (sockets)

### ISSUE THREAD

**Issue by zolter** [ClassicUO/ClassicUO#419]
![40SUPIN](https://user-images.githubusercontent.com/1370602/55674497-423f8380-58be-11e9-9f7b-1773151beb86.jpg)

![40SV1ET](https://user-images.githubusercontent.com/1370602/55674503-597e7100-58be-11e9-8b0d-3080e114c04f.jpg)

Outlands

**Comment by oroechimaru** [comment]
Can you post -info if item specific for those items? (then screenshot) thanks!
