### ISSUE TITLE
Sitting In Chairs

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#426]
Players and NPCs, that can sit in chairs, do not sit down. They only stand when over the chair.

Windows 10
UO Client 7.0.15.1

**Comment by andreakarasho** [comment]
done

**Comment by BlackTeaOutlands** [comment]
NPCs still stand on certain chairs (wooden benches). Sitting down is also still bugged for the player, the lower body doesn't seem to sit down. Also the cloak is layered wrong when facing north.

https://imgur.com/h4DM8Ch

![image](https://user-images.githubusercontent.com/39037141/61462724-6b6ab800-a973-11e9-9984-51da695a6656.png)
