### ISSUE TITLE
Radar Map Colors Are Default Colors

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#427]
The in-game radar shows statics with their default colors. So if you used sandstone to build a dungeon (for example), and colored those sandstone walls black in Centred, the radar will still show the sandstone color.

Windows 10
64bit
UO Client 7.0.15.1

**Comment by Djeryv** [comment]
![Untitled](https://user-images.githubusercontent.com/49735284/56360526-85e19980-61aa-11e9-979f-828f2ff461d6.png)

**Comment by zolter** [comment]
and screen from original uo client please :)

**Comment by Djeryv** [comment]
![Untitled](https://user-images.githubusercontent.com/49735284/56363075-fe4b5900-61b0-11e9-9ec2-611aed8c1ae2.png)
This is from the UO client (without razor or steam...just vanilla).

**Comment by SaschaKP** [comment]
done
