### ISSUE TITLE
Lanterns Not Movable

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#429]
When I set a lantern on the ground, I can no longer move it or highlight it when I hover over it. I tried a torch and that was just fine.

**To Reproduce**
buy a lantern and set it on the ground.

Windows 10 64 Bit
UO Client 7.0.15.1
ClassicUO Version 0.0.1.176

**Comment by zolter** [comment]
Drop in ground and use -info please

**Comment by Djeryv** [comment]
![Untitled](https://user-images.githubusercontent.com/49735284/56360436-4024d100-61aa-11e9-9ff6-afdf8a4e7f91.png)

**Comment by andreakarasho** [comment]
Ok got it.
The drag/drop system maybe doesnt consider the animationitem type. Thank you, i'll fix it tomorrow

**Comment by andreakarasho** [comment]
fixed in dev
