### ISSUE TITLE
Font Styles

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#431]
We can customize fonts for chatting, but the names of items and characters are in the more modern font. Is it hard to give options to have that classic UO font from the very beginning for everything in the player window (not gumps as that is controlled elsewhere) but those that appear over monsters/characters? I don't know the name so I put a screenshot here of the font. 

![image](https://user-images.githubusercontent.com/49735284/56472893-df0b3080-6429-11e9-96b1-8d10522b0c89.png)

**Comment by andreakarasho** [comment]
done
