### ISSUE TITLE
Personal Health bar / Status Window and Player Health bar - LOCK REQUEST

### ISSUE THREAD

**Issue by JosephFireborn** [ClassicUO/ClassicUO#436]
Currently, if health bars are grouped you cannot right click them off. However, a single health bar or your personal status health-bar window can be clicked off with a single right click. Is it possible to add an option to lock these bars so that only alt-click a single health bar closes it? Maybe allow this option below the current option for health bars to disappear.

**Comment by oroechimaru** [comment]
is this still an issue?

**Comment by andreakarasho** [comment]
Added these options:
- hold ALT to move gumps
- close single gump in a AnchoredGump group when right click [and alt if needed]
