### ISSUE TITLE
Destructible Items (Healthbar and Floating Damage Numbers)

### ISSUE THREAD

**Issue by UOShadowAge** [ClassicUO/ClassicUO#437]
**Describe the bug**
It is not possible to create destructible items on the ClassicUO client.  You are not able to pull healthbars from an Item nor does it show floating combat text numbers when you attack it as it does on a normal UO Client.

**To Reproduce**
Log into my shard **portal.ultima-shards.com** (**Choose the ML Shard**).
There's a portal sitting next to the starting area that I've marked destructible for ClassicUO testing purposes.  Log in with regular client and classicuo client to check the differences.

**Expected behavior**
You should be able to pull the healthbar of a specific item marked destructible, see the notoriety of the healthbar, and attack and deal damage and see the damage numbers.

**Screenshots**
https://gyazo.com/4c1c61b38d3ece2b893ca57713482b53

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by andreakarasho** [comment]
should be fixed in dev. Lemme know :)
