### ISSUE TITLE
Spell Cursor Disappear 

### ISSUE THREAD

**Issue by JosephFireborn** [ClassicUO/ClassicUO#438]
There is still an issue with spell cursors bugging out and being unable to cast again until you cancel the missing target by unequiping and reequiping armor piece or by using the cancel target key. This is the only way to be able to cast again unless spell times out. This is similar to the pop pouch bug I reported a month ago, where if you had a cursor up and popped a bag the cursor would disappear until you used cancel in razor.

1. Cast a spell on any target that is blue, with query before criminal actions turned on.
2. your cursor will be canceled/invisible
3. try to cast a spell, cannot. Even using last target
4. use cancel target or equip and unequip armor and now you can cast again.

CUO Alpha 8, Razor 1.6

**Comment by andreakarasho** [comment]
fixed
