### ISSUE TITLE
Ctrl+Shift overhead bars cannot be targetted with bard skills

### ISSUE THREAD

**Issue by PaxRomain** [ClassicUO/ClassicUO#439]
When you ctrl+shift to see overhead bars of mobiles and objects, you can not target the overhead bar with bard skills like peacemaking, provo, or discordance. Other skills like anatomy or evaluating intelligence do work, as do spells.

**Comment by zolter** [comment]
Problem in the second target, right?
First you target a musical instrument and next target not worked?

**Comment by andreakarasho** [comment]
fixed in dev
