### ISSUE TITLE
enhancement: keep runebook (blessed) in backpack open after recalling

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#440]
v alpha 8:
a. when you recall with a scroll from a runebook (possibly spells to)
b. after recalling the runebook closes. would be nice if it was kept open.

if you recall from a different book, the one you have blessed/open in your bag stays open currently.

**Comment by zolter** [comment]
Closes only in CUO? In original uo client, it remains open?

**Comment by andreakarasho** [comment]
Server closes them
