### ISSUE TITLE
Counters break after reducing number of rows or columns

### ISSUE THREAD

**Issue by roxya** [ClassicUO/ClassicUO#442]
After enabling counters, I increase the rows/columns and then apply. Then I reduce either of those values and apply. This leaves it with broken formatting.

![unknown](https://user-images.githubusercontent.com/7057924/56658949-d5850100-6693-11e9-9774-8979b2fb4acc.png)

If I log out with the counter in this broken state, the counter does not appear when logging back in (which does happen with a "good" counter)

**Comment by andreakarasho** [comment]
fixed
