### ISSUE TITLE
Mob Name on health bar shows "Razor"

### ISSUE THREAD

**Issue by ichiokada** [ClassicUO/ClassicUO#443]
not sure if this is razor bug or classicUO bug
when drag HP bar of mobs sometimes the name became Razor.

Happens randomly.

- ClassicUO dev 0.0.1.223
- razor 1.5.0.12
- Outlands shard
![bug1](https://user-images.githubusercontent.com/48904458/56668683-8914e200-66e2-11e9-9724-e4ce432c69b3.JPG)

**Comment by andreakarasho** [comment]
fixed in dev
