### ISSUE TITLE
Stuck Mouse Movement

### ISSUE THREAD

**Issue by natryl** [ClassicUO/ClassicUO#445]
Drag your mouse around to move a character but then allow the mouse to go off screen (either to a 2nd monitor or out of the ClassicUO window). Let go of right click while ClassicUO is not in focus. Now when you go back into ClassicUO with your mouse it will continue to move your character even without a mouse click being held down.

**Comment by natryl** [comment]
Update: This behavior also occures when you drag your mouse over a Gump inside the client itself and let go of right click

**Comment by andreakarasho** [comment]
fixed in dev
