### ISSUE TITLE
display counter bar does not display bandages, potions etc from trapped pouches

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#447]
version: 1.232 and alpha8.

previously (a week or so ago) the display bar would keep track of bandages and pots in subpouches (trapped or untrapped). I am having issues now where items are sometimes in my display counter or reset to 0 count randomly (even though they were working earlier). I believe it occurs after I "restock" on uo outlands using the bench/storage feature in our house. 

This makes healing/bandage macros no longer function "item not found" previously it would find /remember the bandage location. 

a. resupply from storage shelf
b. items refresh in display counter and show correct amounts
c. log off/back on, they no longer display correct amounts and are not usable.
d. the storage shelf keeps putting items in trapped pouch. both razor and classic no longer locate the bandages when you log back on.
Thanks!

**Comment by andreakarasho** [comment]
You should open the pouch then server sends to you the items inside

**Comment by BlackTeaOutlands** [comment]
Commenting on this issue.

On ClassicUO you can put items inside a trapped pouch, and it will keep updating the items. If you move the trapped pouch, or re-trap it, it will stop updating the items until you open it again.

On the regular client, you can put items inside a trapped pouch, and it will keep updating the items even if you move or retrap the pouch.

So there's clearly a difference in how it works here.
