### ISSUE TITLE
Problem linking UOC with Razor

### ISSUE THREAD

**Issue by proz9c** [ClassicUO/ClassicUO#449]
Hi guys,

This is probably just me who is a newb... 

But i get this error: 
Plugin 'D:\Games\ClassicUO\Data\Plugins\Assistant\Razor.dll' not found.
I tried to copy my razor file in the same directory as UOC but still not working.
Anyone around who can help me ? 

Thanks in advace!

**Comment by zolter** [comment]
Hi, please show your settings.json and make screenshot "Plugins\Assistant\" folder

**Comment by zolter** [comment]
Here we can help you faster
https://discordapp.com/invite/VdyCpjQ
