### ISSUE TITLE
Pet's health bar sensitive, accidentally editable 

### ISSUE THREAD

**Issue by ichiokada** [ClassicUO/ClassicUO#450]
**Describe the bug**
When trying to heal pet (target hp bar) sometimes there's a purple drag box, sometimes the name became edit state.  Original hp bar needs dclick to edit instead.

https://ibb.co/CW4yDWG
https://ibb.co/LgYZGhR

**Comment by oroechimaru** [comment]
maybe this is how bravos pet got renamed to "razor"?

**Comment by ichiokada** [comment]
I had the razor name issue too but mostly on mobs ... Their hp bar name is razor lol.. no idea why

**Comment by zolter** [comment]
fixed in dev
