### ISSUE TITLE
After Ouch! char no have correct Z

### ISSUE THREAD

**Issue by zolter** [ClassicUO/ClassicUO#452]
![41hlz0R](https://user-images.githubusercontent.com/1370602/56827604-f736e180-6867-11e9-8b01-d04fe0b37c46.jpg)

![41hlzgH](https://user-images.githubusercontent.com/1370602/56827603-f736e180-6867-11e9-9994-8b38ad82c727.png)

![41hlAUq](https://user-images.githubusercontent.com/1370602/56827602-f736e180-6867-11e9-92c8-71b39856a5a9.png)

**Comment by SaschaKP** [comment]
I'm unable to replicate it :(

**Comment by zolter** [comment]
I can't replicate too
