### ISSUE TITLE
ID on items is missing when you click them

### ISSUE THREAD

**Issue by Zandalbugs** [ClassicUO/ClassicUO#454]
Cant get info up on Id wands magic weapons and armor what kind they are or charges left :frowning: its on 0.0.1.8 on UO:F

**Screenshots**
https://media.giphy.com/media/2Yllso5yBUHQmBHwnY/giphy.gif

OS: windows 10
      Uo forever server

**Comment by andreakarasho** [comment]
Fixed in dev
