### ISSUE TITLE
House surveying tool, deed placement and IDOC issue

### ISSUE THREAD

**Issue by ichiokada** [ClassicUO/ClassicUO#455]
Cannot survey home spot with tools nor place a house on outlands shard. 
Doesn't work on alpha8 and newest dev preview versions.

Alpha7 did work.

Thanks!

**Comment by ichiokada** [comment]
- when a IDOC - collapsed, only doors and sign disappeared, the house remains, might have to run away from screen or login/out to "remove" the house.
- after alpha 7, can no longer can place house deed (even though there was no preview house upon placing but i still could place a house)
- after alpha 7, can no longer use house surveying tool


hope we can have this fix :> thank you!


![idochouse](https://user-images.githubusercontent.com/48904458/57053556-675ac280-6cc1-11e9-90f8-79f3cf95f8a0.PNG)

**Comment by aclark13** [comment]
Fixed

**Comment by aclark13** [comment]
Fixed
