### ISSUE TITLE
Improve keyboard movement control

### ISSUE THREAD

**Issue by roxya** [ClassicUO/ClassicUO#456]
The default UO movement using arrow keys has been implemented, I would like to see it improved:

- Recognise when two arrow keys are being pressed together (up and right for example) and move in the appropriate diagonal direction
- Same change of direction speed as mouse control – it currently turns and pauses before changing movement direction. In the same breath, the startup delay from stationary is too long.
- Allow rebinding of movement keys e.g. to WASD

Making keyboard movement viable would allow people to drag health bars, click targets, use gumps, etc while moving. Could be a nice quality of life improvement.

**Comment by andreakarasho** [comment]
fixed in dev
