### ISSUE TITLE
Request: ClassicUO restores the X/Y size and position of the main game window when not maximized

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#459]
I run ClassicUO as a window, instead of max size.  When I log in, the main game window client is maximzed full screen.  When I click the button in the upper-right to restore it to a window, that window is always a small 300x300 window, requiring me to resize the window each time.

All the elements in the game window retain the correct position (gumps, inner game window size, etc). It's the actual game window (with the title) that doesn't restore the position and size after login.

**Comment by zolter** [comment]
added in dev
