### ISSUE TITLE
Custom animations not displaying

### ISSUE THREAD

**Issue by zultanz** [ClassicUO/ClassicUO#460]
Custom animations are not displayed correctly.
![capture](https://user-images.githubusercontent.com/50148984/56978387-55ecab80-6b45-11e9-9df9-ce14037f6b3f.png)eproduce**
 - OS: Windows 10 x64
-  Client: 0.0.1.8

This is a great client - I hope it soon becomes my main :) Awesome work everyone!

**Comment by andreakarasho** [comment]
try the dev preview
https://github.com/andreakarasho/ClassicUO/releases/tag/ClassicUO-dev-preview

**Comment by zultanz** [comment]
This one displays the custom graphics. I'll keep using it and sending feedback. Thx!
