### ISSUE TITLE
Add Alt-left click to follow to CUO

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#461]
**Is your feature request related to a problem? Please describe.**
The standard client lets you alt-left click on someone, and it will auto-follow the mobile.

**Describe the solution you'd like**
When I alt-left click on someone, it will auto-follow the mobile until you move, which will break the follow. If the mobile you're following is out of range, follow should also break.

**Comment by andreakarasho** [comment]
Added in dev prev
