### ISSUE TITLE
Restore window location on login

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#462]
**Is your feature request related to a problem? Please describe.**
I run 3 clients, and have them spread across 3 screens that aren't maximized.  When I log in with each client, the window size is now restored thanks to a previous commit, but the position of the window is on my main monitor even though they were on my other desktops.

**Describe the solution you'd like**
When I log out, ClassicUO will remember the location of the window and upon login, restore it in that position.

**Comment by aclark13** [comment]
Added
Options > Experimental > "Disable automatic maximize. Restore windows size after re-login"

**Comment by aclark13** [comment]
Added
Options > Experimental > "Disable automatic maximize. Restore windows size after re-login"

Window still doesn't save monitor choice and X/Y location.  Just size.

**Comment by zolter** [comment]
There is a problem (in XNA) determining the current monitor. I can't make saving display position in other monitor in a simple way. Perhaps something has changed since my last attempt.

**Comment by JakubLinhart** [comment]
[SDL2 uses a global screen space coordinate system](https://stackoverflow.com/a/41746429/291379).

It means GameScene.Unload could call:
```
SDL.SDL_GetWindowPosition(Window.Handle, out var x, out var y);
```

and store it to something like `Profile.WindowClientPosition`. Then call `SDL.SDL_SetWindowPosition` from SceneManager.ChangeScene. SDL should handle multiple monitors automagically. 

Maybe I didn't get it correctly. What I'm missing?
