### ISSUE TITLE
Option to remember healthbar/nameplate gump location

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#463]
**Is your feature request related to a problem? Please describe.**
As a tamer, I often have the healthbars up of my pets, some guild mates on a regular basis.  If I have to log out and back in, all those healthbar/nameplate gumps are gone and need to be pulled again.  

When you have 3 accounts, 1 tamer on each, 9 pets, having to pull those bars each time is no good.

**Describe the solution you'd like**
An option that will save keep the healthbar/nameplate so when you log out and back in on that character, they are in the same location much like your Paperdoll and other gumps are.

**Describe alternatives you've considered**
Setting "Close healthbar gump when" to None works short term, but when you log out and back in, you need to pull healthbars up again.

**Comment by roxya** [comment]
Added to experimental options
