### ISSUE TITLE
Highlight mobile on healthbar/nameplate mouseover

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#466]
On the standard UO client, when you hover your mouse over a healthbar/nameplate, the mobile will highlight based on the notoriety. This doesn't happen in ClassicUO.

This is extremely useful when you have a large number of pets on screen, and you need to quickly find yours. You can hover over the healthbar/nameplate and the pet will highlight on screen.

**Comment by andreakarasho** [comment]
done in dev
