### ISSUE TITLE
Virtue Gump System

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#467]
In the standard OSI client, when you click on the icon above your head in the Paperdoll, it will open the virtue system gump.

![image](http://uo.com/wp-content/uploads/2015/09/virtuebuttoncc.jpg)

This gump is used to self-res, start champs, etc.  More info on the system and gump can be found here.

https://uo.com/wiki/ultima-online-wiki/gameplay/the-virtues/

**Comment by andreakarasho** [comment]
it works

**Comment by markdwags** [comment]
Sorry, I got some different info. The gump will come up, but you can't actually enable the virtue.  You can check status levels, etc.  But using the actual virtues doesn't appear to work.

**Comment by andreakarasho** [comment]
fixed in dev
