### ISSUE TITLE
Issue with party healthbars not updating

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#468]
**Describe the bug**
When someone in your party loses mana or stam, the party bars are not updated to reflect this change. They will always show 100%.  The * SELF * party gump updates correctly with no issues.

Also, when someone in your party has a notoriety change (ie: goes gray), the party bar does not always change color.  When it does, and the person goes back to green/blue, the party bar doesn't sometimes update as well.  

To fix, you can gate or teleport and they party healthbars update.

Expected behavior is that all the party bars reflect the hp/mana/stam and notoriety of the mobile it represents.

**Comment by andreakarasho** [comment]
fixed
