### ISSUE TITLE
Paragon monsters dont have the red colors on UO:f

### ISSUE THREAD

**Issue by Zandalbugs** [ClassicUO/ClassicUO#474]
Some Paragon monsters dont have the red colors on UO:f
Toxic water elemental
 - OS: Windows 10

 - Version Ultima online Forever

**Comment by andreakarasho** [comment]
write "-info" in game and select the paragorn, then post the result Hue.

**Comment by Zandalbugs** [comment]
Found these 3 
ancient lich
balroc
Toxic water elemental

![anicendt lich](https://user-images.githubusercontent.com/50055941/57180135-f9132d00-6e85-11e9-84d2-feb5e4bfee7d.jpg)
![Balron](https://user-images.githubusercontent.com/50055941/57180136-f9132d00-6e85-11e9-8ec0-199a931b2310.jpg)
![Toxie](https://user-images.githubusercontent.com/50055941/57180137-f9132d00-6e85-11e9-818d-1a8b6117587a.jpg)

**Comment by andreakarasho** [comment]
Same issue probably: https://github.com/andreakarasho/ClassicUO/issues/477
Can you try with the dev prev ?
