### ISSUE TITLE
Right clicking a status bar or status gump targets it with a target cursor

### ISSUE THREAD

**Issue by PaxRomain** [ClassicUO/ClassicUO#476]
If you attempt to close a status bar or player status gump by right clicking, and you have a target cursor up, it will target the status bar with the cursor and then close it. Right clicking something should never consume the target cursor.

For example, if you have the explosion spell up and right click your status gump to close it, you will drop the explosion on yourself!

**Comment by andreakarasho** [comment]
fixed in dev
