### ISSUE TITLE
GM is yellow or red

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#477]
**Describe the bug**
A GM on the shard is yellow as seen in the screenshot

![image](https://i.imgur.com/KD5PezB.png)

When I uncheck "Highlight by state" the GM turns full on red

![image](https://i.imgur.com/pcmUV6j.png)

**Expected behavior**
The GM would be a normal human mobile with a red robe  regardless of that checkbox.

**Comment by andreakarasho** [comment]
should be fixed in dev.
Lemme know if it works, if not i ll reopen this issue
