### ISSUE TITLE
Item descriptions are too long

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#478]
**Describe the bug**
The items descriptions are too long on items when they're in a container or paperdoll.  Example:

![image](https://i.imgur.com/C510ynA.png)

![image](https://i.imgur.com/oWCg8Nw.png)

Now with the same item on the ground

![image](https://i.imgur.com/jKcIXCJ.png)

**Expected behavior**
Regardless of the item location, the length of the item description should be limited by a certain # of characters per line.

**Comment by andreakarasho** [comment]
fixed in dev
