### ISSUE TITLE
Item descriptions overlap and flicker

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#479]
**Describe the bug**
Items that are close to each other, when you click to see the description, have issues layering on each other

![image](https://imgur.com/cza11DT.gif)

Here are multiple long named items:

![image](https://i.imgur.com/7llMcUf.png)

**Expected behavior**

The standard OSI client will always layer the most recently clicked item on top of the rest.  The length is also not as long and be limited to #'s per line.

The gif below is taken from the standard OSI client. Hovering your mouse over the text of an item behind will bring it to the front, for example.

![image](https://imgur.com/WUGxff4.gif)

**Comment by andreakarasho** [comment]
fixed in dev
