### ISSUE TITLE
Random wrong animation of objects bug

### ISSUE THREAD

**Issue by ichiokada** [ClassicUO/ClassicUO#482]
Random wrong animation.
Candle happens when I blow it out locked down
Tree happens 2 times 
- in inferno dungeon fighting a daemon
- at outpost bank 

https://streamable.com/ldjv5

https://streamable.com/0b3r5

![Screenshot_20190505-124948](https://user-images.githubusercontent.com/48904458/57188623-4bab2280-6f34-11e9-9dec-928ec1204023.png)

**Comment by andreakarasho** [comment]
should bve fixed in dev.
Closed.
If issue persists i'll reopen it

**Comment by ichiokada** [comment]
just tried on dev 0.0.1.356
still have issues with the candle dancing.. wrong animation
it goes short candle, small candle, tall candle loop

**Comment by andreakarasho** [comment]
fixed ;)

**Comment by Djeryv** [comment]
Campfires want to show tomato plants on the latest dev preview.

![image](https://user-images.githubusercontent.com/49735284/57416582-6f859700-71c6-11e9-9e6f-fc0bfe459afb.png)

**Comment by andreakarasho** [comment]
CUO version?
-info on it and post the graphic please.

**Comment by Djeryv** [comment]
The tomato plant picture is shown next to some other burnt out campfires. Here is my version in the title bar...

![image](https://user-images.githubusercontent.com/49735284/57451237-5ad8eb80-7226-11e9-939c-9509dd2f3652.png)

**Comment by andreakarasho** [comment]
should be fixed from .359 build.

Download the new one
