### ISSUE TITLE
Pitch Variation creating "wrong" sounds

### ISSUE THREAD

**Issue by roxya** [ClassicUO/ClassicUO#484]
https://github.com/andreakarasho/ClassicUO/blob/069ee511b6f88a8eb259e1147a00fc4ebeab8b2d/src/Game/Managers/AudioManager.cs#L58

The PitchVariation effect is applying a random pitch (-1.25 to +1.25) to spells, moongate travel, anything which varies with distance. I don't know why it does that, perhaps to create variation in footsteps / horse hooves, but I'm pretty sure it should not apply to spells and such. I feel like this is the source of comments that sounds feel "off".

I don't want to touch it without knowing why it's doing it in the first place, but changing it to AudioEffects.None made everything sound much more familiar to me.

**Comment by andreakarasho** [comment]
yeah you are right. Removed
