### ISSUE TITLE
Left click drags bars even with target cursor (Video)

### ISSUE THREAD

**Issue by PaxRomain** [ClassicUO/ClassicUO#485]
If you attempt to left click a status bar with target cursor, and your mouse is in motion when you click, you will actually just drag the bar around your screen. In order for the left click to register as a target, your cursor must be completely still. In the original UO client, left clicking a status bar with a target cursor always consumes the target no matter whether the mouse cursor is in motion.

This is a major issue in PvP where you are often flicking your mouse cursor up to a teammate's bar to heal. I believe this is behind the problem with people claiming they sometimes have to click a bar multiple times in PvP.

I have included a video demo of the problem: https://streamable.com/l7vox

**Comment by andreakarasho** [comment]
fixed in dev
