### ISSUE TITLE
ethernet adapter choose

### ISSUE THREAD

**Issue by tibazera** [ClassicUO/ClassicUO#487]
With this feature, you can choose how network you client use to connect.

Example:

I had two connections with differents IP's 

I can choose if which ethernet network I will use

Like old programs, bindmyip , bindipforce...

**Comment by andreakarasho** [comment]
wat?

**Comment by tibazera** [comment]
Ill example again.

I had in my house 2 different internet connections.

Open first CUO, choose what connection ill be used to connect server... with connection X or Y 
Doing this you can open 2 CUO with different ip connections

**Comment by markdwags** [comment]
Sounds like a way to circumvent freeshard policies on a certain number of accounts per IP.

**Comment by DarkLotus** [comment]
Plenty of legitimate uses where you have internet connectivity via multiple adaptors and would rather route via the non primary. But it's out of scope for CUO, use Sockscap or similar software.

**Comment by tibazera** [comment]
I think I got confused when I asked for this.
this should be added as a tool for razor, crossuo (wizards) and not direct to the client.
this same suggestion was sent to the hotride that is implanting in orion
and really the idea is that it can use more than 1 client with different IP, sockscap is a tool for proxy does not exactly what I imagined ... I just did not understand the comment of cheating the server, since in CUO there are several things that cheat , such as landfix, etc ... there are several servers that prohibit this too.

**Comment by oroechimaru** [comment]
my hmo... seems like a super low priority request.. i have not seen it requested by dozens of players and its a rare setup.

a. vpn cheaters with multiple accounts
b. guys playing on a server at work with multiple nics

there is probably no legitimate purpose beyond vpn/proxy ip cheating for bypassing account limits on servers for 99.99999% of players .

**Comment by DarkLotus** [comment]
If your running enough clients to require a VPN your probably macroing using uostealth and not really using CUO for that anyway, I wouldn't want to run 20+ copies of CUO at a time. I still think it's outside the scope of CUO, no other game clients support this functionality.
