### ISSUE TITLE
Cannot Hover Over Items in Sell/Buy Lists

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#488]
When you are in a vendor buy/sell window, you cannot hover your cursor over the items and get descriptions. I am using the latest dev preview on Windows 10.

![image](https://user-images.githubusercontent.com/49735284/57416483-32210980-71c6-11e9-831b-3c14bb30d235.png)

**Comment by andreakarasho** [comment]
Done
