### ISSUE TITLE
Gump Black Fonts Show White in HTML Window

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#489]
I have gumps with black fonts when in the HTML windows (the ones you can set with scrollbars and such). In this client, the font shows white. If I used a gump "label", that is black as it should be...it is just those gumps that I think use HTML coding for styling.

![image](https://user-images.githubusercontent.com/49735284/57416667-a8257080-71c6-11e9-8584-88bc1ae62ea1.png)

**Comment by Djeryv** [comment]
I tried something on a whim. In the normal client, you can use a Color=Black to get the black font...but ClassicUO wants a hex value. So I changed my Black to #000000 and White to #FFFFFF and it looks fine. So I am not sure if you want to fix this or not.

**Comment by andreakarasho** [comment]
fixed! you dont need to change anything.
