### ISSUE TITLE
Journal.txt

### ISSUE THREAD

**Issue by natryl** [ClassicUO/ClassicUO#490]
Following these steps to get text file of your Journal works for the original client with steam or Razor. http://forums.uooutlands.com/index.php?threads/how-to-record-your-journal.533/

This however does not work in ClassicUO. Can you look into this so that doing the same cfg edit allows classicUO to generate a journal.txt file or implement a new method to output the journal to a log file.

**Comment by SaschaKP** [comment]
done, test it
