### ISSUE TITLE
Typing issues - could be due to high ping

### ISSUE THREAD

**Issue by ichiokada** [ClassicUO/ClassicUO#492]
Issues only happens on dev prev cuo + new razor
Dev prev cuo alone has no typing issues

- key strokes not bring registered when I type at normal speed
- harder to type on login screen (have to spam keys many times)
- might due to my high ping avg 300-400ms in-game 
- when ping spike higher, even more difficult to type

I notice other players say no more typing issues but mine still persist.  So it could really be caused by a ping issue, just a guess. 

Hope this helps! Thanks

**Comment by markdwags** [comment]
I don't believe your ping is connected to the input issue especially since you have this at login. You can confirm you're on 1.6.0.12+ of Razor?

**Comment by ichiokada** [comment]
hi there! thanks for your reply. 
I  notice my razor is 1.6.0.8  , maybe this is the issue.  however i used the powershell auto method to update, is there any steps i missed so my razor doesnt update?  thanks a lot

**Comment by markdwags** [comment]
That's your issue.  Sounds like your settings.json isn't pointing to the updated version.  If you ran that script in your existing CUO folder, it isn't going to update your settings.

**Comment by ichiokada** [comment]
i notice theres a folder "Razor" in my CUO folder, and another older Razor in the Plugin folder.. 
my settings.json is
  "plugins": [
    "./Razor/Razor.exe"
  ]
}

is it pointed wrong?

**Comment by markdwags** [comment]
If you're seeing that older version launch, it must not be pointing to the right folder.

**Comment by ichiokada** [comment]
I manually replaced new razor to my plugin razor folder and it's perfect now, thanks!  If I want to make correct path how should I set the JSON file? Thanks

**Comment by markdwags** [comment]
The JSON path should point to the Razor path in the ClassicUO folder.  It will always update that version.

@andreakarasho you can mark this closed :)
