### ISSUE TITLE
CounterBarGump and multiple hued items

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#493]
**Is your feature request related to a problem? Please describe.**
On UOR, they have gold, holiday coin, platinum, etc that use the same gold graphic, but just with a different hue.

When you drop those into the counterbar gump, the counter will display the item with the normal hue and the counter picks up all the gold so you don't know what type of coins you're carrying.

**Describe the solution you'd like**
The CounterBar Gump will also use the hue of the item when counting items and displaying the item in the counterbar.

**Comment by DarkLotus** [comment]
We have the same issue with custom potions using the same art, this effect razor etc as well though which rely on only the ITEMID and not hue for buy/sell lists etc.

Ideally the server fixes this by adding new artid's for their new items.

**Comment by SaschaKP** [comment]
done
