### ISSUE TITLE
Crash when I try to paste title of a book

### ISSUE THREAD

**Issue by TyrAntilles** [ClassicUO/ClassicUO#494]
When I try to paste the title of an in-game book CUO crashes. When I try to paste on the book itself it works correctly.

**To Reproduce**
Have a book in backpack, open it, copy a short text from notepad and paste it on the book title.
CUO crashes.

 - OS: Win7x64
 - CUO v.0.0.1.401, Razor v.1.6.0.19

**Comment by SaschaKP** [comment]
Let me loot at it

**Comment by SaschaKP** [comment]
fixed
