### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by andreakarasho** [ClassicUO/ClassicUO#5]
**Describe the bug**
after a while memory usage increase 2x.
VS says it's a fault of SpriteVertex. WTF???!?

**To Reproduce**
run around the world 🗡 

**Expected behavior**
memory should be around 250mb.

**Screenshots**
none

**Desktop (please complete the following information):**
none

**Additional context**
none

**Comment by 3HMonkey** [comment]
Is it stable at 2x memory?

**Comment by andreakarasho** [comment]
Yes

**Comment by 3HMonkey** [comment]
Mhhh seems like it’s buffer related. Are we unloading the graphics after leaving the screen? When do we flush the buffer or graphics ?

Again, what is wrong with „just“ 500mb if ram for a rendered game? Also do you mean Ram or GPU‘s native ram? Is there another impact? Sorry for this many questions but I want to understand the problem in detail .

**Comment by andreakarasho** [comment]
500mb of RAM.
I do a cleaning into TextureManager.cs .
When a spritetexture is used, i update the Tick property. If a texture is not used after 3s it does a dispose.

Maybe i miss something into SpriteBatch3D? We have to do a deep investigation

**Comment by 3HMonkey** [comment]
I gonna compare it with my spritebatch tomorrow and give a feedback.
