### ISSUE TITLE
Hold "SHIFT" for Context Menu Option

### ISSUE THREAD

**Issue by aclark13** [ClassicUO/ClassicUO#503]
Add an option to enable holding "alt" to bring up context menus with left click.

**Comment by aclark13** [comment]
I actually think the standard client is hold SHIFT, not alt.

**Comment by roxya** [comment]
To clarify, the standard client has 
![image](https://user-images.githubusercontent.com/7057924/59011657-4986fd00-882d-11e9-8759-250c6d0bc2cc.png)

It prevents single-click from getting a context, only showing it when shift was held for the click.
