### ISSUE TITLE
Character creation

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#506]
**Describe the bug**
On UOR, when you create a new character, when you get to the skill selection screen, it will pass this screen and create a character on the shard with 0 skills.

**To Reproduce**
1. Log into UOR (prod or test)
2. Create a new character
3. When you get to the skill screen, observe it will move past it and create your character with 0 skills.

**Expected behavior**
This has worked before, you'd expect to be able to pick your skills first before proceeding.

**Comment by SaschaKP** [comment]
fixed with https://github.com/andreakarasho/ClassicUO/commit/5974f97b75dd43302154e652ad07e2f7939ac2f7
