### ISSUE TITLE
Health bar anchoring error when bars are created from paperdoll "status" button

### ISSUE THREAD

**Issue by roxya** [ClassicUO/ClassicUO#507]
Take two paperdolls and open their health bars by clicking Status
![image](https://user-images.githubusercontent.com/7057924/58856333-4f000e00-869a-11e9-96f5-a73e269a59c1.png)
![image](https://user-images.githubusercontent.com/7057924/58856358-63440b00-869a-11e9-9b9a-6311179ae25c.png)

Anchor the second bar to the first bar
![image](https://user-images.githubusercontent.com/7057924/58856380-70f99080-869a-11e9-9cb5-9a3d3a916b71.png)

Drag the first bar (not yet touched). The second bar gets thrown somewhere else
![image](https://user-images.githubusercontent.com/7057924/58856406-840c6080-869a-11e9-8082-23a3d81a527a.png)

If you move each bar a little before anchoring, it works fine. I think it's to do with _prevX _prevY not being set on the health bar gumps created in this way.

**Comment by oroechimaru** [comment]
is this fixed?

**Comment by andreakarasho** [comment]
looks very random :|

**Comment by andreakarasho** [comment]
Does it still happening?

**Comment by roxya** [comment]
I'm sure it was fixed by the "initialize controls immediately" commit, seems OK now even without the extra Initialize() we were previously doing
