### ISSUE TITLE
Boat commands not fully working "Forward Right" makes boat go only to the right.

### ISSUE THREAD

**Issue by Nic84** [ClassicUO/ClassicUO#511]
Typed commands into CUO are not working as expected.

To reproduce: While in a boat type and enter: "Forward Right" 
The boat will only go right instead of forward right.

But it works fine with Razor's boat control window:

![uwMLYvO8nn](https://user-images.githubusercontent.com/11181203/58978484-4abf1800-87a2-11e9-85b3-068ffdf16d13.gif)

The same happens for commands, "forward left", "back left", "back right".

**Comment by andreakarasho** [comment]
Should be fixed here: https://github.com/andreakarasho/ClassicUO/compare/27c3756f06fa...66310158287c

IF not i'll reopen the issue

**Comment by Nic84** [comment]
Works good now, thanks!
