### ISSUE TITLE
Fency Armoire - displaying incorrectly not opening

### ISSUE THREAD

**Issue by andrehsmendes** [ClassicUO/ClassicUO#516]
Fency Armoire is displaying incorrectly and it is not opening on double click.

**To Reproduce**
1. Create an Fency Armoire
2. Double click on it to open.

It is displaying as it was opened:
![image](https://user-images.githubusercontent.com/2303503/59356584-1f36b300-8cf7-11e9-8b26-0c14fde9344f.png)

When you double click to open, it flashes real quick the container open and closes.

OS: Windows 10
Classic Client Version:  0.0.1.10

**Comment by andreakarasho** [comment]
i added a simplearmoire in my backpack and it works right.

Can you retry with the latest dev preview? 
I close it until i'll not receive a feedback

**Comment by andrehsmendes** [comment]
Nope. same problem on Version 0.0.1.11.

Note: I'm testing on UO Outlands.

![image](https://user-images.githubusercontent.com/2303503/60750236-9fa5a800-9f73-11e9-9d0f-8af3e15a5171.png)

when trying to open. it quickly opens and closes.

I made a video of the issue, please check it out.

https://youtu.be/9Ofgqtv_1y8

**Comment by andreakarasho** [comment]
should be fixed
