### ISSUE TITLE
Spellbook Hover Text

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#523]
I am currently running the dev 0.0.1.11 build and I noticed that you cannot hover over the spellbook pages to get the hover text that would appear in the normal client. Here is a picture of what I mean from the plain client:

![image](https://user-images.githubusercontent.com/49735284/59926765-9a3b5000-9400-11e9-9ff3-bfb3acdba308.png)

**Comment by andreakarasho** [comment]
done
