### ISSUE TITLE
Movement by macro bugs

### ISSUE THREAD

**Issue by roxya** [ClassicUO/ClassicUO#527]
https://github.com/andreakarasho/ClassicUO/blob/7e05a9f9d13c85e2293cb915803e616f60ff06ac/src/Game/Scenes/GameSceneInputHandler.cs#L637-L642

**1. Pressing any key which is not attached to a macro will halt movement, and leave invalid _is(Direction)Down values.**

- Set up MovePlayer-Left and MovePlayer-Right macros
- Be moving using a MovePlayer-Left macro
- Press another keyboard key which is not bound to a macro
- At this point, movement stops when it should not
- Let go of all keys and then start macro moving using the MovePlayer-Right macro
- You will probably be moving left instead of right
- Let go of the macro movement key
- You will continue to run left without any keys pressed

**2. If using modifier+key for movement (e.g. Shift+WASD), letting go of the modifier leaves invalid _is(Direction)Down values.**

- Set up a macro movement key using a modifier, e.g. Shift+A = MovePlayer-Left
- Start moving left using Shift+A
- Keeping A pressed down, let go of Shift
- You will stop. Good.
- Press (not hold) ANY keyboard key.
- You will be moving left without any keys pressed

**Comment by zolter** [comment]
ty 🍺

**Comment by Hezkore** [comment]
Something I've noticed as well is that the MovePlayer macro works through any gump.
For example if you have Options open; pressing any MovePlayer macro key will still trigger, which is not the case for any other macro.

And this also works when typing.
If you for example use W A S D as MovePlayer, then when typing "Wassaup" the player will move around while typing.

**Comment by andreakarasho** [comment]
MovePlayer is not handled anymore.
Replaced with Walk macro
