### ISSUE TITLE
Unknown Cliloc on Shard Selection

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#530]
Just downloaded Alpha 11 and I noticed this when logging in:

![image](https://user-images.githubusercontent.com/49735284/59967031-4efd6c00-94ea-11e9-9c1d-81fdba330c88.png)

**Comment by oroechimaru** [comment]
There is a common warning on UO Outlands I believe with Razor. In your UO folder does cliloc exist? The workaround on UO Outlands is to copy that file into your ClassicUO folder. I may be wrong on this and confusing it with another issue.

**Comment by Djeryv** [comment]
If I don't use ClassicUO, there is no text in the places the screenshot indicates...so I don't know what it wants to show there. My Cliloc is in the ClassicUO folder, but it has been modified for my shard if that even relates to anything.
[Cliloc.zip](https://github.com/andreakarasho/ClassicUO/files/3322511/Cliloc.zip)

**Comment by andreakarasho** [comment]
Fixed in dev

**Comment by Djeryv** [comment]
Yes. I see it is gone when using the dev version. You can close this one then.
