### ISSUE TITLE
Vendor Wrap Text Length

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#533]
Using Alpha 11, I notice that items with longer names overlap items below then when they should resize and adapt to string lengths and space between items appropriately.

m_PetName
![image](https://user-images.githubusercontent.com/49735284/59977787-3bf6a480-959b-11e9-867a-ebff0b152878.png)

**Comment by Djeryv** [comment]
I think it might be doing the height by the item/image height, because here you can see the bottom potion is cut off:

![image](https://user-images.githubusercontent.com/49735284/59978091-3babd880-959e-11e9-8735-2eae395334e3.png)

**Comment by andreakarasho** [comment]
try latest dev prev please https://ci.appveyor.com/project/andreakarasho/classicuo/build/artifacts

**Comment by Djeryv** [comment]
Seems to work fine. I just made the name of the item really long to test it.

![image](https://user-images.githubusercontent.com/49735284/59979392-f511aa80-95ac-11e9-9a33-ef6fe34827aa.png)

**Comment by andreakarasho** [comment]
perfect  :) i close this issue

**Comment by Djeryv** [comment]
I wasn't sure if I should open a new issue, but this is happening again. Perhaps it started when you provided options for the window height in multiples of 60?

![image](https://user-images.githubusercontent.com/49735284/64494864-bf00d000-d257-11e9-9fe3-47be2e5142c1.png)
