### ISSUE TITLE
Cannot Select Animated Items?

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#534]
Using Alpha 11, I noticed that I cannot double click the magic doorway face item like I can in the original client. I am not sure if it is animated items/tiles in general, or not. I can double click this magical doorway (face) if I do a control-shift and double click the context menu above it.

![image](https://user-images.githubusercontent.com/49735284/59978919-03f55e80-95a7-11e9-96f2-35626c3ba63c.png)

**Comment by oroechimaru** [comment]
can you type: 
-type

then hit enter, target the object then take a screenshot and post it here? If -type isnt working try -info or -item , I am at work and always forget lol. Thanks!

**Comment by Djeryv** [comment]
![image](https://user-images.githubusercontent.com/49735284/60093470-1db1b580-970f-11e9-9d2c-46c03d9bc1fc.png)
![image](https://user-images.githubusercontent.com/49735284/60093474-20aca600-970f-11e9-9df9-b01732cc261d.png)
![image](https://user-images.githubusercontent.com/49735284/60093480-22766980-970f-11e9-857b-03210c998110.png)
