### ISSUE TITLE
Allow hovering or a mechanism to flip through vendor names or stacked items

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#535]
ctrl+shift: set to corpses and mobiles

go to a house with 10-20 vendors that are very close to eachother. 

when pressing ctrl+shift the names will stack over eachother
a. one idea: have names/offset
b. another idea: if hovering a partially exposed background vendor name (or any object/mobile) let it "Bring to front" if hovered for a few seconds (or something so you can see the full name of the object in background)

This is tricky to screenshot .

**Comment by aclark13** [comment]
Hovering isn't a bad idea, but by default a single click brings it to the front.

**Comment by oroechimaru** [comment]
i keep having bad luck where the names are stacked near perfect on eachother that i can only click the top.

especially if two corpses die near eachother i have a hard time getting the corpse to open with names being stacked instead of slightly offset

**Comment by Schmorty** [comment]
click doesnt work for me

**Comment by aclark13** [comment]
Right click on the top name to close it to see the bottom name.

![asd](https://user-images.githubusercontent.com/38568913/60121132-0fcc5680-9748-11e9-835f-c6f249f7da4f.gif)

**Comment by Schmorty** [comment]
oh yeah that works for me. I thought we were discussing the 'all names' option...which you cannot bring things to the forefront or remove names. my bad.
