### ISSUE TITLE
suggestion auto open corpses: allow a flag to prevent opening blue corpses

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#536]
If the corpse is blue/good, please allow a check box that prevents opening the corpse (auto open corpses enabled) or a popup warning flag option.

thanks!

**Comment by roxya** [comment]
Information about a corpse being "good" to loot isn't readily available to the client.

**Comment by oroechimaru** [comment]
If anyone sees this (keep it closed), the workaround I use is to create a Razor "overhead message" on the criminal message that appears in the journal or system area, that way I have my own safeguard .
