### ISSUE TITLE
suggestion: allow map objects to not be effected by COT

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#537]
circle of transparency:

similar to ctrl+shift configurations which has different levels of configuration, it may be helpful to allow:
a. game tiles/land features to not go transparent
-example stalagmites in uo outlands may appear invisible (invisible barrier) that you need to run around (in ice temple/fort on outlands)

b. some game tiles are difficult to navigate through (arches, door ways, etc) if they go invisible (you wont see the door)

one suggestion is to allow "only filter player housing" which is the majority of cases where i need it or limit to "roofs" only (i love roofs but not when im trying to see whats hiding behind a wall)

c. another object is to be transparent but retain a stencil/pencil outline like a blueprint so we can find doorways? this is probably too tricky 

thanks for reviewing

**Comment by oroechimaru** [comment]
![2019-06-23 13_55_36-Start](https://user-images.githubusercontent.com/26830362/59980681-e8964d80-95be-11e9-8ba6-632ce1dc5c54.png)
![2019-06-23 13_57_10-Start](https://user-images.githubusercontent.com/26830362/59980682-eaf8a780-95be-11e9-8fa9-d61ae9cbe55e.png)

**Comment by oroechimaru** [comment]
possibly this part needs to be an optional flag in static.cs?

else if (ItemData.Height == 5 && ItemData.IsSurface && !ItemData.IsBackground)
                _canBeTransparent = 1;

**Comment by andreakarasho** [comment]
Looks a fix really custom
