### ISSUE TITLE
alpha 11 (not new): monster corpses display their clothing/gear

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#538]
please hide unlootable items/gear npcs may wear from corpses thanks!

![image](https://user-images.githubusercontent.com/26830362/59981737-94df3080-95cd-11e9-8b90-b1ef0341d51b.png)

**Comment by andreakarasho** [comment]
UOSteam behaves the same?

**Comment by oroechimaru** [comment]
idk dont use steam lol (on vacay). i just was thinking it was similar to corpses having a similar issue in spring.

**Comment by oroechimaru** [comment]
Oh man using steam was like using time travel to ancient times. Lol !!

So it looks "Similar" with the stuff displayed on the body but sorted so that:
a. actual loot is displayed first instead of last
b. unlootable monster clothing shows up last in the list

So if its easier than "hiding the clothing/gear" on npcs, maybe change the sort to function similar to steam?

Screenshot:

![image](https://user-images.githubusercontent.com/26830362/60759753-a3771000-9fef-11e9-9333-3060a0f8170b.png)

**Comment by aclark13** [comment]
This was merged with PR #795 
Still a few bugs, and improvements are being made.  Let me know if it needs to be reopened
