### ISSUE TITLE
suggestion: overhead bandage counters or individual counter bars

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#539]
i have a 1x15 bar. could we get "single" options that we could add seperately that could also have a bandage cooldown timer (even if custom like 10 seconds). 

It would also be cool if we had a feature to block using a bandage if you already have one in use, im just not sure if that is reasonable/possible. (so i dont accidentally use one when im already using one and close to complete)

**Comment by Admin-Yukiko** [comment]
I think the multiple bandage use is best handled server side.

**Comment by oroechimaru** [comment]
hmm ok. i was thinking in the same light of the razor feature to block bandage use if already poisoned ... to block healing use if already healing

**Comment by oroechimaru** [comment]
If this is deemed too powerful, please make it dummkopf proof and add a "numerical countdown" in the counter toolbar over the bandages icon (the newer display counter in CUO client). Would be handy for bandages, food and other countdown items.

**Comment by Belialzao** [comment]
if you want a simple bandage timer in Outlands, just add {energyresist} to razor's titlebar display.

**Comment by oroechimaru** [comment]
The titlebar stuff is too messy for me to keep track of currently . I have neuropathy and I get dizzy quick from certain color patterns. The display counter in cuo is gorgeous. If its possible to build in a count down timer directly in the display counter or as an overhead (over my character) when using aids that is great! if that is a PITA then Karasho can close this=) .

**Comment by andreakarasho** [comment]
seems a bit tricky to do. This client covers more shards
