### ISSUE TITLE
Features [Drag for bars, remove bars, all names/corpses forefront]

### ISSUE THREAD

**Issue by Schmorty** [ClassicUO/ClassicUO#541]
1.) The option to close health bars upon death is awesome when I'm fighting mobs but it also closes my friend/party members/pets bars when they die. Is there a way to change that to not affect other players bars and only mobs/npc?

2.) Is it possible with the drag to open health bar feature for it not to re-open bars that you already have pulled? When I drag for bars it always reopens my pet and party bars but they're stacked up in the middle of the screen instead of organized where I had them.

3.) When using All Names/All Corpses you cannot bring names to the forefront by highlighting them with the mouse. This makes All Names pretty much useless in its current form.

**Comment by andreakarasho** [comment]
I can consider party only, because server doesnt send you any info about pets or friend furthermore CUO doesnt have a friend list so 

About the AllNames, i'll fix it

**Comment by andreakarasho** [comment]
all names fixed according to the request
