### ISSUE TITLE
trees to stump option creates a bunch of non existant trees

### ISSUE THREAD

**Issue by expiation** [ClassicUO/ClassicUO#544]
**Describe the bug**
the option to turn trees to stumps seems to create a bunch of non existent trees making it difficult to tell where you can actually walk.

https://cdn.discordapp.com/attachments/553829720232558613/593133129703751681/unknown.png

trees without the stump option above, and below with the stump option

https://cdn.discordapp.com/attachments/553829720232558613/593133222754385931/unknown.png

**Comment by expiation** [comment]
for clarification this is south of Trinsic around 1662, 3165

**Comment by andreakarasho** [comment]
Cuo version?

**Comment by expiation** [comment]
4:13:24 PM |  Trace   | Starting ClassicUO - 0.1.2.21

**Comment by andreakarasho** [comment]
i added the season, can you retry ?

**Comment by expiation** [comment]
still an issue, Trace   | Starting ClassicUO - 0.1.2.173

client version 7.0.45.0 from the ultima online forever launcher completely updated and unmodified

trees without trees to stump option checked

https://cdn.discordapp.com/attachments/556254750773870592/600942856219262977/unknown.png

and then when you check it there are a bunch of fake trees

https://cdn.discordapp.com/attachments/556254750773870592/600942953438904321/unknown.png

**Comment by andreakarasho** [comment]
Fixed
