### ISSUE TITLE
bug: grabbing healthbars (draw square) also drags healthbars not in square on to mouse

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#548]
v1.2.19

a. pull up a party member's health bar. drag it far to the side of the screen

b. find a mob > draw the square to pull up their health bar. i forget if this only happens when the party member is near the mob you are pulling. 

c. both the party member + the monster's health bars will move to where you drew the square/mouse and often stack/overlap

d. secondary bug: maybe one out of 50-100 times this happens especially if pulling multiple monster bars they will stack so close to eachother they will lock together(alt right click to close). 

suggestion:
a. have multiple bars offset each other and not overlap/stack on eachother
b. have bars outside of your grid be left alone unless they were reselected within your square.  (exclude party members from repulls)
c. ignore healthbars you already put to the side for party members
d. alternatively maybe make an option so it can be set to only pull non-party bars if thats easier? 

![2019-06-26 08_01_48-Start](https://user-images.githubusercontent.com/26830362/60184642-08f81f00-97ee-11e9-8bb9-656012861d6b.png)

**Comment by oroechimaru** [comment]
The issue appears to only occur with party members. Other guild members did not cause this issue when I pulled up monster hp bars in the area that were not in the party.

**Comment by oroechimaru** [comment]
When pulling multiple healthbars when not in a party sometimes they stack 100% on top of each other or in an odd way where they will lock. Can these be offset with a bit of spacing?

**Comment by oroechimaru** [comment]
a. i believe karash mentioned party may be able to be captured by packet... if they could not be repulled that solves part of the issue

b. next part is to only pull the bars of creatures within the square, then once pulled offset them a bit with spacing. 

i havnt had a chance to test since june

**Comment by oroechimaru** [comment]
the party + guild pets would be great if they didnt drag when were all fighting on a tmap:)

![image](https://user-images.githubusercontent.com/26830362/61339014-80bfd500-a801-11e9-9a2d-924610b2bddb.png)

**Comment by oroechimaru** [comment]
I feel most of this is now resolved except the "stacking effect". Can they be offset with a small pixel buffer between boxes?  so there not 100% overlapping or super close to each other (lock)?

thanks!

**Comment by andreakarasho** [comment]
![image](https://user-images.githubusercontent.com/20810422/61570630-4dde4100-aa8e-11e9-9c2d-9055f6f2cf3a.png)
better?
