### ISSUE TITLE
yell and whisper

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#551]
from ace:
a. using ! as a chat prefix doesn't make your text yell
b. ; doesn't activate the chat box

From ROE:
a. I have issue A (cant yell)
b. issue b when I type ; it says whisper in the chat box

dev: 0.1.2.29

**Comment by zolter** [comment]
I need your help about "; doesn't activate the chat box"
I can not reproduce it

**Comment by zolter** [comment]
and I add Yell, please check it

**Comment by aclark13** [comment]
Sorry it was : and not ;
They are seem to be working now with todays build.
