### ISSUE TITLE
ctrl+shift displays blue corpses with a gray "Corspe" text

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#552]
can the ctrl+Shift be made to match the color of the corpse? thanks! 
6/27/19 dev

**Comment by oroechimaru** [comment]
still exists. Closed similar ticket due to recent enhancements to ctrl+shift.

**Comment by roxya** [comment]
Corpses don't have a notoriety attached. I don't think it's realistic to guess/cache it from the server text colour.
