### ISSUE TITLE
enhancement: longer journal and chat filter

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#557]
often the journal is filled with system message spam which leads you to miss out on conversations that quickly leave the log. can either of these exist?

a. longer journal (2x-3x). 
b. a filter to just show chats/conversation

often you miss what someone says and by the time u try finding it in the journal its gone due to system message spam

thanks

**Comment by aclark13** [comment]
Would group this with issue #205

**Comment by oroechimaru** [comment]
dupe

**Comment by BlackTeaOutlands** [comment]
Issue : "Additional buttons also activate chat" - not all of them work for me. \ / | doesn't work (guild, party, alliance). Only one that works is ! = yell.
