### ISSUE TITLE
enhancement: is it possible to not render tiles/statics out of range?

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#559]
this is an optimization suggestion. Is this even possible? THANKS!!!

UO is isometric and a diamond even though players feel it is a square. Since the number of statics can be intense on higher resolutions (1600x1500 is ideal if not 1700x1700+ if you could) to see all objects, is it possible to do the following?

a. for the feature "no color for object out of range" this had me the idea: "no rendering for tiles out of range/just show black/gray". This could cut down on statics to boost fps on what is "truly visible". Basically the sections in grey should not be rendered.

b. confirm the tiles/statics are not being rendered that are outside the resolution (unless that is prefetching). For instance if someone is playing 640x480 but it is loading 1800x1800 worth of tiles  (i doubt it is doing this

screenshot taken at 2k res with cuo set to 1600*1500 or so

![image](https://user-images.githubusercontent.com/26830362/60762799-e2778680-a02c-11e9-8cde-3f9bc9200630.png)

**Comment by andreakarasho** [comment]
reduce your game window size

**Comment by oroechimaru** [comment]
that doesnt solve the issue at high rez =} maybe its just my pc then
