### ISSUE TITLE
Container (With Custom Gump) Defaulting To Backpack Gump

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#560]
I compiled the source from the DEV yesterday and I am getting a particular issue with a container. The green urn here should open up with the GumpID set in the second picture, but the top image (ClassicUO) is showing the backpack gump. Both the urn and gump are custom added items to the client files.

![image](https://user-images.githubusercontent.com/49735284/60774168-ed3a2600-a0d5-11e9-8c59-2b5dc6bb733c.png)

![image](https://user-images.githubusercontent.com/49735284/60774171-f88d5180-a0d5-11e9-9210-5b07c9a14ae4.png)

**Comment by andreakarasho** [comment]
gumpid?

**Comment by Djeryv** [comment]
This particular one is 0x13B1 in my client files.

**Comment by SaschaKP** [comment]
the gump id is non present in original client, I defaulted to the requested graphic, but without any particular sound. (tests done in original client showed me that this is the normal behaviour).

I've made it so that, as in original client, requested graphic will be shown.

**Comment by Djeryv** [comment]
So does this mean that my proper gump will appear (the actual one I set for that container)? But there is no sound?

If that is the case...I do know about the sound issue and I have that scripted in my Container.cs file to play a sound based on GumpID so that isn't a big deal at all.

**Comment by SaschaKP** [comment]
unless you can specify if it's a standard one or not it's hard to tell what can be done, I've searched in gumps.mul the gumpid, but it's not present in standard files, so it's custom and by examining the original client I mimic it's functionality.
![image](https://user-images.githubusercontent.com/15030741/63640316-f6d81700-c69e-11e9-8fa9-c003c6ef62b0.png)

if the image and sound is specified and you see other missing gumps, tell me and I will try to find the correct match (sorry if I misunderstood on first read)

**Comment by Djeryv** [comment]
Actually...I just want the right gump to open. I don't care about the sound. So if the gump is the correct one I set for the Container.cs in RunUO...then I say you fixed it. The sound...like you mentioned...is a client limitation that I already have a workaround for.

**Comment by SaschaKP** [comment]
it's fixed, test in latest dev build, if server sends that particular gump graphic, it will be added to the valid ones (as in original client, I suppose).

**Comment by Djeryv** [comment]
Cool. I would have to compile to try it but thanks again.
