### ISSUE TITLE
Drag-select doesnt work at different zoom levels

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#565]
Drag select doesnt work if you deviate from 100% zoom levels.

**Comment by zolter** [comment]
What do you mean?
Please make screenshot

**Comment by BlackTeaOutlands** [comment]
Hard to take a screen shot, but if I zoom out or in (deviate from 100%) a little bit, then the drag to select will no longer open the bars.

I actually dont know if it was recently changed or not, but trying it right now I return to 100% zoom level if I try to drag-select. And returning to 100% means that it works again. That's not how it worked a few days ago.

This is the option I'm talking about unless it wasn't clear already 
![image](https://user-images.githubusercontent.com/39037141/61163078-4659ed80-a50c-11e9-88ec-cce11625ad7f.png)

**Comment by andreakarasho** [comment]
should be fixed
