### ISSUE TITLE
Drag select is not accurate enough

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#566]
Drag select is not properly accurate. The point of selection is around the targets feet. The desired selection area would be the targets graphic including the name bar if you have it open with ctrl-shift.

https://cdn.discordapp.com/attachments/531214935804608515/598288656738025474/unknown.png

**Comment by andreakarasho** [comment]
now the drag select takes all mobiles that intersects their boundingbox with the selection.

Name bar not included because it is a different behaviour from the scope of that feature
