### ISSUE TITLE
Add ability to change the terrain rendering lightning options

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#570]
Terrain is rendered differently in CUO. I believe it is set way too high in the brightness level, making certain areas overexposed and others too dark shadows. Would be good to add a slider to be able to adjust the brightness levels (this is not the same thing as light levels). I believe Jaedan was working with this in his old Orion version, maybe he knows more about it (the slider existed in that version).

In the image, left = regular UO, right = CUO.

https://cdn.discordapp.com/attachments/458277173208547353/598306621617340472/unknown.png

**Comment by andreakarasho** [comment]
default: https://cdn.discordapp.com/attachments/458277173208547353/599524961576550402/unknown.png
50%:
https://cdn.discordapp.com/attachments/458277173208547353/599525075472875520/unknown.png
100%
https://cdn.discordapp.com/attachments/458277173208547353/599525199867805696/unknown.png

**Comment by BlackTeaOutlands** [comment]
I don't think this one emulated the regular client. The highlights are still overexposed and the shadows look different. I dont know if that's because it's not possible, or because the fix implementation is wrong.

I would not include this feature as it is now, because it does not make the game look better.
