### ISSUE TITLE
Can't select text in floating gumps

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#571]
Can't select text in certain gumps (in this case related to faction system). The graphics (hourglass in the image below) can be selected however. Selected = means you can move the gump.

https://cdn.discordapp.com/attachments/531214935804608515/598325488280403978/unknown.png

**Comment by andreakarasho** [comment]
Note to myself: check if staticpic has CanMove prop to true

**Comment by andreakarasho** [comment]
Unable to replicate . I close it until i’ll receive news

**Comment by BlackTeaOutlands** [comment]
Try it with the town struggle hotbar on Outlands - it's still bugged.

**Comment by andreakarasho** [comment]
can you tell me how to replicate this issue?

**Comment by BlackTeaOutlands** [comment]
If you join a town struggle (previous faction struggle), open the Guild -> Battle -> Town Struggle (Open Menu) -> Launch Faction Hotbar

The faction hotbar has the text that cannot be selected. If it's just a fringe issue, then maybe it doesn't matter.
![image](https://user-images.githubusercontent.com/39037141/69524441-54158a00-0f66-11ea-9dbe-5658e5cf4b2e.png)

**Comment by andreakarasho** [comment]
Due to the big changes during the time i wonder if it still an issue. I close it until i got a feedback
