### ISSUE TITLE
More CTRL-SHIFT options

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#572]
A) CTRL-SHIFT doesn't save the setting between sessions. 

B) Also I'd like more options to control shift such as being able to set your bar size, text color, background color. Why? Its scaled based on name length atm, certain names render very small bars such as pets or players named "xd". Harder to grab. Options should include specific settings for each type of bar, i.e. corpses can be scaled based on name length, but I'd put players at a fixed length and size regardless of name.

C) The little option menu that appears when you hit CTRL-SHIFT needs to be minimizable, or moveable, or move it to the options menu, it's quite annoying especially since it stays always on top. https://cdn.discordapp.com/attachments/533337855439929344/598326442828496896/unknown.png

D) I want an option to freeze bars in place, so with that option toggled, the bars will stay in whichever location they were when you hit CTRL-SHIFT, i.e. they won't move along as players move along. Makes it easier to pull bars, especially if they're small.

**Edit** E) CTRL-SHIFT doesn't show the amount of items in a pile. For example it will not show how much gold is in a gold pile that is on the ground. It should definately show the amount.

**Comment by BlackTeaOutlands** [comment]
Another addition:

F) Want a filter function where you can add items and create a list of stuff that will not be shown in CTRL-SHIFT. So it'll be another option called "Filtered list". This is needed mostly when playing/fighting around houses and your CTRL-SHIFT list overflows and won't show other relevant stuff. It's not enough to just disable items because there are certain items you do want to see on CTRL-SHIFT. So a filter list would be good. Picture below is just an example, if you ever do fighting around this house or drop stuff on the ground you'll never be able to find it with CTRL-SHIFT: 

![image](https://user-images.githubusercontent.com/39037141/61078717-8b552580-a421-11e9-9299-550f1dd7d0ce.png)

**Comment by BlackTeaOutlands** [comment]
A bit mixed stuff in this issue, many enhancements, but I would isolate one as a bug though that should be priority: Namely that it does not show the amount in a pile. Another bug of minor importance is that it shows a erronous letter % in many cases.

**Comment by Djeryv** [comment]
Can the CTRL-SHIFT option also be turned off for hidden items. We shard admins are used to hidden items not showing their names.

**Comment by roxya** [comment]
Most of these have been addressed in one way or another, closing due to age.
