### ISSUE TITLE
Spell Cursor Cancelled when dropping item on the ground

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#577]
A) Cast a spell and hold the spell cursor

B) Pick up an item

C) Try to drop the item on the ground

D) The spell cursor has now been cancelled.

- The desired function is that the cursor is not cancelled by dropping items on the ground while you have a spell up. You are able to drop items in bags, and still keep the spell, it seems that just dropping on the ground is bugged at the moment.

**Comment by andreakarasho** [comment]
fixed
