### ISSUE TITLE
Paperdoll Additional Info Scroll does not show

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#580]
There is usually a scroll here that you can double click to see for example previous aliases and whatever the player has decided to write in his profile. It does not show in ClassicUO when you open the paperdoll of other players. It does show on your own paperdoll however.

![image](https://user-images.githubusercontent.com/39037141/61079255-bdb35280-a422-11e9-9b1d-bce9dea03020.png)

**Comment by andreakarasho** [comment]
fixed
