### ISSUE TITLE
Sound Volume Amplified if Multiple instances play simultaneously

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#581]
Not entirely sure if it's intended or not. But it does cause your ears to get murdered (for no good reason). Sound volume will become amplified if multiple instances of that sound clip are played simultaneously, typical example is closing multiple bags at the same time. Would rather it just play one instance of the sound instead.

**Comment by andreakarasho** [comment]
i fixed the delay between sounds
