### ISSUE TITLE
Count Items in Container (Useful for many things, for example vendors)

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#582]
I suggest adding a new feature called "Count Items". It can be bound to a hotkey and will count items in any container you target (which you have access to obviously), your own player mobile or a vendor. The result will be displayed as a system message with the most numerous items listed first. Also display total number of items as well as (if possible) total weight.

Would be very useful mostly when stocking vendors, but I suppose it can also be used in various other situations, and also add versatility to various macros.

Example in image below:

![image](https://user-images.githubusercontent.com/39037141/61081160-db82b680-a426-11e9-8ecd-693e13ceebd9.png)

**Comment by andreakarasho** [comment]
assistant option i guess
