### ISSUE TITLE
The Text Cursor does not default to the item stack when pulling items from the ground

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#585]
The text cursor does not default to edit the stack size of the item stack when you pull items from the ground. You have to click the item number to edit it. If you pull it straight from your backpack, it does however (correctly) default to the item stack.

Example :
https://imgur.com/CRGp7W4

*Edit* When you have the option of "press enter to chat" enabled, then the text cursor will default to the item stack if you pull from the ground. If you don't, however, see above.

**Comment by andreakarasho** [comment]
shoudl be fixed
