### ISSUE TITLE
Removing robe with double click also removes leather chest

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#586]
Outlands specific. You can double click items to equip/unequip them. Double clicking the robe will also remove the leather chest from your paperdoll view. Equipping robe or re-opening paperdoll will make the leather chest appear again.

https://imgur.com/V1GgWiG

**Comment by andreakarasho** [comment]
News?

**Comment by aclark13** [comment]
Appears to be fixed since I cannot reproduce it.
