### ISSUE TITLE
Wrong color of tiles on the minimap

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#587]
The minimap doesn't register the correct in game hue of certain tiles. In this case the crystal is seen as green on the minimap, where it's white in game. I'm guessing the original hue is green, and CUO doesn't pick up on the modified hue. Probably applies to many other tiles in game (guess).

![image](https://user-images.githubusercontent.com/39037141/61138301-88147500-a4c7-11e9-8b23-f4242efe486f.png)

**Comment by oroechimaru** [comment]
can you post a screenshot of the expected/standard client?

**Comment by BlackTeaOutlands** [comment]
Regular:
![image](https://user-images.githubusercontent.com/39037141/61139064-e726b980-a4c8-11e9-8dd7-a5e54d974285.png)

CUO:
![image](https://user-images.githubusercontent.com/39037141/61139106-fa398980-a4c8-11e9-86da-3f050396c867.png)

**Comment by oroechimaru** [comment]
ahh ok! i always wondered why it was green

**Comment by Djeryv** [comment]
I already posted this bug and that one is still open.

**Comment by Djeryv** [comment]
https://github.com/andreakarasho/ClassicUO/issues/427

**Comment by andreakarasho** [comment]
Already reported: https://github.com/andreakarasho/ClassicUO/issues/427

If needed continue to the referenced issue, thanks
