### ISSUE TITLE
Terrain Rendering Issues

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#588]
A few issues regarding rendering of the terrain. In this case apparent in many places in Cavernam dungeon:

A) There is a black terrain tile that for some rason doesnt seem to be rendered/becomes invisible a few tiles out from the wall. I checked in CentrED and it does seem to be a terrain tile & not a static layered on top. The tile in question is the one in the image there.
![image](https://user-images.githubusercontent.com/39037141/61142168-6919e100-a4cf-11e9-941e-1a1abb640f44.png)

B) Cave entrance tiles which should be invisible is rendered as visible in CUO. See the image below. The black tiles at the cave entrance should be invisible, but they are rendered.
![image](https://user-images.githubusercontent.com/39037141/61142255-9bc3d980-a4cf-11e9-935d-1ca5e7cb59d1.png)

**Comment by andreakarasho** [comment]
can you give me the coordinates ? 
I'll test locally

**Comment by BlackTeaOutlands** [comment]
6034, 822

6022, 650

**Comment by BlackTeaOutlands** [comment]
There are still a lot of terrain rendering issues. It's one of the most immediately apparent buggy things about CUO right now.

**Comment by Alias-Alan** [comment]
if you use -info, or maybe code it so it could be a hotkey and screenshot when you use it on those tiles can help extradite fixing these... I think a pr was put in for this exact type of issue

**Comment by BlackTeaOutlands** [comment]
Still a lot of issues with terrain rendering. Do you need more information? Ask me. Otherwise you will see it easily on Outlands.

![image](https://user-images.githubusercontent.com/39037141/68767921-daa2a100-0621-11ea-8ad0-e839db65b44b.png)

**Comment by oroechimaru** [comment]
@BlackTeaOutlands  hi tea, which dev build # are you on? I know a while back there were several layering tile issues to be squashed yet. Please post -info in the screenshot it may help... otherwise it could be related to zaxis layering


If you turn on debug from the grey menu bar it will show coordinates which you could include next to -info in screenshot and of the title issue :)

**Comment by BlackTeaOutlands** [comment]
I'm on 0.1.2.772. I can't collect information about everything, I think the screenshots show the issue. If you start looking into it, you will probably be able to find the information to solve the issue, otherwise if there is any specific information I can maybe get it.

**Comment by oroechimaru** [comment]
I hear ya, I am not a dev just providing the common feedback that can help. Screenshots look similar to collision/tile issues I have observed by those demons .


Karasho doesnt get much time to play/explore so I try to encourage folks to provide as much detail possible. He can reach out if anything more is needed.

**Comment by andreakarasho** [comment]
https://github.com/andreakarasho/ClassicUO/issues/593

**Comment by K4T** [comment]
There are more rendering issues (at least on Outlands). Please, check following screenshot:

![roof-render-bug](https://user-images.githubusercontent.com/379159/71644137-f0e4e900-2cc3-11ea-9021-fcda0e86b82f.jpg)

COU version: 0.1.2.2

**Comment by keenerb** [comment]
Don't believe that's a bug.  Owyn used the black tiles under some house roofs, you only see them if you check hide house roof option.

**Comment by BlackTeaOutlands** [comment]
Don't have coordinates, it's in Cavernam to the left (level 1).

@keenerb It's probably not a bug per se, but an unintended effect of having the option to remove roof tiles. I'm sure Owyn just wanted some tile there in order to have the inside of the building work properly. You can place many types of tiles, including ones that are not drawn, so I dont know why he selected this one.

**Comment by andreakarasho** [comment]
Pushed a patch.
Waiting for a feedback!

**Comment by andreakarasho** [comment]
If something is wrong i’ll reopen the issue

**Comment by BlackTeaOutlands** [comment]
Still alot of terrain rendering issues. Stuff like this. Do you need more examples? 

1. https://imgur.com/a/1XDHf4q

2. https://imgur.com/a/4HB5owk - see also corpses how they distort the tiles.

**Comment by andreakarasho** [comment]
yes but technically it is a different issue and the latter is well know.
I closed this because mixing stuff is  not the optmial way
