### ISSUE TITLE
Can't pull CTRL-SHIFT bars with cursor up without dropping cursor

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#589]
Not sure if bug or feature request. This is a request to mimic the default handling. Usually you can pull bars from CTRL-SHIFT with a cursor up, and the cursor will not drop to it's target. For example, when casting Greater Heal and then using CTRL-SHIFT to pull a bar, the heal spell should not drop on the player. 

Example in video, I'm trying to pull bars open with the heal spell in cursor, but it drops immediately.

https://imgur.com/a/PB3r2oS

**Comment by roxya** [comment]
The fix was committed two days ago, did you update?

**Comment by BlackTeaOutlands** [comment]
Using version 0.1.2.112

**Comment by roxya** [comment]
Yeah it was fixed in .116, you're behind :)
