### ISSUE TITLE
Can't target certain tiles with field spells

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#591]
I'm unable to target certain tiles with field spells. In particular it's wooden tiles used for bridges. If you want to be proactive about it, there may be more tiles, I obviously have not tried casting field spells on every tile in the game.

Here:
![image](https://user-images.githubusercontent.com/39037141/61163579-18c27380-a50f-11e9-82c0-eaeaf2f86b4c.png)

This ID:
![image](https://user-images.githubusercontent.com/39037141/61163565-07796700-a50f-11e9-94b4-e788968fe2c6.png)

**Comment by owyn-outlands** [comment]
On the edge of this bridge there are invisible no-draw tiles:  0x21A4 
They have background, transparent, impassable and internal flags
This may be due to my map and not ClassicUO 

![bridge](https://user-images.githubusercontent.com/45541111/61167758-211bae00-a511-11e9-96a7-c0e456a582f8.PNG)

**Comment by SaschaKP** [comment]
Are you con current dev preview, please also send -info complete gump here if you are on current.

**Comment by BlackTeaOutlands** [comment]
I can't target other similar tiles which are elsewhere (presumably where there aren't no draw tiles). I am in the current preview.

![image](https://user-images.githubusercontent.com/39037141/61170258-e2184780-a566-11e9-83f7-a0b5f36ac126.png)

![image](https://user-images.githubusercontent.com/39037141/61170261-e6dcfb80-a566-11e9-9cce-25aced6ed9c8.png)

**Comment by andreakarasho** [comment]
fixed
