### ISSUE TITLE
Annoying issue: Bag is grabbed when cursor is in hand

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#592]
This is just an annoying issue I found, it is possible to get used to it, but I do not believe it adds any real value to the game.

When you have an item in your cursor, you are able to grab bags and move them around. When you release cursor, the item drops to the bag. In the regular client, you can't grab bags when you have item in cursor, i.e. even if you left-click and hold on a bag, it will not select the bag and move it, it will drop the item first always and you have to click again to move the bag.

The fact that you can select the bag with item in cursor means that you often by accident select the bag and move it around while you are dropping stuff into your backpack or other containers.

Video example below:
https://imgur.com/CaXisza

**Comment by andreakarasho** [comment]
fixed in dev
