### ISSUE TITLE
Gate layered wrong when leaving and re-entering update range

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#593]
Minor issue, but:

If you cast a gate, then leave and re-enter within update range, the gate will be be displayed layered wrong in this case in respect to fishing nets on the ground: 

![image](https://user-images.githubusercontent.com/39037141/61170762-6fab6580-a56e-11e9-9fca-bc8f330c0402.png)

Initially when you cast it, it is layered correctly (above the nets).

**Comment by andreakarasho** [comment]
Continue the issue here https://github.com/andreakarasho/ClassicUO/issues/588
