### ISSUE TITLE
Double clicking your mount is not recognized as Last Object

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#595]
Double clicking your mount is not stored as your Last Object when using the in game macro to access that function.

**Comment by andreakarasho** [comment]
should be fixed

**Comment by BlackTeaOutlands** [comment]
Doesn't work for me, using latest dev version.

**Comment by andreakarasho** [comment]
If you are unmounted and dclick the mount it is a mobile.
LastObject is referred to item type.

How does it work on regular client?

**Comment by BlackTeaOutlands** [comment]
Hm you are right, it works the same as on regular client!
