### ISSUE TITLE
Not possible to "mount" boats and seal it using the mouse. 

### ISSUE THREAD

**Issue by Pumpk1ns** [ClassicUO/ClassicUO#597]
**Describe the bug**
UO has a "new" feature that allows the player to "mount" a boat or galleon by double clicking the steering wheel, by doing it the player will equip a boat piece in the layer 25 and will be able to move the boat/galleon holding the right mouse button like riding a horse.

But when you try to "mount" the boat in CUO, you end mounting a horse instead. 

**To Reproduce**
1. Go to a shard that allows you to move a boat/galleon in the new way.
2. Place a boat or galleon and double click the steering wheel.
3. In the original client you will start moving the boat, on cuo you will ride a horse.

**Expected behavior**

**Screenshots**
Original Client:
![boat original client](https://user-images.githubusercontent.com/46279173/61168311-8640c500-a54c-11e9-9f4f-43cb0b1ea565.gif)

CUO:
![boat CUO](https://user-images.githubusercontent.com/46279173/61168313-8ccf3c80-a54c-11e9-85a4-e9c0b85ccdcd.gif)

 - OS: Win 10
 - Original UO Version - 7.0.76.4
 - ClassicUO Version - 0.1.2.0

**Comment by andreakarasho** [comment]
done.
