### ISSUE TITLE
Dropping items on your own CTRL-SHIFT bar requires you to click one more time

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#599]
Ok so this is a feature request/bug report. CTRL-SHIFT doesnt quite work as in the regular client.

In the regular client you can left click an item and hold and release on a CTRL-SHIFT bar (your player, or a container) and it will drop the item into that container.

With CUO you left click an item and hold and release on a CTRL-SHIFT bar and it will not drop the item. To drop the item you have to click the CTRL-SHIFT bar again. This doesn't match the original client and also removes some functionality, since it is often very handy to be able to easily drag and release to drop into a container using the CTRL-SHIFT bar.

This situation is what I'm talking about:
https://imgur.com/qWXNOKT

**Comment by andreakarasho** [comment]
fixed
