### ISSUE TITLE
Special Effects are rendered with some amount of transparency

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#601]
Not sure if this is a bug or feature request.

Alot of special effects, such as the explosion from opening a trapped pouch, and I have also noticed other effects such as the flame strike animation when it is used as a part of certain monster abilities (not the player casted one), are rendered using some amount of transparency. That's not the way it was intended to look.

Example here, opening a trapped pouch in CUO:
https://imgur.com/Fk7UbT2

And in regular UO:
https://imgur.com/4C0pgeI

**Comment by andreakarasho** [comment]
Added yesterday, it needs some enchantmen honestly, but it is not an issue :)

**Comment by BlackTeaOutlands** [comment]
Got it, I would say its a nifty feature to have, but does not neccesarilly look better. So it is important that it is only applied to the effects which the creator of the effect intended them to be applied to. Maybe it can be adjusted on the server end then, if for example they don't want transparent pouch explosions on Outlands?
