### ISSUE TITLE
When mobiles first appear on screen their health bar is briefly displayed as zero health

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#602]
When mobiles appear on screen for the first time, their health bar briefly displays it as if they had zero health until it updates to their real amount of health. Example below, where this antlion appears from burrow you see his health bar flicker from zero to his real amount of health:

https://imgur.com/qJUG1hc

**Comment by andreakarasho** [comment]
this is not a real bug.
It depens by FPS. Standar client runs at 10 FPS so the frame time update is really low, infact the network slice runs multiple times between 2 frames.
10 FPS:   [update game] -> [update network] -> [update network] -> [update network] -> [update game]
144 FPS: [update game] -> [update network] -> [update game]-> [update network]
