### ISSUE TITLE
Show HP as Line to be colored according to the notoriety

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#603]
I am using Show HP as both Line & Percentage, and the Line always shows as grey.

It would be nice if the border around the Lines were hued according to the notoriety of the monster. I.e. myself & my pets = green, monster = grey, murderer = red.
![image](https://user-images.githubusercontent.com/39037141/61183392-00eb0c80-a641-11e9-98f6-6e47a3f9a772.png)

- Side note: Be aware that you also get a Line from Razor on your current target, which will be hued according to notoriety, and which is layered ontop of the Line provided from CUO. Razor Line looks like this:
![image](https://user-images.githubusercontent.com/39037141/61183407-37c12280-a641-11e9-9154-c36d50ff1254.png)

**Comment by Alias-Alan** [comment]
I think the issue with this is a red bar would never show dmg dealt, I'll play around with colors and see

**Comment by andreakarasho** [comment]
pushed 
![image](https://user-images.githubusercontent.com/20810422/79698480-79928f80-8289-11ea-944c-fb82a90516e4.png)
