### ISSUE TITLE
Gump - Status

### ISSUE THREAD

**Issue by 3HMonkey** [ClassicUO/ClassicUO#61]
**Describe the solution you'd like**
Status Gump needs to be included.

**Comment by 3HMonkey** [comment]
Max resists need to be added to the gump.

**Comment by 3HMonkey** [comment]
Done so far, but I leave this open for enhancements and bugs.

**Comment by 3HMonkey** [comment]
Added max resists today. So just lock arrows are left.

**Comment by andreakarasho** [comment]
Done
