### ISSUE TITLE
Sallos EasyGrab possibly not entirely accurate

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#610]
Using Sallos EasyGrab, you can move your cursor around in a small area for a while before it will actually grab the item. You can possibly grab something other than what you actually clicked on.

In the video below I am clicking every time I start moving the cursor in small circles, you can see even though I hold down left click it won't grab it until I move in a large enough area.

https://imgur.com/H2MiRo8

**Comment by andreakarasho** [comment]
As i answered in discord:
there is a little offset (5px) to allow user to grab stuff in the screen according to the standard client.
