### ISSUE TITLE
Party chat not working when offscreen.

### ISSUE THREAD

**Issue by Nic84** [ClassicUO/ClassicUO#613]
When you type /hello while in party, other party member should read you even if you are far away from his location.

This does not happen on CassicUO. Your party member cannot read you if he is using ClassicUO and ie. 20 tiles away from you.

- Shard: UOR
- Client Version: 5.0.8.3

- ClassicUO: 0.1.2.183
- Razor: v1.6.1.10

**To Reproduce**
1. /add a member to your party that is using ClassicUO
2. Ask him to talk to you by party like "/hello friend" + enter
3. Move away from your friend, ie. 20 tiles away.
4. And send him messages via party chat, he won't read you.

**Comment by andreakarasho** [comment]
fixed

**Comment by BlackTeaOutlands** [comment]
Could this be related? You are not sent messages in party chat when your party members die (this one happened off screen).

**Comment by andreakarasho** [comment]
@BlackTeaOutlands are you running the latest cuo version?
