### ISSUE TITLE
Paperdoll doesn't update properly when using Toggle/Dress/Undress in Razor

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#615]
Paperdoll doesn't seem to update properly when you use Toggle/Dress/Undress in Razor. Doesn't seem to be related to how fast you spam the command. Usually you end up with nothing showing in your paperdoll, but sometimes the weapon will show in your paperdoll but you don't actually have it equipped.

https://imgur.com/88MuK0l

**Comment by oroechimaru** [comment]
same here... heater shield and mace sometimes disappear from paperdoll and backpack but still equip/unequip and show in game

**Comment by binff04** [comment]
I want to confirm this issue. Happens when I use my potions macro that basically un-equips what my char has in the left hand, does couple of checks and then drinks the potion and re-equips what the char had. After playing this macro the re-equipped weapon does not show in paperdoll.

**Comment by binff04** [comment]
Quick follow-up: closing and opening the paperdoll fixes the disappeared weapon until the next time I run the macro.

**Comment by andreakarasho** [comment]
shuold be fixed
