### ISSUE TITLE
Hold TAB key for combat does not function properly

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#616]
The Hold TAB key for combat does not function properly. In CUO, when you hold tab it will toggle the war mode while holding it, and then toggle it back when you release it. This means that if you were initially in war mode, when you hold TAB it will toggle you to peace mode, and when you release it, it will toggle you back to warmode. 

The normal function of this setting would be to toggle you to warmode regardles of your initial state (i.e. you should never be toggled to peace mode while you hold TAB with this option enabled), and toggle you to peace mode when you release the button, regardless of your initial state. That way you can quickly tap it to return to peace mode.

![image](https://user-images.githubusercontent.com/39037141/61548547-3c754480-aa4e-11e9-9b47-62eeb65e285e.png)

![image](https://user-images.githubusercontent.com/39037141/61548816-d63cf180-aa4e-11e9-80f4-4e1b0c178739.png)

**Comment by andreakarasho** [comment]
fixed
