### ISSUE TITLE
Party Bars not Displaying the Full Name

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#617]
Party bars don't always display the full name, see image below:

![image](https://user-images.githubusercontent.com/39037141/61565328-fda8b400-aa78-11e9-96ac-effdb3cf9386.png)

**Comment by BlackTeaOutlands** [comment]
Also if you pull up your own health bar while in a party, you sometimes get the non-party version: 
![image](https://user-images.githubusercontent.com/39037141/61565640-fd5ce880-aa79-11e9-87da-edb210045596.png)

**Comment by andreakarasho** [comment]
Names: fixed
Im not able to reproduce the 2nd bug

**Comment by BlackTeaOutlands** [comment]
I'll see if I can reproduce it. Happened a few times after dying in Faction Struggles.

**Comment by andreakarasho** [comment]
i'll reopen it if the second one will appear once again

**Comment by BlackTeaOutlands** [comment]
2nd one is same issue as reported in #636
