### ISSUE TITLE
tile/demon overlap 1.2.217

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#618]
![2019-07-20 01_42_16-Start](https://user-images.githubusercontent.com/26830362/61575476-e924e580-aa91-11e9-9723-e635d535d91a.png)
![2019-07-20 01_42_04-](https://user-images.githubusercontent.com/26830362/61575477-e924e580-aa91-11e9-873b-7677b6b0bd49.png)
![2019-07-20 01_42_29-Start](https://user-images.githubusercontent.com/26830362/61575478-e924e580-aa91-11e9-8384-1c35c65d2932.png)

**Comment by andreakarasho** [comment]
yeah we know it's related to the algorithm. @SaschaKP is working on it

**Comment by oroechimaru** [comment]
ok cool feel free to close thanks man! it may be also be due to wide screen... tiles are about 1600x1600 (18x18)... so this may be more messy torwards the edges but it may be in range too. i was getting my arse kicked while screenshotting lol

**Comment by andreakarasho** [comment]
fixed in dev
