### ISSUE TITLE
two related issues: CUO bandage self vs Auto queue object delay in razor" with shield equipped

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#619]
a. if "Auto queue object delay in razor" is checked then you get green text prompts when using CUO bandage self macro. however it will auto equip the shield and let you use potions in the CUO display counter bar. 

b.  if you uncheck this box, then you cannot use potions in the CUO display counter bar (must unequipped shield first message... if unequipped then it works)

c. goal:
- no green messages about queueing
- potions drink 

**Additional context**
![image](https://user-images.githubusercontent.com/26830362/61580836-ce775e80-aadb-11e9-9283-38a433cced2b.png)

**Comment by andreakarasho** [comment]
Assistant related
