### ISSUE TITLE
Inconsistent line formatting and order in item descriptions

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#620]
Item descriptions are formatted differently depending on if the item is in your backpack or on the ground.

In backpack, for crafted items they are ordered wrong with the crafted name first and item name second, and it is also centered.

On ground lines are ordered properly with crafter name last, and text is left adjusted.

Personally I think the centered text looks terrible, and is also not the way the regular client is set up. So if you fix, I would recommend go with left adjusted text overall.

![image](https://user-images.githubusercontent.com/39037141/61585308-7cc0e980-ab58-11e9-936a-f3293092eb97.png)

Same issue in another example, text when you click on it, the newest line appears on top:
![image](https://user-images.githubusercontent.com/39037141/61673030-34d3cb00-acee-11e9-8fcc-374b6757d47b.png)

**Comment by andreakarasho** [comment]
fixed
