### ISSUE TITLE
Two Small Quality of Life Requests 

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#621]
1. Is it possible to adjust text position when name plates are toggled on? It currently appears behind the nameplate. Would be nice if it appeared one line up.

![image](https://user-images.githubusercontent.com/39037141/61586613-2d3ee580-ab79-11e9-8477-332adc9a3db4.png)

2. This is a bit more like a bug. If you use CTRL-SHIFT you will often perform a drag-select action as well if you have it toggled on. That is because your hotkey for drag-select will be either ctrl, shift or none at all. So when you're trying to grab a bar from someone's nameplate, you'll often accidentally do a drag select. It would be good if drag-select did not activate unless you specifically Only pressed the hotkey for drag-select. I.e. if hotkey for drag-select is Ctrl-left click, then also pressing shift would disqualify it.

**Comment by andreakarasho** [comment]
1- done
2- done
