### ISSUE TITLE
Allow aura colour to be set for party members

### ISSUE THREAD

**Issue by wuffa** [ClassicUO/ClassicUO#623]
Would like a new option with a tick box and a colour picker, to be able to override the aura colour for everyone you are partied with.

At the moment, if you are playing in a team of people with differing notoriety (some of your mates are red) and the people you are fighting against have some reds, the aura doesn't help you differentiate friend from foe.

It would be extremely useful to have everyone in your party highlighted in this way.

**Comment by aclark13** [comment]
I like this idea, and could see it being very useful.

**Comment by Stallind** [comment]
Working on it

**Comment by Stallind** [comment]
Added & PR sent: https://gyazo.com/16705c5828f9d7d0bd081ee8d15fe82e

**Comment by wuffa** [comment]
This is great! except it seems to have broken all other auras from working.

**Comment by Stallind** [comment]
Pushed a fix, waiting for merge =)
