### ISSUE TITLE
Character proportions comically wrong when seated

### ISSUE THREAD

**Issue by canterberry** [ClassicUO/ClassicUO#625]
**Describe the bug**

When seated, players become comically deformed.
A picture is worth 1,000 words:

![Screenshot from 2019-07-22 20-30-19](https://user-images.githubusercontent.com/4053794/61680812-cd068b80-acbf-11e9-9c49-4239ba39065b.png)

For comparison, here's the same character, naked, seated in a wooden chair facing South:

![Screenshot from 2019-07-22 20-33-52](https://user-images.githubusercontent.com/4053794/61680897-1f47ac80-acc0-11e9-8b56-caa4b444436f.png)

**To Reproduce**
1. Sit in a chair facing South.

**Expected behavior**

Here's the same poses in the OSI client:

![Screenshot from 2019-07-22 20-39-03](https://user-images.githubusercontent.com/4053794/61681073-c9273900-acc0-11e9-8461-1ec1a555a777.png)

![Screenshot from 2019-07-22 20-37-27](https://user-images.githubusercontent.com/4053794/61681010-9bda8b00-acc0-11e9-8597-711933e3f033.png)

**Comment by andreakarasho** [comment]
Cuo version?

**Comment by canterberry** [comment]
Latest stable build -- about to see if I can confirm against latest dev build.

**Comment by andreakarasho** [comment]
fixed in dev
