### ISSUE TITLE
Missing Left-Click Item Pickup Functionality

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#627]
In the regular client, you will pick an item up if you left click and hold on that spot for about 2-3 seconds. This functionality is missing in CUO. In CUO you have to move the cursor a bit to pick an item up. It is significantly harder to grab items in CUO in some situations for that reason.

Example of how it works in regular client (you can't see the actual click, but I left click and just hold):
https://imgur.com/Et3tKBp

Example in CUO why it is bad (static image), I cannot pick this sulphur ash up because I have to move the cursor in some direction. To have a chance to grab it, I have to guess my way to it by aiming outside of the sulphur ash graphic and swinging across it:

![image](https://user-images.githubusercontent.com/39037141/61687929-e04b4280-ad23-11e9-8e1c-02dd6f5642ea.png)

**Comment by andreakarasho** [comment]
done
