### ISSUE TITLE
Spells can be targeted on invalid targets such as the ground

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#628]
In CUO you are able to target invalid targets such as the ground with spells such as Greater Heal or Energy Bolt. In the regular client, this is not possible, and you can only target the ground with spells where it is a valid target such as Teleport.

It is good to fix this, because if you can target the ground with any spell, it leads to inadvertedly wasting your spells in many situations where you are trying to pull people's health bars (in a faction fight, for example), and by mistake click the ground instead.

The only spells that should be able to target the ground are the ones where it is a purposeful target (teleport, walls).

**Comment by andreakarasho** [comment]
fixed

**Comment by andreakarasho** [comment]
fixed.. again
