### ISSUE TITLE
left clicking the ground consumes target cursor

### ISSUE THREAD

**Issue by PaxRomain** [ClassicUO/ClassicUO#629]
left clicking the ground consumes a target cursor in ClassicUO, whether its a spell, skill, bandage, etc. In the regular client, left clicking the ground/environment should only consume the cursor if it is a field or teleport spell. Otherwise, only clicking an object/mobile should consume the target.

**Comment by oroechimaru** [comment]
this is a dupe of 628. some skills need to target the ground on various servers (bard and taste id for example on uoo)

**Comment by andreakarasho** [comment]
dupe: https://github.com/andreakarasho/ClassicUO/issues/628
