### ISSUE TITLE
Gump - Top Bar Menu

### ISSUE THREAD

**Issue by 3HMonkey** [ClassicUO/ClassicUO#63]
**Describe the solution you'd like**
Top bar Menu needs to be included.

**Comment by 3HMonkey** [comment]
Done so far. Btw buttons need to be set to functions. I will provide more information later on what is to do here.

**Comment by 3HMonkey** [comment]
Done so far, but I leave this open for enhancements and bugs.

**Comment by andreakarasho** [comment]
Done
