### ISSUE TITLE
Journal Time Toggle

### ISSUE THREAD

**Issue by matsamilla** [ClassicUO/ClassicUO#632]
**Is your feature request related to a problem? Please describe.**
No, journal working as intended

**Describe the solution you'd like**
Can we have an option to toggle journal time on/off in the journal gump? I like the feature, but think it should be togglable. 

**Describe alternatives you've considered**
Toggle option for journal time log in-game gump in options, or on gump itself.

**Comment by andreakarasho** [comment]
Reason?

**Comment by matsamilla** [comment]
Visual clutter.

**Comment by andreakarasho** [comment]
It's much awful without time imho
