### ISSUE TITLE
Character "jumps for joy" when casting a spell

### ISSUE THREAD

**Issue by canterberry** [ClassicUO/ClassicUO#635]
**Describe the bug**

Similar to #625. In the latest stable build of ClassicUO, when casting a spell (facing any direction), an unmounted standing character enters an animation state that looks very much like the character is "jumping for joy", pumping a fist in the air.

![Screenshot from 2019-07-23 15-52-48](https://user-images.githubusercontent.com/4053794/61752911-64bcb600-ad62-11e9-94f0-53e6068b9c18.png)

![Screenshot from 2019-07-23 15-52-52](https://user-images.githubusercontent.com/4053794/61752913-64bcb600-ad62-11e9-8233-719c56ba1472.png)

(it's hard to communicate this effectively with a still image, but at least it's very easy to repro)

While this makes for an amusing visual, it is nonetheless incorrect.

**To Reproduce**

1. Cast any spell as an unmounted, unseated character facing any direction.

Observe the character performing a "leaping" animation while casting the spell.

**Expected behavior**

The character performs a spellcasting animation.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Version: 0.0.1.11

**Comment by andreakarasho** [comment]
should be solved in dev
