### ISSUE TITLE
Your own Party bar sometimes bugs out

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#636]
I noticed your own party bar sometimes bugs out. It looks like it gets duplicated so there are more than one layered. If you remove it, and pull up a new bar, the new bar you get looks like a non-party bar.

I caught this happening, and it happened exactly as a player was removed from the party. So might want to check the code in relation to that, if it does something buggy with your own health bar:

![image](https://user-images.githubusercontent.com/39037141/61840928-270b7a80-ae93-11e9-9f59-cc14295beb6b.png)

**Comment by andreakarasho** [comment]
news?

**Comment by andreakarasho** [comment]
fixed
