### ISSUE TITLE
Can't double click on someone's HP Percentage to bring up their paperdoll/attack

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#638]
Ordinarily you can double click on someone's health percentage, as seen in the image below, to perform the same type of action as if you'd double click on the player/mobile. You can't do that here. It is useful in many cases to be able to do that, without having to press all names, just in casual play. I can also remember some fringe scenarios where there were bosses spawned with a lot of people, and the only way to be able to see/target the boss was to click on it's health Percentage.

![image](https://user-images.githubusercontent.com/39037141/61843755-342d6700-ae9d-11e9-9de1-e90265b0dd01.png)

**Comment by SaschaKP** [comment]
this is currently fixed in current DEV-CUO
