### ISSUE TITLE
Gump - Skill 

### ISSUE THREAD

**Issue by 3HMonkey** [ClassicUO/ClassicUO#64]
**Describe the solution you'd like**
Skill Gump needs to be implemented. First skill gump will be (one of two different) an advanced one with some additional features.

**Comment by 3HMonkey** [comment]
There are some known bugs inside. I gonna fix these before deploying the alpha version.

**Comment by 3HMonkey** [comment]
Done so far, but I leave this open for enhancements and bugs.

**Comment by andreakarasho** [comment]
@3HMonkey 
my Dev branch contains an optimized SkillGump.
Missing 2 stuffs:
1. i removed the lines drawed directly. Please use the new Line control instead.
2. missing the button near an "usable" skill. 
   2.1. missign the shortcut gump draggable from an usable skill.

**Comment by 3HMonkey** [comment]
Doing that now.

**Comment by 3HMonkey** [comment]
Done
