### ISSUE TITLE
Hovering over speech text does not turn it yellow (does not highlight it)

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#640]
Placing your mouse cursor over speech text will turn it yellow (highlight it) in the regular client. That does not happen in CUO. This is useful if someone is using a hard to read color, for example.

![image](https://user-images.githubusercontent.com/39037141/61907308-81591980-af2d-11e9-9a34-38093f2cb08f.png)

**Comment by andreakarasho** [comment]
it should work, do you know the hue value and the font?

**Comment by BlackTeaOutlands** [comment]
It works with the white text, but not with this one and not with a guy who had really dark blue. Sorry I can't get the hue value, it doesn't show anywhere.

![image](https://user-images.githubusercontent.com/39037141/61912466-81134b00-af3a-11e9-9d59-68478b59b6f3.png)

Maybe certain hues (more than the one in the screenshot) will disable it.

**Comment by andreakarasho** [comment]
Take a ss of the selector color menu with that hue selected

**Comment by andreakarasho** [comment]
fixed
