### ISSUE TITLE
Issues targeting with cannons on Outlands

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#642]
On a ship, you cannot target the ground with your cannons - usually you can target the sea and fire into just a land tile. But you cannot do that on CUO.

![image](https://user-images.githubusercontent.com/39037141/61921542-ca28c680-af5d-11e9-8c30-ca437e2e2559.png)

**Comment by owyn-outlands** [comment]
There is ground targeting issue in general in CUO.

**Comment by jinh86** [comment]
Yes I noticed as well today, with one of the latest updates. It starts ok, then after a while some tiles (in our server TileID 5 for example) becomes unclickable. If I restart CUO it becomes clickable again for a while, then it breaks again.

**Comment by SaschaKP** [comment]
yes, confirmed bug, there are problems in targeting ground or land in general, sometime

**Comment by andreakarasho** [comment]
Should be fixed here https://github.com/andreakarasho/ClassicUO/commit/fccad486f226cea186dc4fc5463a6b8649a66f14

**Comment by SaschaKP** [comment]
fixed with: https://github.com/andreakarasho/ClassicUO/commit/2cb194a2972199469c3994e3963fbbbe31fc712b
