### ISSUE TITLE
dark mode journal: difficult to see grey fonts

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#648]
Nalco from UO Outlands reported grey notoriety flagged names/talking was difficult to read.

The workaround was to use type #4 font override. 

Possibly change grat shades to another color or add a font outline. I do not have a screenshot.

**Comment by andreakarasho** [comment]
That's why the option has been added to the gumo directly.
With dark hues you will ever have difficulty to see gray strings.
Switch dark journal when needed
