### ISSUE TITLE
Virtues Gump (additional)

### ISSUE THREAD

**Issue by LeopoldUOR** [ClassicUO/ClassicUO#653]
Virtue GUMP system was enabled via previous request, however I've noticed 2 issues I'd like to report:
1. On OSI client if you hover the cursor over each virtue, it will display which level the virtue is at (e.g. Knight of Valor, Seeker of Compassion, Follower of Sacrifice).  Using the GUMP menu to check status only gives the progress on the tier you are currently working on, but doesn't indicate which tier you are on.
2. Sometimes when double clicking either the Sacrifice or Valor virtues, I get the message "System: That is too far away". I couldn't figure out exactly how to reproduce it, but if you repeatedly bring up the cursor for either the Sacrifice or Valor virtues, then cancel the cursor, it will eventually happen.

![image](https://user-images.githubusercontent.com/54108706/63025375-af67b480-be6e-11e9-83f0-b3f13f38c99c.png)

**Comment by andreakarasho** [comment]
should be fixed

**Comment by dissident76** [comment]
It doesn't display the level in a virtue for me, only the virtue name (Sacrifice instead of Seeker of Sacrifice)

**Comment by dissident76** [comment]
I just submitted a pull request with a fix for it (it is now showing the virtue level in the tooltip, just no coloured text)
