### ISSUE TITLE
idoc scavenger issue - items still locked when house collapse

### ISSUE THREAD

**Issue by ichiokada** [ClassicUO/ClassicUO#654]
when idoc house falls, items dropped on ground doesn't refresh to see as unlocked objects
this issue makes scavenger not working for idoc players

on the other hand, steam users can easily scavenge items when house collapse.

please take a look thanks :)

**Comment by andreakarasho** [comment]
In theory server should send all items info when they drop down, so they should be refreshed with the new properties. Am I missing anything?

**Comment by andreakarasho** [comment]
No news. Closed
