### ISSUE TITLE
cannot customize vendor clothing via paperdoll 

### ISSUE THREAD

**Issue by ichiokada** [ClassicUO/ClassicUO#657]
since few updates ago, i no longer can customize vendors clothing, cannot take clothing off etc.

thanks.

**Comment by SaschaKP** [comment]
can't seem to reproduce it locally, I'll need some more information:

Shard (address port and eventually a test account to try out this bug), eventual download to get the correct files to log-in (or only the client version)

**Comment by SaschaKP** [comment]
non reproducible
