### ISSUE TITLE
Macros to open healthbars for all visible mobiles on screen

### ISSUE THREAD

**Issue by binff04** [ClassicUO/ClassicUO#664]
We already have super convenient feature that allows drag-to-select (draw square) type of selection for healthbars. It's great when you want to select healthbars of mobiles concentrated in one area.

Since all the healthbars, that we open by drag-selecting some area, appear in a grid pattern on the left part of the screen, what if we will have **a macro** that will basically do the same but **for all visible mobiles on screen**?

Already opened healthbars will be skipped and will remain at their places if already dragged from the left as it works now.

Also, there may be some variations of this macro: All Mobiles, Friendly Mobiles, Gray Mobiles, Criminal Mobiles, Murderer Mobiles, Enemy Mobiles, All Mobiles but Friendly, etc...

Sounds like a nice addition to the macro system itself and definitely will bring more value for players who want to avoid unnecessary mouse movements for such things like opening healthbars.

**Comment by Syrupz-UO** [comment]
I am currently working on customized health bars,  I've already completed an organizer for them that places them in columns of ally/innocent | gray/criminal | red/enemy - I will look into options available to pull only certain mobiles instead of all.

**Comment by binff04** [comment]
Filtering can be added at later time. Let's start with the macro for opening healthbars of all visible mobiles.

**Comment by roxya** [comment]
Filtering could be like this

Macro = GrabHealthbarsHuman and GrabHealthbarsMonster
Sub macro = Innocent, Grey, Criminal, Enemy, Murderer. Maybe party as well but it complicates things.

Then anyone could create one macro key which contains as many of these as they want, for a fully custom selection. So if you want all non-friendly humanoids, one macro can do 4 commands:

GrabHealthbarsHuman
___Murderer

GrabHealthbarsHuman
___Criminal

GrabHealthbarsHuman
___Grey

GrabHealthbarsHuman
___Enemy

This way it keeps the macro list a bit clean, and doesn't miss anything. With predefined filters, you will always get someone who wants something different.

**Comment by Alias-Alan** [comment]
Binff04 do you mean a hotkey to grab all bars rather than using the draw function?

**Comment by Stallind** [comment]
I personally feel having a macro to pull all bars would be kind of dodgy.

I believe it was even a cheat feature back in the days on custom PlayUO versions.

**Comment by Alias-Alan** [comment]
It was, was speaking to roxya about that. Was a feature called Pull All Bars and did this, it infringes on the cheatside of things imo.

**Comment by roxya** [comment]
While I wrote how I would do it macro wise to keep it neat, I kinda agree that it's more automation than a lot of people would be comfortable with.

**Comment by Stallind** [comment]
I guess auto-pulling bars with a macro for != humanoids would be fine . However since it's open source it might be bad still, would be very easy to edit out

**Comment by Syrupz-UO** [comment]
but also still easy to replicate into a private build

**Comment by aclark13** [comment]
Not on the road map.

**Comment by Alias-Alan** [comment]
This is in every way fathomable cheaty, there is already drag-select. There doesn't need to be further automation added to this, this would be so widely abused and I verily believe the community at large would agree that this would be a cheat, much like it was considered a cheat plugin in Sallos.
