### ISSUE TITLE
is there a journal log limit exported to CUO folder?

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#677]
I delete the daily timestamp logs every once in a while when i see more than 10. A few suggestions

a. have a journal log subfolder instead of placing in the cuo root folder
b. possibly keep them all if in subfolder, otherwise maybe delete if older then 60 days? 

Super low priority, just something I forgot to submit a while back from feedback. Thanks!!

**Comment by SaschaKP** [comment]
this is something that will be done, it's on the list, I'll see also if there is something else to do, if you have further ideas expose them.

**Comment by aclark13** [comment]
I think a folder is a good place to put them.  How do you handle the limit, is it time based or count based?  I'm thinking count since a new file is made for every session.  How many seem reasonable, 100, 200?

**Comment by SaschaKP** [comment]
currently journal are saved on game folder, with date-time stamped on the filename, 100 files, this can be considered done, current system can be perfected, but it needs minor modifications.
