### ISSUE TITLE
dragging windows/bars unresponsive

### ISSUE THREAD

**Issue by dissident76** [ClassicUO/ClassicUO#682]
When trying to quickly drag bars/windows (i.e. status bars, options window, etc), left clicking and rapidly moving the mouse will not actually get the bar. f you left click and move slowly the first pixels, the cursor then will change to a closed fist and the bar gets dragged.

Can be annoying when trying to quickly drag windows out of the way.

Windows 10
latest dev version (28/Aug/2019)

**Comment by Alias-Alan** [comment]
I've noticed this issue as well and have tried to fix it, even with my custom bars I have a similiar issue when using the anchor Gump feature . I will look into it again tomorrow, maybe I missed something.

**Comment by zolter** [comment]
https://i.imgur.com/ZdKcKTO.gifv

Are you talking about this?

**Comment by Alias-Alan** [comment]
yes zolter

**Comment by roxya** [comment]
I noticed lately that sometimes when you try to move a healthbar, it counts as a single click on the mobile instead of dragging the bar e.g. the single click context menu can appear, especially when you move the mouse quickly. Maybe this is what the OP meant

**Comment by zolter** [comment]
This problem is almost a year old, it was just me who could reproduce it earlier. 
Apparently I have the fastest mouse))

**Comment by roxya** [comment]
![fastclick](https://user-images.githubusercontent.com/7057924/64001639-2dc78600-cb00-11e9-980c-10726669a0e9.gif)

**Comment by dissident76** [comment]
> https://i.imgur.com/ZdKcKTO.gifv
> 
> Are you talking about this?

Exactly that

**Comment by SaschaKP** [comment]
this seems, to me, when you get a black pixel, and that pixel is true black, so It get this as if you where in black area (transparent)

**Comment by roxya** [comment]
![fastclick2](https://user-images.githubusercontent.com/7057924/64039016-85daa880-cb51-11e9-91bc-38362b2f42e5.gif)

I can do it on any control, including those drawn natively by CUO.

![fastclick3](https://user-images.githubusercontent.com/7057924/64039128-db16ba00-cb51-11e9-8f21-fe52625bd936.gif)

**Comment by SaschaKP** [comment]
even on a native you can spot a true "0" pixel, it's in the texture _data, I've done a cross-spot check, I bet we'll have to use it to be absolutely sure that the surrounding area is also true black

**Comment by SaschaKP** [comment]
should be fixed with https://github.com/andreakarasho/ClassicUO/commit/7b0c8ea92a653f1fe2158f5f0783a12353a7a0a6

please test and answer back here, in case of need I'll reopen it.

**Comment by dissident76** [comment]
tested and still the same for me

**Comment by Alias-Alan** [comment]
will thoroughly test but not having issue on items with gameborders at 1x(check map)

**Comment by andreakarasho** [comment]
I have done a fix.
Let me know if the issue persists

**Comment by dissident76** [comment]
Still the same for me

**Comment by dissident76** [comment]
Should be fixed
