### ISSUE TITLE
Mounts Turn to Default Hue When Mounted

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#684]
The bear is hued a brown color but in ClassicUO it turns back to the default white color. It works find in the regular client. I tried a horse with a custom color and it is doing the same thing. Reverting back to a hue of zero when mounted.

![image](https://user-images.githubusercontent.com/49735284/64083174-80f82f00-cce0-11e9-8e55-c6fc82a6d038.png)

**Comment by Djeryv** [comment]
Horses seem immune to this behavior and act as normal, so it just seems like custom mobiles we make for our shards suffer from this hue-mount problem.

**Comment by Djeryv** [comment]
It looks like ostards might be immune to this problem as well. Just to elaborate on the image above, the bear is colored brown but the default body is the polar bear. When I get onto the brown hued bear it turns back to hue zero.

**Comment by andreakarasho** [comment]
fixed
