### ISSUE TITLE
Minor Bug with Virtues, Party system and spellbooks

### ISSUE THREAD

**Issue by Ilikeshrimpalot** [ClassicUO/ClassicUO#685]
**Describe the bug**
Hello there, CUO client version 0.1.2.432 just some minor things on UO:R; still having some trouble with partying (not getting invites when they are sent and no messages about them) and the virtues menu when holding the cursor above a virtue does not display the level you are (i.e. Follower of Valor or Knight of Valor). I have also noticed that when I have one spellbook open and double click another one there is a pause of between 2-3 seconds where the client locks up. Again, these are very minor but just wanted to make y'all aware :slight_smile: thanks for all the great features!
**To Reproduce**
1. Go to '...' Add a character to party either by typing /add then targeting them or by using the scroll in the paper doll to open the party menu. To open virtues double click the star at the top of the paper doll

**Expected behavior**
When invited to a party: be notified of the invite, and then accepted the first time you type /accept
When trying to activate a virtue, once the cursor is held over the virtue is should display your rank in the virtue i.e. follower, knight, etc.

**Screenshots**

![Toto_9-3_13 25-1 (2)](https://user-images.githubusercontent.com/54859398/64195002-6774f580-ce4e-11e9-95b4-ed2a086eb1dc.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 0.1.2.432

**Additional context**

**Comment by oroechimaru** [comment]
cam you try the latest build? you are about 60 commits out of date.

**Comment by Ilikeshrimpalot** [comment]
heh sorry about that, I usually update once a week. 

On the latest builds I am still having these issues with the virtues and some party issues as well.

I.E. when a player would leave the party, I as the leader could not add a new member and the person who left still had their health bar display as a party member. If I log out and back in I am able to re-add people to the party

**Comment by dissident76** [comment]
Virtue tooltips with level fixed.
Party invites seem to work fine, also.
