### ISSUE TITLE
containers in backpack (bags, pouches, etc) not being re-opened on login

### ISSUE THREAD

**Issue by dissident76** [ClassicUO/ClassicUO#686]
I am able to save the desktop layout with a macro, but containers (main backpack/bags/pouches, etc) sometimes will not open (like the queue to open them timed out, my latency is ~350ms), or they will open in the same position (containers will be stacked right on top of each other). If I log out and back in a few times, each time I have one or two fewer bag re-opened until none re-open.

Override container gump location is enabled (last dragged position). If disabled, containers will open anywhere on the screen.

Windows 10

**Comment by andreakarasho** [comment]
done a fix. Lemme know. 
I close it atm

**Comment by dissident76** [comment]
they re-open now, but they do not open in the same position they were when logged off (desktop not fully remembered). Also, backpack/bags need to be closed, otherwise items cannot be dropped in the bags
