### ISSUE TITLE
Water Creatures Below Tiles

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#687]
The beta version shows this squid going underneath the water tiles. These particular tiles are actual item-tiles and not surface-land-tiles.

![image](https://user-images.githubusercontent.com/49735284/64392874-6097df80-d014-11e9-951e-a99c4cc6d807.png)

**Comment by oroechimaru** [comment]
do a -info or -item i forget on the tiles and on the creature unless its related to known issues .

**Comment by andreakarasho** [comment]
It is a known issue about sorting
