### ISSUE TITLE
Some Mounts Invisible When Mounted

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#691]
On the latest build, whenever I mount this creature the mount disappears. The BodyValue of the monster is 272 and the ItemID for the mount is 16070. The ItemID was in my version of the client 7.0.15.1 and it was for a ethereal boura but I am using it as the mount for the actual animal on my server.

![image](https://user-images.githubusercontent.com/49735284/64824432-9a6e6600-d57f-11e9-930e-e3ebcad47d27.png)

**Comment by andreakarasho** [comment]
I need this particular uo installation

**Comment by Djeryv** [comment]
The entire server and client can be obtained here. I designed it if you have further questions.

https://www.servuo.com/archive/ultima-odyssey.1117/

**Comment by andreakarasho** [comment]
on latest dev it works
![image](https://user-images.githubusercontent.com/20810422/64895169-0635f900-d67c-11e9-8994-c8d5cacdcce0.png)
