### ISSUE TITLE
crash when changing sound output device

### ISSUE THREAD

**Issue by dissident76** [ClassicUO/ClassicUO#693]
Windows 10
ClassicUO crashes when switching to another sound device after it has started.

**Comment by oroechimaru** [comment]
what cuo version?

a. update audio drivers
b. update .net and c++

if on outlands look for my performance guide (or google uo outlands performance guide) for links. i cant copy/paste atm

**Comment by dissident76** [comment]
Always using latest dev version.
Drivers are all the latest version available (never had an issue with sound in any other program). No other issues, computer runs like a swiss watch

Thanks for the offer for the troubleshooting guide, I'm sure it's great, but I worked in IT for over 20 years, the first few years redacting troubleshooting guides for users ;)

**Comment by natryl** [comment]
Been an issue for a very long time. Switching audio devices can cause a hard crash.

**Comment by oroechimaru** [comment]
I have helped reduce this issue for a dozen folks or so since May by updating the audio driver if realtek based using a newer version that dell hosts . I still strongly recommend it . 


https://forums.uooutlands.com/index.php?threads/uo-performance-troubleshooting-collection-and-guide-network-ping-lag-choppy-gameplay-etc.1945/

**Comment by dissident76** [comment]
Thanks mate, appreciate your help.

But in my case I don't have a Realtek sound device, and it is already on the latest manufacturer driver

**Comment by andreakarasho** [comment]
Crash log?

**Comment by dissident76** [comment]
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-09-30T21:35:01.633154900Z" /> 
  <EventRecordID>17809</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>HPG6-SSD</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>ClassicUO.exe</Data> 
  <Data>0.1.2.602</Data> 
  <Data>f9e2aea1</Data> 
  <Data>ntdll.dll</Data> 
  <Data>10.0.18362.356</Data> 
  <Data>f24fc044</Data> 
  <Data>c0000374</Data> 
  <Data>00000000000f9269</Data> 
  <Data>3260</Data> 
  <Data>01d577d6def02daa</Data> 
  <Data>C:\Ultima Online\ClassicUO-dev-preview-release\ClassicUO.exe</Data> 
  <Data>C:\Windows\SYSTEM32\ntdll.dll</Data> 
  <Data>56a8d267-e0b7-4d66-8bb4-318d2bc969ad</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by dissident76** [comment]
Version=1
EventType=APPCRASH
EventTime=132143529018359197
ReportType=2
Consent=1
UploadTime=132143529027782142
ReportStatus=268435456
ReportIdentifier=1d60d3b1-229d-4b2b-822d-2c12e1c929ee
IntegratorReportIdentifier=56a8d267-e0b7-4d66-8bb4-318d2bc969ad
Wow64Host=34404
NsAppName=ClassicUO.exe
OriginalFilename=ClassicUO.exe
AppSessionGuid=00003260-0001-0076-aa2d-f0ded677d501
TargetAppId=W:00068953cf9c8b8d94efccae587a849c3f0500000000!0000aa1690f8708a9732219ac01be3655188de90e598!ClassicUO.exe
TargetAppVer=2102//11//07:22:43:45!0!ClassicUO.exe
BootId=4294967295
ServiceSplit=3824415137
TargetAsId=2157
UserImpactVector=808465200
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=78bedd948a78fbd492167b52180568f7
Response.BucketTable=4
Response.LegacyBucketId=1303364734690879735
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=ClassicUO.exe
Sig[1].Name=Application Version
Sig[1].Value=0.1.2.602
Sig[2].Name=Application Timestamp
Sig[2].Value=f9e2aea1
Sig[3].Name=Fault Module Name
Sig[3].Value=StackHash_c15e
Sig[4].Name=Fault Module Version
Sig[4].Value=10.0.18362.356
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=f24fc044
Sig[6].Name=Exception Code
Sig[6].Value=c0000374
Sig[7].Name=Exception Offset
Sig[7].Value=PCH_8C_FROM_ntdll+0x000000000009CC24
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.18362.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=2057
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=c15e
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=c15e49110a621a2a69a5a705f6767c9f
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=fdeb
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=fdeb61828b5a9d35c48f7e446eca75ff
UI[2]=C:\Ultima Online\ClassicUO-dev-preview-release\ClassicUO.exe
LoadedModule[0]=C:\Ultima Online\ClassicUO-dev-preview-release\ClassicUO.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\Windows\System32\KERNEL32.dll
LoadedModule[4]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[5]=C:\Windows\System32\ADVAPI32.dll
LoadedModule[6]=C:\Windows\System32\msvcrt.dll
LoadedModule[7]=C:\Windows\System32\sechost.dll
LoadedModule[8]=C:\Windows\System32\RPCRT4.dll
LoadedModule[9]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[10]=C:\Windows\System32\SHLWAPI.dll
LoadedModule[11]=C:\Windows\System32\combase.dll
LoadedModule[12]=C:\Windows\System32\ucrtbase.dll
LoadedModule[13]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[14]=C:\Windows\System32\GDI32.dll
LoadedModule[15]=C:\Windows\System32\win32u.dll
LoadedModule[16]=C:\Windows\System32\gdi32full.dll
LoadedModule[17]=C:\Windows\System32\msvcp_win.dll
LoadedModule[18]=C:\Windows\System32\USER32.dll
LoadedModule[19]=C:\Windows\System32\IMM32.DLL
LoadedModule[20]=C:\Windows\System32\kernel.appcore.dll
LoadedModule[21]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[22]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
LoadedModule[23]=C:\Windows\SYSTEM32\ucrtbase_clr0400.dll
LoadedModule[24]=C:\Windows\SYSTEM32\VCRUNTIME140_CLR0400.dll
LoadedModule[25]=C:\Windows\System32\psapi.dll
LoadedModule[26]=C:\Windows\assembly\NativeImages_v4.0.30319_64\mscorlib\6be7b71ba8ec1ec519f633ef15aa982f\mscorlib.ni.dll
LoadedModule[27]=C:\Windows\System32\ole32.dll
LoadedModule[28]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
LoadedModule[29]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System\ab7db4bb476e741e1f09a230a3b50d63\System.ni.dll
LoadedModule[30]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Core\a314e918c1d1153fa4c3fd8d696974ae\System.Core.ni.dll
LoadedModule[31]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Configuration\aaa5d956b83ee5a1afc731909cdca249\System.Configuration.ni.dll
LoadedModule[32]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Xml\e2a5ebe21ab9ae2c699393d8bd65171b\System.Xml.ni.dll
LoadedModule[33]=C:\Windows\System32\shell32.dll
LoadedModule[34]=C:\Windows\System32\cfgmgr32.dll
LoadedModule[35]=C:\Windows\System32\shcore.dll
LoadedModule[36]=C:\Windows\System32\windows.storage.dll
LoadedModule[37]=C:\Windows\System32\profapi.dll
LoadedModule[38]=C:\Windows\System32\powrprof.dll
LoadedModule[39]=C:\Windows\System32\UMPDC.dll
LoadedModule[40]=C:\Windows\System32\cryptsp.dll
LoadedModule[41]=C:\Windows\System32\bcrypt.dll
LoadedModule[42]=C:\Windows\system32\rsaenh.dll
LoadedModule[43]=C:\Windows\SYSTEM32\CRYPTBASE.dll
LoadedModule[44]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.IO.Cf61e09c5#\39ea3c69e4847312c92bdcb376f4deff\System.IO.Compression.FileSystem.ni.dll
LoadedModule[45]=C:\Windows\SYSTEM32\rasapi32.dll
LoadedModule[46]=C:\Windows\SYSTEM32\rasman.dll
LoadedModule[47]=C:\Windows\SYSTEM32\rtutils.dll
LoadedModule[48]=C:\Windows\System32\WS2_32.dll
LoadedModule[49]=C:\Windows\system32\mswsock.dll
LoadedModule[50]=C:\Windows\SYSTEM32\winhttp.dll
LoadedModule[51]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[52]=C:\Windows\System32\NSI.dll
LoadedModule[53]=C:\Windows\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[54]=C:\Windows\SYSTEM32\dhcpcsvc.DLL
LoadedModule[55]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[56]=C:\Windows\SYSTEM32\WINNSI.DLL
LoadedModule[57]=C:\Windows\System32\rasadhlp.dll
LoadedModule[58]=C:\Windows\System32\fwpuclnt.dll
LoadedModule[59]=C:\Windows\SYSTEM32\secur32.dll
LoadedModule[60]=C:\Windows\SYSTEM32\SSPICLI.DLL
LoadedModule[61]=C:\Windows\system32\schannel.DLL
LoadedModule[62]=C:\Windows\System32\CRYPT32.dll
LoadedModule[63]=C:\Windows\System32\MSASN1.dll
LoadedModule[64]=C:\Windows\SYSTEM32\mskeyprotect.dll
LoadedModule[65]=C:\Windows\SYSTEM32\ncrypt.dll
LoadedModule[66]=C:\Windows\SYSTEM32\NTASN1.dll
LoadedModule[67]=C:\Windows\system32\ncryptsslp.dll
LoadedModule[68]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Numerics\73167e9f93cebca29482546008c17f30\System.Numerics.ni.dll
LoadedModule[69]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Runteb92aa12#\909e5f207dae45a8bc4f7882be50bd97\System.Runtime.Serialization.ni.dll
LoadedModule[70]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Data\50ebfb2d7a19ca1468e894cfae777e4b\System.Data.ni.dll
LoadedModule[71]=C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
LoadedModule[72]=C:\Ultima Online\ClassicUO-dev-preview-release\libs\x64\SDL2.DLL
LoadedModule[73]=C:\Windows\System32\OLEAUT32.dll
LoadedModule[74]=C:\Windows\System32\SETUPAPI.dll
LoadedModule[75]=C:\Windows\SYSTEM32\WINMM.dll
LoadedModule[76]=C:\Windows\SYSTEM32\WINMMBASE.dll
LoadedModule[77]=C:\Windows\system32\uxtheme.dll
LoadedModule[78]=C:\Windows\System32\clbcatq.dll
LoadedModule[79]=C:\Windows\System32\dinput8.dll
LoadedModule[80]=C:\Windows\SYSTEM32\inputhost.dll
LoadedModule[81]=C:\Windows\SYSTEM32\PROPSYS.dll
LoadedModule[82]=C:\Windows\SYSTEM32\CoreMessaging.dll
LoadedModule[83]=C:\Windows\SYSTEM32\CoreUIComponents.dll
LoadedModule[84]=C:\Windows\SYSTEM32\wintypes.dll
LoadedModule[85]=C:\Windows\SYSTEM32\ntmarta.dll
LoadedModule[86]=C:\Windows\SYSTEM32\HID.DLL
LoadedModule[87]=C:\Windows\SYSTEM32\DEVOBJ.dll
LoadedModule[88]=C:\Windows\System32\WINTRUST.dll
LoadedModule[89]=C:\Windows\SYSTEM32\XInput1_4.dll
LoadedModule[90]=C:\Windows\SYSTEM32\OPENGL32.DLL
LoadedModule[91]=C:\Windows\SYSTEM32\GLU32.dll
LoadedModule[92]=C:\Windows\SYSTEM32\dxcore.dll
LoadedModule[93]=C:\Windows\System32\MSCTF.dll
LoadedModule[94]=C:\Windows\SYSTEM32\ig4icd64.dll
LoadedModule[95]=C:\Ultima Online\ClassicUO-dev-preview-release\libs\x64\mojoshader.DLL
LoadedModule[96]=C:\Windows\SYSTEM32\urlmon.dll
LoadedModule[97]=C:\Windows\SYSTEM32\iertutil.dll
LoadedModule[98]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Drawing\01364013d99075b5243ae18539409c29\System.Drawing.ni.dll
LoadedModule[99]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\e7b22d5345ed54fe506b7cac96f898dd\System.Windows.Forms.ni.dll
LoadedModule[100]=C:\Windows\assembly\NativeImages_v4.0.30319_64\Microsoft.CSharp\542c2ac222d0eaa03f57a8a06d3cbad7\Microsoft.CSharp.ni.dll
LoadedModule[101]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Dynamic\ffe06dedf946b2c9741ad4202d726eec\System.Dynamic.ni.dll
LoadedModule[102]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.356_none_2a28023246698435\comctl32.dll
LoadedModule[103]=C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.18362.356_none_17afa2626da1a19a\gdiplus.dll
LoadedModule[104]=C:\Windows\SYSTEM32\WindowsCodecs.dll
LoadedModule[105]=C:\Windows\System32\TextInputFramework.dll
LoadedModule[106]=C:\Windows\SYSTEM32\DWrite.dll
LoadedModule[107]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.18362.356_none_e6c4af7d130f27cc\comctl32.dll
LoadedModule[108]=C:\Windows\system32\msctfp.dll
LoadedModule[109]=C:\Windows\SYSTEM32\mscms.dll
LoadedModule[110]=C:\Windows\SYSTEM32\USERENV.dll
LoadedModule[111]=C:\Windows\SYSTEM32\ColorAdapterClient.dll
LoadedModule[112]=C:\Windows\SYSTEM32\icm32.dll
LoadedModule[113]=C:\Windows\SYSTEM32\dwmapi.dll
LoadedModule[114]=C:\Windows\SYSTEM32\dxgi.dll
LoadedModule[115]=C:\Windows\SYSTEM32\d3d11.dll
LoadedModule[116]=C:\Windows\SYSTEM32\igd10umd64.dll
LoadedModule[117]=C:\Windows\system32\napinsp.dll
LoadedModule[118]=C:\Windows\system32\pnrpnsp.dll
LoadedModule[119]=C:\Windows\System32\winrnr.dll
LoadedModule[120]=C:\Windows\system32\NLAapi.dll
LoadedModule[121]=C:\Windows\system32\wshbth.dll
LoadedModule[122]=C:\Ultima Online\ClassicUO-dev-preview-release\libs\x64\FAudio.DLL
LoadedModule[123]=C:\Windows\System32\MMDevApi.dll
LoadedModule[124]=C:\Windows\SYSTEM32\avrt.dll
LoadedModule[125]=C:\Windows\SYSTEM32\AUDIOSES.DLL
LoadedModule[126]=C:\Windows\SYSTEM32\resourcepolicyclient.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=18362
OsInfo[3].Key=ubr
OsInfo[3].Value=356
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=2057
OsInfo[7].Key=geoid
OsInfo[7].Value=111
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=125667
OsInfo[15].Key=osinsty
OsInfo[15].Value=2
OsInfo[16].Key=iever
OsInfo[16].Value=11.356.18362.0-11.0.145
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=8139
OsInfo[19].Key=svolsz
OsInfo[19].Value=735
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=190318
OsInfo[22].Key=bldtm
OsInfo[22].Value=1202
OsInfo[23].Key=bldbrch
OsInfo[23].Value=19h1_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.18362.356.amd64fre.19h1_release.190318-1202
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=ClassicUO
AppPath=C:\Ultima Online\ClassicUO-dev-preview-release\ClassicUO.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=B16F3307EBB81F12A8668013BC7F2319
MetadataHash=-1830424130

**Comment by andreakarasho** [comment]
Fixed in dev, but it is a workaround. This issue should be referenced to the FNA owner
