### ISSUE TITLE
Double healthbar

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#697]
A health bar is, for some reason, always displayed when health is below 100% for enemies.
So enabling "Show HP" makes a double health bar display.

Enable "Show HP"
![ClassicUO_2019-09-15_20-07-07](https://user-images.githubusercontent.com/1727541/64925684-c3e3f780-d7f4-11e9-8f77-a4795d1af6fa.png)

Double health bar.
![ClassicUO_2019-09-15_19-59-20](https://user-images.githubusercontent.com/1727541/64925693-eaa22e00-d7f4-11e9-8fe4-154775c2f78c.png)

Playing on UO Outlands.
Windows 10, ClassicUO Beta - 0.1.2.0

**Comment by andreakarasho** [comment]
That’s the target bar, it appears when you target something so this is not a real issue

**Comment by Hezkore** [comment]
I'd still argue it's an issue.
If anything; it should change the healthbar for the current target, not display two on top of each other.
