### ISSUE TITLE
Black text on single click is hard to see

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#698]
Single clicking an item in the world shows a black info text, which is very hard to see again almost any background.

Clicking a 'lantern', and I can barely see the text.
![ClassicUO_2019-09-15_20-00-07](https://user-images.githubusercontent.com/1727541/64925914-9a789b00-d7f7-11e9-9d60-c678021ec01b.png)

Playing on UO Outlands.
Windows 10, ClassicUO Beta - 0.1.2.0

**Comment by andreakarasho** [comment]
That's a negative consequence of the option "Override font"

**Comment by Hezkore** [comment]
Ah, right you are.
A bug nonetheless. :)

**Comment by dissident76** [comment]
Did a quick fix -text shouldn't be black anymore with Unicode. Will eventually do a better fix that includes ASCII as well
