### ISSUE TITLE
Journal shows current time instead of time of event

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#699]
The journal items do not show the time they were posted, they instead show the current time.

Opening the journal after one minuter:
![2019-09-15_20-01-12](https://user-images.githubusercontent.com/1727541/64925945-f93e1480-d7f7-11e9-9ad8-6d4e76992438.gif)

Playing on UO Outlands.
Windows 10, ClassicUO Beta - 0.1.2.0

**Comment by andreakarasho** [comment]
fixed
