### ISSUE TITLE
Auto open door does not always work

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#700]
Doors sometimes only auto open from one side.

Example from the healer cabin at Shelter Island where auto open only works from the inside:
http://hezkore.com/junk/2019-09-15_20-38-42.mp4

Playing on UO Outlands.
Windows 10, ClassicUO Beta - 0.1.2.0

**Comment by Alias-Alan** [comment]
afaik, that issue was reported to Owyn/Luthius back at Launch and they said they would fix it. I'll look at the cuo code with doors but probably something they need to fix as it was an issue with original client/razor,steam and Orion before they stopped supporting that there.

**Comment by oroechimaru** [comment]
I have this issue at mage shop north of uoo prev bank about 3/4 of the time possibly just uoo bug.

**Comment by roxya** [comment]
I'm fairly sure it's a server side issue since auto open doors doesn't click doors, it asks the server to open any nearby door.

**Comment by andreakarasho** [comment]
Depends by server, but this PR might solve the issue (partially)
https://github.com/andreakarasho/ClassicUO/pull/855
