### ISSUE TITLE
Always use fullsize game window resizes after applying settings

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#701]
1. Make sure 'Always use fullsize game window' is enabled.
2. Keep the configuration window open.
3. Click and drag with the mouse in the game world.
4. Hit 'apply' in the configuration window.
5. Repeat from step 3.
(you may need to have the 'Video' menu open)
The game window will keep resizing and end up outside of the actual window.

Enable  'Always use fullsize game window':
![ClassicUO_2019-09-15_21-16-16](https://user-images.githubusercontent.com/1727541/64926466-1b3a9580-d7fe-11e9-9e67-b89a53fac483.png)

Click and drag in the game world and then hit 'apply', repeat:
http://hezkore.com/junk/2019-09-15_21-15-05.mp4

I also believe that correct English would be "full size" not "fullsize".

**Comment by andreakarasho** [comment]
fixed
