### ISSUE TITLE
Typing in configuration always types to the last info bar item

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#703]
When opening the configuration window; the last info bar item is always selected, even if the info bar menu isn't displayed.
That means that anything you type will always end up there.

Example:
http://hezkore.com/junk/2019-09-15_22-13-20.mp4

**Comment by andreakarasho** [comment]
Looks like a textbox focus issue.
I tried and it happens when you still have Options gump open and this is not a right behaviour

**Comment by Hezkore** [comment]
Textboxes should not fetch input if they're not visible on screen.

**Comment by aclark13** [comment]
I actually had this happen last night and found it odd, but wasn't sure exactly what happened.  I changed the circle of transparency radius and turned on part invite gump (both in general tab), and 
 before i could turn on the gump i got an invite.  I tried to type /accept but it didn't work.  I looked at my info bar and noticed /accept in one of the fields.

**Comment by andreakarasho** [comment]
fixed
