### ISSUE TITLE
Macro 'WorldMap' not implemented

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#705]
A 'World Map' exists in the dev build, but trying to open it via a macro results in `|  Warning | Macro 'WorldMap' not implemented`.

![ClassicUO_2019-09-16_10-48-44](https://user-images.githubusercontent.com/1727541/64944854-912b1500-d86f-11e9-9bab-f9eeac38548d.png)

Also worth noting is that options for the World Map is not saved.
Closing and opening it resets its options:
![ClassicUO_2019-09-16_10-50-16](https://user-images.githubusercontent.com/1727541/64944963-d8b1a100-d86f-11e9-99d0-7156bb846808.png)

**Comment by Stallind** [comment]
The world map is still in development and isn't fully implemented.

**Comment by Hezkore** [comment]
Yeah I figured as much.
But since it's available via the button in-game; I figured it should be available via a macro as well.

**Comment by andreakarasho** [comment]
added
