### ISSUE TITLE
[Request] Open drag-select health bars at mouse location

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#707]
Right now; using drag-select to open health bars will always create them in the upper left corner.
I would like an option for the health bars to be created a mouse location instead.

Example:
![healthbar](https://user-images.githubusercontent.com/1727541/65086390-dce5d780-d9b1-11e9-9a3e-bb4a2887f68d.gif)

**Comment by Alias-Alan** [comment]
This is due to the way they are anchored. It's setup to pull multiple bars not just one, so if you were to grab say 10 bars, it would fill up one column at that location and then start a new row to the right and fill up that column.

**Comment by Hezkore** [comment]
I see.
It's pretty annoying when you're selecting a bunch of enemies in the lower right corner, and the health bars appear in the top left.
Basically as far away as possible.

**Comment by Alias-Alan** [comment]
I've made an organizer for Notorieties just testing around, I'll see if I can make it something the user can position themselves. For now, either grab bars normally or wait patiently to see if that comes to fruition.

**Comment by aclark13** [comment]
@Hezkore have you tried Sallos Easy grab?  Its a lot more similar to what you want to do.  Maybe not perfect but may work

**Comment by andreakarasho** [comment]
This solution is jot really useful when user wants to drag on top right of the screen the selection will become a slim line
