### ISSUE TITLE
Very low game audio, even at 100% volume

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#709]
The game audio is very low, compared to just about every other UO client there is.
I need to set things like Spotify and other applications to about 25% volume to match the ClassicUO volume, which is not the case when using any other UO client.

![ClassicUO_2019-09-18_19-11-21](https://user-images.githubusercontent.com/1727541/65170058-284ac500-da48-11e9-8745-4d027c20d116.png)

(bonus; 'Reproduce music when ClassicUO is not focused' is oddly phrased, as it also produces sound effects, not just music in background)

**Comment by Hezkore** [comment]
After digging around and experimenting; I've found that the Orion client is about 10 times as loud as ClassicUO and the classic client is about 2 times as loud as ClassicUO.
If you do a dirty hack and change `m_ThisInstance.Volume = volume;` in `Sound.cs` to `m_ThisInstance.Volume = volume*10;`, you get about the same volume as Orion.

**Comment by Alias-Alan** [comment]
oddly enough, I can't reproduce this. I have sound set at 30 and can hear the sounds out of my headset 2ft away from me. Are your devices configured correctly?

**Comment by Hezkore** [comment]
I haven't had issues with any other game or application at least.
And I can see in the Windows mixer that ClassicUO produces very low audio levels compared to everything else.
I've tried setting a different sampling rate and bit-depth for my soundcard, but nothing from 16-bit 44100hz to 32-bit 192000hz has made any difference in ClassicUO.
I've also tried Windows "Disable all sound effects" and "Immediate mode" without any luck.
I've got a standard Stereo setup, but also tried it on a surround system with the same issue.
My laptop also has very low game audio in ClassicUO.
So at this point I just kind of assumed that it's the client and not me.
Though, you can never be sure I guess, and if you have any suggestions on what I should try then please do tell me.

**Comment by Hezkore** [comment]
Btw. the way I've tested this is by starting the Orion client next to the ClassicUO client.
Take one step in Orion, listen and look at the volume mixer.
Take one step in ClassicUO, listen and look at the volume mixer.

**Comment by binff04** [comment]
I can confirm the issue: on both platforms (macOS and Windows10), the sound level of ClassicUO is lower than everything else, even the original client.

**Comment by Hezkore** [comment]
Here's a recording of UOS while showing the Windows Volume Mixer: [uos_sound.mp4](http://hezkore.com/junk/uos_sound.mp4)
Notice that the volume reaches about 25-30%:
![vlc_2019-10-12_15-15-08](https://user-images.githubusercontent.com/1727541/66702019-269cb600-ed03-11e9-98e3-416d4538a817.png)

And here's a recording of ClassicUO while showing the Windows Volume Mixer: [cuo_sound.mp4](http://hezkore.com/junk/cuo_sound.mp4)
The volume only reaches about 10-15%:
![vlc_2019-10-12_15-16-42](https://user-images.githubusercontent.com/1727541/66702053-8bf0a700-ed03-11e9-87b3-156505adc117.png)

And just as a refence; here's the Orion client:
![vlc_2019-10-12_15-22-01](https://user-images.githubusercontent.com/1727541/66702100-16390b00-ed04-11e9-96d5-c3b7d60d5bf7.png)

The volume is always lowest in ClassicUO and needs to be, at least, 2 times as loud.
And while I don't think playing footsteps at 100% is a good idea (like Orion does), it still bugs me that ClassicUO's volume is so low that I have to turn up the sound on my sound system, to the point where any Telegram or Discord message almost blows my speakers out.

**Comment by Hezkore** [comment]
Fixed in https://github.com/andreakarasho/ClassicUO/commit/228818bc31c03fb7fff83cb790c0995de4f60e2b
