### ISSUE TITLE
Inventory Containers Not Accessible On Facet Switch

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#711]
On the original client, your bags would close when you switched facets (from Felucca to Trammel for example). I never understood why...but now I am thinking it has something to do with the location of items and thus the game forced you to reopen bags.

In ClassicUO, they stay open but you cannot access the stuff in the "still open" gumps until you reopen the containers. If this is a client limitation that cannot be avoided, then perhaps have the gumps close like the original client...to avoid confusion.

**Comment by andreakarasho** [comment]
fixed
