### ISSUE TITLE
Health bars

### ISSUE THREAD

**Issue by Hoogie1980** [ClassicUO/ClassicUO#716]
Playing with my brother last night and the party bars would not stay updated.   Once one of us went off the others screen and came back on the party bar would just show full health/mana/stam and never change.

**Comment by andreakarasho** [comment]
cuo version?

**Comment by Hoogie1980** [comment]
0.1.2.558 is my version.

**Comment by Hoogie1980** [comment]
Just downloaded the latest version, I will test it out when my brother comes online and update this thread.

**Comment by Hoogie1980** [comment]
Looks like the health bars are fixed.  Thanks
