### ISSUE TITLE
List scrolling with mousewheel is too slow

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#719]
Scrolling through a list is very slow when using the mouse wheel.
Example:
![2019-09-23_09-16-43](https://user-images.githubusercontent.com/1727541/65407563-3e0f1000-dde3-11e9-80af-8b1f8e9ec31f.gif)

I think increasing the scroll speed 6 or 7 times would make it feel a lot better.
6 times faster:
![2019-09-23_09-29-49](https://user-images.githubusercontent.com/1727541/65408139-c346f480-dde4-11e9-95e9-7d64a3008abc.gif)

**Comment by Hezkore** [comment]
This is btw done by changing `public int ScrollStep { get; set; } = 5;` in `ScrollFlag.cs` to `public int ScrollStep { get; set; } = 30;`.
This may have negative effects on other gumps, but I haven't noticed any issues so far.
But it might be a better idea to set it specifically for the shop gump.
Also, I feel like maybe 35-40 might be a better value.

**Comment by andreakarasho** [comment]
Setted up 15
