### ISSUE TITLE
Game crashes when open some paperdoll

### ISSUE THREAD

**Issue by andreakarasho** [ClassicUO/ClassicUO#72]
As above.

I think there are some gumps issues when PaperdollGump try to gets bodies and items on layers.

Atm no idea which kind of gump causes this crash.

**Comment by 3HMonkey** [comment]
Is this related to a NullPointerException?

**Comment by andreakarasho** [comment]
Game loads gumps, but the Graphic param is wrong and we receive null pixels array.

**Comment by andreakarasho** [comment]
Done
