### ISSUE TITLE
Empty trade gump from hidden player

### ISSUE THREAD

**Issue by canterberry** [ClassicUO/ClassicUO#730]
**Describe the bug**

When a hidden player initiates a trade with another player, both players see a trade window, but the non-hidden player's trade window appears empty. If the trade is confirmed by both players, then it is completed successfully.

**To Reproduce**

1. Initiate a trade from a hidden player to a non-hidden player.
2. The non-hidden player sees an empty trade gump.

**Expected behavior**

The non-hidden player should see a trade gump containing the item being traded.

**Desktop**
 - OS: Windows
 - Version: Commit 0cdb7d9afd52acd51d4b40c2715f59c69736f913 (latest dev build as of this issue's creation)

**Additional context**

Follow-up to #728, which has some discussion about this.

**Comment by andreakarasho** [comment]
fixed.
Standard client doesn't allow you to see any trade if one of the trades is null (= invisible, so server didn't send any data to the client)
