### ISSUE TITLE
Slight render alignment discrepancies

### ISSUE THREAD

**Issue by roxya** [ClassicUO/ClassicUO#733]
It appears mobiles and land tiles can be aligned slightly differently from the standard client.

![cuo_align](https://user-images.githubusercontent.com/7057924/65721743-890a7b00-e0a2-11e9-8c85-8eef92480b7f.gif)

Also just saw that on standard the player creates a shadow on the horse! Look at the brown horse

**Comment by andreakarasho** [comment]
different engines :)
i think it is not a real issue
