### ISSUE TITLE
Suppress hotkeys when navigating client's options dialogs

### ISSUE THREAD

**Issue by jaqenn** [ClassicUO/ClassicUO#737]
ClassicUO has an option to ignore hotkeys from Razor and from ClassicUO macros while chat is up.  This allows me to usefully bind undecorated QWER keystrokes to trigger my macros, and it's great.

The ClassicUO options dialog wants keyboard text for some of it's inputs (mainly macro creation and definition, but some other pages too).  This dialog is not smart enough to ignore hotkeys, so while I'm typing in my macro settings I'm triggering other macros in the background.

I think you could safely ignore hotkeys from all sources any time the options dialog is active, or maybe at least when dialog fields have cursor focus.

**Comment by roxya** [comment]
Have you used the latest version? This has been fixed.

**Comment by jaqenn** [comment]
I got the same results with ClassicUO 0.1.2.0, built locally from this repo's master branch.

Is that the latest?

**Comment by andreakarasho** [comment]
dev is the latest

**Comment by jaqenn** [comment]
I tried with 0.1.2.1 build locally from dev, and I do not have the issue.

Thanks!
