### ISSUE TITLE
Need to Double Click Containers Multiple Times to Open

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#739]
Just as the title says...but it seems to perhaps revolve around either a customer container or a custom container gump...where I have to double click 2 or 3 times to get it to finally open.

**Comment by andreakarasho** [comment]
I’m not able to reproduce, here everything seems to work fine.

**Comment by Djeryv** [comment]
You know what...if I don't use RAZOR with CUO I don't have an issue either. I just tried that this morning to see if there was some razor container check going on. Still don't know that is the cause but it was happening to me every time before and with no RAZOR...containers are normal.

**Comment by andreakarasho** [comment]
Razor has a function: grab item, maybe it is disturbing your action

**Comment by Djeryv** [comment]
Should we just close this one? I haven't had the issue since I stopped using Razor so if someone really cares enough about this they can start a bug report for Razor. Otherwise...I have been playing fine without using Razor because I know how to play UO.
