### ISSUE TITLE
Hued Lights are Default Color on Ground

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#740]
In this picture, every light source is dyed a blue color and it appears blue when in my bag. When I set them on the ground, they turn to the default "0" hue. The two circled, however, are partial hue torches I made where the fire part colors only. Those seem to be working as expected.

![image](https://user-images.githubusercontent.com/49735284/65831437-ee1ac800-e27e-11e9-8f6c-c98e98daf288.png)

**Comment by Djeryv** [comment]
This seems to affect much more. Below is a safe I dyed blue. In my bag...it looks correct but on the ground it is trying to do a partial hue when in fact it is not set to partial hue in the TILEDATA.

![image](https://user-images.githubusercontent.com/49735284/65831915-ed386500-e283-11e9-905f-1454e4c2638d.png)

**Comment by andreakarasho** [comment]
I reverted the fix, lemme know

**Comment by Djeryv** [comment]
Back to normal here now....

![image](https://user-images.githubusercontent.com/49735284/65832460-a9485e80-e289-11e9-968d-bdad783b9a22.png)

**Comment by Djeryv** [comment]
Also, my town building signs were hued in a town and I noticed they were not today...after I recompiled this those signs are back to their hue as I intended. I think you had some type of hue setting for tiledata weight of 255 that may have caused it...but just a guess.

**Comment by andreakarasho** [comment]
Seems like the weight == 255 doesn’t mean partial hue ever

**Comment by Djeryv** [comment]
Nope. It is a tag in the TILEDATA file called PARTIALHUE that does it. I just remember reading what you have here:

https://github.com/andreakarasho/ClassicUO/commit/a099dae1c8cd6051458452727aafb6b5cfc9933e

and thought I would point it out.

**Comment by andreakarasho** [comment]
Can i close?

**Comment by Djeryv** [comment]
I think so. Things look good now.
