### ISSUE TITLE
[Feature] Spellname tooltips when hovering over spellbook drag+drop icons

### ISSUE THREAD

**Issue by jaqenn** [ClassicUO/ClassicUO#743]
It is hard to remember which spellbook icons represent which spell.  Also, some players drag out dozens of spell icons to their play window.  Here is an example from a random google search I did:

![image](https://user-images.githubusercontent.com/6549932/65881418-fe06da80-e358-11e9-915d-7a3e059b3530.png)

The Buffs bar provides hover-over tooltips to help describe which icons mean what.  It would be great to provide the same kind of hover tooltip for spellbook icons that lists the name of the spell.

It would also be interesting to list the reagents required by that spell, and chance of success at current magery level.  

I'm trying to get started contributing to ClassicUO, and would be interested implementing this if I can get buyin that it's a good idea.

**Comment by andreakarasho** [comment]
The spellname when mouse is over already exists in dev

**Comment by jaqenn** [comment]
I couldn't find it earlier today.  Is this enabled by default, or do I have to turn it on somewhere?

**Comment by andreakarasho** [comment]
You should switch to the dev branch or use the dev preview release.
Yes it is

**Comment by jaqenn** [comment]
I thought I'm using dev branch as fetched last Friday.  I'll check when I get home today and see if I'm missing something.

**Comment by jaqenn** [comment]
You are correct that this feature is already here.  I don't know how I missed this.
