### ISSUE TITLE
Sell-All button in shopkeeper UI

### ISSUE THREAD

**Issue by jaqenn** [ClassicUO/ClassicUO#744]
Navigating the shopkeeper UI in ultima online is often a pain.

If you arrive at the jeweler to sell a handful of each gem, you've got to click and drag for 20 seconds to accomplish this simple task.

It would be nice to have a Sell-All button that would populate the pending transaction with a full sale of every item the shopkeeper is willing to buy from you.  Users could then review the populated contents and click accept if they are satisfied.

Razor provides something similar to this, but it would be nice to include it in the base client as well.

I'm trying to get started contributing to ClassicUO, and would be interested implementing this if I can get buyin that it's a good idea.

**Comment by Hezkore** [comment]
Yeah I guess a sell all would be nice.
For now you can shift click the items to sell the maximum quantity.
But as I said, I'm not against a 'Sell all' button.

**Comment by Stallind** [comment]
The sell agent is a feature that any server can prohibit razor/uosteam to execute (for whatever reason). 
I don't think we should bypass that functionality.
