### ISSUE TITLE
Add a 10x plus icon to shopkeeper window for buying large quantities

### ISSUE THREAD

**Issue by jaqenn** [ClassicUO/ClassicUO#745]
Navigating the shopkeeper UI in ultima online is often a pain.

If you want to buy the full stock of reagents from a mage shopkeeper, you've got to click and hold the [+] icon for 10 seconds to reach the maximum purchase amount.

It would be nice to have a [++] button next to the [+] button that increases the pending amount by 10, or 50, or maybe just maximum per click.

Alternately maybe holding shift while clicking the button, or while adding the item to the pending dialog would add with the maximum purchase amount?

I'm trying to get started contributing to ClassicUO, and would be interested implementing this if I can get buyin that it's a good idea.

**Comment by Hezkore** [comment]
I could have sworn that both sell and buy supported; "hold shift for larger quantities".
Are you using the Dev branch?
I'm not at home for a couple of weeks so I can't try it myself.

**Comment by jaqenn** [comment]
You are correct that this feature is already here.  I tried holding shift while clicking + and - in the UI, and it didn't do anything.  But holding shift while double-clicking the shopkeeper inventory adds the item to the pending transaction list with the maximum value.
