### ISSUE TITLE
Quivers do not show over armor

### ISSUE THREAD

**Issue by calemccammon** [ClassicUO/ClassicUO#750]
Windows 10 64-bit
ClassicUO version cf4b4a88ef75003a64efb7cc0286260d210ff01a
UO Client version 7.0.79.6

1. Equip armor.
2. Equip quiver.
3. Observe it is not visible over the armor.

Expected:
On OSI, quivers are visible over the armor so that you don't need to unequip your armor in order to access them.

Actual:
Quivers are not visible over armor.

**Comment by andreakarasho** [comment]
fixed
