### ISSUE TITLE
Item properties do not show initially when equipped

### ISSUE THREAD

**Issue by calemccammon** [ClassicUO/ClassicUO#751]
Windows 10 64-bit
ClassicUO version cf4b4a8
UO Client version 7.0.79.6

1. Login and open your paperdoll.
2. Hover your mouse over an item.
3. Observe item properties tool tip does not show.
4. Un-equip and re-equip the item.
5. Hover your mouse over the item.
6. Observe item properties tool tip shows.

Expected:
Item properties tool tip will show immediately after login.

Actual:
You need to un-equip and re-equip the items for the item properties tool tip to show.

**Comment by andreakarasho** [comment]
already fixed
