### ISSUE TITLE
Not enough mana message appears as a 'You see' message in the journal

### ISSUE THREAD

**Issue by calemccammon** [ClassicUO/ClassicUO#754]
Windows 10 64-bit
ClassicUO version cf4b4a8
UO Client version 7.0.79.6

1. Deplete your mana pool by casting spells.
2. Attempt to cast a spell that you don't have enough mana for.
3. Observe there is no 'You must have at least X Mana to use this ability.' message in the lower left.
4. Open your journal.
5. Observe there is a message 'You see: You must have at least X Mana to use this ability.'

Expected:
Message will appear in the lower left.

Actual:
Message is being filtered as a 'You see' message.

**Comment by andreakarasho** [comment]
Unable to replicate
