### ISSUE TITLE
Two buff icons display while under the Enemy of One effect

### ISSUE THREAD

**Issue by calemccammon** [ClassicUO/ClassicUO#755]
Windows 10 64-bit
ClassicUO version cf4b4a8
UO Client version 7.0.79.6

1. Cast Enemy of One
2. Observe active buff icons: There are two.

Expected:
OSI displays only one icon.

Actual:
Two icons display.
![Capture](https://user-images.githubusercontent.com/16568056/66364282-2beeaf00-e957-11e9-8866-2b22dbb7c7a2.PNG)

**Comment by andreakarasho** [comment]
looks good in local

**Comment by andreakarasho** [comment]
Unable to replicate
