### ISSUE TITLE
Player model does not return to normal when disabling polymorphing spells

### ISSUE THREAD

**Issue by calemccammon** [ClassicUO/ClassicUO#756]
Windows 10 64-bit
ClassicUO version cf4b4a8
UO Client version 7.0.79.6

1. Cast any polymorphing spell (Polymorph, Reaper Form, Animal Form, etc.).
2. Cast again to disable the form.
3. Observe character model does not return to normal.

**Comment by andreakarasho** [comment]
Tried in local and it works

**Comment by calemccammon** [comment]
The server I’m on doesn’t officially support ClassicUO (I’d rather not say which server), so this issue and some of the others I logged could be the result of that. I’ll check if there’s any sort of log that might be helpful.

**Comment by andreakarasho** [comment]
There is not a server that supports cuo or not.
Depens what kind of packet server sends.
Did you set the right client version in settings.json?

**Comment by calemccammon** [comment]
[packets.txt](https://github.com/andreakarasho/ClassicUO/files/3705024/packets.txt)
Some packets while casting. Not sure how helpful this is, as I don't understand it.

**Comment by calemccammon** [comment]
Another data point: The character model reverts back to normal if I open my paperdoll.

**Comment by andreakarasho** [comment]
Unable to replicate
