### ISSUE TITLE
Item stuck to cursor when using ArmDisarm macro in ClassicUO

### ISSUE THREAD

**Issue by binff04** [ClassicUO/ClassicUO#759]
**Describe the bug**
When using CUO's ArmDisarm macro action (Options -> Macro -> ArmDisarm -> Left/Right Hand), the item that is being disarmed (taken of the paperdoll and placed into backpack) will stick to the cursor as a ghost item that you can only get rid of by clicking somewhere in your backpack or on other in-game items while the actual item is properly disarmed and placed into your backpack.

**To Reproduce**
1. Open in-game options and navigate to the Macro section;
2. Add a new macro and add "ArmDisarm - Left Hand" action (don't forget to bind a hotkey);
3. Equip a shield, for example, or anything else what goes into the left hand;
4. Execute the macro and you will see how item will be disarmed and placed into your backpack but also the same graphic will stick to the cursor.

**Expected behavior**
There should be no ghost item stuck on the cursor.

**Comment by andreakarasho** [comment]
fixed
