### ISSUE TITLE
[Request] Scaleable containers XBR effect

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#762]
The World Viewport supports the XBR effect, but I would like to suggest that scaleable containers/gumps also make use of the effect.

This is how it looks now at scale 200:
![ClassicUO_2019-10-12_18-56-45](https://user-images.githubusercontent.com/1727541/66705011-0cbe9b80-ed22-11e9-8576-3bd4622e6733.png)
And I think it would look a lot better if the XBR effect was in use here.

**Comment by andreakarasho** [comment]
xBR is a post processing effect.
To apply it you need to render single gumps in a dedicated rendertatget. It’s always the best option to avoid RT because it’s the most expensive action you can do in computer graphics. 
Then UO graphics are not made to be scaled.. at least in runtime
