### ISSUE TITLE
Alternative light method

### ISSUE THREAD

**Issue by Hezkore** [ClassicUO/ClassicUO#763]
I think it's safe to say that most people use the "Light Level" option and set it fairly high, around ~20 or so. This makes it easier to see things in-game, especially in dungeons.
But the downside is that you never get to see the pretty coloured lights.
So I would like to suggest an alternative light drawing method!
Basically just clear `RenderTarget2D _darkness` to a solid black, and draw the lights as normal.
Then when rendering the `_scene.Darkness` just use `batcher.SetBlendState(BlendState.Additive)` instead of the currently used `batcher.SetBlendState(_blend)`.
This would make sure that lights are always visible.
You'll also want to set the opacity to about 40% to make the lights softer and not full bright.

I would have done a pull request for this as this already works, but I can't figure out how set opacity for lights.

Here's how it would look (GIF):
![lights](https://user-images.githubusercontent.com/1727541/66708669-558f4800-ed54-11e9-89f7-7229116cdfd4.gif)

**Comment by andreakarasho** [comment]
You can set opacity here: 
https://github.com/andreakarasho/ClassicUO/blob/46f0ee4c1e2d3b7ecc3ce4b7782b78b44ddacc00/src/Game/Scenes/GameScene.cs#L753

0 = no alpha
1 = full alpha

Honestly i don't really like this effect, maybe with opacity will looks better

**Comment by Hezkore** [comment]
Setting Z to 1 was the first thing I tried, but there's no difference between Z 0 and Z 1.

**Comment by Hezkore** [comment]
So after adding alpha support to the shader and recompiling the shaders, this is what I ended up with:
![2019-10-16_02-09-16](https://user-images.githubusercontent.com/1727541/66900232-b80a7180-effc-11e9-9f49-1738eaa1ba47.gif)

Basically; if your custom light level is set to max (30) it will render the lights using a new method.
This new method is only used when you've got a custom light level set, so it won't change how the normal day and night cycle looks.

I'm pretty happy with it, I think it looks good.
It's nice to finally see the lights that are normally always hidden.
Not sure this is Pull Request worthy though.
Here's the branch if anyone's interested: https://github.com/Hezkore/ClassicUO/commits/daytime-lights
Comments and suggestions are welcomed, and let me know if I should make a pull request.

UPDATE:
I decided to make a pull request.
You can find it here: https://github.com/andreakarasho/ClassicUO/pull/770
I will remove this old branch.
