### ISSUE TITLE
Player cannot select location for summoned creature

### ISSUE THREAD

**Issue by JakubLinhart** [ClassicUO/ClassicUO#778]
**To Reproduce**
1. Cast Summon creature
2. A summon menu opens
3. Double click on selected creature in the menu.
4. Target cursor appears and client immediately targets location that was directly under the selected creature in the menu. It means it is not select target location for summoned creature.

**Expected behavior**
Player is able to select a location for a summoned creature.

**Screenshots**
![summon creature](https://user-images.githubusercontent.com/1675735/67147350-95928580-f294-11e9-91a2-4fb74b998936.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - ClassicUO version: 0.1.2.1
 - Client version: 3.0.6m
 - Server: Sphere 99z8

**Comment by andreakarasho** [comment]
I need these infos to reproduce that issue:
- server ip
- client 3.0.6m files

**Comment by JakubLinhart** [comment]
Thank you very much that you are open to test it on a real server. The issue appears on UOErebor and testing on this server is difficult for three reasons:

1) You cannot cast this spell with a newbie character.
2) Encryption cannot be turned off on this server.
3) There is no single package with client files.

I will prepare an all-in-one zip package with everything pre-configured and functional. Unfortunately I cannot share it publicly. I'm going to contact you on Discord with needed.

I would understand if you don't want to dive into this issue :).

**Comment by andreakarasho** [comment]
on latest cuo it works
