### ISSUE TITLE
TargetNext Macro does not work

### ISSUE THREAD

**Issue by merttumer** [ClassicUO/ClassicUO#784]
When i assign a key to TargetNext macro it does not work. It should change my target and the little health bar should switch between characters that is targeted on my screen

**Comment by binff04** [comment]
The `TargetNext` macros action has really strange code that basically assigns the same mobile to the `LastAttack` instead of targeting next mobile in list.

Recently I implemented `Select Next/Previous/Nearest` actions, so try one of them -- they work as expected.

P.S. I will take a look at what `TargetNext` does and why it isn't working as expected.

**Comment by merttumer** [comment]
I actually fixed it in my local but another problem is last target, when i target the ground the last target does not change i mean it does not add the ground as last target. Thats a really bad problem and When I check the code i see last target only get a mobile serial as an argument. I am looking for a way to add the ground too

**Comment by merttumer** [comment]
else if ((TargeringType == TargetType.Neutral || TargeringType == TargetType.Harmful) && selectedEntity is GameObject gobj) also see I added  "TargeringType == TargetType.Harmful)" this here because spells like wall of stone or meteor swarm coulnt not be targeted on the ground too

**Comment by binff04** [comment]
Where did you add that?

**Comment by merttumer** [comment]
TargetManager.cs:244

**Comment by binff04** [comment]
Actually you are right: `LastTarget` should be able to point to both mobiles and items. It's widely used in macros, like "last skill -> last target" where "last target" could be a mobile or an item.

**Comment by merttumer** [comment]
Also the ground(the land) but I dont know if its count as items in this case.

**Comment by Hezkore** [comment]
I know that, a long time ago in the original client, I used "Use Last Target" to open doors.
So I can confirm that LastTarget should be able to target a lot of things.

**Comment by binff04** [comment]
> Also the ground(the land) but I dont know if its count as items in this case.

It's a `Point` then.

**Comment by andreakarasho** [comment]
LastTarget and Selection next/nearest/prev now works with items
