### ISSUE TITLE
Cannot open armoire in a container

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#785]
**Describe the bug**
When you have an armoire in any container, a bag on the ground, or within our own backpack, when you open it, it will immediately close.

You can hear the open/close sound.

**To Reproduce**
1. Get a bag and place it on the ground
2. Get an armorie and place it in the bag
3. Attempt open the armorie from the bag

**Expected behavior**
The actual container gump for the armoire to open and display the contents.

Using the latest dev build as of the time of posting.

**Comment by andreakarasho** [comment]
I tried on UOR with standard client and this is the correct behaviour [sometime you see the opened armoire and then client closes it].
You can open armoire if it is on ground only.

**Comment by markdwags** [comment]
Thanks, forgot to test OSI client.
