### ISSUE TITLE
Light color & hue on items

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#786]
**Describe the bug**
I know this has been reported but just wanted to add it here for visibility.

The issue is related to items that have light sources, either the light doesn't display at all, or the hue doesn't match what you see in the OSI client.

Here are some examples:

![image](https://user-images.githubusercontent.com/577652/67229314-ac55eb00-f400-11e9-94d4-0dd9b52a054e.png)

![image](https://user-images.githubusercontent.com/577652/67229321-b0820880-f400-11e9-9d8f-777140ab75eb.png)

OSI on the left, CUO on right:

![image](https://user-images.githubusercontent.com/577652/67229337-b8da4380-f400-11e9-9732-e29b87bdaa00.png)

![image](https://user-images.githubusercontent.com/577652/67229346-bd9ef780-f400-11e9-9123-b0f6c8d1d5f9.png)

![image](https://user-images.githubusercontent.com/577652/67229359-c4c60580-f400-11e9-8e99-8727fa7ddc55.png)

**Comment by andreakarasho** [comment]
should be fixed

**Comment by markdwags** [comment]
Thanks! I tested it out, that item now has light, but it's the wrong light hue (like the others)

![image](https://user-images.githubusercontent.com/577652/67236150-4ff9c800-f40e-11e9-958e-59dbbd8d9a63.png)

**Comment by andreakarasho** [comment]
it's green here

![image](https://user-images.githubusercontent.com/20810422/67236357-696c3580-f449-11e9-8183-470db8e3e955.png)


edit increased:

![image](https://user-images.githubusercontent.com/20810422/67236559-c4059180-f449-11e9-96b4-7273bd466062.png)

**Comment by Hezkore** [comment]
There are still a lot of incorrect colors.
For example all torches in Outlands are purple instead of orange.

CUO:
![ClassicUO_2019-10-21_23-40-34](https://user-images.githubusercontent.com/1727541/67245489-63338480-f45c-11e9-93c4-d64e312fa876.png)

Standard:
![client_2019-10-21_23-41-24](https://user-images.githubusercontent.com/1727541/67245497-6890cf00-f45c-11e9-93b0-ee638a4f2640.png)

**Comment by Agetian** [comment]
Notably, the referenced issue with the green light showing on most light sources is a very recent change, since it works fine on both the 0.1.3.500 beta release and the recent 0.1.3.750 dev build snapshot. Thus, it must have been a recent alteration that affected this behavior.

**Comment by Agetian** [comment]
As of 0.1.3.600 beta hotfix, most of the light colors are back to normal, but some (e.g. the bank colors in Odyssey) are still incorrectly green-hued. Thanks for your efforts to investigate and fix this!

**Comment by andreakarasho** [comment]
With recent changes lights should be ok.
I close this.
If something still broken let me know here
