### ISSUE TITLE
Incorrect riding animation

### ISSUE THREAD

**Issue by merttumer** [ClassicUO/ClassicUO#804]
When mounted, the riding animation of human is incorrect. If you check out the original client or orion client you will see that the animation is not right. 

I made some experiments on this for example:

In MobileView.cs:298 -- under DrawInternal function

 var frame = direction.Frames[frameIndex] --> i reversed frameIndex order like from 1 2 3 4 5 to 5 4 3 2 1 for only human riding animations then the riding animation looked like the original. But of course this change can't be done here because every animation when mounted gets reversed too. Only riding animations must be reversed. I am not sure how the animations are read but this way it feels weird and annoying.

**Comment by andreakarasho** [comment]
I found the issue and fixed. It will be available in dev
