### ISSUE TITLE
Unable to cast non-magery spells with CastSpell Macro

### ISSUE THREAD

**Issue by creamcast** [ClassicUO/ClassicUO#810]
**Description**
When using the CastSpell macro with spells other than Magery (i.e. Necromancy) it gives an error message saying spell is not in the book even when it is.

Possible fix: [link](https://github.com/andreakarasho/ClassicUO/pull/811/commits/a9aa2d78d261643678bc7f66802640d9df6750ab)

**Comment by andreakarasho** [comment]
fixed
