### ISSUE TITLE
Clicking links or URL buttons does not launch a browser

### ISSUE THREAD

**Issue by OrbitStorm** [ClassicUO/ClassicUO#815]
When clicking on links or a button with an embedded URL, the client should open your browser and navigate to the URL that was clicked. It simply doesn't launch the browser at all.

**To Reproduce**
1. Locate a link or URL button in-game
2. Click on link/button
3. Wait for browser to launch
4. Browser does not launch

**Expected behavior**
Browser should launch and navigate to URL that was clicked in-game.

**Desktop (please complete the following information):**
 - OS: Windows 10 v1903
 - Browser: Google Chrome Version 77.0.3865.120
 - Version : 7.0.15.1
- Razor v1.6.2.16

**Comment by andreakarasho** [comment]
Hi, the function should work, can you provide an example and a how to reproduce?

**Comment by OrbitStorm** [comment]
Apologies. It appears this is either an unknown issue or an issue that simply hasn't been corrected on the server that I experienced this with. Was able to confirm that some buttons work, some don't. Clearly not an issue with ClassicUO. Thank you for your time!
