### ISSUE TITLE
Mastery Chain disappears

### ISSUE THREAD

**Issue by Hoogie1980** [ClassicUO/ClassicUO#817]
On UO Outlands CUO version 0.1.2.736, my mastery chain is equipped on my paperdoll(goes in talisman slot), but as soon as I take one step the graphic disappears until I log out and back in.  At this time I can move it back to my backpack or if I take a step it will disappear again.  I just got this chain on this current version so I'm not sure how it acted on previous builds.

I just expect that once I move the Mastery chain would not disappear.
![chain](https://user-images.githubusercontent.com/38014315/67832107-327bcc80-faa6-11e9-89ef-156caa50835a.png)

**Comment by andreakarasho** [comment]
I need:
- graphic
- layer on paperdoll

**Comment by Hoogie1980** [comment]
Graphic: 0xa8c7
Layer: 9

**Comment by andreakarasho** [comment]
From Owyn: it’s not a cuo issue
