### ISSUE TITLE
Multi Lightning Bolt At same place

### ISSUE THREAD

**Issue by panalgin** [ClassicUO/ClassicUO#821]
**Describe the bug**
Unlike in the original client, CUO always plays the same animation whenever a lightning bolt is supposed to be drawn on the screen. However it should draw a random form on each attempt. 

Because of this, whenever more than one Lightning Bolt animation is requested on the client, each animation frame stacks up on each other and instead of several different lightning bolts, it looks like a one thick bolt. It is better explained in the picture below where I simply cast multiple lightning bolts to the same target with a custom script of mine.

Left: Old Client
Right: ClassicUO
  ![https://media.discordapp.net/attachments/531214935804608515/639954203086815242/unknown.png](https://media.discordapp.net/attachments/531214935804608515/639954203086815242/unknown.png)

**To Reproduce**
just do a `mobile.BoltEffect(hue);`  on any script multiple times. I am also adding my special effects hide/unhide script as an addition for the lazy people. 

use as [catadis [cataapp on yourself
[CataDis.zip](https://github.com/andreakarasho/ClassicUO/files/3801078/CataDis.zip)

**Expected behavior**
The far superior almighty CUO should outperform the old client, maybe it can even support Lightning Hue color ????? :D. The expected behavior is same with the old client as you can see. 

**Screenshots**
I have already added it

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Latest dev preview of CUO

**Comment by oroechimaru** [comment]
This was resolved for others by updating intel graphics drivers https://downloadcenter.intel.com/product/80939/Graphics-Drivers

**Comment by panalgin** [comment]
I'm not using an onboard/external intel vga chip but an old nvidia gpu. Still, I'm going to update my gpu drivers and give it a retry then report back, thanks.

**Comment by oroechimaru** [comment]
Sounds good. It may help to make sure cuo dev is up to date as well (build should be higher than 733) https://www.nvidia.com/Download/index.aspx

**Comment by panalgin** [comment]
CUO Version -> 0.1.2.736
GPU Version -> 10.17.13.5362 -> Dates: 7/22/2015 (I believe this is the latest driver I was able to find nvidia website for this GT 430 old gpu)

Still same. For the record, animation plays well but all 8 lightning bolts animations are played in a linearly and over on each other that it looks like a single lightning bolt. I don't think anything related to gpu/opengl happens here but there is a logical difference compared to the original client.

CUO plays same animation sequence/order/ for lightning effect but old client randomizes/mixes the frames I guess. This achieves each lightning following a different path to the earth, kind of. 

Thanks

**Comment by andreakarasho** [comment]
fixed
