### ISSUE TITLE
Left Click to Pickup items is not accurate enough when using SallosEasyGrab

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#824]
Left click to pickup items is not accurate enough when using SallosEasyGrab. You often (can be ping related - I don't know) grab items close to the item you initially clicked on:

Video:
https://imgur.com/kMpOXtT

This is bad because you want SallosEasyGrab for the functionality of grabbing bars so easily, even if you don't want it for grabbing items. With SallosEasyGrab turned off, this problem of grabbing items does not exist.

Suggestion: Fix the issue (i.e. the original item you clicked on should always be grabbed), or make it so you can toggle SallosEasyGrab to only apply to pulling bars (not items).

**Comment by andreakarasho** [comment]
fixed
