### ISSUE TITLE
space as last character in name crashes when settings changed

### ISSUE THREAD

**Issue by expiation** [ClassicUO/ClassicUO#835]
**Describe the bug**
I have a character where the last character in their name is a space, and when I try to save any setting it crashes.  I believe this is due to the fact that windows doesn't allow space to be the last character in a folder name.  For reference my character is named "Lily ".

**To Reproduce**
make a character with a space as the last character

**Expected behavior**
I would like to save my settings 😄

**Comment by andreakarasho** [comment]
fixed, let me know
