### ISSUE TITLE
Grey fonts do not display well in dark mode journal

### ISSUE THREAD

**Issue by oroechimaru** [ClassicUO/ClassicUO#840]
Anyway to outline or change shade of grey fonts? I try to change all my font colors (system  / cuo messages, general chats etc)

Possibly this is redundant to the basic chat font colors and I need to reverify my colors

**Comment by andreakarasho** [comment]
TODO: use unicode on journal if possible

**Comment by Stallind** [comment]
@oroechimaru a temporary fix would be enabling this checkbox.

![image](https://user-images.githubusercontent.com/43113499/71455770-db892f80-2796-11ea-9e0e-7632dee96ede.png)

I'm working on forcing unicode for journal input : )

**Comment by Stallind** [comment]
#873 💯

**Comment by Stallind** [comment]
Added in latest dev
