### ISSUE TITLE
ClassicUO not launching. Log attached!

### ISSUE THREAD

**Issue by justjimmy84** [ClassicUO/ClassicUO#845]
Double clicking the .exe doesn't launch the program. Here's the crash log.

> ClassicUO - v0.1.2.1
> OS: Win32NT x64
> Thread: CUO_MAIN_THREAD
> 
> Exception:
> System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
>    at SDL2.SDL.INTERNAL_SDL_CreateWindow(Byte[] title, Int32 x, Int32 y, Int32 w, Int32 h, SDL_WindowFlags flags)
>    at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow()
>    at Microsoft.Xna.Framework.Game..ctor()
>    at ClassicUO.Engine..ctor(String[] args)
>    at ClassicUO.Engine.Run(String[] args)
>    at ClassicUO.Bootstrap.Main(String[] args)
> ClassicUO - v0.1.2.1
> OS: Win32NT x64
> Thread: CUO_MAIN_THREAD
> 
> Exception:
> System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
>    at SDL2.SDL.INTERNAL_SDL_CreateWindow(Byte[] title, Int32 x, Int32 y, Int32 w, Int32 h, SDL_WindowFlags flags)
>    at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow()
>    at Microsoft.Xna.Framework.Game..ctor()
>    at ClassicUO.Engine..ctor(String[] args)
>    at ClassicUO.Engine.Run(String[] args)
>    at ClassicUO.Bootstrap.Main(String[] args)
>

**Comment by andreakarasho** [comment]
Hi,
post a DxDiag or send it to me in pvt on discord

**Comment by justjimmy84** [comment]
Managed to fix it. For future reference, I had to force run it with GPU instead of the onboard CPU. Display Settings > Grahphic Settings. Hope that'll work for those who run into the same issue in the future!

**Comment by andreakarasho** [comment]
nice!
