### ISSUE TITLE
Dragon armor shows as plate when body paint on

### ISSUE THREAD

**Issue by matsamilla** [ClassicUO/ClassicUO#848]
**Describe the bug**
Dragon armor shows as plate armor in paper doll when body paint is applied

**To Reproduce**
Use body paint (tribal paint used for my test)
Equip dragon armor
look at paper doll

**Expected behavior**

**Screenshots**
https://puu.sh/EHU9B/0171e9946a.png

**Desktop (please complete the following information):**
 - Windows 10
- CUO Version 0.1.2.834

**Additional context**
Haven't tried any other paint colors.

**Comment by andreakarasho** [comment]
fixed
