### ISSUE TITLE
Loading Razor from classicUO doesn't show macros

### ISSUE THREAD

**Issue by wwford** [ClassicUO/ClassicUO#849]
If I load classicUO, which then loads Razor, the macros do not show up.  But if I run Razor.exe directly, it loads up and shows the macros.

**Comment by andreakarasho** [comment]
try to run cuo as admin

**Comment by wwford** [comment]
Ok.  I ran as administrator but still don't see the original macros copied from AppData.

I made a macro called Test right after I submitted the issue. I still see that macro available when ran as administrator.  However, when I search my computer I also can't find where it's storing Test.macro

**Comment by andreakarasho** [comment]
open the issue [here](https://github.com/markdwags/Razor/issues): maybe mark can give you the answer
