### ISSUE TITLE
Auto run bug when macro hotkeying movement to keys

### ISSUE THREAD

**Issue by jonnydreamer** [ClassicUO/ClassicUO#852]
I wanted to use the keyboard to move. WSAD movement keys. And although it is sooooo nice to play like that for me and it works so well. There is a bug that happens very often where my character will start auto running in a perticular direction until that direction key is pressed again. It happens very frequently when chatting and can happen even when other buttons are hit on the keyboard such as Backspace or Enter. Making it a very nice feature to play with but almost totally unplayable.

From all the different tests I have done to set it off. It seems to be triggered when you press to many buttons on the key board to fast. Which is why it tends go off alot when you are typing.

This does not  happen when the arrow keys are being used to move, only the Macro'd WSAD keys cause this to happen.

**Comment by andreakarasho** [comment]
Fixed
