### ISSUE TITLE
Party Bars not updating mana and stamina

### ISSUE THREAD

**Issue by natryl** [ClassicUO/ClassicUO#859]
Enable this in ClassicUO
![image](https://user-images.githubusercontent.com/48296812/70723946-58a8a500-1cbf-11ea-8745-73aabc548d96.png)

Enable this in Razor
![image](https://user-images.githubusercontent.com/48296812/70724017-7970fa80-1cbf-11ea-8334-d99d0c0817dc.png)

Now when you invite that toon it will auto accept the invite but the party gump still comes up. Hitting accept on the gump gets you this message.
![image](https://user-images.githubusercontent.com/48296812/70724167-b5a45b00-1cbf-11ea-8cbb-bc0bc30867d9.png)

Now get off screen and back on and party bars will break.
![image](https://user-images.githubusercontent.com/48296812/70724229-d66cb080-1cbf-11ea-955e-33afcfd96c68.png)

**Comment by Stallind** [comment]
Looks like I missed a check when I added the gump. I'll take a look at this shortly

**Comment by Stallind** [comment]
I was wrong, I have no idea why this happens :D

**Comment by andreakarasho** [comment]
merged the @Stallind PR.

**Comment by Stallind** [comment]
Didn't seem to have fixed the issue. Since I can't recreate it Im waiting for someone from outlands to try.

**Comment by Stallind** [comment]
#861 should fix it
