### ISSUE TITLE
Animated Stacked Item Flicker

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#866]
On the latest build, on two separate/different computers, any animated stackable item has the stacked offset item flicker in and out of view. So below you can see what CUO does with it and how it looks in the original client. Again, the gold nuggets in the picture are animated hence the sparkles.

![cuo](https://user-images.githubusercontent.com/49735284/71222113-d60e7f80-2294-11ea-8981-db7cdfd7f03d.gif)

![orgin](https://user-images.githubusercontent.com/49735284/71222118-dad33380-2294-11ea-985b-f0ad900f0d98.gif)

**Comment by andreakarasho** [comment]
should be fixed
