### ISSUE TITLE
Unable to create new characters on 5.x client

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#868]
**Describe the bug**
When you walk through the character creation process, two issues occur:

1) The skills you select don't always line up with the skills your character is created with the following:

![image](https://user-images.githubusercontent.com/577652/71367551-04c57800-256b-11ea-9323-f5b850251600.png)

Ended up with a character created with:

![image](https://user-images.githubusercontent.com/577652/71367560-127afd80-256b-11ea-87a6-6a0d2c5c35f6.png)

I fired up a 7.x client and I noticed the skill list is in a different order.  On 5.x, Animal Taming is the 4th one down, whereas on the 7.x client its half way down the list.

2) When you move beyond the skill selection gump, it will auto-skip the select city gump.

To get the gump to correctly display, changing the value to 5528 here https://github.com/andreakarasho/ClassicUO/blob/2dcff874605817cb6eddc872176d9aea4545974f/src/Game/UI/Gumps/CharCreation/CreateCharCityGump.cs#L41 will display the correct gump

![image](https://user-images.githubusercontent.com/577652/71368155-badd9180-256c-11ea-91a4-9fd4d25e7b9b.png)

But after you select the city, clicking Next doesn't actually move you forward as it does when it auto-skips.

**To Reproduce**
1) Log onto UOR Test server (or live)
2) Create a character with the skills above
3) Observe the city menu doesn't come up, auto-spawned in Yew (which is index 0)
3a) Change gump value so city menu comes up, city is selected, debug shows button being hit but the UI won't advance and no character created

**Expected behavior**
That during the creation process, you can select a city to spawn to and the skills you select are the ones that carry forward.

**Screenshots**
See above

**Additional context**
Running on the latest build from the dev branch as of the posting of this issue.

**Comment by Stallind** [comment]
It's related to putting the skills in an alphabetical order that I put in yesterday, not the client version. Looking to fix it atm :)

**Comment by markdwags** [comment]
> It's related to putting the skills in an alphabetical order that I put in yesterday, not the client version. Looking to fix it atm :)

Ah ok, makes sense. The city selection though, I believe that has been around prior to your change.

**Comment by andreakarasho** [comment]
everything should be fixed now

**Comment by markdwags** [comment]
Thank you! I verified that the skills now correctly set and the map selection works.
