### ISSUE TITLE
Missing Latest Special Abilities

### ISSUE THREAD

**Issue by xG00BERx** [ClassicUO/ClassicUO#869]
When playing the newer servers some of the abilities in the game do not align..

for example I am wielding a "Gnarled Staff" the client shows that the abilities for this weapon are:
Primary: Concussion Blow
Secondary: Paralyzing Blow

When this is incorrect if use the standard client or check on UOGuide you will see that it should be Concussion Blow/Force of Nature as the abilities for this weapon.
http://www.uoguide.com/Gnarled_Staff

I am playing on a very current server but if you check on UOGuide it says "Force of Nature" was added back in 2005 
"Force of Nature is an Mace Fighting Special Move was added during the Mondain's Legacy expansion in the fall of 2005."

It seems from quick testing that a lot of the abilities that were changed in Modains Legacy just have not been added to this client, I dont know if there is a way for you to do a patch check or something so the client will know what era and put the right ability etc but it is something that is current broken.

**Comment by andreakarasho** [comment]
fixed in dev

**Comment by xG00BERx** [comment]
Im not sure if this is the place to post it, but if you use the primary + secondary ability buttons in Razor it still recognizes the secondary as Para Blow.

**Comment by andreakarasho** [comment]
here https://github.com/markdwags/Razor
