### ISSUE TITLE
Chat Button

### ISSUE THREAD

**Issue by xG00BERx** [ClassicUO/ClassicUO#870]
The most current version of UO has a chat button which is the , in game.

On a regular client when you click this button just like "Guild: " or "Party: " it should say "Chat: " which will allow you to then post in the public chat that you are currently in. 

Also the chat button has no functions in the client right now so it seems, you should get a menu when you click chat where you can join or create chats but currently it does nothing.. not sure if this is because I am not on the official servers or if its just not been worked on yet.

http://www.uoguide.com/Chat

**Comment by andreakarasho** [comment]
Done in dev build.
Surely it is not perfect. Can you test it a little bit and then give me a feedback?

**Comment by xG00BERx** [comment]
> Done in dev build.
> Surely it is not perfect. Can you test it a little bit and then give me a feedback?



Everything is working great so far thank you so much!
