### ISSUE TITLE
UO Store Button

### ISSUE THREAD

**Issue by xG00BERx** [ClassicUO/ClassicUO#871]
Currently in the client there is no UO Store button - it is a newer thing on newer servers and on the official servers but it currently is completely missing from the client.

Here is an overview of the system and what not, I am not sure how gumps work whether they are server side or client side etc but all I know is currently I play on a server where this button is enabled with the most recent Real UO client and it functions there but when I login to ClassicUO I cannot access it.

https://uo.com/ultima-store/

**Comment by andreakarasho** [comment]
added in dev
