### ISSUE TITLE
Book of Ninjitsu Wrong ID on NPC Buy

### ISSUE THREAD

**Issue by xG00BERx** [ClassicUO/ClassicUO#878]
When looking at the Ninjitsu NPC who sells ninjitsu books in New Haven the Book of Ninjitsu shows the graphic ID of a Book of Chivalry.. Minor bug - but still a bug.

**Comment by andreakarasho** [comment]
it looks like a server issue.
On my local server [servuo] with standard client i've the same issue:

![image](https://user-images.githubusercontent.com/20810422/71543639-9111d980-2975-11ea-8af5-1b12d2e53916.png)
