### ISSUE TITLE
Hover over Ninjitsu

### ISSUE THREAD

**Issue by xG00BERx** [ClassicUO/ClassicUO#879]
Whenever you drag a Ninjitsu ability from the ninjitsu ability and hover over it it says weird shit.

For example when I hover over 
Focused Attack it says: "Current Insure Items in inventory:"
Ki Attack says: "Walls"
Mirror Image says: "Teleporters"

long story short hovering over these icons in game AFTER THEY HAVE BEEN REMOVED FROM THE NINJA BOOK it says weird shit.. check all the abilities and you will see.

I am playing on a server with the very most up to date ServUO Repo if that helps.

**Comment by andreakarasho** [comment]
done
