### ISSUE TITLE
Hover over Teleporters

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#880]
On today's build, there is an issue if I hover over a teleporter where it is showing too much information...especially to a player account.

![image](https://user-images.githubusercontent.com/49735284/71551134-0fd23b00-29a5-11ea-96df-6b09d7444c6d.png)

**Comment by andreakarasho** [comment]
This is what server sends as opl. Did you try with the standard client?

**Comment by Djeryv** [comment]
The standard client focuses on the flags set in TILEDATA to what you see when you single click and hover over items. So in the standard client, a moongate graphic (that I use for these teleporters) have a weight set of 255 and light levels and animation flags. So you can't hover over them to have text appear and if you single click it it will just say "moongate" or whatever name the item has set in game.

Now for RunUO servers, we often have chaos shield graphics used for teleporters and they are often set to hidden so players don't see them. Because shields have certain flags set in TILEDATA, they will show their attribute text when you hover over them.

So CUO needs to focus on what the tiledata states should happen with the graphic when in the game world like the standard client does.

An item with a 255 weight means that items don't have any hover color with a cursor when they are set to non-movable. If I set the CONTAINER flag for this moongate, then I can make the item show hover text/attributes when in game (as an example of flags changing behavior of items).

![image](https://user-images.githubusercontent.com/49735284/71555828-b2b2a580-29f5-11ea-9183-0dc7a2133f1f.png)

**Comment by andreakarasho** [comment]
F I X E D
