### ISSUE TITLE
Whips + Abilities

### ISSUE THREAD

**Issue by xG00BERx** [ClassicUO/ClassicUO#882]
ClassicUO is currently not recognizing whips and their respective abilities.

There are three different types of Whips, one for each combat skill and they have different abilities.

Fencing - Spiked Whip - Primary: Armor Pierce Secondary: Whirlwind
Swords - Bladed Whip - Primary: Bleed Attack Secondary: Whirlwind
Mace Fighting - Barbed Whip - Primary: Concussion Blow Secondary: Whirlwind

This can be referenced here:
https://uo.com/wiki/ultima-online-wiki/items/weapons/

**Comment by Stallind** [comment]
Can you provide the graphics for these items? (By typing -info, click the item and scroll to "Graphics")

**Comment by andreakarasho** [comment]
This is something new for me to be honest. I did a quick search, but i found nothing really useful

**Comment by Darkling89** [comment]
I have fixed this issue "Fixed 3 issues for Eventine" issue #973

**Comment by Darkling89** [comment]
it took alot of digging for info, Apparently it was made for christmal on osi, so these are actually something that needs to ne be fixed.

**Comment by andreakarasho** [comment]
Done!
