### ISSUE TITLE
Flying as Garg Animation

### ISSUE THREAD

**Issue by xG00BERx** [ClassicUO/ClassicUO#883]
When you are flying as a Gargoyle as long as you stay still you are fine and everything looks swell but the second you go to move you immediately land and take off running at ADMIN speeds.. sounds like an animation issue :)

**Comment by andreakarasho** [comment]
Tell me the steps to reproduce it please

**Comment by xG00BERx** [comment]
All I did was use flying ability and then try running and when I did my character wouldn't use his wings hed be on the ground and running fast as he could fly

**Comment by andreakarasho** [comment]
Can it be related to the sitting issue?
Can you do a quick test with lastet CUO [0.1.2.1013]?
