### ISSUE TITLE
New Trade Gump

### ISSUE THREAD

**Issue by xG00BERx** [ClassicUO/ClassicUO#884]
In the new trade gump on current UO you can transfer any number of gold that is in your bank to another play it should show up in the gump!

It currently will not let you type the amount you would like to give to another player, it does not show them how much gold they are sending you, and it does not tell you how much you have in the bank.

I would upload more pics in these bug reports but im not sure how btw..

**Comment by xG00BERx** [comment]
to replicate just hop on current ServUO and go trade with an alt or another player.

**Comment by Stallind** [comment]
Please post some screenshot of what you mean 
Press SHIFT + WIN + S , choose the area and then just CTRL + V in this comment box =) 

Looks like this for me 
![image](https://user-images.githubusercontent.com/43113499/71606187-17ddd680-2b6f-11ea-920f-69185b5e9f70.png)

**Comment by andreakarasho** [comment]
@Stallind this is the gump he is referring

![](http://uo.com/wp-content/uploads/2015/10/tradehouseCC.jpg)

**Comment by andreakarasho** [comment]
done
