### ISSUE TITLE
House Teleporter/World NOt Loading

### ISSUE THREAD

**Issue by xG00BERx** [ClassicUO/ClassicUO#886]
Lots of times when I use a house teleporter from one house to another when I get to the other side almost 0 in game items load, I just see empty and bare lots with no items, walls, mobiles etc.

How to Replicate: Take a house teleporter from one place to the next(might have to be a populated server/house?)
*Note: I do have "show content inside houses" check marked this might have something to do with it?

Also, running away and back DOES reload everything but if you dont plan on running away and back relogging reloads it as well.

**Comment by andreakarasho** [comment]
Seems like a server issue, because it is handled by server.

First of all make sure you have the option "Show house content" checked [to do a clear test relogin if you had it unchecked].
Then try to use the house teleporter.
If the test will give NEGATIVE result, so you are not able to see items inside house, test it with standard client.
If standard client does not work too i think it is a server issue

**Comment by Reetus** [comment]
![image](https://user-images.githubusercontent.com/6239195/72209348-266dab80-34e8-11ea-98a4-d8573ff16fae.png)

Assuming he means like this?

**Comment by andreakarasho** [comment]
is there a way to test?

**Comment by Reetus** [comment]
Happens randomly for me... heres another example...

![image](https://user-images.githubusercontent.com/6239195/72216599-daf5e480-355d-11ea-9757-00556e33fbc0.png)

**Comment by andreakarasho** [comment]
In the lastest pic you are using an old cuo version.
Did you try with dev version?

**Comment by Reetus** [comment]
I haven't no.

**Comment by Reetus** [comment]
Still happens in dev...

![screenshot_2020-01-28_06-27-15](https://user-images.githubusercontent.com/6239195/73219986-52e81f80-4198-11ea-95d1-dbfe76afb1f0.png)

**Comment by andreakarasho** [comment]
In local it works.
I should try it out on your server guys

**Comment by andreakarasho** [comment]
should be fixed.
