### ISSUE TITLE
Odd graphic tiles displayed next to character in certain locations

### ISSUE THREAD

**Issue by Agetian** [ClassicUO/ClassicUO#888]
**Describe the bug**
In certain locations (mostly around stairs, it seems, and also inside some buildings), an odd tile is displayed next to the character, which may appear or disappear as you walk in different directions, or change shape.

**To Reproduce**
Go to New Haven, go towards the bank near the spawn location. Around the stairs, as well as inside the bank, the issue will manifest itself.
This is tested with ClassicUO running on client files 7.0.82.17 (official classic client). Tried both with the latest released beta (0.1.2.2) and with the current upstream master that I compiled myself.

**Expected behavior**
There should be no strange glitchy tiles near the character. Tested with the same official classic client 7.0.82.17 and the issue does not manifest itself.

**Screenshots**
(Check the strange angular tile to the bottom left of where the character is, in the middle of the red-tiled area).
![weird-gfx-issue](https://user-images.githubusercontent.com/24357441/71599796-5cf90d00-2b5d-11ea-9e46-59516588bdf4.jpg)

**Desktop (please complete the following information):**
- OS: Linux Mint 18.3 with Mono 6.6.0.161.
- ClassicUO v0.1.2.2 Beta and ClassicUO git (upstream master)

**Comment by Stallind** [comment]
Fine here https://gyazo.com/53c6e9d1987361c9f1b83c37e0c4d453
Maybe your art files are modified wrongfully?

**Comment by Agetian** [comment]
Hmm, I'm using the stock client, and interestingly enough, it's alright with the official classic client executable, but to eliminate the possibility of some corruption, I'll try a fresh install of the current UO client and see if that plays better for me, I'll report back once I do.

**Comment by Agetian** [comment]
This was definitely closed prematurely, the issue persists after a complete reinstall. Also, it's clear that it's a ClassicUO issue, since the same client files work correctly on the official client executable. 

Here's a screenshot showing the issue on a fresh install of 7.0.82.17 when using ClassicUO (this is the "dev" branch, but it's the same on stock 0.1.2.2 beta):
![classic-uo-glitch](https://user-images.githubusercontent.com/24357441/71611279-b5093100-2ba8-11ea-9a16-6e75e24edd9a.jpg)

Here's the same place using the standard UO classic client 7.0.82.17 executable, no glitch:
![classic-client-no-glitch](https://user-images.githubusercontent.com/24357441/71611291-c6523d80-2ba8-11ea-95fa-7e9593a131ff.jpg)

To exclude the possibility of the server doing something funny, I also completely regenerated the world, it made no change whatsoever. I'm using stock ServUO by the way, the newest version.

**Comment by Agetian** [comment]
Updating the client to 7.0.83.27 doesn't help, too (same issue - glitchy on ClassicUO, normal on official executable)

**Comment by Agetian** [comment]
Also, to exclude the possibility of it being a Linux-specific issue, I just tried it with the Windows version of ClassicUO running on .NET Framework v4.7, same issue.

What else can I try to mitigate this?

**Comment by andreakarasho** [comment]
It is a well-know issue, basically there is something wrong with sorting

**Comment by Agetian** [comment]
Ok, thanks a lot for the info! It's interesting that it doesn't seem to happen for Stallind, as demonstrated on the animated screenshot above, I wonder why :/ For me it consistently happens on all versions of the game I tried. Anyhow, glad to know you're aware of the issue :)
