### ISSUE TITLE
Merchant Sell Names Missing

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#889]
I updated today and I see this in the merchant sell screen...

It seems to handle items I name in scripts but these regs get the name from the TILEDATA.

![image](https://user-images.githubusercontent.com/49735284/71636856-0262be00-2bfc-11ea-8018-4e032bb54a1a.png)

**Comment by andreakarasho** [comment]
Does not work with all vendors?

**Comment by Djeryv** [comment]
It isn't doing it now. Should we just close this and see if it happens again? Because if I can't reproduce it then I call it a fluke.
