### ISSUE TITLE
Containers & containers.txt

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#890]
So some of the gumps I am using are working as intended with the format of the file for containers.txt. These seem to be the rectangle ones in a landscape view but it may have nothing to do with it. I chose one that was not working correctly...the giant backpack.

![image](https://user-images.githubusercontent.com/49735284/71756265-80b99d00-2e54-11ea-95f2-db4de66fb58f.png)

**Comment by Djeryv** [comment]
I provided the x,y coordinates of the top left and bottom right. If I do the math I should be using the width and height of 292 and 195...but it will only work correctly if I use the bottom right x,y values.

So I am not sure why some behave as you intended while others have this odd behavior.

**Comment by andreakarasho** [comment]
fixed the notation.
Thank
