### ISSUE TITLE
Container.txt Addon

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#892]
FEATURE REQUEST: I would like to see if ClassicUO can not only read the information in the "containers.txt" file in the "Client\Data" folder...but also read a "containers.txt" file from wherever the settings.json path is pointing to. So basically it reads the file from the ClassicUO release, and allows shard admins to add extra containers (unique to their shards) in their custom client's "containers.txt" file if they choose to create one (like myself). Then our custom entries in our "containers.txt" file will be preserved in case some update to CUO changes/replaces the "containers.txt" file in "Client\Data".

**Comment by andreakarasho** [comment]
This is exactly the target of containers.txt: it allows server owners to customize containers.

ClassicUO will not delete/update your containers.txt until it exists into Data/Client folder

**Comment by Djeryv** [comment]
But let's say I have a custom client someone downloads...but it does not include CUO files because they should choose to use CUO and then go get the latest from the source. If CUO looks in my custom clients game directory, and sees that I placed my own containers.txt in there, it would read that as well as CUO's containers.txt in its own directory.

Otherwise, I would have to give instructions to players to copy my containers.txt file and paste it in their CUO "Client\Data" directory and overwrite it...if they chose to download CUO and use that.

So I cannot control or determine if a player is using CUO or where they put their CUO files...but since the settings.json is looking for my custom client directory...I can control that and place my custom containers.txt file in there and have it always be read in conjunction with Client\Data\containers.txt from CUO.

I am simply sharing the shard admin perspective on how they distribute their clients and manage the changes.

**Comment by Djeryv** [comment]
Perhaps instead of having it read...

**string path = Path.Combine(CUOEnviroment.ExecutablePath, "Data", "Client");**

...it could just always read from the settings.json setting...

**"ultimaonlinedirectory": "C:\Ultima Online",**

**Comment by andreakarasho** [comment]
If you are a server owner, my suggestion is to make a ClassicUO package with your custom settings and stuff.
I've 2 valid reasons why you should do it:
- In this way cuo will read your custom containers.txt without making a new one.
- The end user will not need to configure the settings.json [i'll drop the support to it probably]

**Comment by Djeryv** [comment]
We can close this.
