### ISSUE TITLE
Hold Tab for Combat

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#893]
VERY MINOR REQUEST: Can we have this particular option "unchecked" by default? I am really not sure if anyone has ever played this way and I think it is just something that was there since the early days of the game. I only asked a few people in the community, but all of them uncheck this when they start a new character.

![image](https://user-images.githubusercontent.com/49735284/71766348-b007f280-2ec4-11ea-9ccd-2e083795bb41.png)

**Comment by andreakarasho** [comment]
I prefer to maintain the standard client behaviour as default

**Comment by Djeryv** [comment]
No worries.
