### ISSUE TITLE
Double click too sensitive to minor mouse jitter in between clicks

### ISSUE THREAD

**Issue by Agetian** [ClassicUO/ClassicUO#895]
**Is your feature request related to a problem? Please describe.**
Currently ClassicUO seems super sensitive to how double clicks are performed. You have to be dead precise in clicking the button twice without moving the mouse even a single pixel. If the mouse moves even a tiny bit while the second click is being made, it is treated as a single click, not as a double click. This is very hard to get used to, especially with sensitive high dpi mice, and leads to many misclicks, which is especially aggravating in combat.

**Describe the solution you'd like**
Perhaps it's possible to introduce a (configurable) option for the period and/or mouse jitter distance which is allowed for double clicks? This should help minimize potential misclicks while still allowing the client to feel responsive.

**Describe alternatives you've considered**
Nothing came to mind. I tried playing with my mouse sensitivity controls but that didn't amount to anything acceptable.

**Additional context**
The relevant code appears to be in GameController SDL2 mouse event handler and also in Mouse.cs in Input and it appears to be quite unforgiving when it comes to jitter during double clicks.

**Comment by Agetian** [comment]
It looks like introducing a tiny delay to IsDragging in Mouse.cs allows to mitigate this,e.g. in Mouse.Update:

`            IsDragging = (LButtonPressed && LastLeftButtonClickTime + MOUSE_DELAY_DOUBLE_CLICK / 4 < SDL.SDL_GetTicks()) || RButtonPressed || MButtonPressed;
`

 Perhaps if this setting and the double click delay were configurable, it could allow enough flexibility in how to tune this for each particular player (and the mouse that they use).

**Comment by andreakarasho** [comment]
Can you give me an example when it happens?
When i do:
- click on an object
- move mouse fast to another object
- click to that object
= d clicked

**Comment by Agetian** [comment]
Sure, for me I don't really have to do anything special, just play normally and try double clicking things, e.g. containers to open them, monsters to attack them (seems to happen less often when I double click the monster's health bar than when I double click the monster itself, but it may be subjective), items in my inventory to use them (e.g. bandages), that kind of thing. I don't really have to deliberately move my mouse to make it happen. What seems to happen is the following:

* I left click once. At this point, I notice a single pixel movement of the mouse, potentially happening from the higher dpi of the mouse (that's my guess anyway).
* I left click the second time, but the click is not registered as a double click, and instead a single click is performed.

This is especially easy for me to notice with vendors in towns. When you double click them, their paperdoll should pop up, and when you single click them, their context menu should pop up. What happens for me is that about 30-40% of the time, a double click will result in the context menu popping up, and the rest of the time the paperdoll will pop up.

I tried debugging this and I'm pretty positive that it happens due to the way IsDragging is implemented and treated in the mouse handler. Basically, IsDragging is set whenever a button is pressed, with no relation to the possibility of the double click (the line referenced above in Mouse.Update). Then, the other code (most notably SDL_MOUSEBUTTONDOWN handler in GameController) interprets it in such a way that it should reset the time for double clicks when the mouse button is not down (e.g. lines 606-609 in GameController), which effectively cancels the double click. Note that _dragStarted is set to true on mouse motion in SDL_MOUSEMOTION handler in GameController, which interacts with the above-mentioned "dragging" code (depends on whether IsDragging is set).

I don't know how specific this behavior is to a particular hardware mouse, I'm using a Logitech M705 for the record. It's a rather sensitive mouse that's a bit difficult to be absolutely pixel-precise with when it comes to double clicks, so a single pixel jitter during or in between the two clicks is rather likely, at least for me. If I get a chance to test this with a different mouse, I'll report back as to how it works for me as well. I'm also not sure how specific this behavior is to the implementation of mouse movement under Linux, which is the primary OS I'm using - if I get a chance to test on Windows any time soon, I'll also report back.

**Comment by Agetian** [comment]
Btw, comparing the default way ClassicUO handles double click with the way the official client does it, there is definitely some kind of a minor delay in the official client before the dragging starts (e.g. when it comes to inventory items), possibly to offset for the possibility of double clicking (though there's no way to tell without reverse engineering the code). It feels a bit less responsive when it comes to dragging but clicking and double clicking is always precise for me. That's why I mentioned in my original request that maybe it could be a configurable option (as to how much of a tolerance would be allowed in between clicks before dragging starts), with 0 being the default option if that's what works well for most people on most mice and with the possibility to go up to something like 100 ms or whatever for highly sensitive configurations where jitter tends to break double clicks :) In my experiments, even something like 60-80 ms of a tolerance period between clicks when IsDragging doesn't yet kick in tends to fix the issue.

**Comment by andreakarasho** [comment]
I pushed a fix on dev branch. Can you test it?

**Comment by Agetian** [comment]
Sure thing, testing it right now. It's definitely a big improvement when it comes to double clicking, I believe it fixes the issue. However, there are two problems that I can see with the fix:
- For some reason, it changes the behavior of drag-release for items. I can no longer release the dragged item by just releasing the left mouse button, I have to click it an additional time to release the item (to reproduce: open your backpack, start dragging an item by holding the LMB over it, move it around, then release the LMB. The item is not dropped at that point, you're still holding on to it until you press LMB again). This is different from how it was before.
- There are some debug messages in the console that will probably need to be removed.
Otherwise, looking good! :) Thanks a lot for the effort to fix this!

**Comment by Agetian** [comment]
Tested after the item drop fix, seems to work well :)

**Comment by andreakarasho** [comment]
nice!
