### ISSUE TITLE
No spells listed in mastery book

### ISSUE THREAD

**Issue by EquinoxQNX** [ClassicUO/ClassicUO#897]
No spells listed in mastery book.

1. Read some mastery primers such as Swordsmanship Mastery
2. Get your related skills to min 90, prefereably 120
3. Single click on mastery book, choose Switch Mastery
4. Select mastery
5. Double click on mastery book

There should be all mastery spells listed on left, active and passives of activated mastery on right. 

View in ClassicUO
![image](https://user-images.githubusercontent.com/49026539/71892551-430d8a80-315a-11ea-8a66-1d7fed349dd0.png)

View in regular client (Swordsmanship Mastery)
![image](https://user-images.githubusercontent.com/49026539/71892836-1148f380-315b-11ea-9851-c6ebc9e7a59c.png)

 - OS: Windows 10
 - Browser: Not related
 - Version: Beta - 0.1.2.2

https://uo.com/wiki/ultima-online-wiki/skills/skill-masteries/
http://www.uoguide.com/Skill_Mastery

**Comment by andreakarasho** [comment]
Mastery book is available in dev version.
It does not show the abilities icons like pic above, but you can drag and cast spells

**Comment by EquinoxQNX** [comment]
How can I use latest dev version? I've cloned and build latest master but it's old...

**Comment by Stallind** [comment]
@EquinoxQNX https://ci.appveyor.com/project/andreakarasho/classicuo/build/artifacts

**Comment by EquinoxQNX** [comment]
@Stallind thank you for sharing... I've installed and started using it...

@andreakarasho you are doing a great job, I feel like I'm playing UO first time... Really amazing!!!

**Comment by andreakarasho** [comment]
Added the current masteries icons active on the right side in dev.
I mark this issue as done.
