### ISSUE TITLE
Mastery bufficons doesn't shown in buff bar

### ISSUE THREAD

**Issue by EquinoxQNX** [ClassicUO/ClassicUO#898]
Mastery buff icons doesn't shown in buff bar

1. Read some mastery primers such as Swordsmanship Mastery
2. Get your related skills to min 90, prefereably 120
3. Single click on mastery book, choose Switch Mastery
4. Select mastery
5. Open Buff Bar

There should be passive mastery bonus icon displayed on Buff Bar as default. Actives should be displayed on use if applicable.

Regular client
![image](https://user-images.githubusercontent.com/49026539/71892802-f24a6180-315a-11ea-9b96-e47109e8c3ab.png)

Classic UO
![image](https://user-images.githubusercontent.com/49026539/71893398-9aacf580-315c-11ea-8671-afe7bd249efb.png)

- OS: Windows 10
- Browser: Not related
- Version: Beta - 0.1.2.2

**Comment by andreakarasho** [comment]
fixed in dev
