### ISSUE TITLE
City Trade Buff shown double on login

### ISSUE THREAD

**Issue by EquinoxQNX** [ClassicUO/ClassicUO#899]
City Trade Buff shown double on login.

1. Activate a City Trade Buff
2. Open Buff Bar
3. Logout
4. Login

There should be only one City Buff icon.

ClassicUO
![image](https://user-images.githubusercontent.com/49026539/71893746-8caba480-315d-11ea-8496-033d512537b8.png)

Regular client
![image](https://user-images.githubusercontent.com/49026539/71893722-7bfb2e80-315d-11ea-9026-ae1f06e06d9a.png)

OS: Windows 10
Browser: Not related
Version: Beta - 0.1.2.2

**Comment by andreakarasho** [comment]
fixed
