### ISSUE TITLE
ClassicUO fails to load if you're missing an anim*.idx file

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#90]
With the installation of UOR, the following files exist:

- anim.idx
- anim4.idx
- anim5.idx

In Animation.cs, lines 140-149 assume that you have anim, anim2, anim3, anim4, and anim5.

1. Delete/rename of of the anim*.idx files
2. Run ClassicUO
3. Observe error

**Expected behavior**
ClassicUO can handle data directories that don't come with all of the anim* files.

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: master branch, 5.0.8.3 of client from UOR

**Comment by andreakarasho** [comment]
fixed with: https://github.com/Pack4Duck/ClassicUO/commit/e05988b7b25c9570e16f1637160d5758cf5c6bdd
