### ISSUE TITLE
Wrong icon for Double Strike

### ISSUE THREAD

**Issue by EquinoxQNX** [ClassicUO/ClassicUO#900]
Wrong icon for Double Strike. Double Shot icon is used instead of the right one.

1. Get a Double Axe on hand
3. Open Weapon Abilities book

http://www.uoguide.com/Double_Strike

ClassicUO
![image](https://user-images.githubusercontent.com/49026539/71895737-ed89ab80-3162-11ea-9cb4-a599fb9d1dc3.png)

Regular Client
![image](https://user-images.githubusercontent.com/49026539/71895767-02fed580-3163-11ea-923e-a841d61a55c3.png)

OS: Windows 10
Browser: Not related
Version: Beta - 0.1.2.2

**Comment by Stallind** [comment]
Thanks,  fixed in dev
