### ISSUE TITLE
UOAM no longer working

### ISSUE THREAD

**Issue by mtbrasher** [ClassicUO/ClassicUO#901]
**Describe the bug**
UOAM had been functioning normally (as long as an OSI client.exe is running in background) until a recent dev branch commit. UOAM now hangs shortly after loading and "ERROR | Attempted to register command: '0' twice." is spammed in ClassicUO debug window until UOAM is force closed.

**To Reproduce**
Start client.exe
Start ClassicUO (Razor auto loads)
Start UOAM

**Expected behavior**
UOAM to load normally and player tracking to lock onto most recently opened ClassicUO instance

**Screenshots**
![image](https://user-images.githubusercontent.com/59674863/72032643-987a9200-3255-11ea-871d-ded5ec3ecb35.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903

**Additional context**
UOAM tracking was functioning well even with multiple ClassicUO instances open. 
Tracking still working on a laptop with older version of ClassicUO (2ec83e93532af4cc8baf50f3602488c6bcfdeb26)

**Comment by andreakarasho** [comment]
fixed thanks
