### ISSUE TITLE
Wrong informations on hover on spell icons

### ISSUE THREAD

**Issue by EquinoxQNX** [ClassicUO/ClassicUO#902]
Wrong informations on hover for spell icons. 
Chivalry: Irrelevant text shown, should be spell name
Bushido: Irrelevant text shown, should be spell name
Necromancy: Nothing shown, should be spell name
Weapon Abilities: Nothing shown, should be ability name

1. Drag and drop icons to the desktop
2. Bring mouse cursor on icons

ClassicUO
![image](https://user-images.githubusercontent.com/49026539/72195083-c9a7bd80-3421-11ea-8c4a-65bad74fd352.png)
![image](https://user-images.githubusercontent.com/49026539/72195089-d0cecb80-3421-11ea-9da4-7a0e51b8142a.png)

Regular client
![image](https://user-images.githubusercontent.com/49026539/72195124-fd82e300-3421-11ea-81f0-f29249614313.png)
![image](https://user-images.githubusercontent.com/49026539/72195134-0a9fd200-3422-11ea-9ccf-17ba31a6d2a4.png)
![image](https://user-images.githubusercontent.com/49026539/72195143-15f2fd80-3422-11ea-8d0d-ed98a52b4d82.png)
![image](https://user-images.githubusercontent.com/49026539/72195152-24d9b000-3422-11ea-93f2-2efa3f13c620.png)

 - OS: Windows 10
 - Version 0.1.2.2

**Comment by andreakarasho** [comment]
already fixed in dev
