### ISSUE TITLE
Desktop icons doesn't became activated when related action used by RazorEnchanced macro

### ISSUE THREAD

**Issue by EquinoxQNX** [ClassicUO/ClassicUO#903]
Desktop icons doesn't became activated when related action used by RazorEnchanced macro. Including any Bushido spell icons and any Weapon Ability icons. Probably Swords master Onslaught  spell icon.

1. Add some icons for bushido spells and weapon abilities to the desktop
2. Run related macro on Razor Enhanced, such as:
Spells.CastBushido('Lightning Strike')
Spells.CastBushido('Confidence')
Spells.CastMastery('Onslaught')
Player.WeaponPrimarySA()
Player.WeaponSecondarySA()

or create a spell grid from Razor Enhanced, add spells and abilities to it, then use them by click

![image](https://user-images.githubusercontent.com/49026539/72195980-55234d80-3426-11ea-8c01-b082caf9ee28.png)
![image](https://user-images.githubusercontent.com/49026539/72196051-aaf7f580-3426-11ea-9313-9e6007cfa59e.png)

Needs to be:

![image](https://user-images.githubusercontent.com/49026539/72196138-438e7580-3427-11ea-9172-e282065ca4c3.png)

 - OS: Windows 10
 - Version 0.1.2.2

**Comment by andreakarasho** [comment]
Added the spell highlighting support, cause it is a server side stuff and ClassicUO ignored it.
About abilities i can do nothing because server sends nothing to figure out if ability is on, it sends only a reset. Infact the same behaviour happens with other assistants too with standard client.
I mark this as done

**Comment by EquinoxQNX** [comment]
You're right about abilities. It doesn't highlight desktop ability icons even in OSI when I tried with UOSteam.

Other icons works like a charm on ClassicUO Dev Preview, thank you.
