### ISSUE TITLE
Virtual Machine compatibility

### ISSUE THREAD

**Issue by SkoDave** [ClassicUO/ClassicUO#905]
**Describe the bug**
I was not able to run correctly the client inside a Virtual Machine

**To Reproduce**
Install and run the client The Miracle server http://themiracleshard.com/file/TheMiracle3New.exe inside a Virtual Machine.

**Screenshots**
![loginVBox](https://user-images.githubusercontent.com/13698496/72207671-8722c700-349b-11ea-946f-8da43a987360.PNG)
![loginVMware](https://user-images.githubusercontent.com/13698496/72207672-8722c700-349b-11ea-92ba-77883ff69e3f.png)

**Desktop (please complete the following information):**
Windows 7 installed in VirtualBox 6 or VMWare 11
.NET Framework 4.8 and VisualC++ (2015-2019) redist. installed
2d and 3d graphics enabled on VBox6, 3d graphics enabled on Vmware11

**Additional context**
Inside VirtualBox 6 the client window is formed by big pixels (check loginvbox screenshot)
Inside VMWare 11 the client is "topdown" (check loginVmware screenshot)

**Comment by andreakarasho** [comment]
VMs don't support graphic driver conversion correctly and they might generate artifacts like above.
I can do nothing about.

Just FYI ClassicUO is crossplatform. You can run it on Windows, Linux and MacOS.
