### ISSUE TITLE
Some menu items  on City Stone needs to be disabled for unauthorized players

### ISSUE THREAD

**Issue by EquinoxQNX** [ClassicUO/ClassicUO#906]
All menu items look like available in the city stone menu even if you have not authorized to related action. I seems available by don't any action as it should be.

1. Go to any City Stone which you are not the Governor
2. Click on the stone

Menu items of unauthorized actions should be disabled.

ClassicUO

![image](https://user-images.githubusercontent.com/49026539/72218592-6ca92600-354d-11ea-8806-f42a39bf2671.png)

Regular UO

![image](https://user-images.githubusercontent.com/49026539/72218600-8c404e80-354d-11ea-9ca3-eaba6f25aa8e.png)

 - OS: Windows 10
 - Browser: Not Related
 - Version: 0.1.2.2

**Comment by andreakarasho** [comment]
Odyssey?

**Comment by andreakarasho** [comment]
fixed
