### ISSUE TITLE
Last target

### ISSUE THREAD

**Issue by natryl** [ClassicUO/ClassicUO#909]
Last target macro in original client can target ground tiles while in classicuo that is not the case. I tested with a simple macro that works just fine on the original client.

https://cdn.discordapp.com/attachments/132639701810151425/660018879984041986/lastuo.JPG
https://cdn.discordapp.com/attachments/132639701810151425/660019303747289149/lastuo2.JPG
vs
https://cdn.discordapp.com/attachments/132639701810151425/659996586616815616/lastlastuoR.JPG

**Comment by andreakarasho** [comment]
Pushed a fix in dev. Tested in local and seems good! 
Let me know :)

**Comment by natryl** [comment]
Seems fixed to me! Thanks.
