### ISSUE TITLE
ClassicUO fails to open if you don't have 6 map#.mul files

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#91]
**Describe the bug**
ClassicUO requires 6 map files, but for UOR at least, it only had 1 map file (map0.mul).

**To Reproduce**
1. Remove all your maps except map0.mul
2. Run ClassicUO
3. See error

The error happens in Map.cs, and if MAP_COUNTS is set to 1, and MapsDefaultSize is set to just one size, it will continue to load.

**Expected behavior**
ClassicUO should allow 1-6 map files and continue to load.

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: UOR 5.0.8.3

**Additional context**

**Comment by andreakarasho** [comment]
fixed with: https://github.com/Pack4Duck/ClassicUO/commit/e05988b7b25c9570e16f1637160d5758cf5c6bdd
