### ISSUE TITLE
Cannot browse to the second page of the loot grid

### ISSUE THREAD

**Issue by EquinoxQNX** [ClassicUO/ClassicUO#911]
**Describe the bug**
Cannot browse to the second page of the loot grid, next page button is present but not clickable

**To Reproduce**
1. Just open a corpse with lots of loot items

**Expected behavior**
Next page button should be clickable if there is next page

**Screenshots**
![image](https://user-images.githubusercontent.com/49026539/72680599-bb663b00-3acc-11ea-9f04-fad7c3ee47c0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Not related
 - Version: 0.1.2.1131

**Comment by keenerb** [comment]
I have the same problem.

**Comment by andreakarasho** [comment]
fixed in dev
