### ISSUE TITLE
No tooltips in Vendor search menu / UOStore

### ISSUE THREAD

**Issue by Meireffer** [ClassicUO/ClassicUO#913]
When using vendor search, none of displayed items have tooltips, making it impossible to check what's being sold (only way is to get map to vendor and check manualy, can be annoying after a while).

Steps to reproduce?
1. Open Vendor Search
2. Search for any item
3. Hover mouse over item
4. No tooltip displayed.

I did check on both classic and enhanced client. Both work fine with tooltips on that server.

Also some items in UOStore are missing tooltips (which are available in classic 2d and 3d clients). Can provide exact item names if needed.

**Comment by andreakarasho** [comment]
any sample?

**Comment by andreakarasho** [comment]
fixed
