### ISSUE TITLE
Crash when client files are too old?

### ISSUE THREAD

**Issue by Agetian** [ClassicUO/ClassicUO#915]
**Describe the bug**
I'm experimenting with some of the older shard code bases intended to run on older clients, including pre-AoS ones. I decided to give ClassicUO a try and see if it supports those older client files, judging by the description in the readme that states that ClassicUO is intended to emulate all standard client versions, not listing the minimum supported version. So far I tried quite a few old UO clients ranging from 2.0.3 to 4.0.0a (including the 3.0.x series), and none of them worked, crashing ClassicUO at startup with the same error. I intend to try the 5.x series next (Mondain's Legacy), but haven't done so yet.

The crash text is as follows, indicating that it has something to do with loading and visualizing the login gump:

```
13:05:57 |  Error   | System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.UI.Controls.GumpPicTiled.set_Graphic(UInt16 value) in c:\projects\classicuo\src\Game\UI\Controls\GumpPicTiled.cs:line 79
   at ClassicUO.Game.UI.Gumps.Login.LoginBackground..ctor() in c:\projects\classicuo\src\Game\UI\Gumps\Login\LoginBackground.cs:line 42
   at ClassicUO.Game.Scenes.LoginScene.Load() in c:\projects\classicuo\src\Game\Scenes\LoginScene.cs:line 102
   at ClassicUO.GameController.SetScene(Scene scene) in c:\projects\classicuo\src\GameController.cs:line 155
   at ClassicUO.GameController.LoadContent() in c:\projects\classicuo\src\GameController.cs:line 127
   at Microsoft.Xna.Framework.Game.Initialize()
   at ClassicUO.GameController.Initialize() in c:\projects\classicuo\src\GameController.cs:line 104
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Client.Run() in c:\projects\classicuo\src\Client.cs:line 77
   at ClassicUO.Bootstrap.Main(String[] args) in c:\projects\classicuo\src\Main.cs:line 159
```

**To Reproduce**
1. Install an old Ultima Online standard client (at least 2.x.x - 4.x.x series).
2. Configure ClassicUO to point to its directory and specify the necessary version in settings.json.
3. Start ClassicUO.
4. At this point, the game will crash before getting to the login screen.

**Expected behavior**
I'm not sure if ClassicUO is even meant to support clients that old, but it's a good idea to either specify the minimum supported client version (if known, or at least the major version that's expected to work as the bare minimum) in case it's not meant to work, and perhaps implement an error message in case the user tries to start the game with a client file set that's too old and unsupported, or, if it's meant to work, then the crash issue needs to be fixed in such a way that ClassicUO can start up correctly with these files.

**Screenshots**
N/A, nothing is shown except for the crash window, the contents of which are described above.

**Desktop (please complete the following information):**
 - OS: tried on both Linux Mint 18.2 and on Windows 8.1.
 - Version: current upstream "dev" branch of ClassicUO

**Comment by andreakarasho** [comment]
- Do you use the original files? Any mod?
- Link to download the old standard client?

**Comment by Agetian** [comment]
Yes, they are unmodded original clients, as far as I can tell. Here's a link to my Dropbox with UO v4.0.0a client files that I tried last: 
https://www.dropbox.com/s/hoji9x4pbud2v37/UO_4.0.0a.zip?dl=0
The original client works perfectly well, but the files crash when used with ClassicUO.

I can upload the other client files if necessary too.

This resource has links to 4.0.6a and 4.0.11c, though I haven't tried them personally yet:
https://www.servuo.com/threads/poor-mans-uo-resource.1739/

**Comment by andreakarasho** [comment]
Pushed a fix in DEV. Let me know if it works

**Comment by Agetian** [comment]
It seems like it gets a little bit further, but then crashes at a different point:
```

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ClassicUO.Game.UI.Controls.Button.set_ButtonGraphicNormal(UInt16 value) in c:\projects\classicuo\src\Game\UI\Controls\Button.cs:line 132
   at ClassicUO.Game.UI.Gumps.Login.LoginGump.Update(Double totalMS, Double frameMS) in c:\projects\classicuo\src\Game\UI\Gumps\Login\LoginGump.cs:line 297
   at ClassicUO.Game.Managers.UIManager.Update(Double totalMS, Double frameMS) in c:\projects\classicuo\src\Game\Managers\UIManager.cs:line 795
   at ClassicUO.GameController.Update(GameTime gameTime) in c:\projects\classicuo\src\GameController.cs:line 275
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Client.Run() in c:\projects\classicuo\src\Client.cs:line 77
   at ClassicUO.Bootstrap.Main(String[] args) in c:\projects\classicuo\src\Main.cs:line 159

```

**Comment by andreakarasho** [comment]
I dclick client.exe and it crashes too

**Comment by Agetian** [comment]
It could be because the registry entries are not set up for you. Older UO clients required some registry entries to be set up in order to find the necessary data files, otherwise they wouldn't work. You can try installing older UO from one of those .iso images I linked above (on Poor Man's UO Resource), that should set up the registry entries.

**Comment by Agetian** [comment]
Alternatively, here are the contents of a regedit .reg file that can be tweaked to point at the UO client directory:

32-bit Windows:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Origin Worlds Online]

[HKEY_LOCAL_MACHINE\SOFTWARE\Origin Worlds Online\Ultima Online]

[HKEY_LOCAL_MACHINE\SOFTWARE\Origin Worlds Online\Ultima Online\1.0]
"ExePath"="[your client path]\\client.exe"
"InstCDPath"="[your client path]"
"PatchExePath"="[your client path]\\uopatch.exe"
"StartExePath"="[your client path]\\uo.exe"
```

64-bit Windows:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Origin Worlds Online]

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Origin Worlds Online\Ultima Online]

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Origin Worlds Online\Ultima Online\1.0]
"ExePath"="[your client path]\\client.exe"
"InstCDPath"="[your client path]"
"PatchExePath"="[your client path]\\uopatch.exe"
"StartExePath"="[your client path]\\uo.exe"
```

**Comment by Agetian** [comment]
By the way, on that note, I tested 4.0.6a (Ultima Online Gold) from that link above and it works. Will see if I can test some more earlier versions from original .iso installations shortly.

**Comment by Agetian** [comment]
Version 3.0.6j also works when installed from an .iso file (Lord Blackthorn's Revenge). Hmm, this might signify that my v2.0.3 and v4.0.0a copies may be somehow "broken" in a subtle way, though I can't imagine what's wrong with them and they work correctly for me when run via client.exe :/

**Comment by andreakarasho** [comment]
Yes it works

**Comment by Agetian** [comment]
Ok, I definitely get the "crash" behavior if I install The Second Age (v1.26.0) from the original CD and try that with ClassicUO (the same login gump crash as referenced before). This is from the official installation CD, so the copy shouldn't be broken or tampered with in any way.

**Comment by andreakarasho** [comment]
Now should be fine
![image](https://user-images.githubusercontent.com/20810422/73021813-9ce3a500-3e28-11ea-8202-e059296ed2c8.png)

**Comment by Agetian** [comment]
I can confirm that this works fine now :) Thanks!
