### ISSUE TITLE
Negative values are corrupted on Character Status

### ISSUE THREAD

**Issue by EquinoxQNX** [ClassicUO/ClassicUO#917]
**Describe the bug**
Negative values are corrupted on Character Status such negative Defence Chance Increase

**To Reproduce**
1. Cast Divine Fury on a char with 0 DCI

**Expected behavior**
It should be displayed a correct negative value.

**Screenshots**

![image](https://user-images.githubusercontent.com/49026539/73017084-39f60c00-3e30-11ea-9bd8-f5e12bcb30ea.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Not related
 - Version 0.1.2.1171

**Comment by andreakarasho** [comment]
should be fine now

**Comment by EquinoxQNX** [comment]
Yes, it is, thank you.

![image](https://user-images.githubusercontent.com/49026539/73065400-85ea9480-3eb4-11ea-9515-70b68c979396.png)
