### ISSUE TITLE
Item names missing when selling on Pre-AoS code bases

### ISSUE THREAD

**Issue by Agetian** [ClassicUO/ClassicUO#919]
**Describe the bug**
When running ClassicUO with older pre-AoS RunUO servers, certain item names seem to be missing when selling items. For example, I'm running the old UOGamers Rebirth Release3 server (a version available here: https://github.com/zerodowned/Rebirth-Repack ) with client 7.0.15.1. When connecting to it with the original UO client, I get this when I "vendor sell" a cut of ribs to the butcher in Occlo:

![OrigUO-nobug](https://user-images.githubusercontent.com/24357441/73116494-39e92f80-3f48-11ea-9bb6-fbfa67060d32.png)

At the same time, when connecting with ClassicUO and doing the exact same thing, I get this kind of situation where the item name is missing:

![ClassicUO-bug](https://user-images.githubusercontent.com/24357441/73116503-48cfe200-3f48-11ea-9f45-bd42183b5ba3.png)

**To Reproduce**
1. Install the UOGamers Rebirth code base (or possibly another pre-AoS codebase). Start a character in Occlo (may be marked as Haven on the map).
2. Kill and skin a farm animal.
3. Try to sell the ribs to the butcher ("vendor sell").
4. Compare the original UO client and ClassicUO.

**Expected behavior**
The item name should be present in the vendor sell window, as in the original UO client.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.2 and Windows 8.1
 - ClassicUO "dev" git (current)

**Additional context**
I've seen this happen with other items as well, but not with everything. I can't figure out the pattern or determine what it's based on (whether the item name is present or not).

**Comment by andreakarasho** [comment]
pushed a fix

**Comment by Agetian** [comment]
Hmm, I still get the same issue... what's interesting is that the items in the buy list have names but items in the sell list don't :/  (even the cut ribs that I'm experimenting with)

**Comment by andreakarasho** [comment]
pushed another fix

**Comment by Agetian** [comment]
That definitely works :) Thanks for the fix!
