### ISSUE TITLE
Ingame music partly missing on some clients

### ISSUE THREAD

**Issue by Agetian** [ClassicUO/ClassicUO#921]
**Describe the bug**
On some clients (e.g. stock 7.0.15.1), some (most) of the music is missing for some reason. At first I thought it's a file naming issue on case-sensitive systems, but it's also true when running ClassicUO on Windows. For example, on the Angel Island server (https://github.com/Luke-Tomasello/Angel-Island/commits/master) running on included client 5.0.9.1 files in ClassicUO, the login music works correctly, but the ingame music mostly won't play at all. For instance, the in-town "turfin" music loop (turfin.mp3) doesn't play. Messing around with the Config.txt entry, removing the "loop", adding or removing the .mp3 extension in Config.txt don't seem to help. I made sure that the file is named correctly and even matches the case. The "combat music" that plays in the original client in war mode also doesn't play.

The same issue happens with the UOGamers Rebirth Release 3 server running on stock client 7.0.15.1, most ingame loops don't play (including "turfin").

Attempting to debug this, I added a log line in UOMusic.cs when the path is constructed and the file is about to be loaded, I can confirm that the path to the file is constructed correctly.

**To Reproduce**
1. Try going ingame with the 7.0.15.1 client and one of the compatible server code bases (something RunUO 2.2-based, I believe), or the Angel Island server with the included 5.0.9.1 client..
2. The town music (typically turfin.mp3) doesn't play on ClassicUO. The war mode music doesn't play either.

**Expected behavior**
The music should play, as it does in the original client.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Linux Mint 18.2 and Windows 8.1.
- Version: current "dev" branch

**Comment by VoxelBoy** [comment]
Can you see if commenting out the following line in Sound.cs does anything for you?
`if (_lastPlayedTime > now)
                return false;`
I had a few cases where login music played fine but game music didn't play because this statement was causing an early out. This line itself isn't the cause of the problem, but rather this one a few lines below, which seems to rely on high frame-rates to work reliably:
`_lastPlayedTime = now + Delay;`

**Comment by Agetian** [comment]
Yes, commenting that line out fixes the music for me, it plays normally.

**Comment by andreakarasho** [comment]
Thanks. I’ll fix it

**Comment by andreakarasho** [comment]
should be fine now

**Comment by Agetian** [comment]
It looks like it's fixed :) Thanks!
