### ISSUE TITLE
Incorrect values on character creation screen

### ISSUE THREAD

**Issue by Meireffer** [ClassicUO/ClassicUO#922]
When you try to create new character, you can notice that sum of skillpoints available to choose is incorrect. 
In normal clients (2d classic, 3d) you can select 2 skills with 50 points and have 20 poits left (120 total)
In CUO all you can get is 100 total.

Also, it's possible to select Spellweaving as a starting skill (which is not possible in official clients)
Because of that (my guess) you get a nice freeze on "Creating Character" screen.

![charcreate](https://user-images.githubusercontent.com/59940856/73132056-a9752280-400d-11ea-963d-c95c63b83182.png)

**Comment by andreakarasho** [comment]
should be ok now
