### ISSUE TITLE
Music issues, part 2: no war mode music, music transition issues

### ISSUE THREAD

**Issue by Agetian** [ClassicUO/ClassicUO#923]
**Describe the bug**
It looks like there are still some music issues remaining after the last fix went in. In particular, compared to the original UO client (e.g the latest current version 7.0.83.27 running on stock ServUO server):

1) The music doesn't transition between "war" and "peace" when you enter or leave war mode.
2) The music doesn't transition between various tunes in many cases, e.g. as you leave town and go into the wilderness and then back, in the original client the music will change, but in ClassicUO not necessarily so.

**To Reproduce**
1. Run the current UO client 7.0.83.27, e.g. on ServUO server.
2. Try the experiments above.

**Expected behavior**
The music should transition between tunes (war/peace, town/wilderness, etc.), as in the original UO client.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3 and Windows 8.1.
 - ClassicUO "dev" (current)

**Comment by Agetian** [comment]
By the way, it looks like the "Combat Music" option on the Sound tab doesn't do anything to change this behavior when it comes to war/peace music toggle.

**Comment by Agetian** [comment]
Another observation is that with ClassicUO, the town/wilderness music will make a transition sometimes, but it feels like it catches on slower than on the original client and doesn't always do so?..

**Comment by andreakarasho** [comment]
pushed a fix

**Comment by Agetian** [comment]
Combat music now works when war mode is toggled, but for some reason toggling it off (back to peace mode) stops the music completely until the soundtrack is changed. I had to leave town and then reenter town to make the town music play. Toggling combat on and then off again stops the music again until the same procedure is repeated.

**Comment by andreakarasho** [comment]
done

**Comment by Agetian** [comment]
Thanks a lot! :) I can confirm it's fixed.
