### ISSUE TITLE
Ninjitsu Animal Form Menu Non-Functional

### ISSUE THREAD

**Issue by TiffanyDiVita** [ClassicUO/ClassicUO#924]
**Describe the bug**
When standing still and casting the Ninjitsu "Animal Form" skill, you are presented with a menu of forms to transform into depending on your Ninjitsu skill.  When clicking any of the forms from the menu, nothing happens and the menu simply remains on screen.

**To Reproduce**
1. Cast the "Animal Form" Ninjitsu spell while your character is not moving.
2. Attempt to select any of the forms from the animal form menu.
3. Note the menu will remain on screen and you will not be transformed.

**Expected behavior**
The menu should disappear and your character should cast an attempt to transform into the selected animal form.

**Screenshots**
![anform](https://user-images.githubusercontent.com/5758780/73177002-c12fd200-4105-11ea-99bd-38551389d14d.png)

**Desktop (please complete the following information):**
 - OS: Win 8.1

**Additional context**
Using the latest dev build of the ClassicUO client emulating specified client version 7.0.83.27.

**Comment by andreakarasho** [comment]
Fixed in dev, thank you
