### ISSUE TITLE
Combat music option has no effect

### ISSUE THREAD

**Issue by Agetian** [ClassicUO/ClassicUO#926]
**Describe the bug**
The option in the Sound group called "Combat Music" seems to have no effect. Toggling it on or off has no effect on whether the combat music is playing when the war mode is toggled (if that was the intent of the option).

**To Reproduce**
1. Disable Combat Music in Sound options.
2. Switch to war and then to peace mode, the music changes between the two (but probably shouldn't if the option is disabled?)

**Expected behavior**
If I understand the intent of the option correctly, it was meant to disable the combat music toggle. If that's correct, then the music shouldn't switch between war and peace when this option is disabled.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3 and Windows 8.1
 - ClassicUO "dev" (current)

**Comment by andreakarasho** [comment]
done
