### ISSUE TITLE
Mac build fails because of newtonsoft.json / paket integration

### ISSUE THREAD

**Issue by ray77** [ClassicUO/ClassicUO#927]
Mac build fails because of newtonsoft.json. paket dependencies are not recognized by mono.
I installed everything (without any issue) as described under installation instructions mac. (brew, mono, paket)
output: Configuration/Profile.cs(37,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?) [/Users/jim/uo/src/ClassicUO.csproj]

```
source https://api.nuget.org/v3/index.json

storage: none
framework: netcore3.0, netstandard2.0, netstandard2.1
nuget Newtonsoft.Json 12.0.2
```

**Comment by roxya** [comment]
I think the issue is that paket puts dependencies in a directory with the name of the package, while nuget includes the version number. The csproj references Newtonsoft.Json.12.0.2

Try to rename the Newtonsoft.Json package dir to Newtonsoft.Json.12.0.2

**Comment by Lapin** [comment]
> I think the issue is that paket puts dependencies in a directory with the name of the package, while nuget includes the version number. The csproj references Newtonsoft.Json.12.0.2
> 
> Try to rename the Newtonsoft.Json package dir to Newtonsoft.Json.12.0.2

Where to find the dir for Newtonsoft.Json? There a few on mono's folder. I'm assuming I shouldn't be messing with those.

![Screenshot 2020-04-09 at 15 04 48](https://user-images.githubusercontent.com/1576470/78893302-cd280080-7a73-11ea-9523-f61362216d0f.png)
(that red error is a pretty long one tho, guessing every line of csproj is listed)

**Comment by roxya** [comment]
in the packages directory

**Comment by Lapin** [comment]
> in the packages directory

ok, sorry for the silly bump. I've noticed that I've been trying to run the game from build -_- I've followed the PLAY guide wiki and could able to launch it. So basically you can disregard my question lol. Sorry for that. Now I'll look if there's any workaround to launch either razor or uosteam.

**Comment by andreakarasho** [comment]
Newtonsoft.json is no longer supported
