### ISSUE TITLE
Changing accounts without closing the game makes the game crash (stop responding)

### ISSUE THREAD

**Issue by Excrementz** [ClassicUO/ClassicUO#944]
**Describe the bug**
Almost every time i play on UOF when i am on a character and have to swap for another character, the game get stuck and i need to close it and open again, UOS and standardt Razor works fine.

**To Reproduce**
1. 'log in'
2. play for five minutes
3. 'log out'
4. change character
5. window stop responding

**Screenshots**
![Bug 1](https://user-images.githubusercontent.com/33267698/74474332-0b45e100-4e84-11ea-9f23-6f0ba1c73869.png)

**Desktop (please complete the following information):**
 - UO: 7.0.45.0
 - UOC Version 0.1.3.41

**Comment by Excrementz** [comment]
Do not know if it is related or associated.

Sometimes when changing characters and it does not crash, instead the game audio does not work and i can not type anything, the only key that works (even hotkeys does not works) is Enter and it only brings Razor window up to focus.
![Bug 2](https://user-images.githubusercontent.com/33267698/74474620-a50d8e00-4e84-11ea-9dd1-59ea19c76709.png)

**Comment by andreakarasho** [comment]
Did you have multiples CUO instances open?

**Comment by Excrementz** [comment]
No, i did not. The bug is also present when i have multi-clients up. Each window will crash individually.

**Comment by Excrementz** [comment]
Found the problem: "use smart always stay on top", it caused both the crash's and the keyboard problem @andreakarasho, no idea why though.

**Comment by andreakarasho** [comment]
Post the issue here: https://github.com/markdwags/Razor
