### ISSUE TITLE
Containers on layers not showing in counters

### ISSUE THREAD

**Issue by fogliam** [ClassicUO/ClassicUO#945]
We have a quiver created on our shard that is worn on the Cloak layer and holds only arrows/bolts.  When the item (container) is inside the player's backpack, the counters will property pick up the arrow count, but if it is equipped and worn, the counters roll to zero.

Can the counters please detect containers worn on all layers other than the bank?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version RunUO 2.5

Should be a simple fix to include scanning on layers aside from the bank.

**Comment by andreakarasho** [comment]
done
