### ISSUE TITLE
Character automated movement when trying to face attacked mobile

### ISSUE THREAD

**Issue by HankTheDrunk** [ClassicUO/ClassicUO#948]
**Describe the bug**
With the recent _fix_ for turning the character towards the mobile it's attacking it's causing the character to automatically move into a tile position directly N,S,E or W of the mobile
It does not always happen but has never happened prior to this update.
I believe this is being caused by this addition
> turn to combat packet 

**To Reproduce**
1. Stand North West tile position from a mob facing away or south or east
2. Attack the mob
3. There is a chance the character will move a tile south or east instead of facing the mob

**Expected behavior**
Character is supposed to turn towards the mobile it's attacking but not move.

**Version**
Beta - 0.1.3.100

**Additional context**
Willing to record a video of it happening if needed.

**Comment by andreakarasho** [comment]
should be fixed in dev
