### ISSUE TITLE
Runebook recall/gate still casting despite moving cursor off icon

### ISSUE THREAD

**Issue by HankTheDrunk** [ClassicUO/ClassicUO#949]
**Describe the bug**
When you open a runebook and flip into it where you see the recall/gate spell icons. If you single left click still holding the left mouse button down and move the cursor off the icon it still casts the spell.

**To Reproduce**
1. Have a marked rune in a runebook
2. Go to the runebook page the rune at
3. Left click the recall spell icon still holding left mouse and drag your cursor off the icon before releasing

**Expected behavior**
If the cursor is not on the spell icon upon releasing it should not cast the spell

**Version**
Beta - 0.1.3.100

**Comment by andreakarasho** [comment]
should be ok now
