### ISSUE TITLE
Invisible interior of houses, furniture and characters after use [go to (it is possible that also teleportation spells)

### ISSUE THREAD

**Issue by LordFenris** [ClassicUO/ClassicUO#950]
**Describe the bug**
In the case of moving between locations with houses (by using the GMa [go to command and traveling from one location - the house to the other), the contents of the custom houses set in the destination location as well as the players located there are not displayed.

**To Reproduce**
1. Go to 'any house'
2. Use [Admin '....'
3.  Choose a specific player located in the house
4. select "go to"
5. When you reach the destination, you will see an empty foundation in the walls without doors, decorations inside and the target player

**Expected behavior**
You should see the interior of the building, home furnishings and the character in the house.

**Screenshots**
https://mega.nz/#!Yv5GHCbK!5lRpbSQjhwsLbJA9rjaAPL8vflX8Pkz3pXJBh3WF_3w

**Desktop (please complete the following information):**
 - OS: Server: Windows server 2019, Client - Win 10
 - Browser -  Edge MS
 - Version - 80.0.361.57

**Comment by LordFenris** [comment]
Same problem with journey via recall itp _ if player got a rune marked inside home.
The problem does not occur when I reach such a house on foot, or when I move away from it (when I cannot see the interior) and return again (then the interior appears).

**Comment by LordFenris** [comment]
Interestingly, the problem does not occur on the current (latest version) Enhanced Razor 0.7.5 and Razor 1.5.0.16 without ClassicUO

**Comment by andreakarasho** [comment]
I tested with ServUO Version 0.5, Build 7325.25513.
No issues :| 

Can you give access to your server?

**Comment by LordFenris** [comment]
I created a test GM Account for you -
Login: EDITED
Pass: EDITED

niedz., 23 lut 2020 o 15:04 Andrea Angelini <notifications@github.com>
napisał(a):

**Comment by LordFenris** [comment]
I will create an test Gm account for you - pass/login send via mail
Our how to play 
https://mmogspot.com/how-to-play-uo/
– IP : 195.201.167.253
– port: 2593

**Comment by LordFenris** [comment]
Latest ServUO code / UO version 7.0.83.27

**Comment by andreakarasho** [comment]
should be fixed

**Comment by LordFenris** [comment]
Movies: https://www.youtube.com/watch?v=ddqGn4rzLXg
https://www.youtube.com/watch?v=-CweGt078go&feature=youtu.be

**Comment by andreakarasho** [comment]
> should be fixed

^

**Comment by LordFenris** [comment]
Do you plan to release a revised version for general download (beta) with
this fix? I would not like to provide players with DEV versions - moreover,
a large part of them may not be able to do their own work with powershell.

niedz., 23 lut 2020 o 15:42 Andrea Angelini <notifications@github.com>
napisał(a):

**Comment by LordFenris** [comment]
Do you plan to release a revised version for general download (beta) with
this fix? I would not like to provide players with DEV versions - moreover,
a large part of them may not be able to do their own work with powershell.

---------- Forwarded message ---------
Od: T S <tomasz.k.sikorski@gmail.com>
Date: niedz., 23 lut 2020 o 17:35
Subject: Re: [andreakarasho/ClassicUO] Invisible interior of houses,
furniture and characters after use [go to (it is possible that also
teleportation spells) (#950)
To: andreakarasho/ClassicUO <
reply@reply.github.com>


Do you plan to release a revised version for general download (beta) with
this fix? I would not like to provide players with DEV versions - moreover,
a large part of them may not be able to do their own work with powershell.

niedz., 23 lut 2020 o 15:42 Andrea Angelini <notifications@github.com>
napisał(a):

**Comment by LordFenris** [comment]
Alternatively, he suggests replacing the last zip beta with the corrected version so that people who use the package as new don't experience this error anymore.
