### ISSUE TITLE
Item ID 0x9e7d is not visible

### ISSUE THREAD

**Issue by andreakarasho** [ClassicUO/ClassicUO#955]
shard: outlands
in backpack it's ok.

tiledata from 7.0.58.9
![image](https://user-images.githubusercontent.com/20810422/75387108-1a487c80-58e3-11ea-9ef3-cf89a48aaf8b.png)

tiledata from outlands installation:
![image](https://user-images.githubusercontent.com/20810422/75387186-3d732c00-58e3-11ea-9f1f-8891c4e5ed69.png)

**Comment by roxya** [comment]
https://github.com/andreakarasho/ClassicUO/blob/042efe0ab5e659e6ac6952e2388e2bbd8a6532b6/src/Utility/GameObjectHelper.cs#L33-L42

**Comment by andreakarasho** [comment]
Original client does not draw that object for some reason due to the tiledata.mul

**Comment by andreakarasho** [comment]
pushed a fix
