### ISSUE TITLE
Character Creation: Wrong map location

### ISSUE THREAD

**Issue by markdwags** [ClassicUO/ClassicUO#970]
**Describe the bug**
When you create a character with client version 5.0.8.3 on UOR, when you select the city, it will send you to the wrong location.

**To Reproduce**
1. Create a new character
2. Skills/stats won't matter
3. Select Britain and you will end up in Minoc, select Trinsic and you go to Moonglow.

**Expected behavior**
The town selected on the map is where your new character will spawn.

**Comment by andreakarasho** [comment]
should be ok now
