### ISSUE TITLE
VvV gump stucking

### ISSUE THREAD

**Issue by LordFenris** [ClassicUO/ClassicUO#971]
**Describe the bug**
VvV gump during the factional battle for the city, on the client Classic UO cannot be moved, it doubles, sometimes covers the entire screen

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows 10

https://uo.com/wp-content/uploads/2015/09/vvv-fight.jpg
On 3D and 2d client without classicuo and client+ razor - the problem does not occur.

**Comment by brndd** [comment]
This screenshot was posted on the Discord the other day:

![unknown](https://user-images.githubusercontent.com/5822375/75796497-67fa3480-5d7c-11ea-9889-b6b015016217.png)

Judging by that screenshot, the gump might be creating a new gump every time the timer at the top ticks down one second. Apparently this also causes performance degradation.
