### ISSUE TITLE
UpdateSkills uses skill BaseVal instead of RealVal for skill adjustment messages

### ISSUE THREAD

**Issue by brndd** [ClassicUO/ClassicUO#972]
https://github.com/andreakarasho/ClassicUO/blob/4305a4f0c355dacb25f99fabe17c1c86eba0415f/src/Network/PacketHandlers.cs#L1463

Some servers (old ones, erroneously?) send BaseVal as 0.00 with RealVal as the actual skill value. When you toggle the skill's arrow/lock status CUO will display the skill as having changed to 0.00.

I think this might also cause equipping jewellery that increases your skills to not display the skill as having increased. I seem to remember such jewellery displaying the "Your skill in xxxx has increased by 5.0. It is now 105.0" message on the official client.

**Comment by andreakarasho** [comment]
fixed
