### ISSUE TITLE
Fixed 3 issues for Eventine

### ISSUE THREAD

**Issue by Darkling89** [ClassicUO/ClassicUO#973]
I fixed the skill icons being the wrong icons and not working on The Eventine Server, most people would have to use uosteam to fix it and not be able to play Eventine with ClassicUO.

I already have it fixed in the same way you did all the other items on the client. And just hope that you will take a look at it and think about adding it in so players there have another client to play.

![Code Comparison](https://user-images.githubusercontent.com/61405638/76112231-cf4bfa80-5faf-11ea-86ec-21408e09227b.jpg)

[PlayerMobile.zip](https://github.com/andreakarasho/ClassicUO/files/4299874/PlayerMobile.zip)

Thanks for even going to consider helping a server, I believe the new players will want to use ClassicUO instead of UOSteam and modding it to support its weapon icons.

**Comment by Darkling89** [comment]
Especially since its easier to setup

**Comment by andreakarasho** [comment]
why not a PR?

**Comment by Darkling89** [comment]
I just never learned how to use push or merge and all that, I just recently jumped into helping out with open source projects. Sorry for no push request, I'll read up on in,

**Comment by andreakarasho** [comment]
done thank you
