### ISSUE TITLE
Healthbar not working for IDamageableItem

### ISSUE THREAD

**Issue by gmocciaro** [ClassicUO/ClassicUO#975]
Hi, i created an item that implements the IDamageableItem interface in order to create a damageable item.

Now the problem is:
In the classiUO client, the healtbar is broken, while in the regular ultima online client works just fine! Maybe i'm missing something? Thanks for your time, i'm available to test more with you!

I'll attach some screenshots for you to understand!

ClassicUO Client
![classicUOclient](https://user-images.githubusercontent.com/12816659/76167241-8047c600-6165-11ea-9beb-3e6541e84853.jpg)

Old Client (fullhp)
![oldclientfullhp](https://user-images.githubusercontent.com/12816659/76167243-8178f300-6165-11ea-9da8-3395187f0e86.JPG)

Old Client (with some hp removed)
![oldclientlesshp](https://user-images.githubusercontent.com/12816659/76167244-8178f300-6165-11ea-9e46-908b8e37b990.JPG)

Thanks for your time!

**Comment by andreakarasho** [comment]
fixed in dev
