### ISSUE TITLE
Project build error

### ISSUE THREAD

**Issue by canerksk** [ClassicUO/ClassicUO#99]
hello, readme.md file does not implement the project can not accomplish the compilation. I'm constantly experiencing different mistakes. Visual Studio 2013 - 2015- 2017. What do I need to install? I would appreciate it if you could help with the compilation. Thank you.

**Comment by andreakarasho** [comment]
vs 2017 and net 4.7
https://visualstudio.microsoft.com/downloads/

**Comment by canavar2212** [comment]
not working. Is this a console? with original customer mi interface. I'm getting some bugs.

**Comment by andreakarasho** [comment]
"not working" is a very generic explenation. Can you provide specific errors?

**Comment by canavar2212** [comment]
The error is below. I am compiling without changing the default state. a client is compiling as a cmd screen instead. can you please help?
![1](https://user-images.githubusercontent.com/10347131/47163604-fe03fb00-d2fe-11e8-8a3b-5697f5bade91.png)

**Comment by andreakarasho** [comment]
Check settings inside this branch into the README.md.
https://github.com/Pack4Duck/ClassicUO/blob/dev/README.md

This should be resolve.

**Comment by canavar2212** [comment]
As all settings are assuming, but the result has not changed. Is this normally a console screen or my client application?
![2](https://user-images.githubusercontent.com/10347131/47164373-9b136380-d300-11e8-964a-109847a81afc.png)

**Comment by andreakarasho** [comment]
I think game doesnt find map files.
Be sure you are setted the correct folder.


edit: i see you are not settings the correct folder. Edit the settings.json and compile

```
"username": "YOUR_USERNAME",
  "password": "YOUR_PASSWORD",
  "ip": "SERVER_IP",
  "port": SERVER_PORT,
  "lastcharactername": "",
  "ultimaonlinedirectory": "YOUR\\PATH\\TO\\ULTIMAONLINE",
  "clientversion": "YOUR.CLIENT.0.VERSION",
```

**Comment by canavar2212** [comment]
Yes, all files were uploaded but the full client did not open. I guess he doesn't want bugs. 7.0.59.8 Where can I find this?
![3](https://user-images.githubusercontent.com/10347131/47165641-0f4f0680-d303-11e8-87ba-db4a4c57c967.png)

**Comment by canavar2212** [comment]
Can you connect with your team viewer?

**Comment by andreakarasho** [comment]
Which vlient version have you got?

**Comment by canavar2212** [comment]
uo version : mondain's legacy 
client versions
![4](https://user-images.githubusercontent.com/10347131/47168670-29401780-d30a-11e8-8c9b-3f9e3ae26402.png)
 ;
