### ISSUE TITLE
Server error question

### ISSUE THREAD

**Issue by jprules321** [ClassicUO/ClassicUO#991]
This is more of a question related to my server. Unfortunaly I don't have access to the source-code for for POL92 core since it doesnt exist anymore. My server has 15+ years of coding scripts and balance into it and is very oldschool and well balanced so I don't plan on trying to upgrade it. However, if possible, I would like to know if I can modify the ClassicUO client to not sent unknown packets to my server so I can use it ? Right now when I try to login I get the following :

`
Undefined message type 84
Unexpected message type 84, 62 bytes
0000: 84 59 6a......
0010: 9a bc bf 47
0020: c8 19 e0....
0030: 9a bc bf 47......
`
By the way, max client version I can go for compat is 2.0.0

**Comment by andreakarasho** [comment]
ClassicUO does not send any 0x84 packet.
Probably your sever cuts data due to the old protocol.
To make cuo compliant with your server you should review the whole packet system in cuo
