### ISSUE TITLE
Text books are very buggy

### ISSUE THREAD

**Issue by brndd** [ClassicUO/ClassicUO#998]
Text books have many bugs:

1- Edits sometimes do not save when the book is closed, presumably because CUO is sending malformed packets that are rejected by the server. Happens often on POL servers, but also on ServUO.
2- The book opening sound often plays when it shouldn't play because of unnecessary calls to `SetActivePage()` in [BookGump.cs](https://github.com/andreakarasho/ClassicUO/blob/master/src/Game/UI/Gumps/BookGump.cs) when for example pressing the enter key.
3- Pasting into books bugs out with multiple consecutive newlines and in other circumstances.
4- Moving the caret to the end of a long line (eg. line with 26 lowercase `a` characters) causes the line to wiggle left and right.
5- Caret doesn't align with first character of line for some lines.
6- Pages can sometimes end up having 9 lines when they should be limited to 8 lines.
7- Newer clients (above version 7?) use 10-line books with bigger book gumps. This is currently not supported by ClassicUO, but it is also not supported by POL/ServUO servers at all.
8- This error message is frequently sent to console accompanied by edits rejected by server: `"Book page 40 split into too many lines: 1 Additional lines will be lost"`

**Comment by andreakarasho** [comment]
fixed in dev with the stb_textedit implementation
